Repository karmada-io/karmada, pull requests merged in 2021-05, with the labels that each got.

#374 fix issue that Scheduler do not schedule resourcebinding generated fr…
  pkg/scheduler/scheduler.go
Labels: priority/important-soon

#381 reschedule resource bindings when reference cluster propagation policy update
  artifacts/example/policy_with_labelSelector.yaml
  pkg/scheduler/scheduler.go
Labels: lgtm, priority/important-soon

#376 Add kubebuilder shortName tag
  artifacts/deploy/policy.karmada.io_clusteroverridepolicies.yaml
  artifacts/deploy/policy.karmada.io_clusterpropagationpolicies.yaml
  artifacts/deploy/policy.karmada.io_overridepolicies.yaml
  artifacts/deploy/policy.karmada.io_propagationpolicies.yaml
  artifacts/deploy/policy.karmada.io_replicaschedulingpolicies.yaml
  artifacts/deploy/work.karmada.io_clusterresourcebindings.yaml
  artifacts/deploy/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/replicascheduling_types.go
  pkg/apis/work/v1alpha1/binding_types.go
Labels: lgtm, priority/backlog

#379 add e2e of imageoverride
  test/e2e/overridepolicy_test.go
  test/helper/overridepolicy.go
  test/helper/resource.go
Labels: priority/backlog
