Repository karmada-io/karmada, pull requests merged in 2021-08, with the labels that each got.

#574 clean up logs init in controller-manager
  cmd/controller-manager/app/controllermanager.go
Labels: approved, kind/cleanup, lgtm, size/XS

#572 fix bug: score plugin does not work
  pkg/scheduler/framework/runtime/framework.go
Labels: approved, kind/bug, lgtm, size/S

#560 Retain pvc volumeName when updating
  pkg/util/constants.go
  pkg/util/objectwatcher/retain.go
Labels: approved, kind/bug, lgtm, size/S

#561 Fix an error in cluster fault rescheduling
  pkg/scheduler/cache/snapshot.go
  pkg/scheduler/scheduler.go
  pkg/util/binding.go
Labels: approved, kind/bug, lgtm, size/L

#564 Docs: Add FAQ about What is the difference between PropagationPolicy and ClusterPropagationPolicy?
  docs/frequently-asked-questions.md
Labels: approved, kind/documentation, lgtm, size/S

#577 Fix an bug when add secret ownerreference with cluster
  pkg/karmadactl/config.go
  pkg/karmadactl/join.go
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup

#555 Move wellknown labels to apis package
  pkg/apis/policy/v1alpha1/well_known_labels.go
  pkg/apis/work/v1alpha1/well_known_labels.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/scheduler/scheduler.go
  pkg/util/constants.go
  pkg/util/detector/detector.go
  pkg/util/helper/binding.go
  pkg/util/helper/workstatus.go
  pkg/util/objectwatcher/objectwatcher.go
  pkg/util/worker.go
Labels: approved, size/L, lgtm, kind/cleanup

#584 bump go version to 1.15
  .github/workflows/ci.yml
  .github/workflows/image.yml
  go.mod
  go.sum
Labels: approved, size/L, lgtm, kind/cleanup

#578 informermanager: cleanup lock operation
  pkg/util/informermanager/multi-cluster-manager.go
Labels: kind/bug, approved, lgtm, size/M, kind/cleanup

#586 remove duplicated constants in binding.go
  pkg/util/helper/binding.go
Labels: size/S, approved, lgtm, kind/cleanup

#576 Leader election: clean up and add leader election to agent
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
  pkg/util/constants.go
Labels: kind/bug, approved, size/L, lgtm

#464 cluster unschedulable support for schedulers
  pkg/apis/cluster/v1alpha1/well_known_taints.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, kind/api-change, approved, size/L, kind/documentation, lgtm, kind/design, tide/merge-method-squash

#570 Adapt karmada-bootstrap.sh for macOS
  hack/karmada-bootstrap.sh
  hack/local-up-karmada.sh
  hack/util.sh
Labels: kind/feature, approved, size/L, lgtm

#582 skip disabled gvr when new informers
  pkg/util/detector/detector.go
Labels: kind/feature, approved, lgtm, size/M

#594 Add cluster lifecycle management using the cluster-api
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/clusterdiscovery/clusterapi/handler.go
  pkg/karmadactl/join.go
  pkg/karmadactl/unjoin.go
  pkg/util/detector/detector.go
  pkg/util/names/names.go
Labels: kind/feature, approved, size/L, lgtm

#573 Docs: add hack guidelines
  hack/README.md
Labels: approved, kind/documentation, lgtm, size/M

#598 cleanup: change file format to unix
  artifacts/deploy/clusterrolebinding.yaml
  artifacts/deploy/namespace.yaml
  artifacts/deploy/serviceaccount.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#597 Delete the extra getClusterHealthStatus logic and use the wait.Poll framework directly
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/M, kind/cleanup

#591 cleanup: use component-helpers instead of k/k
  go.mod
  go.sum
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/scheduler.go
  vendor/k8s.io/kubernetes/pkg/apis/core/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/field_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/features/BUILD
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/util/topologies.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/utils.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup

#592 Support propagation and retain Job resource
  pkg/util/constants.go
  pkg/util/objectwatcher/retain.go
  pkg/webhook/work/mutating.go
  test/e2e/propagationpolicy_test.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: kind/feature, approved, size/L, lgtm

#600 Add image override support for DaemonSet
  pkg/util/constants.go
  pkg/util/overridemanager/imageoverride.go
  pkg/util/overridemanager/imageoverride_test.go
Labels: kind/feature, approved, lgtm, size/M

#595 Add applied result in aggregated status
  artifacts/deploy/work.karmada.io_clusterresourcebindings.yaml
  artifacts/deploy/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha1/binding_types.go
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/M, kind/cleanup

#604 Cleanup: update misleading log
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#590 informer-manager: stop the informer before deleting the cluster
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/context.go
  pkg/util/detector/detector.go
  pkg/util/informermanager/multi-cluster-manager.go
  pkg/util/informermanager/single-cluster-manager.go
Labels: kind/feature, approved, size/L, lgtm

#608 Docs: introduce the usage 'CLUSTER_IP_ONLY=true' to the readme
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#613 Add flaking test issue template
  .github/ISSUE_TEMPLATE/flaking-test.md
Labels: size/S, approved, lgtm, kind/cleanup

#580 add KEP-521: Cluster Accurate Replica Estimator
  docs/proposals/scheduling/521-replica-estimator/README.md
  docs/proposals/scheduling/521-replica-estimator/design.png
Labels: approved, size/L, lgtm, kind/design

#609 reflect status of job/service/ingress to resource template
  pkg/util/constants.go
  pkg/util/detector/aggregate_status.go
  pkg/util/detector/detector.go
  vendor/k8s.io/kubernetes/pkg/apis/batch/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/batch/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/batch/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/batch/register.go
  vendor/k8s.io/kubernetes/pkg/apis/batch/types.go
  vendor/k8s.io/kubernetes/pkg/apis/batch/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#625 Move QPS and Burst to cluster status controller
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/membercluster_client.go
  test/e2e/namespace_test.go
  test/e2e/suite_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#611 add client QPS and burst options to components
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
Labels: kind/feature, approved, lgtm, size/M

#615 Command and Args Overrider
  artifacts/deploy/policy.karmada.io_clusteroverridepolicies.yaml
  artifacts/deploy/policy.karmada.io_overridepolicies.yaml
  artifacts/example/overridepolicy_command.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/util/overridemanager/commandargsoverride.go
  pkg/util/overridemanager/commandargsoverride_test.go
  pkg/util/overridemanager/overridemanager.go
Labels: kind/feature, approved, size/XL, lgtm

#610 Proposal: Configurable local value retention
  docs/proposals/configurable-local-value-retention/README.md
  docs/proposals/runtime-value-retention/README.md
Labels: approved, size/L, kind/documentation, lgtm, kind/design

#636 Cleanup cyclomatic complexity with function JoinCluster
  pkg/karmadactl/join.go
Labels: approved, size/L, lgtm, kind/cleanup

#631 fix flake: propagation with taint and toleration testing
  test/e2e/tainttoleration_test.go
Labels: approved, lgtm, size/M, kind/cleanup, kind/flake

#640 reuse AddPodRequest in detector.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/detector/detector.go
  pkg/util/resource.go
Labels: size/S, approved, lgtm, kind/cleanup

#643 redundant docs removed
  docs/proposals/runtime-value-retention/README.md
Labels: approved, size/L, lgtm

#626 Remove the automatic generation secrets in ServiceAccount
  pkg/webhook/work/mutating.go
Labels: kind/feature, size/S, approved, lgtm

#646 retain necessary fields in Pod object
  pkg/util/helper/unstructured.go
  pkg/util/objectwatcher/retain.go
Labels: approved, lgtm, size/M, kind/cleanup

#633 Docs: Add override policy doc
  docs/override_policy.md
Labels: approved, size/L, kind/documentation, lgtm

#637 move ReplicaResourceRequirements and Replicas into ResourceBindingSpec
  artifacts/deploy/work.karmada.io_clusterresourcebindings.yaml
  artifacts/deploy/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha1/binding_types.go
  pkg/apis/work/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/scheduler.go
  pkg/util/binding.go
  pkg/util/detector/detector.go
Labels: kind/api-change, approved, size/L, lgtm

#645 stop the lease controller when cluster does not exist
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/informermanager/single-cluster-manager.go
Labels: kind/feature, size/S, approved, lgtm

#641 Disable ServiceAccount admission plug-in in karmada apiserver
  artifacts/deploy/karmada-apiserver.yaml
Labels: kind/bug, approved, lgtm, size/XS

#601 keep ResourceBinding when removing PropagationPolicy
  pkg/util/detector/detector.go
  test/e2e/mcs_test.go
Labels: kind/feature, approved, lgtm, size/M

#630 remove health data explicitly when a cluster is being deleted
  pkg/controllers/cluster/cluster_controller.go
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup

#651 Add compatibility Matrix
  README.md
Labels: size/S, approved, kind/documentation, lgtm

#667 Add docs about working with argocd
  docs/images/argocd-new-app-cluster.png
  docs/images/argocd-new-app-name.png
  docs/images/argocd-new-app-repo.png
  docs/images/argocd-new-app.png
  docs/images/argocd-register-karmada.png
  docs/images/argocd-status-aggregated.png
  docs/images/argocd-status-overview.png
  docs/images/argocd-status-resourcebinding.png
  docs/images/argocd-sync-apps.png
  docs/working-with-argocd.md
Labels: approved, kind/documentation, lgtm, size/M

#649 move helper.EnsureWork() to pkg/controllers/binding package
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/util/helper/binding.go
Labels: approved, size/XL, lgtm, kind/cleanup

#674 improve readme
  README.md
Labels: size/S, approved, kind/documentation, lgtm

#663 Docs: Add MCS doc
  docs/multi-cluster-service.md
  docs/override-policy.md
Labels: approved, size/L, kind/documentation, lgtm

#579 Retry conflict errors when aggregating binding status
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/util/helper/workstatus.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#647 refactor imageoverride: use converted resouce to extract json patches
  pkg/util/overridemanager/imageoverride.go
  pkg/util/overridemanager/overridemanager.go
Labels: approved, lgtm, size/M, kind/cleanup
