Repository karmada-io/karmada, pull requests merged in 2021-10, with the labels that each got.

#777 add pod constraint in general estimator
  pkg/estimator/client/general.go
Labels: kind/feature, size/S, approved, lgtm

#785 fix/log-severity
  pkg/webhook/cluster/validating.go
  pkg/webhook/clusterpropagationpolicy/validating.go
Labels: approved, lgtm, size/XS

#885 fix: stop informer manager Instance once
  pkg/util/informermanager/multi-cluster-manager.go
Labels: kind/bug, approved, lgtm, size/XS

#887 Extract join,unjoin parameters and pass struct to avoid too many parameters in the signature
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/karmadactl/join.go
  pkg/karmadactl/unjoin.go
Labels: kind/feature, approved, lgtm, size/M
