Repository karmada-io/karmada, pull requests merged in 2021-12, with the labels that each got.

#989 feature: change namespace filter rule
  cmd/controller-manager/app/options/options.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/detector/detector.go
  pkg/util/names/names.go
Labels: approved, lgtm, size/M

#1050 Add Reserved Namespace Rule
  docs/reserved-namespaces.md
Labels: size/S, approved, kind/documentation, lgtm

#1030 add metrics for scheduler estimator
  cmd/scheduler-estimator/app/scheduler-estimator.go
  pkg/estimator/server/metrics/metrics.go
  pkg/estimator/server/server.go
  pkg/util/metrics/metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm

#632 add KEP-377: proposal about Karmada ResourceQuota
  docs/proposals/resource-quota/README.md
Labels: approved, size/L, lgtm, kind/design

#1057 Example bugFix：artifacts/example/policy_with_labelSelector.yaml
  artifacts/example/policy_with_labelSelector.yaml
Labels: kind/bug, approved, lgtm, size/XS

#1061 update error report when cluster already exist
  pkg/karmadactl/join.go
Labels: size/S, approved, lgtm, kind/cleanup

#1063 update the compatibility matrix
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1037 add resources to karmada-agent in chart template
  charts/templates/karmada_agent.yaml
Labels: kind/bug, approved, lgtm, size/XS

#1065 update bug report template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, kind/documentation, lgtm, size/XS

#1069 fix slow enqueue of async worker
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/detector/detector.go
  pkg/scheduler/scheduler.go
  pkg/util/worker.go
Labels: kind/bug, priority/important-soon, approved, lgtm, size/M

#1075 Add more comment on AsyncWorker
  pkg/util/worker.go
Labels: size/S, approved, lgtm, kind/cleanup

#988 update Scheduled conditon when failed scheduling
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/scheduler/scheduler.go
  pkg/util/condition.go
  pkg/util/helper/binding.go
  test/e2e/framework/deployment.go
Labels: approved, size/L, lgtm, kind/cleanup

#1051 karmada-scheduler: merge scalescheduling with normal scheduling
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/division_algorithm_test.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
  pkg/scheduler/scheduler.go
  pkg/util/helper/binding.go
Labels: kind/feature, approved, size/XL, lgtm

#1074 Chart enhancement
  charts/Chart.yaml
  charts/README.md
  charts/templates/etcd.yaml
  charts/templates/karmada_apiserver.yaml
  charts/templates/post-install-job.yaml
  charts/templates/pre-install-job.yaml
  charts/values.yaml
Labels: kind/feature, approved, lgtm, size/M

#1073 Print pointer variables correctly in the scheduler log
  pkg/apis/cluster/v1alpha1/cluster_utils.go
  pkg/apis/cluster/v1alpha1/cluster_utils_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1083 add flag `--controllers`: a list of controllers to enable
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
Labels: kind/feature, approved, size/L, lgtm

#1084 Optimize the controllers flag
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
Labels: approved, lgtm, size/M, kind/cleanup

#1060 update FullyApplied condition after aggregating works status
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/util/helper/workstatus.go
Labels: approved, size/L, lgtm, kind/cleanup

#1087 Introduce ResourceConflictResolution annotation to control the strategy for managing resources with the same name
  pkg/apis/work/v1alpha2/well_known_labels.go
  pkg/util/annotation.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/feature, approved, lgtm, size/M

#1067 add velero integration doc
  docs/working-with-velero.md
Labels: approved, size/L, kind/documentation, lgtm

#1095 update the base k8s version
  hack/local-up-karmada.sh
Labels: approved, lgtm, size/XS

#1092 Add document structure
  docs/README.md
Labels: size/S, approved, kind/documentation, lgtm

#1099 Cleanup names package
  pkg/util/names/names.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1098 Add e2e test for managing existing resources scenario
  test/e2e/framework/deployment.go
  test/e2e/framework/propagationpolicy.go
  test/e2e/porting_workloads_test.go
Labels: kind/feature, approved, size/L, lgtm

#1103 Cleanup k8s.io/kubernetes from .import-aliases
  hack/.import-aliases
Labels: approved, lgtm, size/XS, kind/cleanup

#1109 Enhanced override policy for easily define all overrides
  charts/Chart.yaml
  charts/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/_crds/bases/policy.karmada.io_overridepolicies.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, kind/api-change, approved, size/XL, lgtm

#1108 Fix namespace issue in the porting workloads e2e test
  test/e2e/porting_workloads_test.go
Labels: approved, lgtm, size/XS, kind/failing-test

#1110 Add more printcolumn for rb, crb and work when executing kubectl get
  charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/_crds/bases/work.karmada.io_resourcebindings.yaml
  charts/_crds/bases/work.karmada.io_works.yaml
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha2/binding_types.go
Labels: kind/feature, approved, lgtm, size/M

#1093 Enhancement --controllers flag of karmada-controller-manager
  cmd/controller-manager/app/controllermanager.go
Labels: kind/feature, approved, size/L, lgtm

#1116 retain ownerReferences when update member cluster object
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup

#1114 Implementing the new OverrideRules
  artifacts/example/clusteroverridepolicy.yaml
  artifacts/example/example-override.yaml
  artifacts/example/overridepolicy_command.yaml
  artifacts/example/overridepolicy_image.yaml
  artifacts/example/overridepolicy_simple.yaml
  pkg/util/overridemanager/overridemanager.go
Labels: kind/feature, approved, size/L, lgtm

#1112 set default for clusterCacheSync timeout and make it configurable
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
Labels: kind/feature, approved, lgtm, size/M

#1119 fix panix in DivideReplicasByTargetCluster
  pkg/util/binding.go
  pkg/util/binding_test.go
Labels: kind/bug, approved, size/L, lgtm

#1094 kubectl-karmada add `init` Command
  go.mod
  go.sum
  pkg/karmadactl/cmdinit/cert/cert.go
  pkg/karmadactl/cmdinit/cert/cert_test.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/cmdinit/kubernetes/check.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/namespace.go
  pkg/karmadactl/cmdinit/kubernetes/node.go
  pkg/karmadactl/cmdinit/kubernetes/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/secret.go
  pkg/karmadactl/cmdinit/kubernetes/serviceaccount.go
  pkg/karmadactl/cmdinit/kubernetes/services.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
  pkg/karmadactl/cmdinit/options/global.go
  pkg/karmadactl/cmdinit/utils/examples.go
  pkg/karmadactl/cmdinit/utils/examples_test.go
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/karmadactl/cmdinit/utils/kubeclient.go
  pkg/karmadactl/cmdinit/utils/kubeconfig.go
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/karmadactl/cmdinit/utils/util_test.go
  pkg/karmadactl/karmadactl.go
  vendor/github.com/lithammer/dedent/.travis.yml
  vendor/github.com/lithammer/dedent/LICENSE
  vendor/github.com/lithammer/dedent/README.md
  vendor/github.com/lithammer/dedent/dedent.go
  vendor/github.com/lithammer/dedent/go.mod
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/design

#1125 replace github.com/pkg/errors with golang native errors
  go.mod
  pkg/karmadactl/cmdinit/kubernetes/namespace.go
  pkg/karmadactl/cmdinit/kubernetes/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/secret.go
  pkg/karmadactl/cmdinit/kubernetes/services.go
  vendor/modules.txt
Labels: size/S, approved, lgtm, kind/cleanup

#1120 Remove redundant sort in scale up schedule
  pkg/scheduler/core/division_algorithm.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1123 controller-manager: automatically generate all controllers list in flag
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
Labels: approved, lgtm, size/M, kind/cleanup

#1115 Move function `RemoveIrrelevantField` to `pkg/resourceinterpreter`
  pkg/resourceinterpreter/prune/prune.go
  pkg/webhook/work/mutating.go
Labels: approved, size/L, lgtm, kind/cleanup

#1124 Implementing karmada-webhook of validating OverridePolicy
  artifacts/deploy/webhook-configuration.yaml
  charts/templates/_karmada_webhook_configuration.tpl
  cmd/webhook/app/webhook.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
  pkg/webhook/overridepolicy/validating.go
Labels: kind/feature, approved, size/L, lgtm

#1107 update kube-apiserver and kube-controller-manager default version
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  charts/values.yaml
  hack/.import-aliases
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/util/helper/mcs.go
  pkg/util/helper/policy.go
  pkg/util/helper/unstructured.go
  pkg/webhook/propagationpolicy/mutating.go
  test/e2e/mcs_test.go
Labels: approved, lgtm, size/M

#1128 Fix incorrect cluster demo yaml
  artifacts/example/cr_cluster.yaml
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup

#1126 Add a e2e test for OverrideRules of OverridePolicy
  test/e2e/overridepolicy_test.go
  test/helper/policy.go
Labels: kind/feature, approved, size/L, lgtm

#1053 abort deleting workload when the member cluster is unready
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/helper/cache.go
Labels: approved, size/L, lgtm, kind/cleanup

#1130 add rate limited when errors occur in scheduler
  pkg/scheduler/scheduler.go
Labels: kind/bug, approved, lgtm, size/XS

#1102 add istio doc
  docs/images/istio-on-karmada.png
  docs/istio-on-karmada.md
Labels: approved, size/L, kind/documentation, lgtm

#1070 add events to resource template
  charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/_crds/bases/work.karmada.io_resourcebindings.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/events.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/detector/detector.go
  pkg/scheduler/scheduler.go
Labels: approved, size/L, lgtm, kind/cleanup

#1133 Add Garrybest on the owner list of karmada-scheduler-estimator
  cmd/scheduler-estimator/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#1134 Update webhook_configuration of `karmadactl init`
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: approved, lgtm, size/M, kind/cleanup

#1138 change the default path of `karmadactl init`
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: kind/feature, size/S, approved, lgtm

#1121 Refactor the matching method in overridemanager
  pkg/apis/policy/v1alpha1/override_utils.go
  pkg/util/overridemanager/overridemanager.go
  pkg/util/overridemanager/overridemanager_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1132 Implementing `karmadactl promote` to promote workloads from legacy clusters to karmada
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/promote.go
  pkg/resourceinterpreter/defaultinterpreter/prune/prune.go
  pkg/webhook/work/mutating.go
Labels: kind/feature, approved, size/L, lgtm

#1148 fix typos
  hack/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1142 Enable `karmada-aggregated-apiserver` installation by `kubectl-karmada init`
  go.mod
  go.sum
  pkg/karmadactl/cmdinit/cert/cert.go
  pkg/karmadactl/cmdinit/cert/cert_test.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/services.go
  pkg/karmadactl/cmdinit/options/global.go
  pkg/karmadactl/cmdinit/utils/kubeclient.go
  vendor/k8s.io/kube-aggregator/LICENSE
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/helpers.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/clientset.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/generated_expansion.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm, kind/cleanup

#1150 Add installation document
  docs/README.md
  docs/installation/install-kubectl-karmada.md
  docs/installation/installation.md
Labels: approved, size/L, kind/documentation, lgtm

#1154 fix division bugs when pod request zero scalar resource
  pkg/util/resource.go
Labels: kind/bug, approved, lgtm, size/XS

#1104 add impersonation config sync controller
  artifacts/agent/clusterrole.yaml
  artifacts/agent/namespace.yaml
  artifacts/agent/serviceaccount.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/karmadactl/join.go
  pkg/util/constants.go
  pkg/util/names/names.go
  pkg/util/rbac.go
Labels: kind/feature, approved, size/XL, lgtm

#1156 add filebeat doc
  docs/working-with-filebeat.md
Labels: approved, size/L, kind/documentation, lgtm

#1157 add prometheus doc
  docs/working-with-prometheus.md
Labels: approved, size/L, kind/documentation, lgtm

#1131 Add --controllers flag to karmada-agent and move ControllerContext to a separate package
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/context/context.go
Labels: kind/feature, approved, size/L, lgtm

#1160 fix the name of impersonate service account
  pkg/util/rbac.go
Labels: kind/bug, approved, lgtm, size/XS

#1052 Add auto-completion document for karmadactl
  docs/bash-auto-completion-on-linux.md
Labels: approved, kind/documentation, lgtm, size/M

#1158 Add ClusterProxy for Cluster
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  cmd/aggregated-apiserver/app/options/options.go
  go.sum
  pkg/aggregatedapiserver/apiserver.go
  pkg/apis/cluster/register.go
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/v1alpha1/zz_generated.register.go
  pkg/apis/cluster/zz_generated.deepcopy.go
  pkg/registry/cluster/storage/proxy.go
  pkg/registry/cluster/storage/storage.go
  vendor/github.com/mxk/go-flowrate/LICENSE
  vendor/github.com/mxk/go-flowrate/flowrate/flowrate.go
  vendor/github.com/mxk/go-flowrate/flowrate/io.go
  vendor/github.com/mxk/go-flowrate/flowrate/util.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/dial.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/doc.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/transport.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#1135 Add e2e test for unjoining not ready cluster
  test/e2e/unjoin_test.go
Labels: kind/feature, approved, size/L, lgtm

#1149 Implementing the ReviseReplica hook
  cmd/controller-manager/app/controllermanager.go
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/controllers/context/context.go
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/defaultinterpreter/default.go
  pkg/resourceinterpreter/defaultinterpreter/revisereplica.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/helper/unstructured.go
  pkg/webhook/configuration/validating.go
Labels: kind/feature, approved, size/L, lgtm

#1155 update `kubectl-karmada init`
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/check.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/namespace.go
  pkg/karmadactl/cmdinit/kubernetes/node.go
  pkg/karmadactl/cmdinit/kubernetes/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/secret.go
  pkg/karmadactl/cmdinit/kubernetes/serviceaccount.go
  pkg/karmadactl/cmdinit/kubernetes/services.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
  pkg/karmadactl/cmdinit/options/global.go
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, approved, size/XL, lgtm, kind/cleanup

#1161 Remove deprecated ReplicaSchedulingPolicy API
  artifacts/example/replicaschedulingpolicy_selector.yaml
  artifacts/example/replicaschedulingpolicy_simple.yaml
  charts/_crds/bases/policy.karmada.io_replicaschedulingpolicies.yaml
  charts/_crds/kustomization.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/replicascheduling_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/policy/v1alpha1/zz_generated.register.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/fake/fake_policy_client.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/fake/fake_replicaschedulingpolicy.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/policy_client.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/replicaschedulingpolicy.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/policy/v1alpha1/interface.go
  pkg/generated/informers/externalversions/policy/v1alpha1/replicaschedulingpolicy.go
  pkg/generated/listers/policy/v1alpha1/expansion_generated.go
  pkg/generated/listers/policy/v1alpha1/replicaschedulingpolicy.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#1167 simplify waitForCacheSync func
  pkg/estimator/server/server.go
Labels: size/S, approved, lgtm, kind/cleanup

#1170 Upgrade for unified auth
  artifacts/agent/namespace.yaml
  artifacts/agent/serviceaccount.yaml
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/unifiedauth/ensure_impersonation_secret.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/karmadactl/join.go
  pkg/util/namespace.go
  pkg/util/serviceaccount.go
Labels: kind/feature, approved, size/L, lgtm

#1169 adjust the steps of karmadactl init, update examples
  go.mod
  go.sum
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/services.go
  pkg/karmadactl/cmdinit/utils/examples.go
  pkg/karmadactl/cmdinit/utils/examples_test.go
  vendor/github.com/lithammer/dedent/.travis.yml
  vendor/github.com/lithammer/dedent/LICENSE
  vendor/github.com/lithammer/dedent/README.md
  vendor/github.com/lithammer/dedent/dedent.go
  vendor/github.com/lithammer/dedent/go.mod
  vendor/modules.txt
Labels: approved, size/L, lgtm, kind/cleanup

#956 Replace clusterIP with hostIP in karmada-kubeconfig when using remote-up-karmada.sh
  docs/installation/fromsource.md
  hack/README.md
  hack/deploy-karmada-agent.sh
  hack/deploy-karmada.sh
  hack/remote-up-karmada.sh
  hack/undeploy-karmada.sh
Labels: kind/feature, approved, lgtm, size/M

#1165 Put lonelyCZ on the owner list
  cmd/OWNERS
  pkg/karmadactl/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#1164 completes ClusterSpec and create impernator secret for pull mode cluster
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  pkg/karmadactl/join.go
  pkg/registry/cluster/storage/proxy.go
  pkg/util/cluster.go
  pkg/util/namespace.go
Labels: kind/feature, approved, size/L, lgtm

#1175 support install karmada aggregated apiserver by helm
  charts/README.md
  charts/templates/_helpers.tpl
  charts/templates/_karmada_apiservice.tpl
  charts/templates/_karmada_system_namespace.tpl
  charts/templates/_karmada_webhook_configuration.tpl
  charts/templates/karmada-aggregated-apiserver.yaml
  charts/templates/karmada_apiserver.yaml
  charts/templates/karmada_cert.yaml
  charts/templates/pre-install-job.yaml
  charts/values.yaml
Labels: approved, size/L, lgtm

#1173 Add cluster registration documents
  docs/README.md
  docs/frequently-asked-questions.md
  docs/userguide/cluster-registration.md
Labels: approved, size/L, kind/documentation, lgtm

#1137 Adapt for hostname in LoadBalancer
  hack/util.sh
Labels: kind/bug, size/S, approved, lgtm

#1177 Add upgrade document for v0.10-v1.0.
  docs/upgrading/README.md
  docs/upgrading/v0.10-v1.0.md
Labels: approved, size/L, kind/documentation, lgtm

#1180 Add impersonator secret reference to Cluster API
  examples/customresourceinterpreter/apis/workload/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/cluster_utils_test.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
Labels: kind/api-change, approved, lgtm, size/M

#1174 Log print karmada text logo
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: size/S, approved, lgtm

#1181 expose more than name/creation timestamp columns for cluster api
  pkg/apis/cluster/v1alpha1/types.go
  pkg/printers/interface.go
  pkg/printers/internalversion/printers.go
  pkg/printers/internalversion/printers_test.go
  pkg/printers/storage/storage.go
  pkg/printers/tablegenerator.go
  pkg/registry/cluster/storage/storage.go
Labels: kind/feature, approved, size/L, lgtm

#1184 add impersonatorSecretRef for cluster object
  cmd/agent/app/agent.go
  pkg/controllers/unifiedauth/ensure_impersonation_secret.go
  pkg/karmadactl/join.go
  pkg/registry/cluster/storage/proxy.go
Labels: kind/feature, approved, size/L, lgtm

#1186 remove the karmada client from aggregated-apiserver
  cmd/aggregated-apiserver/app/options/options.go
  pkg/aggregatedapiserver/apiserver.go
  pkg/registry/cluster/storage/proxy.go
  pkg/registry/cluster/storage/storage.go
Labels: kind/bug, approved, lgtm, size/M, kind/cleanup

#1179 deploy apiserver-network-proxy
  docs/working-with-anp.md
Labels: approved, size/L, kind/documentation, lgtm

#1183 Add parentCommand to make init command compatible with `karmadactl`
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/examples.go
  pkg/karmadactl/cmdinit/utils/examples_test.go
  pkg/karmadactl/karmadactl.go
Labels: approved, size/L, lgtm, kind/cleanup

#1188 Ignore auto-generated user groups when proxy request
  pkg/registry/cluster/storage/proxy.go
Labels: size/S, approved, lgtm, kind/cleanup

#1192 modify filebeat doc reference
  docs/working-with-filebeat.md
Labels: approved, kind/documentation, lgtm, size/XS

#1146 changed the installation mode of k8s kind
  hack/README.md
  hack/local-up-karmada.sh
  hack/util.sh
Labels: kind/bug, size/S, approved, lgtm

#1187 add docs: access member clusters through karmada
  docs/README.md
  docs/userguide/aggregated-api-endpoint.md
  docs/working-with-anp.md
Labels: approved, size/L, kind/documentation, lgtm

#1176 Run karmada-interpreter-webhook-example in CI
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
  hack/run-e2e.sh
  hack/util.sh
  test/e2e/framework/workload.go
  test/e2e/resourceinterpreter_test.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: kind/feature, approved, size/L, lgtm

#704 update apis for automatically propagate dependencies
  charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/work/v1alpha2/binding_types.go
Labels: kind/feature, approved, size/L, lgtm

#1172 Add e2e test for the ReviseReplica hook
  test/e2e/framework/workload.go
  test/e2e/resourceinterpreter_test.go
Labels: kind/feature, approved, lgtm, size/M

#1197 add docs: failover policy overview
  docs/README.md
  docs/userguide/failover.md
Labels: approved, size/L, kind/documentation, lgtm
