Repository karmada-io/karmada, pull requests merged in 2021-06, with the labels that each got.

#396 bug fix wrong folder kickstart
  hack/local-up-karmada.sh
Labels: approved, kind/bug, lgtm, size/XS

#391 enable gosec and fix warnings
  .golangci.yml
  pkg/controllers/status/cluster_status_controller.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/util/detector/detector.go
  pkg/util/helper/binding.go
Labels: approved, kind/cleanup, lgtm, size/S

#327 modify the way of getting GOPATH variable
  hack/karmada-bootstrap.sh
  hack/util.sh
Labels: approved, lgtm, size/XS

#365 using cached lister to get node summary
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/L

#408 Add good first issue template
  .github/ISSUE_TEMPLATE/good-first.md
Labels: approved, kind/cleanup, lgtm, size/M

#406 Embed certs to kubeconfig
  hack/util.sh
Labels: approved, kind/feature, lgtm, size/XS

#410 fix #402 replicaschedulingpolicy does not take effect
  pkg/util/selector.go
Labels: approved, kind/bug, lgtm, size/XS

#328 after install package, add $GOPATH/bin to env PATH
  hack/update-codegen.sh
  hack/util.sh
Labels: approved, lgtm, size/XS

#418 modify hard code in cluster_status_controller
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, kind/cleanup, lgtm, size/XS

#404 Change the receiver of Stringer interface implementation
  pkg/util/imageparser/parser.go
  pkg/util/imageparser/parser_test.go
  pkg/util/informermanager/keys/keys.go
  pkg/util/informermanager/keys/keys_test.go
Labels: approved, kind/cleanup, lgtm, size/M

#409 add E2E cases for policy matching with nil resourceSelectors
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/failover_test.go
  test/e2e/fieldselector_test.go
  test/e2e/overridepolicy_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/resource_test.go
  test/e2e/scheduling_test.go
  test/e2e/tainttoleration_test.go
  test/helper/clusterpropagationpolicy.go
  test/helper/overridepolicy.go
  test/helper/policy.go
  test/helper/propagationpolicy.go
Labels: approved, kind/failing-test, lgtm, size/XL

#415 Introduce --karmada-context flag to karmada-agent to select context in kubeconfig file
  artifacts/agent/karmada-agent.yaml
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  hack/deploy-karmada-agent.sh
  pkg/karmadactl/options/global.go
Labels: approved, kind/feature, lgtm, size/S

#382 Remove dead code
  pkg/util/detector/detector.go
Labels: approved, kind/cleanup, lgtm, priority/backlog, size/M

#429 Revert "remove Makefile SOURCES variable (#334)"
  Makefile
Labels: approved, lgtm, priority/important-soon, size/S

#423 Add hack owners
  hack/OWNERS
Labels: approved, kind/cleanup, lgtm, size/XS

#430 clean up works when resource binding has been removed
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/util/helper/binding.go
Labels: approved, kind/feature, lgtm, size/M

#431 Making resource selector required
  artifacts/deploy/policy.karmada.io_clusterpropagationpolicies.yaml
  artifacts/deploy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/util/detector/detector.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: approved, kind/api-change, kind/cleanup, lgtm, size/L

#420 Refactor karmada bootstrap
  artifacts/agent/karmada-agent.yaml
  hack/deploy-karmada-agent.sh
  hack/deploy-karmada.sh
  hack/karmada-bootstrap.sh
  hack/run-e2e.sh
Labels: approved, kind/feature, lgtm, size/L

#417 make cluster represents more precise resources
  artifacts/deploy/cluster.karmada.io_clusters.yaml
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, kind/api-change, lgtm, size/L

#436 Split listNodesAndPods function
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, kind/cleanup, lgtm, size/M

#441 calculate ResourceSummary in new cluster API
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, kind/feature, lgtm, size/M

#440 Update good first template
  .github/ISSUE_TEMPLATE/good-first.md
Labels: approved, kind/cleanup, lgtm, size/S

#448 Fix redundant log
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/XS

#444 modify pending pods resource calculation
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/resource.go
Labels: approved, kind/cleanup, lgtm, size/L

#442 No informer for sync status back when k8s resource applied failed to member clusters
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/M

#421 add cluster lease controller
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  go.mod
  go.sum
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/cluster.go
  pkg/util/clusterlease.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/apimachinery/lease/controller.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XL

#455 use meta.IsStatusConditionTrue in cluster.go
  pkg/util/cluster.go
Labels: approved, kind/cleanup, lgtm, size/S

#457 fix(controller): rm useless subresource status
  artifacts/deploy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
Labels: approved, kind/cleanup, lgtm, size/XS

#453 Change APIEnablement.Resources to an optional field
  artifacts/deploy/cluster.karmada.io_clusters.yaml
  pkg/apis/cluster/v1alpha1/types.go
Labels: approved, kind/bug, lgtm, size/XS

#461 Enable gocyclo static check
  .golangci.yml
  pkg/karmadactl/join.go
  pkg/scheduler/scheduler.go
  pkg/util/helper/binding.go
  pkg/util/objectwatcher/retain.go
Labels: approved, kind/cleanup, lgtm, size/S

#456 add ScalarResources in cluster ResourceSummary
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/resource.go
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/k8s.io/kube-scheduler/LICENSE
  vendor/k8s.io/kube-scheduler/extender/v1/doc.go
  vendor/k8s.io/kube-scheduler/extender/v1/types.go
  vendor/k8s.io/kube-scheduler/extender/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/features/BUILD
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/util/clock.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/non_zero.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/topologies.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/utils.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, size/XXL

#462 Extend cluster.status.APIEnablements.Resources to struct with Kind
  artifacts/deploy/cluster.karmada.io_clusters.yaml
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/M

#449 Add binary files to gitignore
  .gitignore
Labels: approved, kind/cleanup, lgtm, size/XS

#469 fix(controller): rm sub-resources from cluster api enablement list
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, kind/cleanup, lgtm, size/XS

#468 Fix sync work status
  pkg/controllers/status/workstatus_controller.go
Labels: approved, kind/bug, lgtm, size/XS

#471 adopt applying manifest to member cluster when resource with the same name and kind already exists
  pkg/controllers/execution/execution_controller.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, kind/bug, lgtm, size/M

#454 monitor cluster health in cluster_controller
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, kind/feature, lgtm, size/L

#475 Added mcs API schemes
  go.mod
  go.sum
  pkg/util/gclient/gclient.go
  vendor/modules.txt
  vendor/sigs.k8s.io/mcs-api/LICENSE
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/BUILD
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/doc.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/serviceexport.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/serviceimport.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/well_known_labels.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/mcs-api/pkg/apis/v1alpha1/zz_generated.register.go
Labels: approved, kind/feature, lgtm, size/XL

#482 Run E2E on selfhosted environment
  .github/workflows/ci.yml
Labels: approved, kind/cleanup, lgtm, size/XS
