Repository karmada-io/karmada, pull requests merged in 2021-07, with the labels that each got.

#480 resolve the 'AlreadyExist' conflicts in a 'Create' process
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, kind/bug, lgtm, size/M

#472 disable StorageObjectInUseProtection admission plugin
  artifacts/deploy/karmada-apiserver.yaml
Labels: approved, kind/bug, lgtm, size/XS

#476 Cleanup cyclomatic complexity with function retainServiceFields
  pkg/util/objectwatcher/retain.go
Labels: approved, kind/cleanup, lgtm, size/M

#470 Add new scheduler plugin for checking if required api has installed in target cluster
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/apiinstalled/api_installed.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/registry.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/L

#485 Fix misleading logs
  pkg/util/detector/detector.go
Labels: approved, lgtm, size/XS

#478 Wait context done to satisfy Runnalble interface
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/XS

#484 Add ServiceExport controller to report EndpointSlice
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  cmd/webhook/app/webhook.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/constants.go
  pkg/util/helper/binding.go
  pkg/util/helper/cache.go
  pkg/util/helper/predicate.go
  pkg/util/helper/work.go
  pkg/util/helper/workstatus.go
Labels: approved, kind/feature, lgtm, size/XL

#488 Pin testing environment to ubuntu-18.04
  .github/workflows/ci.yml
  .github/workflows/image.yml
Labels: approved, lgtm, size/S

#458 Karmada-agent install script support the standalone cluster and some misc
  README.md
  artifacts/agent/karmada-agent.yaml
  artifacts/deploy/karmada-apiserver.yaml
  hack/deploy-karmada-agent.sh
  hack/deploy-karmada.sh
  hack/remote-up-karmada.sh
  hack/undeploy-karmada.sh
  hack/util.sh
Labels: approved, kind/feature, lgtm, size/L

#452 Support scheduling according to member cluster resources
  artifacts/deploy/policy.karmada.io_clusterpropagationpolicies.yaml
  artifacts/deploy/policy.karmada.io_propagationpolicies.yaml
  artifacts/deploy/work.karmada.io_clusterresourcebindings.yaml
  artifacts/deploy/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha1/binding_types.go
  pkg/apis/work/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#493 replace wait.Poll with wait.PollImmediate from e2e testing
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/failover_test.go
  test/e2e/namespace_test.go
  test/e2e/overridepolicy_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/resource_test.go
  test/e2e/scheduling_test.go
  test/e2e/suite_test.go
Labels: approved, lgtm, size/M

#490 share informer manager in global
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/informermanager/multi-cluster-manager.go
  pkg/util/informermanager/single-cluster-manager.go
Labels: approved, kind/feature, lgtm, size/L

#497 Update ReplicaScheduling type
  artifacts/deploy/policy.karmada.io_clusterpropagationpolicies.yaml
  artifacts/deploy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#498 resolve AlreadyExists conflict when create resource in member cluster
  pkg/util/cluster.go
  pkg/util/objectwatcher/objectwatcher.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: approved, kind/bug, lgtm, size/L

#495 add object resource info to binding
  pkg/util/constants.go
  pkg/util/detector/detector.go
Labels: approved, kind/feature, lgtm, size/L

#489 Get MCS APIs installation by default
  artifacts/deploy/multicluster.x-k8s.io_serviceexports.yaml
  artifacts/deploy/multicluster.x-k8s.io_serviceimports.yaml
  hack/deploy-karmada.sh
Labels: approved, kind/cleanup, lgtm, size/L

#494 Collect endpointslices from executionNamespace to serviceexport namespace
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/util/helper/mcs.go
  pkg/util/names/names.go
Labels: approved, kind/feature, lgtm, size/L

#496 ensure work with given replicas
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/util/helper/binding.go
Labels: approved, kind/feature, lgtm, size/M

#501 add cluster connectivity in e2e
  artifacts/kindClusterConfig/member1.yaml
  artifacts/kindClusterConfig/member2.yaml
  hack/karmada-bootstrap.sh
  hack/util.sh
Labels: approved, kind/feature, lgtm, size/M

#491 Increase E2E poll timeout setting
  test/e2e/suite_test.go
Labels: approved, kind/cleanup, lgtm, size/XS

#504 Derive service from ServiceImport
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/mcs/service_import_controller.go
Labels: approved, kind/feature, lgtm, size/L

#503 scheduler with Duplicated ReplicaSchedulingStrategy
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/scheduler.go
  pkg/util/spreadstate.go
Labels: approved, kind/feature, lgtm, size/M

#502 refactor utils for checking API enablements
  pkg/scheduler/framework/plugins/apiinstalled/api_installed.go
  pkg/util/cluster.go
  pkg/util/helper/cluster.go
  pkg/util/helper/cluster_test.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#388 Add skippedPropagatingAPIs option
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/util/apigroup.go
  pkg/util/apigroup_test.go
  pkg/util/detector/detector.go
Labels: approved, lgtm, size/L

#506 scheduler with weighted ReplicaDivisionPreference
  pkg/scheduler/core/generic_scheduler.go
  pkg/util/helper/binding.go
Labels: approved, kind/feature, lgtm, size/M

#513 Suppress reported work from propagating
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/util/constants.go
  pkg/util/helper/predicate.go
Labels: approved, kind/feature, lgtm, size/M

#508 Mutate policy's ResourceSelectors in webhook
  pkg/controllers/mcs/service_import_controller.go
  pkg/util/constants.go
  pkg/util/helper/policy.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: approved, kind/feature, lgtm, size/M

#516 suppress reported work from propagating in agent
  cmd/agent/app/agent.go
  pkg/util/helper/predicate.go
Labels: approved, kind/feature, lgtm, size/M

#514 Remove duplicate import
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, kind/cleanup, lgtm, size/XS

#512 implementation of aggregated ReplicaDivisionPreference strategy
  pkg/scheduler/core/generic_scheduler.go
Labels: approved, kind/feature, lgtm, size/L

#519 cleanup: use meta.IsStatusConditionTrue
  pkg/util/helper/workstatus.go
Labels: approved, kind/cleanup, lgtm, size/S

#523 enable log collection for e2e testing
  .github/workflows/ci.yml
  hack/run-e2e.sh
Labels: approved, kind/cleanup, lgtm, size/M

#524 add docker Status check in util::check_clusters_ready
  hack/util.sh
Labels: approved, kind/bug, lgtm, size/XS

#525 Fix taints testing failling.
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-webhook.yaml
  artifacts/deploy/kube-controller-manager.yaml
  test/e2e/failover_test.go
  test/e2e/tainttoleration_test.go
Labels: approved, kind/cleanup, lgtm, size/S

#511 fix bugs of agent deployment
  cmd/agent/app/agent.go
  hack/deploy-karmada-agent.sh
  pkg/util/cluster.go
  pkg/util/namespace.go
Labels: approved, kind/bug, lgtm, size/M

#473 Cleanup cyclomatic complexity with function EnsureWork
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/util/helper/binding.go
  pkg/util/helper/work.go
Labels: approved, kind/cleanup, lgtm, size/L

#526 webhook: when clusterIP=None do not remove clusterIP
  pkg/webhook/work/mutating.go
Labels: approved, lgtm, size/S

#528 Add more debug logs for failing case.
  pkg/util/detector/detector.go
  test/e2e/scheduling_test.go
Labels: approved, kind/cleanup, lgtm, size/S

#530 Replace util.CreateOrUpdateWork with helper.CreateOrUpdateWork
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/util/binding.go
Labels: approved, kind/cleanup, lgtm, size/M

#413 fix make verify cmd generated codes output package is ./
  hack/update-codegen.sh
Labels: approved, kind/bug, lgtm, size/XS

#531 Fix Resource's annotation have not been updated after the overridepolicy updated
  pkg/util/annotation.go
  pkg/util/detector/detector.go
  pkg/util/objectwatcher/retain.go
  test/e2e/scheduling_test.go
Labels: approved, kind/bug, lgtm, size/M

#538 Adapt for macOS in local(kind) environment
  artifacts/kindClusterConfig/karmada-host.yaml
  hack/create-cluster.sh
  hack/deploy-karmada-agent.sh
  hack/deploy-karmada.sh
  hack/karmada-bootstrap.sh
  hack/local-up-karmada.sh
  hack/remote-up-karmada.sh
  hack/util.sh
Labels: approved, kind/feature, lgtm, size/L

#545 fix informer cache delay issue
  pkg/util/detector/detector.go
  pkg/util/helper/unstructured.go
Labels: approved, kind/bug, lgtm, size/M

#515 Replicas changes with Duplicated ReplicaSchedulingStrategy or Weighte…
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/scheduler.go
  pkg/util/binding.go
Labels: approved, kind/feature, lgtm, size/L

#544 never drop binding in scheduler when failed
  pkg/scheduler/scheduler.go
Labels: approved, kind/feature, lgtm, size/S

#529 Add e2e test for MCS feature
  artifacts/deploy/controller-manager.yaml
  pkg/controllers/mcs/service_export_controller.go
  pkg/util/constants.go
  test/e2e/mcs_test.go
  test/e2e/suite_test.go
Labels: approved, kind/cleanup, lgtm, size/XL

#533 controller-manager: introduce --skipped-propagating-namespaces flag
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/util/detector/detector.go
Labels: approved, kind/feature, lgtm, size/M

#551 prevent nil key from queue
  pkg/util/worker.go
Labels: approved, kind/cleanup, lgtm, size/XS

#550 remove inline json tag from status field
  artifacts/deploy/work.karmada.io_clusterresourcebindings.yaml
  artifacts/deploy/work.karmada.io_resourcebindings.yaml
  artifacts/deploy/work.karmada.io_works.yaml
  pkg/apis/work/v1alpha1/binding_types.go
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/detector/detector.go
Labels: approved, kind/api-change, kind/cleanup, lgtm, size/M

#546 Replicas changes with aggregated ReplicaDivisionPreference
  pkg/scheduler/core/generic_scheduler.go
  pkg/util/binding.go
Labels: approved, kind/feature, lgtm, size/L

#549 use RB lister generated from the SingleClusterInformerManager
  pkg/util/detector/detector.go
  pkg/util/helper/unstructured.go
Labels: approved, kind/bug, lgtm, size/M

#556 cleanup waitlist after resource template is removed
  pkg/util/detector/detector.go
Labels: approved, kind/bug, lgtm, size/XS

#552 added validation rules to replicaSchedulingStrategy
  artifacts/deploy/policy.karmada.io_clusterpropagationpolicies.yaml
  artifacts/deploy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
Labels: approved, kind/cleanup, lgtm, size/S

#547 Enable validation for --skipped-propagating-apis flag
  cmd/controller-manager/app/controllermanager.go
  pkg/util/apigroup.go
  pkg/util/apigroup_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#554 E2E: Stop prepare namespace for member clusters
  test/e2e/suite_test.go
Labels: approved, kind/cleanup, lgtm, size/S

#557 Fix an issue when misdeleting namespace in member cluster
  pkg/util/worker.go
Labels: approved, kind/bug, lgtm, size/XS

#562 Fix scheduling test failing
  test/e2e/scheduling_test.go
Labels: approved, kind/bug, lgtm, size/S

#563 sync observed generation
  pkg/util/detector/detector.go
Labels: approved, kind/cleanup, lgtm, size/XS

#509 Generate work name by hash code
  go.mod
  go.sum
  pkg/util/hash/hash.go
  pkg/util/names/names.go
  vendor/github.com/kr/pretty/.gitignore
  vendor/github.com/kr/pretty/License
  vendor/github.com/kr/pretty/Readme
  vendor/github.com/kr/pretty/diff.go
  vendor/github.com/kr/pretty/formatter.go
  vendor/github.com/kr/pretty/go.mod
  vendor/github.com/kr/pretty/go.sum
  vendor/github.com/kr/pretty/pretty.go
  vendor/github.com/kr/pretty/zero.go
  vendor/github.com/kr/text/License
  vendor/github.com/kr/text/Readme
  vendor/github.com/kr/text/doc.go
  vendor/github.com/kr/text/go.mod
  vendor/github.com/kr/text/indent.go
  vendor/github.com/kr/text/wrap.go
  vendor/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem.go
  vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem_1.11.go
  vendor/github.com/rogpeppe/go-internal/fmtsort/sort.go
  vendor/modules.txt
Labels: approved, kind/bug, lgtm, size/XXL

#567 CI: switch runner to selfhosted
  .github/workflows/ci.yml
Labels: approved, kind/failing-test, lgtm, size/XS

#568 CI: Reduce pod wait time and the number of retries
  hack/util.sh
Labels: approved, kind/failing-test, lgtm, size/S

#569 Docs: Add proposal template
  docs/proposals/proposal-template/proposal-template.md
Labels: approved, kind/documentation, lgtm, size/L
