Repository karmada-io/karmada, pull requests merged in 2021-09, with the labels that each got.

#683 switched runner to github action
  .github/workflows/ci.yml
  hack/karmada-bootstrap.sh
Labels: approved, lgtm, size/XS

#638 add replica estimator proto struct definition with generated files and scripts
  go.mod
  hack/generate-proto.sh
  hack/tools/tools.go
  pkg/estimator/pb/generated.pb.go
  pkg/estimator/pb/generated.proto
  pkg/estimator/pb/service.pb.go
  pkg/estimator/pb/service.proto
  pkg/estimator/pb/types.go
  third_party/protobuf/google/protobuf/compiler/plugin.proto
  third_party/protobuf/google/protobuf/descriptor.proto
  vendor/github.com/gogo/protobuf/plugin/compare/compare.go
  vendor/github.com/gogo/protobuf/plugin/compare/comparetest.go
  vendor/github.com/gogo/protobuf/plugin/defaultcheck/defaultcheck.go
  vendor/github.com/gogo/protobuf/plugin/description/description.go
  vendor/github.com/gogo/protobuf/plugin/description/descriptiontest.go
  vendor/github.com/gogo/protobuf/plugin/embedcheck/embedcheck.go
  vendor/github.com/gogo/protobuf/plugin/enumstringer/enumstringer.go
  vendor/github.com/gogo/protobuf/plugin/equal/equal.go
  vendor/github.com/gogo/protobuf/plugin/equal/equaltest.go
  vendor/github.com/gogo/protobuf/plugin/face/face.go
  vendor/github.com/gogo/protobuf/plugin/face/facetest.go
  vendor/github.com/gogo/protobuf/plugin/gostring/gostring.go
  vendor/github.com/gogo/protobuf/plugin/gostring/gostringtest.go
  vendor/github.com/gogo/protobuf/plugin/marshalto/marshalto.go
  vendor/github.com/gogo/protobuf/plugin/oneofcheck/oneofcheck.go
  vendor/github.com/gogo/protobuf/plugin/populate/populate.go
  vendor/github.com/gogo/protobuf/plugin/size/size.go
  vendor/github.com/gogo/protobuf/plugin/size/sizetest.go
  vendor/github.com/gogo/protobuf/plugin/stringer/stringer.go
  vendor/github.com/gogo/protobuf/plugin/stringer/stringertest.go
  vendor/github.com/gogo/protobuf/plugin/testgen/testgen.go
  vendor/github.com/gogo/protobuf/plugin/union/union.go
  vendor/github.com/gogo/protobuf/plugin/union/uniontest.go
  vendor/github.com/gogo/protobuf/plugin/unmarshal/unmarshal.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/Makefile
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/doc.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/generator/generator.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/generator/helper.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/generator/internal/remap/remap.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/grpc/grpc.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/main.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/plugin/Makefile
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/plugin/plugin.pb.go
  vendor/github.com/gogo/protobuf/vanity/command/command.go
  vendor/github.com/gogo/protobuf/vanity/enum.go
  vendor/github.com/gogo/protobuf/vanity/field.go
  vendor/github.com/gogo/protobuf/vanity/file.go
  vendor/github.com/gogo/protobuf/vanity/foreach.go
  vendor/github.com/gogo/protobuf/vanity/msg.go
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#623 fix panic: when the summary weight is zero
  pkg/controllers/binding/common.go
Labels: kind/bug, approved, lgtm, size/XS

#682 fix comment mistake in pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#684 cleanup label from resource template after PP is removed
  pkg/util/detector/detector.go
Labels: kind/bug, approved, lgtm, size/XS

#687 resetConfig should be restConfig
  cmd/controller-manager/app/controllermanager.go
Labels: approved, lgtm, size/XS

#685 Cleanup cyclomatic complexity with function getScheduleType
  pkg/scheduler/scheduler.go
Labels: approved, size/L, lgtm, kind/cleanup

#690 Update kind version to v0.11.1 from 0.10.0
  go.mod
  go.sum
  vendor/github.com/alessio/shellescape/.gitignore
  vendor/github.com/alessio/shellescape/.golangci.yml
  vendor/github.com/alessio/shellescape/.goreleaser.yml
  vendor/github.com/alessio/shellescape/.travis.yml
  vendor/github.com/alessio/shellescape/CODE_OF_CONDUCT.md
  vendor/github.com/alessio/shellescape/README.md
  vendor/github.com/alessio/shellescape/shellescape.go
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/default.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/types.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/installcni/cni.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit/init.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/create.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeadm/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/patch/mergepatch.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/common/logs.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/network.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/util.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/util.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/provider.go
  vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
  vendor/sigs.k8s.io/kind/pkg/errors/errors.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/convert_v1alpha4.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/default.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/types.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/validate.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/zz_generated.deepcopy.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#693 set default weightPreference when WeightPreference is not set
  pkg/scheduler/core/generic_scheduler.go
Labels: kind/bug, approved, lgtm, size/M

#446 fix bug of choosing candidate clusters when failover schedule
  pkg/scheduler/cache/snapshot.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, size/L, lgtm

#698 introduce --leader-elect-resource-namespace flag
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/options/options.go
  cmd/scheduler/app/options/options.go
Labels: kind/feature, release-note, approved, lgtm, size/XS

#657 add node claim into ReplicaRequirements
  artifacts/deploy/work.karmada.io_clusterresourcebindings.yaml
  artifacts/deploy/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha1/binding_types.go
  pkg/apis/work/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/util/detector/detector.go
  pkg/util/helper/binding.go
Labels: kind/api-change, approved, size/XL, lgtm

#702 Modify .gitignore to ingore karmada bninary
  .gitignore
Labels: size/S, approved, lgtm

#696 add E2E test of ReplicaScheduling
  test/e2e/scheduling_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#699 refactor func getScheduleType
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/M

#707 cleanup status after work object gone
  pkg/controllers/binding/common.go
Labels: kind/bug, approved, lgtm, size/XS

#668 feature: support helm chart
  charts/Chart.yaml
  charts/README.md
  charts/_crds/cluster.karmada.io_clusters.yaml
  charts/_crds/multicluster.x-k8s.io_serviceexports.yaml
  charts/_crds/multicluster.x-k8s.io_serviceimports.yaml
  charts/_crds/policy.karmada.io_clusteroverridepolicies.yaml
  charts/_crds/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/_crds/policy.karmada.io_overridepolicies.yaml
  charts/_crds/policy.karmada.io_propagationpolicies.yaml
  charts/_crds/policy.karmada.io_replicaschedulingpolicies.yaml
  charts/_crds/work.karmada.io_clusterresourcebindings.yaml
  charts/_crds/work.karmada.io_resourcebindings.yaml
  charts/_crds/work.karmada.io_works.yaml
  charts/templates/_helpers.tpl
  charts/templates/_karmada_system_namespace.tpl
  charts/templates/_karmada_webhook_configuration.tpl
  charts/templates/etcd.yaml
  charts/templates/karmada_agent.yaml
  charts/templates/karmada_apiserver.yaml
  charts/templates/karmada_cert.yaml
  charts/templates/karmada_controller_manager.yaml
  charts/templates/karmada_kubeconfig.yaml
  charts/templates/karmada_scheduler.yaml
  charts/templates/karmada_webhook.yaml
  charts/templates/kube_controller_manager.yaml
  charts/templates/post-install-job.yaml
  charts/templates/pre-install-job.yaml
  charts/values.yaml
Labels: kind/feature, approved, size/XXL, lgtm

#710 add issue template of question
  .github/ISSUE_TEMPLATE/question.md
Labels: kind/feature, size/S, approved, lgtm

#713 Update binding object with replicas and replicaRequirements
  pkg/util/detector/detector.go
  test/e2e/scheduling_test.go
Labels: kind/bug, approved, lgtm, size/M

#712 makes sure crds in chart always up to date and re-org the crds.
  artifacts/crds/bases/cluster.karmada.io_clusters.yaml
  artifacts/crds/bases/multicluster.x-k8s.io_serviceexports.yaml
  artifacts/crds/bases/multicluster.x-k8s.io_serviceimports.yaml
  artifacts/crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  artifacts/crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  artifacts/crds/bases/policy.karmada.io_overridepolicies.yaml
  artifacts/crds/bases/policy.karmada.io_propagationpolicies.yaml
  artifacts/crds/bases/policy.karmada.io_replicaschedulingpolicies.yaml
  artifacts/crds/bases/work.karmada.io_clusterresourcebindings.yaml
  artifacts/crds/bases/work.karmada.io_resourcebindings.yaml
  artifacts/crds/bases/work.karmada.io_works.yaml
  hack/deploy-karmada.sh
  hack/update-crdgen.sh
  hack/verify-crdgen.sh
Labels: approved, lgtm, size/M, kind/cleanup

#714 unify the crds used by helm chart and the installation scripts
  artifacts/crds/bases/cluster.karmada.io_clusters.yaml
  artifacts/crds/bases/multicluster.x-k8s.io_serviceexports.yaml
  artifacts/crds/bases/multicluster.x-k8s.io_serviceimports.yaml
  artifacts/crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  artifacts/crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  artifacts/crds/bases/policy.karmada.io_overridepolicies.yaml
  artifacts/crds/bases/policy.karmada.io_propagationpolicies.yaml
  artifacts/crds/bases/policy.karmada.io_replicaschedulingpolicies.yaml
  artifacts/crds/bases/work.karmada.io_clusterresourcebindings.yaml
  artifacts/crds/bases/work.karmada.io_resourcebindings.yaml
  artifacts/crds/bases/work.karmada.io_works.yaml
  charts/_crds/bases/cluster.karmada.io_clusters.yaml
  charts/_crds/bases/multicluster.x-k8s.io_serviceexports.yaml
  charts/_crds/bases/multicluster.x-k8s.io_serviceimports.yaml
  charts/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/_crds/bases/policy.karmada.io_overridepolicies.yaml
  charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/_crds/bases/policy.karmada.io_replicaschedulingpolicies.yaml
  charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/_crds/bases/work.karmada.io_resourcebindings.yaml
  charts/_crds/bases/work.karmada.io_works.yaml
  charts/templates/post-install-job.yaml
  charts/templates/pre-install-job.yaml
  hack/deploy-karmada.sh
  hack/update-crdgen.sh
  hack/verify-crdgen.sh
Labels: approved, size/XXL, lgtm, kind/cleanup

#700 Add karmada-scheduler-estimator component
  .gitignore
  Makefile
  cluster/images/karmada-scheduler-estimator/Dockerfile
  cmd/scheduler-estimator/app/options/options.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler-estimator/main.go
  pkg/estimator/server/nodes/filter.go
  pkg/estimator/server/nodes/node_info.go
  pkg/estimator/server/replica/replica.go
  pkg/estimator/server/server.go
  pkg/util/resource.go
Labels: kind/feature, approved, size/XL, lgtm

#717 Introduced version command to karmada-controller-manager
  cmd/controller-manager/app/controllermanager.go
  pkg/version/sharedcommand/sharedcommand.go
  pkg/version/version.go
Labels: kind/feature, approved, lgtm, size/M

#709 Add Import-Aliases Verification
  hack/.import-aliases
  hack/update-import-aliases.sh
  hack/verify-all.sh
  hack/verify-import-aliases.sh
Labels: kind/feature, priority/important-soon, approved, size/L, lgtm

#719 add version command to components
  cmd/agent/app/agent.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/scheduler.go
  cmd/webhook/app/webhook.go
Labels: kind/feature, size/S, approved, lgtm

#728 unify version command
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/version.go
Labels: approved, lgtm, size/M, kind/cleanup

#715 docs: move installation docs out of readme
  README.md
  docs/installation/fromsource.md
Labels: approved, size/L, lgtm, kind/cleanup

#732 update import-aliases
  hack/.import-aliases
  hack/update-import-aliases.sh
  hack/verify-import-aliases.sh
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/propagationpolicy/propagationpolicy_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/scheduler.go
  pkg/util/cluster.go
  pkg/util/detector/aggregate_status.go
  pkg/util/helper/cache.go
  pkg/util/helper/override.go
  pkg/util/informermanager/keys/keys_test.go
  pkg/util/membercluster_client.go
  pkg/util/objectwatcher/objectwatcher.go
  pkg/util/selector.go
  pkg/util/validation/validation.go
  pkg/webhook/overridepolicy/mutating.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/failover_test.go
  test/e2e/mcs_test.go
  test/e2e/namespace_test.go
  test/e2e/overridepolicy_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/scheduling_test.go
  test/e2e/suite_test.go
  test/helper/namespace.go
Labels: approved, size/XL, lgtm, kind/cleanup

#739 CI: Enable import alises verification
  .github/workflows/ci.yml
  hack/update-all.sh
  hack/update-estimator-protobuf.sh
  hack/verify-all.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#721 karmada-scheduler: integrate karmada-scheduler-estimator
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/estimator/client/accurate.go
  pkg/estimator/client/cache.go
  pkg/estimator/client/general.go
  pkg/estimator/client/interface.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/scheduler.go
  pkg/util/dial.go
  pkg/util/error.go
  pkg/util/names/names.go
Labels: kind/feature, approved, size/XL, lgtm

#743 make update-estimator-protobuf.sh executable
  hack/update-estimator-protobuf.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#731 Use cluster lister instead of map to implement scheduler cache
  pkg/scheduler/cache/cache.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/M, kind/cleanup

#733 Quickstart optimization
  .github/workflows/ci.yml
  README.md
  docs/images/sample-nginx.svg
  docs/multi-cluster-service.md
  docs/troubleshooting.md
  docs/working-with-argocd.md
  hack/README.md
  hack/karmada-bootstrap.sh
  hack/local-up-karmada.sh
  hack/util.sh
  samples/nginx/deployment.yaml
  samples/nginx/propagationpolicy.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#723 add resource pod in cluster.status.resourceSummary
  pkg/controllers/status/cluster_status_controller.go
Labels: kind/bug, kind/feature, approved, lgtm, size/XS

#751 Modify typo in README
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#753 Add retry when update object in E2E
  test/e2e/fieldselector_test.go
  test/e2e/mcs_test.go
  test/e2e/scheduling_test.go
Labels: approved, lgtm, size/M, kind/flake

#746 Get member workload from cache instead of api server
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/execution/execution_controller.go
Labels: approved, lgtm, size/M, kind/cleanup

#742 add deploy script of scheduler estimator
  artifacts/deploy/karmada-scheduler-estimator.yaml
  hack/deploy-scheduler-estimator.sh
  hack/local-up-karmada.sh
Labels: kind/feature, approved, size/L, lgtm

#736 adapt to the deployment of Submariner
  artifacts/kindClusterConfig/general-config.yaml
  hack/create-cluster.sh
Labels: kind/feature, approved, lgtm, size/M

#759 back off to general estimator when scheduler estimator is unavailable
  pkg/estimator/client/accurate.go
  pkg/estimator/client/interface.go
  pkg/scheduler/core/generic_scheduler.go
Labels: kind/feature, size/S, approved, lgtm

#755 fix: when matchClusters is empty controller will crash
  pkg/controllers/binding/common.go
Labels: kind/bug, approved, lgtm, size/XS

#758 Move GenerateKey function out of the worker file
  pkg/controllers/status/workstatus_controller.go
  pkg/util/worker.go
Labels: approved, lgtm, size/M, kind/cleanup

#762 Remove extra spaces from artifacts YAML files
  artifacts/agent/karmada-agent.yaml
  artifacts/deploy/controller-manager.yaml
  artifacts/deploy/karmada-cert-secret.yaml
  artifacts/deploy/karmada-etcd.yaml
  artifacts/deploy/karmada-webhook-cert-secret.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#767 fix controller-manager crash when consuming informer before initialized
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/helper/cache.go
Labels: kind/bug, size/S, approved, lgtm

#763 Move the token and caData definitions to the API definition file
  pkg/apis/cluster/v1alpha1/types.go
  pkg/karmadactl/join.go
  pkg/util/membercluster_client.go
Labels: size/S, approved, lgtm, kind/cleanup

#737 Add docs about working with submariner
  docs/multi-cluster-service.md
  docs/working-with-submariner.md
  hack/create-cluster.sh
Labels: approved, kind/documentation, lgtm, size/M

#764 deploy karmada-agent and karmada-scheduler-estimator
  artifacts/deploy/karmada-scheduler.yaml
  hack/deploy-agent-and-estimator.sh
  hack/deploy-scheduler-estimator.sh
  hack/local-up-karmada.sh
Labels: kind/feature, approved, lgtm, size/M

#771 support helm install scheduler estimator
  charts/Chart.yaml
  charts/README.md
  charts/templates/_helpers.tpl
  charts/templates/karmada_scheduler_estimator.yaml
  charts/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#756 Add finalizer in (Cluster)ResourceBinding to delete works
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/util/constants.go
  pkg/util/detector/detector.go
  pkg/util/helper/binding.go
Labels: kind/bug, approved, lgtm, size/M

#775 clean up unstructured conversion
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/helper/unstructured.go
  pkg/webhook/work/mutating.go
Labels: approved, lgtm, size/M, kind/cleanup

#747 add metrics for scheduler
  cmd/scheduler/app/scheduler.go
  go.mod
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/metrics/metrics_record.go
  pkg/scheduler/scheduler.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm

#778 Docs: Add upgrading instructions
  docs/upgrading/README.md
  docs/upgrading/v0.8-v0.9.md
Labels: approved, kind/documentation, lgtm, size/M

#765 add scheduler-estimator docs
  docs/scheduler-estimator.md
Labels: approved, size/L, kind/documentation, lgtm

#779 chart support multi version conversion
  charts/templates/_patch_webhook_in_clusterresourcebindings.tpl
  charts/templates/_patch_webhook_in_resourcebindings.tpl
  charts/templates/post-install-job.yaml
  charts/templates/pre-install-job.yaml
Labels: kind/feature, approved, size/L, lgtm

#781 Add ResourceBinding/ClusterResourceBinding Event
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
Labels: kind/feature, approved, lgtm, size/M

#770 Remove invalid ownerReference in HPA controller
  pkg/controllers/hpa/hpa_controller.go
  pkg/util/constants.go
Labels: approved, lgtm, size/M, kind/cleanup

#782 Deprecate ReplicaSchedulingPolicy API
  charts/_crds/bases/cluster.karmada.io_clusters.yaml
  charts/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/_crds/bases/policy.karmada.io_overridepolicies.yaml
  charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/_crds/bases/policy.karmada.io_replicaschedulingpolicies.yaml
  charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/_crds/bases/work.karmada.io_resourcebindings.yaml
  charts/_crds/bases/work.karmada.io_works.yaml
  hack/update-crdgen.sh
  pkg/apis/policy/v1alpha1/replicascheduling_types.go
  pkg/controllers/hpa/hpa_controller.go
Labels: kind/api-change, size/S, approved, kind/documentation, lgtm, kind/cleanup
