Repository karmada-io/karmada, pull requests merged in 2021-11, with the labels that each got.

#875 Introduce --wait flag for karmada unjoin command
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/unjoin.go
  test/e2e/namespace_test.go
Labels: kind/feature, approved, lgtm, size/M

#886 replace err report with RunE
  cmd/karmadactl/karmadactl.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/unjoin.go
Labels: kind/feature, approved, size/L, lgtm

#888 Update local-up-karmada.sh
  hack/local-up-karmada.sh
Labels: size/S, approved, lgtm, kind/cleanup

#897 docs: install kubectl-karmada
  docs/install-kubectl-karmada.md
Labels: approved, kind/documentation, lgtm, size/M

#902 fix: tips for karmadactl help options
  pkg/karmadactl/cordon.go
Labels: approved, lgtm, size/XS

#904 remove propagationpolicy controller
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/propagationpolicy/propagationpolicy_controller.go
Labels: kind/feature, approved, lgtm, size/M, kind/cleanup

#863 Add custom resource webhook proposal
  docs/proposals/resource-exploring-webhook/README.md
  docs/proposals/resource-exploring-webhook/resource-exploring-webhook.drawio
  docs/proposals/resource-exploring-webhook/resource-exploring-webhook.png
Labels: kind/feature, approved, size/L, lgtm

#909 add object reference information when calling gRPC
  pkg/estimator/client/accurate.go
  pkg/estimator/client/general.go
  pkg/estimator/client/interface.go
  pkg/estimator/server/server.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/util/constants.go
Labels: kind/feature, approved, lgtm, size/M

#907 Remove klog from karmadactl cordon
  pkg/karmadactl/cordon.go
Labels: size/S, approved, lgtm, kind/flake

#911 fix skipped-propagating-apis not take effect
  cmd/controller-manager/app/controllermanager.go
Labels: kind/bug, approved, lgtm, size/XS

#913 Make post-install-job pre-install-job image configurable
  charts/templates/post-install-job.yaml
  charts/templates/pre-install-job.yaml
  charts/values.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#895 prevent empty key from queue
  pkg/controllers/status/workstatus_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#916 add controller-manager parameter validation
  cmd/controller-manager/app/options/validation.go
Labels: kind/feature, approved, lgtm, size/M

#894 add Timeout in WaitForCacheSync
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/constants.go
  pkg/util/informermanager/multi-cluster-manager.go
  pkg/util/informermanager/single-cluster-manager.go
Labels: kind/bug, priority/important-soon, approved, size/L, lgtm

#805 Introduce feature gates for the scheduler component
  artifacts/deploy/karmada-scheduler.yaml
  charts/templates/karmada_scheduler.yaml
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/features/features.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, lgtm, size/M

#928 Skip propagating events by default
  pkg/util/apigroup.go
  pkg/util/apigroup_test.go
Labels: approved, lgtm, kind/design, size/M

#899 Add custom resource webhook API
  charts/_crds/bases/config.karmada.io_resourceexploringwebhookconfigurations.yaml
  charts/_crds/kustomization.yaml
  hack/update-codegen.sh
  pkg/apis/config/v1alpha1/doc.go
  pkg/apis/config/v1alpha1/explorereview_types.go
  pkg/apis/config/v1alpha1/explorewebhook_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/config_client.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/fake/fake_config_client.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/fake/fake_resourceexploringwebhookconfiguration.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/resourceexploringwebhookconfiguration.go
  pkg/generated/informers/externalversions/config/interface.go
  pkg/generated/informers/externalversions/config/v1alpha1/interface.go
  pkg/generated/informers/externalversions/config/v1alpha1/resourceexploringwebhookconfiguration.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/config/v1alpha1/expansion_generated.go
  pkg/generated/listers/config/v1alpha1/resourceexploringwebhookconfiguration.go
Labels: kind/feature, kind/api-change, approved, size/XXL, lgtm

#917 add karmada-scheduler flags verification logic
  cmd/scheduler/app/options/validation.go
  cmd/scheduler/app/options/validation_test.go
  cmd/scheduler/app/scheduler.go
  cmd/scheduler/main.go
Labels: kind/feature, approved, size/L, lgtm

#910 [Trival] remove muti error return when cordon.PatchOrReplace
  pkg/karmadactl/cordon.go
Labels: size/S, approved, lgtm, kind/cleanup

#931 Update the comments of the FeatureGate instance
  pkg/features/features.go
Labels: approved, lgtm, size/XS, kind/cleanup

#925 refactor object watcher interface
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/membercluster_client.go
  pkg/util/objectwatcher/objectwatcher.go
  test/e2e/framework/cluster.go
  test/e2e/namespace_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#891 divide replicas weighted by AvailableReplicas
  charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/_crds/bases/policy.karmada.io_replicaschedulingpolicies.yaml
  pkg/apis/policy/v1alpha1/replicascheduling_types.go
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/division_algorithm_test.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
  pkg/util/binding.go
  pkg/util/helper/binding.go
  test/helper/resource.go
  test/helper/scheduler.go
Labels: kind/feature, approved, size/XXL, lgtm, kind/cleanup

#933 remove orphan works failed cannot print successful logs
  pkg/util/helper/binding.go
Labels: approved, lgtm, size/XS, kind/cleanup

#937 Add CNCF logo
  README.md
  docs/images/cncf-logo.png
Labels: approved, kind/documentation, lgtm, size/XS

#936 cleanup some codes
  cmd/controller-manager/app/controllermanager.go
  hack/local-up-karmada.sh
  pkg/karmadactl/cordon.go
  pkg/karmadactl/get_flags.go
  pkg/scheduler/scheduler.go
  pkg/util/worker.go
Labels: size/S, approved, lgtm, kind/cleanup

#901 add colorful greeting ascii art
  hack/local-up-karmada.sh
Labels: size/S, approved, lgtm

#939 modify resourceexploringwebhookconfigurations to cluster scope
  charts/_crds/bases/config.karmada.io_resourceexploringwebhookconfigurations.yaml
  pkg/apis/config/v1alpha1/explorewebhook_types.go
Labels: kind/api-change, approved, lgtm, size/XS

#930 add agent flag validate
  cmd/agent/app/agent.go
  cmd/agent/app/options/validation.go
  cmd/agent/app/options/validation_test.go
  cmd/agent/main.go
Labels: kind/feature, approved, size/L, lgtm

#943 continue try to get resource when not found
  pkg/karmadactl/join.go
Labels: approved, lgtm, size/XS

#934 Add interface design for Resource Explore Webhook
  pkg/crdexplorer/crdexplorer.go
  pkg/crdexplorer/customizedexplorer/configmanager/accessor.go
  pkg/crdexplorer/customizedexplorer/configmanager/manager.go
  pkg/crdexplorer/customizedexplorer/customized.go
  pkg/crdexplorer/defaultexplorer/default.go
  pkg/crdexplorer/defaultexplorer/healthy.go
  pkg/crdexplorer/defaultexplorer/packing.go
  pkg/crdexplorer/defaultexplorer/replica.go
Labels: kind/feature, approved, size/L, lgtm, kind/design

#898 support job scheduling
  pkg/controllers/binding/common.go
  pkg/detector/detector.go
  pkg/util/binding.go
  pkg/util/constants.go
Labels: kind/feature, approved, lgtm, size/M

#941 Add the validation for ResourceExploringWebhookConfiguration
  artifacts/deploy/webhook-configuration.yaml
  charts/templates/_karmada_webhook_configuration.tpl
  cmd/webhook/app/webhook.go
  pkg/apis/config/v1alpha1/explorewebhook_types.go
  pkg/webhook/crdexplorer/helper.go
  pkg/webhook/crdexplorer/validating.go
Labels: kind/feature, approved, size/L, lgtm

#951 Setup custom resource explorer
  cmd/controller-manager/app/controllermanager.go
  pkg/crdexplorer/crdexplorer.go
  pkg/crdexplorer/customizedexplorer/customized.go
  pkg/crdexplorer/defaultexplorer/default.go
  pkg/crdexplorer/defaultexplorer/replica.go
  pkg/detector/detector.go
  pkg/util/helper/binding.go
Labels: kind/feature, approved, size/L, lgtm

#954 Fix job can not schedule issue
  pkg/crdexplorer/defaultexplorer/default.go
Labels: kind/bug, approved, lgtm, size/XS

#959 fix fossa
  .github/workflows/fossa.yml
Labels: approved, lgtm, size/XS

#961 Define webhook rule instead of import
  charts/_crds/bases/config.karmada.io_resourceexploringwebhookconfigurations.yaml
  pkg/apis/config/v1alpha1/explorewebhook_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/config_client.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/fake/fake_config_client.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/fake/fake_resourceexploringwebhookconfiguration.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/resourceexploringwebhookconfiguration.go
  pkg/generated/informers/externalversions/config/v1alpha1/interface.go
  pkg/generated/informers/externalversions/config/v1alpha1/resourceexploringwebhookconfiguration.go
  pkg/generated/listers/config/v1alpha1/expansion_generated.go
  pkg/generated/listers/config/v1alpha1/resourceexploringwebhookconfiguration.go
  pkg/webhook/crdexplorer/helper.go
  pkg/webhook/crdexplorer/validating.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#953 Match hooks and spawn remote calls to webhook
  pkg/crdexplorer/crdexplorer.go
  pkg/crdexplorer/customizedexplorer/configmanager/accessor.go
  pkg/crdexplorer/customizedexplorer/configmanager/manager.go
  pkg/crdexplorer/customizedexplorer/customized.go
  pkg/crdexplorer/customizedexplorer/webhook/attributes.go
  pkg/crdexplorer/customizedexplorer/webhook/explorereview.go
  pkg/crdexplorer/defaultexplorer/default.go
  pkg/crdexplorer/defaultexplorer/healthy.go
  pkg/crdexplorer/defaultexplorer/packing.go
  pkg/crdexplorer/defaultexplorer/replica.go
  pkg/detector/detector.go
  pkg/util/crdexplorer/rules.go
  pkg/util/helper/unstructured.go
Labels: kind/feature, approved, size/XL, lgtm

#949 unify IsNodeReady function
  pkg/controllers/status/cluster_status_controller.go
  pkg/estimator/server/nodes/filter.go
  pkg/scheduler/framework/plugins/apiinstalled/api_installed.go
  pkg/util/helper/node.go
Labels: approved, lgtm, size/M, kind/cleanup

#958 add more validations for cluster name
  cmd/agent/app/options/validation.go
  pkg/util/validation/validation.go
Labels: size/S, approved, lgtm, kind/cleanup

#966 Rename ExploreReview status to rawstatus
  pkg/apis/config/v1alpha1/explorereview_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/crdexplorer/customizedexplorer/webhook/attributes.go
  pkg/crdexplorer/customizedexplorer/webhook/explorereview.go
Labels: kind/feature, kind/api-change, size/S, approved, lgtm

#960 Feature add validation test
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/validation.go
  cmd/controller-manager/app/options/validation_test.go
Labels: approved, size/L, lgtm, kind/failing-test, tide/merge-method-squash

#968 Add status of explore response
  pkg/apis/config/v1alpha1/explorereview_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/M

#962 add validation test for scheduler-estimator
  cmd/scheduler-estimator/app/options/validation.go
  cmd/scheduler-estimator/app/options/validation_test.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
Labels: approved, size/L, lgtm, kind/cleanup

#970 Set background cacscade deletion by default
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/bug, size/S, approved, lgtm

#971 Add Hook handler interface
  pkg/crdexplorer/customizedexplorer/customized.go
  pkg/crdexplorer/customizedexplorer/webhook/attributes.go
  pkg/crdexplorer/customizedexplorer/webhook/explorereview.go
  pkg/webhook/explorer/decode.go
  pkg/webhook/explorer/http.go
  pkg/webhook/explorer/inject.go
  pkg/webhook/explorer/response.go
  pkg/webhook/explorer/webhook.go
Labels: kind/feature, approved, size/L, lgtm

#973 Setup webhook example structure
  examples/README.md
  examples/customresourceexplorer/apis/workload/v1alpha1/workload_types.go
  examples/customresourceexplorer/webhook/main.go
Labels: kind/feature, approved, lgtm, size/M

#965 pkg/util/secret: Fix GetTargetSecret
  pkg/util/secret.go
Labels: size/S, approved, lgtm, kind/cleanup

#975 update work version in get.go
  pkg/karmadactl/get.go
Labels: kind/bug, approved, lgtm, size/XS

#976 Initialize default custom resource retaintion
  pkg/crdexplorer/crdexplorer.go
  pkg/crdexplorer/defaultexplorer/default.go
  pkg/crdexplorer/defaultexplorer/healthy.go
  pkg/crdexplorer/defaultexplorer/packing.go
  pkg/crdexplorer/defaultexplorer/retain.go
Labels: kind/feature, approved, size/L, lgtm

#977 add examples crd generate file
  examples/customresourceexplorer/apis/workload.example.io_workloads.yaml
  examples/customresourceexplorer/apis/workload/v1alpha1/doc.go
  examples/customresourceexplorer/apis/workload/v1alpha1/workload_types.go
  examples/customresourceexplorer/apis/workload/v1alpha1/zz_generated.deepcopy.go
  examples/customresourceexplorer/apis/workload/v1alpha1/zz_generated.register.go
  hack/update-codegen.sh
  hack/update-crdgen.sh
Labels: kind/feature, approved, size/XXL, lgtm

#974 Solve compatibility for 'sed' on macOS v12.0.1
  hack/local-up-karmada.sh
Labels: size/S, approved, lgtm, kind/cleanup

#981 Add ObservedObject field to ExploreRequest
  pkg/apis/config/v1alpha1/explorereview_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/crdexplorer/crdexplorer.go
  pkg/crdexplorer/defaultexplorer/default.go
Labels: kind/feature, size/S, approved, lgtm

#908 add karmadactl get -h example
  pkg/karmadactl/get.go
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, approved, lgtm, size/M

#982 adapt ObservedObject adding in resource explore webhook
  go.mod
  pkg/crdexplorer/crdexplorer.go
  pkg/crdexplorer/customizedexplorer/webhook/attributes.go
  pkg/crdexplorer/customizedexplorer/webhook/explorereview.go
  pkg/webhook/explorer/decode.go
  pkg/webhook/explorer/response.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, size/M

#979 add retaining webhook
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/crdexplorer/defaultexplorer/default.go
  pkg/crdexplorer/defaultexplorer/retain.go
  pkg/util/objectwatcher/objectwatcher.go
  pkg/util/objectwatcher/retain.go
Labels: kind/feature, approved, size/XL, lgtm

#983 add retion explorer webhook call
  pkg/crdexplorer/crdexplorer.go
  pkg/crdexplorer/customizedexplorer/customized.go
  pkg/crdexplorer/customizedexplorer/webhook/explorereview.go
  pkg/crdexplorer/defaultexplorer/default.go
Labels: kind/feature, approved, lgtm, size/M

#984 fix issue of scheduler-estimator exit
  cmd/scheduler-estimator/app/scheduler-estimator.go
Labels: kind/bug, approved, lgtm, size/XS

#986 add unit test for webhook validation
  pkg/webhook/crdexplorer/helper_test.go
  pkg/webhook/crdexplorer/validating_test.go
Labels: approved, size/L, lgtm

#992 Add upgrade document for v0.9-v0.10
  docs/upgrading/README.md
  docs/upgrading/v0.8-v0.9.md
  docs/upgrading/v0.9-v0.10.md
Labels: size/S, approved, kind/documentation, lgtm

#994 enable unit test for cmd
  Makefile
  cmd/agent/app/options/validation_test.go
Labels: approved, lgtm, size/XS, kind/cleanup

#997 using net.JoinHostPort to generate a network address
  cmd/controller-manager/app/controllermanager.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/scheduler.go
Labels: size/S, approved, lgtm, kind/cleanup

#1000 Update proposal after API changed
  docs/proposals/resource-exploring-webhook/resource-exploring-webhook.drawio
  docs/proposals/resource-exploring-webhook/resource-exploring-webhook.png
  docs/proposals/resource-interpreter-webhook/README.md
  docs/proposals/resource-interpreter-webhook/resource-interpreter-webhook.drawio
  docs/proposals/resource-interpreter-webhook/resource-interpreter-webhook.png
Labels: approved, size/L, kind/documentation, lgtm

#1001 Fix panic: invalid memory address or nil pointer dereference
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/bug, approved, lgtm, size/XS

#996 Add resource interpreter webhook example
  Makefile
  cluster/images/karmada-interpreter-webhook-example/Dockerfile
  examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/options/options.go
  examples/customresourceinterpreter/webhook/app/webhook.go
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  examples/customresourceinterpreter/webhook/main.go
Labels: kind/feature, approved, size/L, lgtm

#1002 Enable build example image and push to registry
  Makefile
Labels: approved, lgtm, size/XS, kind/cleanup

#999 Update slack link to CNCF channel
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#940 Clean klog errorf in karmadactl
  cmd/kubectl-karmada/kubectl-karmada.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
Labels: approved, lgtm, size/M, kind/cleanup

#987 Remove unused policyLister in the genericScheduler
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1004 add validation for webhook example
  Makefile
  examples/customresourceinterpreter/webhook/app/options/validation.go
  examples/customresourceinterpreter/webhook/app/options/validation_test.go
  examples/customresourceinterpreter/webhook/app/webhook.go
Labels: approved, lgtm, size/M, kind/cleanup

#1007 Ignore karmada-interpreter-webhook-example binary
  .gitignore
Labels: approved, lgtm, size/XS, kind/cleanup

#978 Logic patch for dividing remaining replicas to clusters
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/division_algorithm_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1009 Add import alias for config/v1alpha1
  hack/.import-aliases
Labels: approved, lgtm, size/XS

#1012 support update object annotations
  pkg/util/annotation.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1003 fix: fix GenerateBindingReferenceKey bug
  pkg/util/names/names.go
Labels: kind/bug, priority/important-soon, approved, lgtm, size/XS

#1013 Fix generate rb key
  pkg/util/names/names_test.go
Labels: kind/bug, size/S, priority/important-soon, lgtm

#1015 Update upgrade instruction about latest patch version selecting
  docs/upgrading/README.md
Labels: kind/documentation, size/XS

#1020 Add config v1alpha1 schemes to gclient
  pkg/util/gclient/gclient.go
Labels: kind/feature, approved, lgtm, size/XS

#990 Lift some utils code from the k/k repo to avoid relying on it
  go.mod
  go.sum
  hack/verify-import-aliases.sh
  pkg/util/resource.go
  pkg/util/resourcehelper/resourcehelper.go
  vendor/k8s.io/kube-scheduler/LICENSE
  vendor/k8s.io/kube-scheduler/extender/v1/doc.go
  vendor/k8s.io/kube-scheduler/extender/v1/types.go
  vendor/k8s.io/kube-scheduler/extender/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/clock.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/non_zero.go
  vendor/k8s.io/kubernetes/pkg/scheduler/util/utils.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup

#1011 Remove ClusterNamespace from GlobalCommandOptions
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/unjoin.go
  test/e2e/namespace_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#945 clean up metrics package init
  cmd/agent/main.go
  cmd/controller-manager/controller-manager.go
  cmd/scheduler-estimator/main.go
Labels: size/S, approved, lgtm, kind/cleanup

#1028 add karmada-interpreter-webhook-example to make all/clean
  Makefile
Labels: approved, lgtm, size/XS, kind/cleanup

#1024 ignore configv1alpha1 group in detector
  pkg/util/apigroup.go
  pkg/util/apigroup_test.go
Labels: approved, lgtm, size/XS

#1027 Update krew index when release published.
  .github/workflows/release.yml
  .krew.yaml
Labels: approved, lgtm, size/M, kind/flake

#920 Replace go get with go install
  .golangci.yml
  docs/working-with-submariner.md
  go.mod
  hack/tools/preferredimports/preferredimports.go
  hack/update-import-aliases.sh
  hack/util.sh
  hack/verify-import-aliases.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm, kind/cleanup

#1006 delete the TODO logic with binding labels
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/util/helper/binding.go
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/M, kind/cleanup

#1014 Optimization the process of getting PropagationPolicy with higher priority
  pkg/detector/compare.go
  pkg/detector/compare_test.go
  pkg/detector/detector.go
Labels: approved, size/L, lgtm, kind/cleanup

#1019 Refector: add framework for e2e
  test/e2e/failover_test.go
  test/e2e/fieldselector_test.go
  test/e2e/framework/cluster.go
  test/e2e/framework/deployment.go
  test/e2e/framework/job.go
  test/e2e/framework/namespace.go
  test/e2e/framework/overridepolicy.go
  test/e2e/framework/pod.go
  test/e2e/framework/service.go
  test/e2e/mcs_test.go
  test/e2e/namespace_test.go
  test/e2e/overridepolicy_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/resource_test.go
  test/e2e/scheduling_test.go
  test/e2e/tainttoleration_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#1025 Specify the provider manually.
  pkg/karmadactl/join.go
Labels: kind/feature, size/S, approved, lgtm

#957 optimize ResourceList in resource.go
  pkg/apis/work/v1alpha1/binding_types_conversion.go
  pkg/estimator/client/accurate.go
  pkg/estimator/client/general.go
  pkg/util/resource.go
Labels: approved, lgtm, size/M, kind/cleanup

#726 proposal KEP-697: descheduler for karmada
  docs/proposals/scheduling/697-descheduler/README.md
  docs/proposals/scheduling/697-descheduler/descheduler.png
Labels: approved, size/L, lgtm, kind/design

#1022 add unit test for functions of generating names
  pkg/util/names/names_test.go
Labels: approved, size/L, lgtm

#1032 copy CRD files and install in case modifying files in repo
  hack/deploy-karmada.sh
Labels: size/S, approved, lgtm, kind/cleanup

#1034 add startTime and completionTime in job status
  pkg/detector/aggregate_status.go
  pkg/util/helper/job.go
Labels: kind/feature, approved, size/L, lgtm

#932 add conditions for cluster status
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/condition.go
Labels: approved, size/L, lgtm, kind/cleanup

#1031 Add retry on update status
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/status/workstatus_controller.go
Labels: approved, lgtm, size/M, kind/cleanup

#889 Implement karmadactl taint to add taints into a cluster
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/taint.go
Labels: kind/feature, approved, size/L, lgtm

#1040 add ut for AggregateErrors
  pkg/util/error_test.go
Labels: approved, lgtm, size/M

#952 add karmada-wehook flags verification logic
  cmd/webhook/app/options/validation.go
  cmd/webhook/app/options/validation_test.go
  cmd/webhook/app/webhook.go
Labels: kind/feature, approved, size/L, lgtm

#967 Refactor schedule type
  pkg/scheduler/scheduler.go
Labels: approved, size/L, lgtm, kind/cleanup

#1041 Add UT for karmadactl taint
  pkg/karmadactl/taint_test.go
Labels: approved, size/XL, lgtm, kind/failing-test

#1048 add estimator docs in hack directory
  hack/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#946 cleanup karmada ctl code
  pkg/karmadactl/cordon.go
  pkg/karmadactl/get.go
Labels: approved, lgtm, size/M, kind/cleanup
