Repository karmada-io/karmada, pull requests merged in 2022-02, with the labels that each got.

#1319 bug: estimator's os.Exit will not wait for the defer function
  cmd/scheduler-estimator/main.go
Labels: kind/bug, size/S, approved, lgtm, release-note-none

#1320 bug: webhook's os.Exit will not wait for the defer function
  cmd/webhook/main.go
Labels: kind/bug, size/S, approved, lgtm, release-note-none

#1335 set the kindest/node default version to v1.22.0 in create-cluster.sh
  hack/create-cluster.sh
Labels: approved, lgtm, size/XS, kind/flake, release-note-none

#1333 Set up repo owners
  OWNERS
Labels: approved, kind/documentation, lgtm, size/XS, release-note-none

#1324 fix spreadconstraints[i].MaxGroups Invalidation when scaleup replicas
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/division_algorithm_test.go
  pkg/scheduler/core/util.go
Labels: kind/bug, release-note, approved, lgtm, size/M

#1076 Cleanup checking kubeconfig in karmadactl get
  pkg/karmadactl/get.go
Labels: size/S, approved, lgtm, kind/cleanup

#1343 Fix karmadactl get -o yaml|json
  pkg/karmadactl/get.go
Labels: kind/bug, approved, size/L, lgtm, release-note-none

#1341 Introduce `--metrics-bind-address` flag to `karmada-controller-manager`
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
Labels: release-note, approved, lgtm, size/XS, kind/cleanup

#1336 deprecate --master and --karmada-config flags for aggregrated-apiserver
  cmd/aggregated-apiserver/app/options/options.go
Labels: kind/feature, release-note, size/S, approved, lgtm, kind/deprecation

#1352 fix override result will be ignored by ReviseReplica issue
  pkg/controllers/binding/common.go
Labels: kind/bug, release-note, size/S, approved, lgtm

#1342 improve the usage description of `--kubeconfig` flag
  cmd/aggregated-apiserver/app/options/options.go
  cmd/controller-manager/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/webhook/app/options/options.go
Labels: release-note, approved, lgtm, size/XS, kind/cleanup

#1346 Introduce `--metrics-bind-address` and `--health-probe-bind-address` flags to `karmada-webhook`
  cmd/controller-manager/app/options/options.go
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
Labels: kind/feature, release-note, size/S, approved, lgtm

#1354 Add workload sample files in custom resource interpreter example
  examples/customresourceinterpreter/workload-propagationpolicy.yaml
  examples/customresourceinterpreter/workload.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#1355 Fix add retry on createorupdate
  pkg/detector/detector.go
  pkg/util/helper/mcs.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1345 fixes gitVersion is missing from the latest image issue
  .github/workflows/image.yml
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#1357 replace CRLF line terminatiors to LF
  .github/workflows/release.yml
  artifacts/example/namespace.yaml
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1365 build and upload images when publishing
  .github/workflows/release-image.yml
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#1372 return err replace nil
  pkg/controllers/namespace/namespace_sync_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1348 Chart: make `--max-requests-inflight` and `--max-mutating-requests-inflight` configurable
  charts/templates/karmada_apiserver.yaml
  charts/values.yaml
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1368 Rework "bugfix: resource binding not created occasionally"
  pkg/detector/detector.go
Labels: kind/bug, approved, size/L, lgtm, release-note-none

#1384 cherry-pick #1368: "bugfix: resource binding not created occasionally"
  pkg/detector/detector.go
Labels: kind/bug, release-note, approved, lgtm, size/M

#1378 delete some invalid logic in static weight strategy
  pkg/scheduler/core/division_algorithm.go
Labels: approved, lgtm, size/XS, kind/flake, release-note-none

#1381 feat: remove temp files in tests
  pkg/karmadactl/cmdinit/cert/cert_test.go
  pkg/karmadactl/cmdinit/utils/util_test.go
Labels: kind/feature, release-note, size/S, approved, lgtm

#1388 fix bugs of resource computing
  pkg/util/resource.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#1332 add MultiClusterIngress API for MCI feature
  charts/_crds/bases/networking.karmada.io_multiclusteringresses.yaml
  charts/_crds/kustomization.yaml
  hack/update-codegen.sh
  hack/update-crdgen.sh
  pkg/apis/networking/v1alpha1/doc.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/networking/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/fake/fake_multiclusteringress.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/fake/fake_networking_client.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/multiclusteringress.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/networking_client.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/networking/interface.go
  pkg/generated/informers/externalversions/networking/v1alpha1/interface.go
  pkg/generated/informers/externalversions/networking/v1alpha1/multiclusteringress.go
  pkg/generated/listers/networking/v1alpha1/expansion_generated.go
  pkg/generated/listers/networking/v1alpha1/multiclusteringress.go
  pkg/util/gclient/gclient.go
Labels: kind/feature, release-note, approved, size/XXL, lgtm

#1380 Descheduler: Implement GetUnschedulableReplicas for estimator
  cmd/scheduler-estimator/app/scheduler-estimator.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/estimator/server/metrics/metrics.go
  pkg/estimator/server/replica/replica.go
  pkg/estimator/server/server.go
  pkg/estimator/server/server_test.go
  pkg/util/helper/cache.go
  pkg/util/helper/pod.go
  pkg/util/informermanager/single-cluster-manager.go
  pkg/util/workload/deployment.go
  vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: kind/feature, release-note, approved, size/XXL, lgtm

#1394 connect networks between karmada-host, member1 and member2
  hack/local-up-karmada.sh
Labels: kind/feature, approved, lgtm, size/XS, release-note-none

#1395 add default dependenciesInterpreter framework
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/defaultinterpreter/default.go
  pkg/resourceinterpreter/defaultinterpreter/dependencies.go
  pkg/resourceinterpreter/defaultinterpreter/dependencies_util.go
  pkg/resourceinterpreter/interpreter.go
Labels: kind/feature, approved, size/L, lgtm, release-note-none

#1392 add karmada-descheduler
  cmd/descheduler/app/descheduler.go
  cmd/descheduler/app/options/options.go
  cmd/descheduler/app/options/validation.go
  cmd/descheduler/app/options/validation_test.go
  cmd/descheduler/main.go
  pkg/apis/work/v1alpha2/events.go
  pkg/controllers/status/workstatus_controller.go
  pkg/descheduler/core/filter.go
  pkg/descheduler/core/helper.go
  pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
  pkg/estimator/client/accurate.go
  pkg/estimator/client/interface.go
  pkg/estimator/pb/generated.proto
  pkg/estimator/pb/types.go
  pkg/estimator/server/server.go
  pkg/util/constants.go
  pkg/util/helper/policy.go
  pkg/util/helper/workstatus.go
  pkg/util/worker.go
Labels: kind/feature, release-note, approved, size/XXL, lgtm

#1370 feat: quick return in filter phase when unsuccessful state returned
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/runtime/framework.go
Labels: size/S, approved, lgtm, kind/cleanup, release-note-none

#1321 introduce concurrent flags to controllers
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/controllers/context/context.go
  pkg/controllers/status/workstatus_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/detector/detector.go
Labels: kind/feature, release-note, priority/important-soon, approved, size/L, lgtm

#1387 Introduce FederatedResourceQuota API
  charts/_crds/bases/policy.karmada.io_federatedresourcequotas.yaml
  pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/policy/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/fake/fake_federatedresourcequota.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/fake/fake_policy_client.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/federatedresourcequota.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/policy_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/policy/v1alpha1/federatedresourcequota.go
  pkg/generated/informers/externalversions/policy/v1alpha1/interface.go
  pkg/generated/listers/policy/v1alpha1/expansion_generated.go
  pkg/generated/listers/policy/v1alpha1/federatedresourcequota.go
Labels: kind/feature, approved, size/XL, lgtm, release-note-none

#1407 Set subresource for federated resource quota
  charts/_crds/bases/policy.karmada.io_federatedresourcequotas.yaml
  pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1406 improve test coverage
  pkg/util/label_test.go
Labels: approved, size/L, lgtm, release-note-none

#1398 Add FederatedResourceQuota sync controller
  charts/_crds/kustomization.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/util/constants.go
Labels: kind/feature, release-note, approved, size/L, lgtm

#1408 Add FederatedResourceQuota status controller
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
Labels: kind/feature, release-note, approved, size/L, lgtm

#1409 [docs] Using MultiClusterIngress API
  docs/multi-cluster-ingress.md
Labels: kind/feature, approved, size/L, kind/documentation, lgtm, release-note-none
