Repository karmada-io/karmada, pull requests merged in 2022-10, with the labels that each got.

#2600 nominate ikaven1024 as approver
  cmd/karmada-search/OWNERS
  hack/OWNERS
  pkg/search/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#2605 add kubernetes1.25 compatibility for doc
  README.md
Labels: size/S, approved, kind/documentation, lgtm

#2604 imporve readme for chart
  charts/karmada/README.md
  charts/karmada/values.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#2608 karmadactl: modify the wrong noun for karmadactl
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
  pkg/karmadactl/join.go
  pkg/karmadactl/register.go
  pkg/karmadactl/unjoin.go
Labels: size/S, approved, lgtm, kind/cleanup

#2591 Update golangci-lint from 1.46.2 to 1.49.0
  .golangci.yml
  hack/verify-staticcheck.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#2616 fix typos in docs
  docs/keps/cleanup-propagated-resources.md
  docs/proposals/caching/README.md
Labels: size/S, approved, lgtm, kind/cleanup

#2619 add implicit priority E2E for pp
  test/e2e/propagationpolicy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2623 Automated cherry pick of #2608: Modify the wrong noun for karmadactl
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
  pkg/karmadactl/join.go
  pkg/karmadactl/unjoin.go
Labels: size/S, approved, lgtm

#2507 chart: install components with host mode
  .gitignore
  charts/karmada/Chart.lock
  charts/karmada/charts/common-1.17.1.tgz
  charts/karmada/templates/_karmada_apiservice.tpl
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-search.yaml
Labels: kind/feature, size/S, approved, lgtm

#2622 Automated cherry pick of #2608: Modify the wrong noun for karmadactl
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
  pkg/karmadactl/join.go
  pkg/karmadactl/unjoin.go
Labels: size/S, approved, lgtm

#2621 Automated cherry pick of #2608: Modify the wrong noun for karmadactl
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
  pkg/karmadactl/join.go
  pkg/karmadactl/register.go
  pkg/karmadactl/unjoin.go
Labels: size/S, approved, lgtm

#2617 [UT]Add ut for override.go
  pkg/util/helper/override_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2624 chart: support controller manager feature gate
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/values.yaml
Labels: kind/feature, size/S, approved, lgtm

#2599 Unify the dynamic client name for work_status_controller
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/status/workstatus_controller.go
Labels: approved, lgtm, size/M, kind/cleanup

#2615 Add args greater than one
  pkg/karmadactl/cordon.go
Labels: kind/feature, approved, lgtm, size/XS

#2602 gclient handling programmer level errors
  pkg/util/gclient/gclient.go
Labels: kind/bug, size/S, approved, lgtm

#2584 introduce overriders for annotation and label
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/overridemanager/labelannotationoverrider.go
  pkg/util/overridemanager/labelannotationoverrider_test.go
  pkg/util/overridemanager/overridemanager.go
  pkg/util/validation/validation.go
  samples/nginx/overridepolicy.yaml
Labels: kind/feature, approved, size/XL, lgtm

#2625 Update comments for ResourceSelectors in PropagationPolicy to eliminate ambiguity
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: size/S, approved, lgtm, kind/cleanup

#2302 add scheduling diagnosis
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/types.go
Labels: kind/feature, approved, lgtm, size/M

#2626 Add test coverage for pkg/version/release.go
  pkg/version/release_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2572 Add component descriptions
  cmd/agent/app/agent.go
  cmd/aggregated-apiserver/app/aggregated-apiserver.go
  cmd/controller-manager/app/controllermanager.go
  cmd/karmada-search/app/karmada-search.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/scheduler.go
  cmd/webhook/app/webhook.go
Labels: approved, lgtm, size/M, kind/cleanup

#2606 add ut function for util/name.go
  pkg/util/names/names_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2578 Fix serviceaccount continual regeneration by service account controller
  pkg/util/lifted/retain.go
  pkg/util/lifted/retain_test.go
Labels: kind/bug, approved, size/L, lgtm

#2630 Bump GitHub Actions to run on Node16
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/fossa.yml
  .github/workflows/lint-chart.yaml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: approved, lgtm, size/M

#2612 raise an error when there is no healthy nodes for etcd installation
  pkg/karmadactl/cmdinit/kubernetes/node.go
Labels: kind/bug, approved, lgtm, size/XS

#2577 addons enable cluster flag usage description wrong
  pkg/karmadactl/addons/init/global.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2611 karmadactl cordon&uncordon uses factory to access cluster
  pkg/karmadactl/cordon.go
  pkg/karmadactl/karmadactl.go
  test/e2e/karmadactl_test.go
Labels: kind/feature, approved, lgtm, size/M

#2636 Take into account MetalLB in Resource Interpreter webhook example
  examples/README.md
Labels: kind/bug, approved, lgtm, size/M

#2631 Unit Test registry.go
  pkg/scheduler/framework/runtime/registry_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2637 helm chart support configuration for ca key
  charts/karmada/templates/karmada-cert.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/values.yaml
Labels: kind/bug, size/S, approved, lgtm

#2582 Add scripts to install cli tools
  hack/install-cli.sh
Labels: kind/feature, approved, size/L, lgtm

#2570 karmadactl apply uses factory to access member cluster
  pkg/karmadactl/apply.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/util/factory.go
Labels: kind/feature, approved, lgtm, size/M

#2527 scheduler & descheduler introduce scheduler-estimator-service-prefix flag
  cmd/descheduler/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/descheduler/descheduler.go
  pkg/estimator/client/cache.go
  pkg/scheduler/scheduler.go
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: approved, lgtm, size/M

#2627 enhance the doc to give more description about InterpretStatus、InterpretHealth、AggregateStatus
  examples/README.md
Labels: approved, kind/documentation, lgtm, size/M

#2643 Add e2e for LabelsOverrider/AnnotationsOverrider
  test/e2e/overridepolicy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2644 [ut] add ut for proxy
  pkg/search/proxy/cache_proxy.go
  pkg/search/proxy/cache_proxy_test.go
  pkg/search/proxy/cluster_proxy.go
  pkg/search/proxy/cluster_proxy_test.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/karmada_proxy.go
  pkg/search/proxy/karmada_proxy_test.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/util_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#2646 The OverriderOperator description does not match the actual function
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: size/S, approved, lgtm, kind/cleanup

#2645 Fix clusterInfoSnapshot may be nil it will caused painc
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/snapshot.go
  pkg/scheduler/core/generic_scheduler.go
Labels: size/S, approved, lgtm

#2648 reorder `make verify`
  hack/verify-all.sh
Labels: size/S, approved, lgtm, kind/cleanup

#2639 Add configurable resource interpreter API
  charts/karmada/_crds/bases/config.karmada.io_resourceinterpretercustomizations.yaml
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/config_client.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/fake/fake_config_client.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/fake/fake_resourceinterpretercustomization.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/config/v1alpha1/resourceinterpretercustomization.go
  pkg/generated/informers/externalversions/config/v1alpha1/interface.go
  pkg/generated/informers/externalversions/config/v1alpha1/resourceinterpretercustomization.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/config/v1alpha1/expansion_generated.go
  pkg/generated/listers/config/v1alpha1/resourceinterpretercustomization.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/XXL, lgtm

#2656 Rename id.k8s.io --> cluster.clusterset.k8s.io
  docs/proposals/clusterid/README.md
Labels: approved, kind/documentation, lgtm, size/XS, kind/cleanup

#2651 cleanup kubeconfig parameter from customized interpreter
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/interpreter.go
Labels: size/S, approved, lgtm, kind/cleanup

#2561 Add gen-docs scripts
  go.mod
  go.sum
  hack/tools/gencomponentdocs/gen_component_docs.go
  hack/tools/gencomponentdocs/postprocessing.go
  hack/tools/gencomponentdocs/postprocessing_test.go
  hack/tools/genkarmadactldocs/gen_karmadactl_docs.go
  pkg/karmadactl/addons/addons.go
  pkg/karmadactl/apply.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/deinit.go
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/logs.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/register.go
  pkg/karmadactl/taint.go
  pkg/karmadactl/token.go
  pkg/karmadactl/unjoin.go
  pkg/karmadactl/util/command_group.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/genutils.go
  pkg/util/lifted/genutils_test.go
  vendor/github.com/cpuguy83/go-md2man/v2/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/entities.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/github.com/spf13/cobra/doc/README.md
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs.md
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs.md
  vendor/github.com/spf13/cobra/doc/util.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.md
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#2660 [UT]Add ut for job.go and policy.go
  pkg/util/helper/job_test.go
  pkg/util/helper/policy_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2662 UT: add ut for rbac.go and webhook_configuration.go
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/karmada/rbac_test.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration_test.go
  pkg/karmadactl/cmdinit/utils/rbac.go
Labels: approved, lgtm, size/M, kind/cleanup

#2663 Fix a typo about TaintClusterByConditionFailed
  pkg/apis/cluster/v1alpha1/events.go
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2666 Fix line error
  hack/tools/genkarmadactldocs/gen_karmadactl_docs.go
Labels: kind/bug, approved, lgtm, size/XS

#2589 karmadactl get uses factory to access cluster
  pkg/karmadactl/get.go
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, approved, size/L, lgtm, ok-to-test

#2668 karmadactl token uses factory to access cluster
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/token.go
Labels: kind/feature, approved, lgtm, size/M

#2667 [ut] add ut for pkg/util/selector.go
  pkg/util/selector_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2676 Create SECURITY.md
  SECURITY.md
Labels: approved, kind/documentation, lgtm, size/XS

#2610 karmadactl taint uses factory to access cluster
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/taint.go
Labels: kind/feature, approved, lgtm, size/M

#2087 Add metrics_recorder for scheduler framework
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/metrics_recorder.go
  pkg/scheduler/metrics/metrics.go
Labels: kind/feature, approved, size/L, lgtm

#2680 add v1.3 compatibility for doc
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#2654 UT: import gomock to make write ut easier
  go.mod
  go.sum
  hack/tools/preferredimports/preferredimports.go
  hack/update-all.sh
  hack/update-mocks.sh
  hack/verify-all.sh
  hack/verify-mocks.sh
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/runtime/framework_test.go
  pkg/scheduler/framework/testing/mock_interface.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: do-not-merge/hold, approved, size/XXL, lgtm

#2683 install mockgen from vendor
  hack/tools/tools.go
  hack/update-mocks.sh
  vendor/github.com/golang/mock/mockgen/mockgen.go
  vendor/github.com/golang/mock/mockgen/model/model.go
  vendor/github.com/golang/mock/mockgen/parse.go
  vendor/github.com/golang/mock/mockgen/reflect.go
  vendor/github.com/golang/mock/mockgen/version.1.11.go
  vendor/github.com/golang/mock/mockgen/version.1.12.go
  vendor/golang.org/x/mod/modfile/print.go
  vendor/golang.org/x/mod/modfile/read.go
  vendor/golang.org/x/mod/modfile/rule.go
  vendor/golang.org/x/mod/modfile/work.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup

#2675 `karmada-controller-manager`: Fixed the panic when cluster ImpersonatorSecretRef is nil.
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: kind/bug, approved, lgtm, size/XS

#2650 add option to disable search and proxy
  cmd/karmada-search/app/options/options.go
  pkg/search/apiserver.go
  pkg/search/controller.go
Labels: approved, size/L, lgtm, kind/cleanup

#2652 Unit Test worker.go
  go.mod
  pkg/util/worker_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2677 Add a description for the karmadactl subcommand
  pkg/karmadactl/describe.go
  pkg/karmadactl/get.go
  pkg/karmadactl/logs.go
Labels: approved, lgtm, size/M, kind/cleanup

#2669 [ut] add ut for pkg/util/clusterrole, rbac, sercret, secret, serviceaccount
  pkg/util/clusterrole_test.go
  pkg/util/rbac.go
  pkg/util/rbac_test.go
  pkg/util/secret.go
  pkg/util/secret_test.go
  pkg/util/serviceaccount_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#2596 Implement auto certificate rotation function for karmada-agent
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  pkg/controllers/certificate/cert_rotation_controller.go
  pkg/controllers/context/context.go
  pkg/karmadactl/register.go
Labels: kind/feature, approved, size/L, lgtm

#2672 [ut] improve download from httptest
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/karmadactl/cmdinit/utils/util_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2690 Automated cherry pick of #2675: check if cluster ImpersonatorSecretRef is nil before using it
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: approved, lgtm, size/XS

#2686 Defaults to 'Always' if image tag is 'latest' for chart
  charts/karmada/README.md
  charts/karmada/values.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#2692 Automated cherry pick of #2675: check if cluster ImpersonatorSecretRef is nil before using it
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: approved, lgtm, size/XS

#2691 Automated cherry pick of #2675: check if cluster ImpersonatorSecretRef is nil before using it
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: approved, lgtm, size/XS

#2693 Install ResourceInterpreterCustomization CRD
  charts/karmada/_crds/kustomization.yaml
Labels: kind/feature, approved, lgtm, size/XS

#2681 Add configurable interpreter api
  charts/karmada/_crds/bases/config.karmada.io_resourceinterpretercustomizations.yaml
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/XL, lgtm

#2696 Add label "namespace.karmada.io/skip-auto-propagation" to control whether to propagate ns to member clusters
  pkg/apis/policy/v1alpha1/well_known_constants.go
  pkg/controllers/namespace/namespace_sync_controller.go
Labels: kind/feature, size/S, approved, lgtm

#2698 [ut] add ut for cluster.go, clusterlease.go, membercluster_client.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
  pkg/util/clusterlease_test.go
  pkg/util/membercluster_client_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2699 fix wrong description for token commond
  pkg/karmadactl/token.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2705 [ut] add ut for binding.go
  pkg/util/helper/binding_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2704 leverage scheduler cache to estimate replicas
  cmd/descheduler/app/descheduler.go
  cmd/scheduler/app/scheduler.go
  go.mod
  pkg/estimator/server/estimate.go
  pkg/estimator/server/eventhandlers.go
  pkg/estimator/server/nodes/filter.go
  pkg/estimator/server/nodes/node_info.go
  pkg/estimator/server/replica/replica.go
  pkg/estimator/server/server.go
  pkg/estimator/server/server_test.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/scheduler/cache/cache.go
  pkg/util/lifted/scheduler/cache/interface.go
  pkg/util/lifted/scheduler/cache/node_tree.go
  pkg/util/lifted/scheduler/cache/snapshot.go
  pkg/util/lifted/scheduler/framework/listers.go
  pkg/util/lifted/scheduler/framework/parallelize/parallelism.go
  pkg/util/lifted/scheduler/framework/parallelize/parallelism_test.go
  pkg/util/lifted/scheduler/framework/types.go
  pkg/util/lifted/scheduler/util/pod_resources.go
  pkg/util/resource.go
  test/helper/resource.go
  vendor/k8s.io/component-helpers/node/topology/helpers.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#2678 Add Proxy Framework
  cmd/karmada-search/app/karmada-search.go
  cmd/karmada-search/app/options/options.go
  pkg/search/proxy/client_factory.go
  pkg/search/proxy/client_factory_test.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/framework/interface.go
  pkg/search/proxy/framework/plugins/cache/cache.go
  pkg/search/proxy/framework/plugins/cache/cache_test.go
  pkg/search/proxy/framework/plugins/cluster/cluster.go
  pkg/search/proxy/framework/plugins/cluster/cluster_test.go
  pkg/search/proxy/framework/plugins/karmada/karmada.go
  pkg/search/proxy/framework/plugins/karmada/karmada_test.go
  pkg/search/proxy/framework/plugins/registry.go
  pkg/search/proxy/framework/runtime/framework.go
  pkg/search/proxy/framework/runtime/registry.go
  pkg/search/proxy/framework/runtime/registry_test.go
  pkg/search/proxy/karmada_proxy.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/testing/constant.go
  pkg/search/proxy/testing/function.go
  pkg/search/proxy/testing/mock_responder.go
  pkg/search/proxy/testing/mock_store.go
  pkg/util/proxy/proxy.go
Labels: kind/feature, approved, size/XXL, lgtm

#2711 fix chart lint failure
  .github/workflows/lint-chart.yaml
  charts/karmada/templates/karmada-apiserver.yaml
Labels: approved, lgtm, size/XS, kind/failing-test

#2502 karmadactl are compatible with v1.24 master node label
  pkg/karmadactl/cmdinit/kubernetes/node.go
Labels: kind/feature, approved, lgtm, size/XS

#2713 Fix Test Not Success in GoLand
  pkg/search/proxy/controller_test.go
Labels: approved, lgtm, size/XS, kind/cleanup
