Repository karmada-io/karmada, pull requests merged in 2022-06, with the labels that each got.

#1916 adjust etcd version
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1917 Support to search resources with labels
  cmd/karmada-search/app/options/options.go
  pkg/apis/search/scheme/register.go
  pkg/registry/search/storage/cache.go
  pkg/search/apiserver.go
Labels: kind/feature, approved, size/L, lgtm

#1930 Automated cherry pick of #1926: update perl image for latest image run err
  test/helper/resource.go
Labels: approved, lgtm, size/XS

#1932 Automated cherry pick of #1926: update perl image for latest image run err
  test/helper/resource.go
Labels: approved, lgtm, size/XS

#1937 Improve flux docs
  docs/working-with-flux.md
Labels: approved, size/L, kind/documentation, lgtm

#1936 Update default kube-apiserver from v1.21 to v1.22
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/karmada-etcd.yaml
  artifacts/deploy/kube-controller-manager.yaml
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: kind/feature, size/S, approved, lgtm

#1935 add livenessProbe for karmada-kube-controller-manager
  artifacts/deploy/kube-controller-manager.yaml
  charts/templates/kube_controller_manager.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#1940 Make documentation descriptions clearer
  docs/installation/install-kubectl-karmada.md
Labels: approved, lgtm, size/XS, kind/cleanup

#1919 adjust etcd port
  artifacts/deploy/karmada-etcd.yaml
  charts/templates/etcd.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#1855 when type wrong etcd-storage-mode throw error
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
Labels: approved, lgtm, size/M, kind/cleanup

#1873 do proxy setting in China mainland when installing Karmada from source
  hack/local-up-karmada.sh
  hack/remote-up-karmada.sh
  hack/util.sh
Labels: kind/feature, approved, lgtm, size/M

#1947 add changelog for v1.2
  docs/CHANGELOG/CHANGELOG-1.2.md
Labels: approved, size/L, kind/documentation, lgtm

#1950 fix log
  pkg/detector/detector.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1948 [doc] update customizing-resource-interpreter.md
  docs/userguide/customizing-resource-interpreter.md
Labels: size/S, approved, kind/documentation, lgtm

#1941 [helm] Update default kube-apiserver from v1.21 to v1.22
  charts/README.md
  charts/values.yaml
Labels: kind/feature, size/S, approved, lgtm

#1931 Automated cherry pick of #1926: update perl image for latest image run err
  test/helper/resource.go
Labels: approved, lgtm, size/XS

#1874 add ProxyHeader API
  api/openapi-spec/swagger.json
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, lgtm, size/M

#1962 Remove useless prefixes in console for README.md
  charts/README.md
Labels: size/S, approved, lgtm, kind/cleanup

#1964 feat: add unit test for requestinfo
  pkg/registry/search/storage/requestinfo_test.go
Labels: approved, size/L, lgtm

#1951 fix(karmada-search): uncomparable `cache.ResourceEventHandler`
  pkg/search/backendstore/defaultstore.go
Labels: kind/bug, size/S, approved, lgtm

#1968 fix the incorrect use of ServerGroupsAndResources() in client-go
  pkg/controllers/status/cluster_status_controller.go
Labels: kind/feature, size/S, approved, lgtm

#1958 tidy the chart file name and values.yaml
  charts/templates/_helpers.tpl
  charts/templates/etcd.yaml
  charts/templates/karmada-agent.yaml
  charts/templates/karmada-aggregated-apiserver.yaml
  charts/templates/karmada-apiserver.yaml
  charts/templates/karmada-cert.yaml
  charts/templates/karmada-controller-manager.yaml
  charts/templates/karmada-descheduler.yaml
  charts/templates/karmada-kubeconfig.yaml
  charts/templates/karmada-scheduler-estimator.yaml
  charts/templates/karmada-scheduler.yaml
  charts/templates/karmada-search.yaml
  charts/templates/karmada-webhook.yaml
  charts/templates/kube-controller-manager.yaml
  charts/values.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#1971 Automated cherry pick of #1951: fix(karmada-search): uncomparable
  pkg/search/backendstore/defaultstore.go
Labels: size/S, approved, lgtm

#1966 Add a CRD sample
  samples/guestbook/README.md
  samples/guestbook/guestbook.yaml
  samples/guestbook/guestbooks-clusterpropagationolicy.yaml
  samples/guestbook/guestbooks-crd.yaml
  samples/guestbook/guestbooks-overridepolicy.yaml
  samples/guestbook/guestbooks-propagationpolicy.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#1965 Add example yaml of ResourceRegistry
  artifacts/example/resourceregistry.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#1824 Fix promoting failed if a resource with other kind used same name has promoted before
  pkg/karmadactl/promote.go
  pkg/util/names/names.go
  test/e2e/karmadactl_test.go
Labels: kind/bug, approved, lgtm, size/M

#1982 update crd version
  docs/installation/installation.md
Labels: approved, lgtm, size/XS, kind/cleanup

#1928 When ServiceImportType is Headless, it should be ignored
  pkg/controllers/mcs/service_import_controller.go
Labels: approved, lgtm, size/XS

#1978 disable StorageObjectInUseProtection admission plugin in charts
  charts/templates/karmada-apiserver.yaml
Labels: approved, lgtm, size/XS

#1902 add syncEvent from execution_controller to resource
  pkg/apis/work/v1alpha2/well_known_labels.go
  pkg/controllers/execution/execution_controller.go
  pkg/util/helper/work.go
  pkg/util/helper/work_test.go
Labels: kind/feature, approved, size/L, lgtm

#1960 rename cache resource annotation
  pkg/apis/cluster/v1alpha1/well_known_constants.go
  pkg/registry/search/storage/cache.go
  pkg/search/backendstore/opensearch.go
Labels: size/S, approved, lgtm, kind/cleanup

#1663 feat: add outOfTree plugin entry when initializing scheduler
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, lgtm, size/M

#1986 Improve docs about helm chart
  charts/README.md
  docs/upgrading/README.md
  docs/working-with-flux.md
  docs/working-with-kyverno.md
  hack/release-helm-chart.sh
Labels: approved, size/L, kind/documentation, lgtm, kind/cleanup

#1984 modify the chart dir
  charts/karmada/Chart.yaml
  charts/karmada/README.md
  charts/karmada/_crds/bases/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  charts/karmada/_crds/bases/multicluster.x-k8s.io_serviceexports.yaml
  charts/karmada/_crds/bases/multicluster.x-k8s.io_serviceimports.yaml
  charts/karmada/_crds/bases/networking.karmada.io_multiclusteringresses.yaml
  charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_federatedresourcequotas.yaml
  charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_works.yaml
  charts/karmada/_crds/kustomization.yaml
  charts/karmada/_crds/patches/webhook_in_clusterresourcebindings.yaml
  charts/karmada/_crds/patches/webhook_in_resourcebindings.yaml
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/_karmada_apiservice.tpl
  charts/karmada/templates/_karmada_cluster_proxy_admin_rbac.tpl
  charts/karmada/templates/_karmada_system_namespace.tpl
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  charts/karmada/templates/_patch_webhook_in_clusterresourcebindings.tpl
  charts/karmada/templates/_patch_webhook_in_resourcebindings.tpl
  charts/karmada/templates/etcd.yaml
  charts/karmada/templates/karmada-agent.yaml
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-cert.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-kubeconfig.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
  docs/installation/installation.md
  docs/upgrading/README.md
  hack/deploy-karmada.sh
  hack/update-crdgen.sh
  hack/verify-crdgen.sh
Labels: size/S, approved, lgtm, kind/cleanup

#1985 update search proposal
  docs/proposals/caching/README.md
Labels: kind/feature, approved, size/L, lgtm

#1987 fix bugs of aggregating job status
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/helper/job.go
  test/e2e/resource_test.go
Labels: kind/bug, kind/feature, approved, lgtm, size/M

#1913 sync status of pod
  docs/userguide/customizing-resource-interpreter.md
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
Labels: kind/feature, approved, size/L, lgtm

#1977 add chart lint ci workflow
  .github/workflows/lint-chart.yaml
  charts/karmada/Chart.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, lgtm, size/M

#1979 rename misleading label constant
  pkg/apis/policy/v1alpha1/well_known_constants.go
  pkg/apis/work/v1alpha1/well_known_constants.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
Labels: approved, lgtm, size/M, kind/cleanup

#1994 Add leaderelection namespace for helm chart
  charts/karmada/templates/karmada-agent.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#2003 fix etcd-default-path
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2006 Improve scheduler-estimator
  docs/scheduler-estimator.md
Labels: approved, lgtm, size/XS, kind/cleanup

#2007 Automated cherry pick of #1987: fix bugs of aggregating job status
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/helper/job.go
  test/e2e/resource_test.go
Labels: approved, lgtm, size/M

#1883 add Error message when unjoining cluster with a non-existent clustername
  pkg/karmadactl/unjoin.go
Labels: approved, lgtm, size/XS, kind/flake

#2005 update karamda working with velero md
  docs/working-with-velero.md
Labels: approved, kind/documentation, lgtm, size/M

#1933 modify output for deinit
  pkg/karmadactl/deinit.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2004 fix typo mistake
  docs/proposals/hpa/federated-hpa.md
Labels: approved, lgtm, size/XS

#1997 add opensearch script for a developing purpose
  artifacts/opensearch/karmada-opensearch-dashboards.yaml
  artifacts/opensearch/karmada-opensearch.yaml
  hack/deploy-karmada-opensearch.sh
  hack/util.sh
Labels: kind/feature, approved, size/L, lgtm

#2010 Automated cherry pick of #1987: fix bugs of aggregating job status
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/helper/job.go
Labels: size/S, approved, lgtm

#2012 Improve working-with-anp
  docs/working-with-anp.md
Labels: size/S, approved, lgtm, kind/cleanup

#2013 Improve working-with-gatekeeper.md
  docs/working-with-gatekeeper.md
Labels: size/S, approved, lgtm, kind/cleanup

#1884 Add cluster success threshold
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/context/context.go
  pkg/controllers/status/cluster_condition_cache.go
  pkg/controllers/status/cluster_condition_cache_test.go
  pkg/controllers/status/cluster_status_controller.go
Labels: kind/feature, approved, lgtm, size/M

#2023 remove dry-run from GlobalCommandOptions
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/join.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/taint.go
  pkg/karmadactl/unjoin.go
  test/e2e/federatedresourcequota_test.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
Labels: kind/bug, do-not-merge/hold, approved, lgtm, size/M

#2024 Improve aggregated-api-endpoint
  docs/userguide/aggregated-api-endpoint.md
Labels: approved, lgtm, size/M, kind/cleanup

#2027 improve docs-prometheus
  docs/working-with-prometheus.md
Labels: size/S, approved, lgtm, kind/cleanup

#2028 Improve working-with-submariner
  docs/working-with-submariner.md
Labels: approved, lgtm, size/M, kind/cleanup

#2018 Improve working-with-kyverno
  docs/working-with-kyverno.md
Labels: size/S, approved, lgtm, kind/cleanup

#2031 Enlarge timeout setting of golangci-lint
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#2038 The package imports can be improved
  pkg/karmadactl/karmadactl.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2032 Update dependencies Go to 1.18.3
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
  README.md
  go.mod
  go.sum
  hack/util.sh
  hack/verify-staticcheck.sh
Labels: kind/feature, approved, lgtm, size/M

#2021 Put lonelyCZ to owner files
  cmd/OWNERS
  pkg/karmadactl/OWNERS
Labels: approved, kind/documentation, lgtm, size/XS, kind/cleanup

#2029 Add prodanlabs to approver list
  pkg/karmadactl/cmdinit/OWNERS
Labels: approved, kind/documentation, lgtm, size/XS, kind/cleanup

#2030 Put Poor12 to chart owner list
  charts/OWNERS
Labels: approved, kind/documentation, lgtm, size/XS, kind/cleanup

#2044 improve deployments.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/M, kind/cleanup

#2045 improve webhook_configuration.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: approved, lgtm, size/M, kind/cleanup

#2048 Manually specify the Zone and Region of the cluster
  pkg/karmadactl/join.go
Labels: kind/feature, size/S, approved, lgtm

#2036 Automated cherry pick of #2023: remove dry-run from GlobalCommandOptions
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/join.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/taint.go
  pkg/karmadactl/unjoin.go
  test/e2e/federatedresourcequota_test.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
Labels: kind/bug, approved, lgtm, size/M

#1975 use istio on karmada when the clusters reside on the different networks
  docs/CHANGELOG/CHANGELOG-1.0.md
  docs/images/istio-on-karmada-different-network.png
  docs/working-with-istio-on-flat-network.md
  docs/working-with-istio-on-non-flat-network.md
Labels: kind/feature, approved, size/L, lgtm

#1998 Clean-up unused code for upgrade scene
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/unifiedauth/ensure_impersonation_secret.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: approved, size/L, lgtm, kind/cleanup

#2049 Use k8s.io/component-base/cli to run cmd
  cmd/agent/main.go
  cmd/aggregated-apiserver/main.go
  cmd/controller-manager/controller-manager.go
  cmd/descheduler/main.go
  cmd/karmada-search/main.go
  cmd/karmadactl/karmadactl.go
  cmd/kubectl-karmada/kubectl-karmada.go
  cmd/scheduler-estimator/main.go
  cmd/scheduler/main.go
  cmd/webhook/main.go
  examples/customresourceinterpreter/webhook/main.go
  go.mod
  vendor/github.com/go-logr/zapr/.gitignore
  vendor/github.com/go-logr/zapr/LICENSE
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/k8s.io/component-base/cli/OWNERS
  vendor/k8s.io/component-base/cli/run.go
  vendor/k8s.io/component-base/logs/json/json.go
  vendor/k8s.io/component-base/logs/json/register/register.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup

#1989 dump controllerruntime's logs to klog
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  cmd/webhook/app/webhook.go
  examples/customresourceinterpreter/webhook/app/webhook.go
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/severity/severity.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup

#2033 Skip updating lease for push mode clusters
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/status/cluster_status_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#2054 Update pkg/printers with Kubernetes v1.24.2
  pkg/printers/internalversion/printers_test.go
  pkg/printers/tablegenerator.go
  pkg/printers/tablegenerator_test.go
Labels: kind/feature, approved, lgtm, size/M

#2043 Add health probe for Karmada-agent
  artifacts/agent/karmada-agent.yaml
  charts/karmada/templates/karmada-agent.yaml
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/agent/app/options/validation.go
  cmd/agent/app/options/validation_test.go
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: approved, size/L, lgtm, kind/cleanup

#2046 add health probe for karmada-search
  artifacts/deploy/karmada-search.yaml
  charts/karmada/templates/karmada-search.yaml
  cmd/karmada-search/app/options/options.go
  cmd/karmada-search/app/options/validation.go
Labels: approved, lgtm, size/M, kind/cleanup

#2060 Add a CronJob to the default dependencinterpreter
  docs/userguide/customizing-resource-interpreter.md
  pkg/resourceinterpreter/defaultinterpreter/dependencies.go
  pkg/util/constants.go
  pkg/util/helper/unstructured.go
Labels: kind/feature, size/S, approved, lgtm

#2055 update chart readme
  charts/karmada/README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#2061 add lifted doc
  docs/contributors/devel/lifted.md
  hack/tools/lifted-gen/lifted-gen.go
  pkg/util/lifted/corehelpers.go
  pkg/util/lifted/corev1helpers.go
  pkg/util/lifted/corevalidation.go
  pkg/util/lifted/deployment.go
  pkg/util/lifted/discovery.go
  pkg/util/lifted/discovery_test.go
  pkg/util/lifted/logs.go
  pkg/util/lifted/nodeselector.go
  pkg/util/lifted/objectwatcher.go
  pkg/util/lifted/podtemplate.go
  pkg/util/lifted/requestinfo.go
  pkg/util/lifted/resourcename.go
  pkg/util/lifted/retain.go
  pkg/util/lifted/taint.go
  pkg/util/lifted/validateclustertaints.go
  pkg/util/lifted/visitpod.go
Labels: approved, size/L, kind/documentation, lgtm

#2056 feat: add leader election options
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
Labels: kind/feature, approved, lgtm, size/M

#1822 fixed a bug that the service could not be promoted and e2e test
  pkg/util/objectwatcher/objectwatcher.go
  test/e2e/karmadactl_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/resource_test.go
  test/helper/resource.go
Labels: kind/bug, approved, size/L, lgtm

#1972 bugfix: support join 1.24 k8s: auto create secret when sa not create
  pkg/util/secret.go
  pkg/util/serviceaccount.go
Labels: kind/bug, size/S, approved, lgtm

#1912 Add helm repo index
  charts/index.yaml
  charts/karmada/README.md
Labels: approved, lgtm, size/M, kind/cleanup

#2063 wait cluster status to be ready after exec local-up-karmada.sh
  hack/local-up-karmada.sh
  hack/util.sh
Labels: kind/feature, size/S, approved, lgtm

#2074 [bugfix]Return err when create resource failed
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/bug, approved, lgtm, size/XS, kind/failing-test

#2052 karmada-search: short circuit event hander for resourceRegistry updation
  pkg/search/controller.go
Labels: kind/bug, approved, lgtm, size/XS

#2076 Update controller-runtime to v0.12.2
  go.mod
  go.sum
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/Dockerfile
  vendor/github.com/onsi/gomega/Makefile
  vendor/github.com/onsi/gomega/docker-compose.yaml
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/gutil/post_ioutil.go
  vendor/github.com/onsi/gomega/internal/gutil/using_ioutil.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/have_field.go
  vendor/github.com/onsi/gomega/matchers/have_http_body_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_http_status_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_value.go
  vendor/github.com/onsi/gomega/tools
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/FAQ.md
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/README.md
  vendor/sigs.k8s.io/controller-runtime/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/transformers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/certwatcher/certwatcher.go
  vendor/sigs.k8s.io/controller-runtime/pkg/certwatcher/metrics/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/watch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/leader_election.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/warning_handler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/signals/signal_posix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2077 [CI] support k8s v1.24 in ci test
  .github/workflows/ci.yml
Labels: kind/feature, approved, lgtm, size/XS

#1850 [E2E] add karmadactl cordon/uncordon e2e test
  pkg/karmadactl/cordon.go
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2078 improve test coverage for validation
  pkg/util/validation/validation_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2083 fix karmadactl e2e
  test/e2e/karmadactl_test.go
Labels: kind/bug, size/S, approved, lgtm, kind/failing-test

#2082 do not start new tests after the first test failure
  Makefile
Labels: kind/feature, approved, lgtm, size/XS

#2064 karmada-scheduler add disable-scheduler-estimator-in-pull-mode flag
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/scheduler/scheduler.go
Labels: kind/bug, approved, lgtm, size/M, kind/cleanup

#2095 upgrade kind version to v0.14.0
  .github/workflows/lint-chart.yaml
  hack/local-up-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup
