Repository karmada-io/karmada, pull requests merged in 2022-04, with the labels that each got.

#1572 Add document about namespace controller
  docs/userguide/configure-controllers.md
Labels: size/S, approved, kind/documentation, lgtm

#1576 Cleanup unused parameters in Makefile
  Makefile
Labels: approved, lgtm, size/XS, kind/cleanup

#1577 Add FAQ about why we need kube-controller-manager
  docs/frequently-asked-questions.md
Labels: size/S, approved, kind/documentation, lgtm

#1579 Implement flags grouping for customresourceinterpreter
  examples/customresourceinterpreter/webhook/app/webhook.go
Labels: kind/feature, size/S, approved, lgtm

#1580 disable `hpa` controller by default
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/context/context.go
Labels: approved, lgtm, size/M, kind/deprecation

#1575 Implement `karmadactl get` to support pull mode cluster
  artifacts/agent/karmada-agent.yaml
  hack/deploy-karmada-agent.sh
  pkg/karmadactl/get.go
Labels: kind/feature, size/S, approved, lgtm

#1581 Add documents about why we need garbagecollector controller
  docs/userguide/configure-controllers.md
Labels: size/S, approved, kind/documentation, lgtm

#1584 fix: bugfix response's patch and patchType is nil, controller panic
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
Labels: approved, lgtm, size/XS

#1582 Automated cherry pick of #1519: bump alpine base image from v3.7 tov3.15.1
  cluster/images/karmada-agent/Dockerfile
  cluster/images/karmada-aggregated-apiserver/Dockerfile
  cluster/images/karmada-controller-manager/Dockerfile
  cluster/images/karmada-interpreter-webhook-example/Dockerfile
  cluster/images/karmada-scheduler-estimator/Dockerfile
  cluster/images/karmada-scheduler/Dockerfile
  cluster/images/karmada-webhook/Dockerfile
  hack/local-up-karmada.sh
Labels: size/S, approved, lgtm

#1583 Automated cherry pick of #1519: bump alpine base image from v3.7 tov3.15.1
  cluster/images/karmada-agent/Dockerfile
  cluster/images/karmada-aggregated-apiserver/Dockerfile
  cluster/images/karmada-controller-manager/Dockerfile
  cluster/images/karmada-interpreter-webhook-example/Dockerfile
  cluster/images/karmada-scheduler-estimator/Dockerfile
  cluster/images/karmada-scheduler/Dockerfile
  cluster/images/karmada-webhook/Dockerfile
  hack/local-up-karmada.sh
Labels: size/S, approved, lgtm

#1570 add filter plugin ClusterProperty to filter cluster
  pkg/scheduler/framework/plugins/registry.go
  pkg/scheduler/framework/plugins/spreadconstraint/spreadconstraint.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, lgtm, size/M

#1525 ignore to propagate service account token
  pkg/detector/detector.go
Labels: kind/bug, size/S, approved, lgtm

#1586 enable aggregateStatusInterpreter for daemonSet and statefulSet
  docs/userguide/customizing-resource-interpreter.md
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
Labels: kind/feature, approved, lgtm, size/M

#1599 Fix `karmadactl get -o yaml|json` reporting null error
  pkg/karmadactl/get.go
Labels: kind/bug, size/S, approved, lgtm

#1600 fix makefile error
  Makefile
Labels: kind/bug, size/S, approved, lgtm

#1592 Automated cherry pick of #1584: fix: bugfix response's patch and patchType is nil, controller
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
Labels: approved, lgtm, size/XS

#1591 Automated cherry pick of #1584: fix: bugfix response's patch and patchType is nil, controller
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
Labels: approved, lgtm, size/XS

#1603 [E2E] Declare in container nodes, initialize in setup nodes
  test/e2e/aggregatedapi_test.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/dependenciesdistributor_test.go
  test/e2e/failover_test.go
  test/e2e/federatedresourcequota_test.go
  test/e2e/fieldselector_test.go
  test/e2e/mcs_test.go
  test/e2e/namespace_test.go
  test/e2e/overridepolicy_test.go
  test/e2e/porting_workloads_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/rescheduling_test.go
  test/e2e/resource_test.go
  test/e2e/resourceinterpreter_test.go
  test/e2e/scheduling_test.go
  test/e2e/tainttoleration_test.go
  test/e2e/unjoin_test.go
  test/helper/resource.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#1604 fix pull mode example bug
  docs/installation/installation.md
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: kind/bug, approved, lgtm, size/XS

#1589 add UT for aggregatestatus
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
Labels: kind/feature, approved, size/L, lgtm

#1606 add OSX trash to gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#1596 helm: remove cluster-proxy-rbac from karmada-host cluster to karmada-apiserver
  charts/templates/_karmada_cluster_proxy_admin_rbac.tpl
  charts/templates/post-install-job.yaml
  charts/templates/pre-install-job.yaml
Labels: kind/bug, approved, lgtm, size/XS

#1608 Automated cherry pick of #1604: fix pull mode example error
  docs/installation/installation.md
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: approved, lgtm, size/M

#1609 Automated cherry pick of #1604: fix pull mode example error
  docs/installation/installation.md
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: approved, lgtm, size/M

#1602 Remove remaining resource when using helm uninstall
  charts/README.md
  charts/templates/post-delete-job.yaml
  charts/values.yaml
Labels: kind/bug, approved, lgtm, size/M

#1611 [E2E] move cleanup to ginkgo setup node
  test/e2e/aggregatedapi_test.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/dependenciesdistributor_test.go
  test/e2e/failover_test.go
  test/e2e/fieldselector_test.go
  test/e2e/mcs_test.go
  test/e2e/overridepolicy_test.go
  test/e2e/porting_workloads_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/rescheduling_test.go
  test/e2e/resource_test.go
  test/e2e/resourceinterpreter_test.go
  test/e2e/scheduling_test.go
  test/e2e/tainttoleration_test.go
  test/e2e/unjoin_test.go
  test/helper/resource.go
Labels: approved, size/XL, lgtm, kind/cleanup

#1613 add ut for condition
  pkg/util/condition_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1382 feat: introduce registry to initialize framework
  cmd/scheduler/app/scheduler.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/plugins/apiinstalled/api_installed.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go
  pkg/scheduler/framework/plugins/registry.go
  pkg/scheduler/framework/plugins/spreadconstraint/spreadconstraint.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/registry.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, size/L, lgtm, release-note-none

#1616 refactor: remove commented codes
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1612 [E2E] Set e2e to run in parallel
  hack/run-e2e.sh
  test/e2e/failover_test.go
  test/e2e/federatedresourcequota_test.go
  test/e2e/framework/ginkgo_decorator.go
  test/e2e/mcs_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
  test/e2e/resourceinterpreter_test.go
  test/e2e/suite.go
  test/e2e/suite_test.go
  test/e2e/tainttoleration_test.go
  test/e2e/unjoin_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1619 add some prompt message in undeploy-karmada.sh
  hack/undeploy-karmada.sh
Labels: kind/bug, size/S, approved, lgtm

#1610 add karmada_descheduler for helm
  charts/README.md
  charts/templates/_helpers.tpl
  charts/templates/karmada_descheduler.yaml
  charts/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#1623 improve test coverage for validation
  pkg/util/validation/validation_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1622 check if cluster secretRef is nil before using it
  cmd/controller-manager/app/controllermanager.go
  pkg/util/membercluster_client.go
Labels: size/S, approved, lgtm

#1625 add ut for revisereplica
  pkg/resourceinterpreter/defaultinterpreter/revisereplica_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1563 [optimize]Consider available resources when selecting clusters
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_cluster.go
  pkg/scheduler/core/spreadconstraint/select_clusters_test.go
  pkg/scheduler/core/spreadconstraint/util.go
Labels: kind/feature, approved, size/L, lgtm

#1628 add ut for filter
  pkg/descheduler/core/filter_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1620 [AA] fix timeout when request of `-w` or `logs -f` flags with cluster/proxy
  cmd/aggregated-apiserver/app/options/options.go
  pkg/registry/cluster/storage/storage.go
  pkg/util/lifted/requestinfo.go
Labels: kind/bug, approved, size/L, lgtm

#1630 Automated cherry pick of #1620: fix timeout when request of -w or logs -f with cluster/proxy
  cmd/aggregated-apiserver/app/options/options.go
  pkg/registry/cluster/storage/storage.go
  pkg/util/lifted/requestinfo.go
Labels: approved, size/L, lgtm

#1631 Automated cherry pick of #1620: fix timeout when request of -w or logs -f with cluster/proxy
  cmd/aggregated-apiserver/app/options/options.go
  pkg/registry/cluster/storage/storage.go
  pkg/util/lifted/requestinfo.go
Labels: approved, size/L, lgtm

#1632 Fix pod exec through cluster/proxy
  pkg/registry/cluster/storage/proxy.go
Labels: kind/bug, approved, lgtm, size/XS

#1639 update lifted doc
  pkg/util/lifted/doc.go
Labels: approved, kind/documentation, lgtm, size/XS

#1637 add ut for rules
  pkg/util/interpreter/rules_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1642 Automated cherry pick of #1632: Fix pod exec through cluster/proxy
  pkg/registry/cluster/storage/proxy.go
Labels: approved, lgtm, size/XS

#1641 Automated cherry pick of #1632: Fix pod exec through cluster/proxy
  pkg/registry/cluster/storage/proxy.go
Labels: approved, lgtm, size/XS

#1636 skip reconciling loop quickly after workload gone
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1386 [proposal] Caching member cluster resources for Karmada
  docs/proposals/caching/README.md
Labels: kind/feature, approved, size/L, lgtm, release-note-none

#1629 Introduce AssignedReplicasForCluster for ResourceBinding
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/apis/work/v1alpha2/binding_types_helper_test.go
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/group_clusters_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1635 docs: add FAQ about reuse kube-apiserver
  docs/frequently-asked-questions.md
Labels: size/S, approved, kind/documentation, lgtm

#964 add CHANGELOG
  CHANGELOG.md
  docs/CHANGELOG/CHANGELOG-0.10.md
  docs/CHANGELOG/CHANGELOG-0.9.md
  docs/CHANGELOG/CHANGELOG-1.0.md
  docs/CHANGELOG/CHANGELOG-1.1.md
  docs/CHANGELOG/OWNERS
Labels: approved, size/L, kind/documentation, lgtm

#1597 Add logs function to karmadactl
  go.mod
  go.sum
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs.go
  pkg/util/lifted/logs.go
  pkg/util/lifted/logs_test.go
  vendor/github.com/fatih/camelcase/.travis.yml
  vendor/github.com/fatih/camelcase/LICENSE.md
  vendor/github.com/fatih/camelcase/README.md
  vendor/github.com/fatih/camelcase/camelcase.go
  vendor/k8s.io/client-go/util/certificate/csr/csr.go
  vendor/k8s.io/kubectl/pkg/apps/kind_visitor.go
  vendor/k8s.io/kubectl/pkg/cmd/util/podcmd/podcmd.go
  vendor/k8s.io/kubectl/pkg/describe/describe.go
  vendor/k8s.io/kubectl/pkg/describe/interface.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/attachablepodforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/canbeexposed.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/history.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/historyviewer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/interface.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/logsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/mapbasedselectorforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectpauser.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectrestarter.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/objectresumer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/portsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/protocolsforobject.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollback.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollbacker.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollout_status.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/statusviewer.go
  vendor/k8s.io/kubectl/pkg/polymorphichelpers/updatepodspec.go
  vendor/k8s.io/kubectl/pkg/util/certificate/certificate.go
  vendor/k8s.io/kubectl/pkg/util/deployment/deployment.go
  vendor/k8s.io/kubectl/pkg/util/event/sorted_event_list.go
  vendor/k8s.io/kubectl/pkg/util/fieldpath/fieldpath.go
  vendor/k8s.io/kubectl/pkg/util/podutils/podutils.go
  vendor/k8s.io/kubectl/pkg/util/qos/qos.go
  vendor/k8s.io/kubectl/pkg/util/rbac/rbac.go
  vendor/k8s.io/kubectl/pkg/util/resource/resource.go
  vendor/k8s.io/kubectl/pkg/util/slice/slice.go
  vendor/k8s.io/kubectl/pkg/util/storage/storage.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#1647 Add comments about why resource template not exist
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1650 Disable fossa on forked repository
  .github/workflows/fossa.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#1654 Add lifted information for logs.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/logs.go
  pkg/util/lifted/logs_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#1633 Add ReflectStatus ResourceInterperter interface to grab workload status
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/status/workstatus_controller.go
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
  pkg/resourceinterpreter/defaultinterpreter/default.go
  pkg/resourceinterpreter/defaultinterpreter/reflectstatus.go
  pkg/resourceinterpreter/defaultinterpreter/reflectstatus_test.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/helper/unstructured.go
  pkg/util/helper/workstatus.go
Labels: kind/feature, approved, size/L, lgtm

#1649 Support multiple arch: amd64, arm64.
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  Makefile
Labels: kind/bug, approved, lgtm, size/M

#1638 Add watch function for karmadactl get
  pkg/karmadactl/get.go
Labels: kind/feature, approved, size/L, lgtm

#1627 introduce schedulerOptions to optimize scheduler instantiation
  cmd/scheduler/app/scheduler.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, approved, size/L, lgtm, tide/merge-method-squash

#1660 Automated cherry pick of #1649: Support multiple arch: amd64, arm64.
  .github/workflows/dockerhub-released-image.yml
  Makefile
Labels: size/S, approved, lgtm

#1661 Automated cherry pick of #1649: Support multiple arch: amd64, arm64.
  .github/workflows/dockerhub-released-image.yml
  Makefile
Labels: size/S, approved, lgtm

#1646 support region spread constraint
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_cluster.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_region_test.go
  pkg/scheduler/core/spreadconstraint/util.go
Labels: kind/feature, approved, size/L, lgtm

#1658 remove karmada-system in chart
  charts/templates/_karmada_webhook_configuration.tpl
Labels: approved, lgtm, size/XS, kind/cleanup

#1657 add ut for discovery
  pkg/util/lifted/discovery_test.go
  pkg/util/lifted/doc.go
Labels: approved, size/L, lgtm, kind/cleanup

#1667 uniform variables for scripts in document
  docs/working-with-anp.md
Labels: approved, kind/documentation, lgtm, size/XS

#1672 improved the output of 'kubectl get cluster -o wide'
  pkg/printers/internalversion/printers.go
  pkg/printers/internalversion/printers_test.go
Labels: size/S, approved, lgtm

#1668 Sort the aggregatedStatus in rb/crb by the clusterName
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1665 [E2E] add e2e for serviceStatus collection
  test/e2e/resource_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1677 adjust the format in charts
  charts/templates/_helpers.tpl
  charts/templates/etcd.yaml
  charts/templates/karmada-aggregated-apiserver.yaml
  charts/templates/karmada_apiserver.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#927 refactor Dockerfile using multi-stage docker build
  Makefile
  cluster/images/karmada-agent/Dockerfile
  cluster/images/karmada-aggregated-apiserver/Dockerfile
  cluster/images/karmada-controller-manager/Dockerfile
  cluster/images/karmada-descheduler/Dockerfile
  cluster/images/karmada-interpreter-webhook-example/Dockerfile
  cluster/images/karmada-scheduler-estimator/Dockerfile
  cluster/images/karmada-scheduler/Dockerfile
  cluster/images/karmada-webhook/Dockerfile
  hack/docker.sh
  hack/util.sh
  hack/version.sh
Labels: kind/feature, approved, size/L, lgtm

#1678 fix typo in sample-nginx.svg
  docs/images/sample-nginx.svg
Labels: approved, lgtm, size/XS, kind/cleanup

#1681 remove arch for dockerhub image ci
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: kind/bug, size/S, approved, lgtm

#1671 add ut for dependencies
  pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1683 Fix karmadactl init karmada-controller-manager leader elect failure
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/bug, approved, lgtm, size/XS

#1655 [Docs]Add karmada-gatekeeper-guide for users
  docs/working-with-gatekeeper.md
Labels: kind/feature, approved, size/L, lgtm

#1688 Automated cherry pick of #1681: remove arch for dockerhub image ci
  .github/workflows/dockerhub-released-image.yml
Labels: size/S, approved, lgtm

#1687 Automated cherry pick of #1681: remove arch for dockerhub image ci
  .github/workflows/dockerhub-released-image.yml
Labels: size/S, approved, lgtm

#1689 Automated cherry pick of #1683: add `leader-elect-resource-namespace` flags
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/XS

#1690 Automated cherry pick of #1683: add `leader-elect-resource-namespace` flags
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/XS

#1693 Automated cherry pick of #927: refactor Dockerfile using multi-stage docker build
  Makefile
  cluster/images/karmada-agent/Dockerfile
  cluster/images/karmada-aggregated-apiserver/Dockerfile
  cluster/images/karmada-controller-manager/Dockerfile
  cluster/images/karmada-interpreter-webhook-example/Dockerfile
  cluster/images/karmada-scheduler-estimator/Dockerfile
  cluster/images/karmada-scheduler/Dockerfile
  cluster/images/karmada-webhook/Dockerfile
  hack/docker.sh
  hack/util.sh
  hack/version.sh
Labels: approved, size/L, lgtm

#1679 [E2E] add e2e for ingressStatus collection
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
  pkg/resourceinterpreter/defaultinterpreter/reflectstatus.go
  pkg/util/helper/unstructured.go
  test/e2e/framework/ingress.go
  test/e2e/resource_test.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm, kind/cleanup
