Repository karmada-io/karmada, pull requests merged in 2022-03, with the labels that each got.

#1414 [docs] Correct the syntax errors in the mci document
  docs/multi-cluster-ingress.md
Labels: size/S, approved, kind/documentation, lgtm, release-note-none

#1413 Add Karmada logo printing in remote-up-karmada.sh
  hack/local-up-karmada.sh
  hack/remote-up-karmada.sh
  hack/util.sh
Labels: approved, lgtm, size/M, kind/flake, release-note-none

#1415 remove duplicated `GetWorks` function
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/util/helper/binding.go
  pkg/util/helper/work.go
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1306 fix: karmada join failed when secret exist
  pkg/util/secret.go
Labels: kind/bug, release-note, approved, lgtm, size/XS

#1421 Add upgrade document about v1.0-v1.1
  docs/upgrading/README.md
  docs/upgrading/v1.0-v1.1.md
Labels: approved, kind/documentation, lgtm, size/M, release-note-none

#1424 Fetch resource from cache instead of api server
  pkg/detector/detector.go
Labels: approved, lgtm

#1399 Introduce ratelimiter flags
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  go.mod
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/context/context.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/descheduler/descheduler.go
  pkg/detector/detector.go
  pkg/scheduler/scheduler.go
  pkg/util/ratelimiter/rate_limiter.go
  pkg/util/worker.go
Labels: release-note, approved, size/L, lgtm, kind/cleanup

#1419 remove redundant code and improve test coverage
  pkg/util/binding.go
  pkg/util/binding_test.go
Labels: approved, size/L, lgtm, kind/cleanup, release-note-none

#1429 add validation for federatedResourceQuota create/update
  artifacts/deploy/webhook-configuration.yaml
  cmd/webhook/app/webhook.go
  pkg/webhook/federatedresourcequota/helper/helper.go
  pkg/webhook/federatedresourcequota/validating.go
  pkg/webhook/federatedresourcequota/validating_util.go
Labels: kind/feature, approved, size/L, lgtm, release-note-none

#1425 Wait for APIService status when installing karmada with `karmadactl init`
  pkg/karmadactl/cmdinit/karmada/check.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/helper/helpers.go
  vendor/modules.txt
Labels: kind/feature, release-note, approved, size/L, lgtm

#1366 moving RB status aggregating from detector to controller
  pkg/controllers/binding/binding_controller.go
  pkg/detector/detector.go
Labels: approved, size/L, lgtm, kind/cleanup, release-note-none

#1383 [feature]support rescheduling when deleting a cluster
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler.go
  test/e2e/rescheduling_test.go
Labels: kind/feature, release-note, approved, size/L, lgtm

#1426 fix bug: fix can not use '-v 6' to set log level when run kubectl-karmada
  pkg/karmadactl/karmadactl.go
Labels: kind/bug, release-note, approved, lgtm, size/XS

#1431 [docs] Update installation.md document
  docs/installation/installation.md
Labels: approved, kind/documentation, lgtm, size/M, release-note-none

#1440 fix failing failover testing
  pkg/scheduler/core/generic_scheduler.go
  test/e2e/rescheduling_test.go
Labels: approved, size/L, lgtm, kind/flake, release-note-none

#1436 improve test coverage
  pkg/util/annotation.go
  pkg/util/annotation_test.go
Labels: approved, size/L, lgtm, kind/cleanup, release-note-none

#1416 `karmadactl`: Fixed `--namespace` flag of `init` command not work issue.
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/bug, release-note, approved, lgtm, size/M

#1442 Fix karmada crds being too big
  charts/templates/pre-install-job.yaml
Labels: kind/bug, approved, lgtm, size/XS, release-note-none

#1438 Fix charts appVersion
  charts/Chart.yaml
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1427 clean up scheduler metrics
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/metrics/metrics_record.go
  pkg/scheduler/scheduler.go
Labels: approved, size/L, lgtm, kind/cleanup, release-note-none

#1401 Generate API documents for Karmada CRD
  api/openapi-spec/swagger.json
  hack/tools/swagger/generateswagger.go
  hack/tools/swagger/lib/render.go
  hack/tools/swagger/lib/storage.go
  hack/update-codegen.sh
  hack/update-swagger-docs.sh
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/config/v1alpha1/doc.go
  pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
  pkg/apis/networking/v1alpha1/doc.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/policy/v1alpha1/doc.go
  pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/work/v1alpha1/doc.go
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/doc.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, release-note, approved, size/XXL, lgtm

#1447 Don't retain service nodeport when updating service
  pkg/resourceinterpreter/defaultinterpreter/retain.go
Labels: kind/feature, release-note, approved, lgtm, size/M

#1457 fix rbac in karmada_agent.yaml for charts
  charts/templates/karmada_agent.yaml
Labels: kind/bug, release-note, approved, lgtm, size/XS

#1452 cherry-pick #1416: `karmadactl`: Fixed `--namespace` flag of `init` command not work issue.
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/bug, release-note, approved, lgtm, size/M

#1451 cherry-pick #1416: `karmadactl`: Fixed `--namespace` flag of `init` command not work issue.
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/bug, release-note, approved, lgtm, size/M

#1458 Prevented network api from propagating
  pkg/util/apigroup.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1448 fix rb spec.Clusters is incorrent in some scenarios
  pkg/scheduler/core/division_algorithm.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1462 accelerate merge clusters during schedule and improve test coverage
  pkg/util/binding.go
  pkg/util/binding_test.go
Labels: approved, size/L, lgtm, kind/cleanup, release-note-none

#1444 [helm chart] fix version constraints skip prerelease issue
  charts/Chart.yaml
Labels: kind/bug, release-note, approved, lgtm, size/XS

#1465 Automated cherry pick of #1444: Fix helm charts k8s version check
  charts/Chart.yaml
Labels: release-note, approved, lgtm, size/XS

#1466 Automated cherry pick of #1444: Fix helm charts k8s version check
  charts/Chart.yaml
Labels: release-note, approved, lgtm, size/XS

#1434 Add a document for Karmadactl promote command
  docs/userguide/promote-legacy-workload.md
Labels: approved, kind/documentation, lgtm, size/M, release-note-none

#1449 replace hard coded namespace with custom namespace
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: release-note, size/S, approved, lgtm, kind/design

#1455 delete the karmada data directory before installing with init
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/format.go
Labels: kind/feature, release-note, size/S, approved, lgtm

#1464 make webhook server certificate name and key name configurable
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
Labels: kind/feature, release-note, size/S, approved, lgtm

#1433 [helm chart] make rolling update strategy configurable
  charts/templates/karmada-aggregated-apiserver.yaml
  charts/templates/karmada_agent.yaml
  charts/templates/karmada_apiserver.yaml
  charts/templates/karmada_controller_manager.yaml
  charts/templates/karmada_scheduler.yaml
  charts/templates/karmada_scheduler_estimator.yaml
  charts/templates/karmada_webhook.yaml
  charts/templates/kube_controller_manager.yaml
  charts/values.yaml
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1475 fix descheduler crash
  artifacts/deploy/karmada-descheduler.yaml
  cmd/descheduler/app/options/options.go
  pkg/descheduler/core/helper.go
  pkg/descheduler/descheduler.go
Labels: kind/bug, size/S, priority/important-soon, approved, lgtm, release-note-none

#1473 Automated cherry pick of #1455: delete the karmada data directory before installing with init
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/format.go
Labels: release-note, size/S, approved, lgtm

#1474 Automated cherry pick of #1455: delete the karmada data directory before installing with init
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/format.go
Labels: release-note, size/S, approved, lgtm

#1437 Fix `karmadactl init` can not read KUBECONFIG environment variable issue
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: kind/bug, release-note, approved, lgtm, size/M

#1468 grouping flags for karmada-controller-manager
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/sharedcli/commandusage.go
  pkg/sharedcli/docs.go
  pkg/sharedcli/klogflag/klogflag.go
  vendor/k8s.io/component-base/term/OWNERS
  vendor/k8s.io/component-base/term/term.go
  vendor/modules.txt
Labels: kind/feature, release-note, approved, size/L, lgtm

#1479 add docs for descheduler
  docs/descheduler.md
Labels: approved, size/L, kind/documentation, lgtm, release-note-none

#1477 replace update method with patch method when updating schedule result
  pkg/scheduler/scheduler.go
Labels: release-note, approved, lgtm, size/M, kind/cleanup

#1481 optimize the failover e2e test case
  test/e2e/failover_test.go
  test/e2e/rescheduling_test.go
  test/helper/scheduler.go
Labels: approved, lgtm, kind/failing-test, size/M, release-note-none

#1483 Automated cherry pick of #1437: fix `karmadactl init` can not read KUBECONFIG environment variable issue
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: release-note, approved, lgtm, size/M

#1482 Automated cherry pick of #1437: fix `karmadactl init` can not read KUBECONFIG environment variable issue
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: release-note, approved, lgtm, size/M

#1484 Rename karmada controller manager yaml file name
  artifacts/deploy/karmada-controller-manager.yaml
  hack/deploy-karmada.sh
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1389 Implement flags grouping for karmada-agent
  cmd/agent/app/agent.go
Labels: kind/feature, size/S, approved, lgtm, release-note-none

#1488 Implement flags grouping for karmada-webhook
  cmd/webhook/app/webhook.go
Labels: kind/feature, size/S, approved, lgtm, release-note-none

#1486 [CI] Support run CI with multi version kubernetes
  .github/workflows/ci.yml
Labels: kind/feature, release-note, size/S, approved, lgtm

#1456 `karmadactl`: Fixed `init` commands can not select default release version issue.
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/version/release.go
  pkg/version/release_test.go
Labels: kind/bug, release-note, approved, size/L, lgtm

#1450 [UT] Add UT for FederatedResourceQuota validating
  pkg/util/lifted/resourcehelpers_test.go
  pkg/util/lifted/validateresourcequota_test.go
  pkg/webhook/federatedresourcequota/validating.go
  pkg/webhook/federatedresourcequota/validating_test.go
Labels: kind/feature, approved, size/L, lgtm, release-note-none

#1496 Automated cherry pick of #1456: fix init image and crd default version #1495: Fix failling test due to outdate vendor
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/version/release.go
  pkg/version/release_test.go
Labels: release-note, approved, size/L, lgtm

#1490 Implement flags grouping for karmada-descheduler
  cmd/descheduler/app/descheduler.go
  cmd/descheduler/app/options/options.go
Labels: kind/feature, size/S, approved, lgtm, release-note-none

#1493 Implement flags grouping for karmada-scheduler-estimator
  cmd/scheduler-estimator/app/options/options.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
Labels: kind/feature, size/S, approved, lgtm, release-note-none

#1497 Automated cherry pick of #1456: fix init image and crd default version #1495: Fix failling test due to outdate vendor
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/version/release.go
  pkg/version/release_test.go
Labels: release-note, approved, size/L, lgtm

#1491 Implement flags grouping for karmada-scheduler
  cmd/scheduler/app/scheduler.go
Labels: kind/feature, size/S, approved, lgtm, release-note-none

#1500 extend the score process to support the normalizeScore and scoreWeight
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/apiinstalled/api_installed.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/runtime/framework.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#1494 Implement flags grouping for karmada-aggregated-apiserver
  cmd/aggregated-apiserver/app/aggregated-apiserver.go
Labels: kind/feature, size/S, approved, lgtm, release-note-none

#1499 bugfixs of dependencies distributor
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: kind/bug, release-note, size/S, approved, lgtm

#1489 Refactor ratelimit flags to make it easier to share with karmada-agent.
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/context/context.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/detector/detector.go
  pkg/sharedcli/ratelimiterflag/ratelimiterflag.go
  pkg/util/ratelimiter/rate_limiter.go
  pkg/util/worker.go
Labels: approved, size/L, lgtm, kind/cleanup, release-note-none

#1502 enable build multi platforms image
  Makefile
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1504 Publish latest image to dockerhub
  .github/workflows/dockerhub-latest-image.yml
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1505 Add ratelimiter flags for karmada-agent
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/execution/execution_controller.go
Labels: kind/feature, release-note, size/S, approved, lgtm

#1507 Automated cherry pick of #1499: bugfix: enqueue the resource binding that has been
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: release-note, size/S, approved, lgtm

#1463 [E2E] Add e2e for FederatedResourceQuota sync
  test/e2e/federatedresourcequota_test.go
  test/e2e/framework/federatedresourcequota.go
  test/e2e/framework/resourcequota.go
  test/e2e/suite_test.go
  test/helper/policy.go
Labels: kind/feature, approved, size/L, lgtm, release-note-none

#1498 build and push image to docker hub in a a separate action
  .github/workflows/dockerhub-released-image.yml
Labels: approved, lgtm, size/M, release-note-none

#1510 Add verify script for swagger-docs
  hack/update-all.sh
  hack/verify-all.sh
  hack/verify-swagger-docs.sh
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#1514 Automated cherry pick of #1502: enable build multi platforms image
  Makefile
Labels: approved, lgtm, size/M, release-note-none

#1515 Automated cherry pick of #1502: enable build multi platforms image
  Makefile
Labels: approved, lgtm, size/M, release-note-none

#1516 Verify swagger docs in CI
  .github/workflows/ci.yml
Labels: size/S, approved, lgtm, kind/cleanup, release-note-none

#1512 Fixed the `FullyApplied` condition of `RB/CRB` mislabeling issue in case of non-scheduled.
  pkg/util/helper/workstatus.go
  pkg/util/helper/workstatus_test.go
Labels: kind/bug, release-note, approved, size/L, lgtm

#1517 Automated cherry pick of #1512: fix the fulluapplied status is wrong in some scenario
  pkg/util/helper/workstatus.go
  pkg/util/helper/workstatus_test.go
Labels: release-note, approved, size/L, lgtm

#1518 Automated cherry pick of #1512: fix the fulluapplied status is wrong in some scenario
  pkg/util/helper/workstatus.go
  pkg/util/helper/workstatus_test.go
Labels: release-note, approved, size/L, lgtm

#1508 add e2e test for dependencies distributor
  artifacts/deploy/karmada-controller-manager.yaml
  test/e2e/dependenciesdistributor_test.go
  test/e2e/framework/configmap.go
  test/e2e/framework/deployment.go
  test/e2e/framework/propagationpolicy.go
  test/e2e/framework/secret.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: release-note, approved, size/L, lgtm, kind/failing-test

#1521 [E2E] move clean operation to AfterEach
  test/e2e/mcs_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1513 bugfix: update binding status when work's applied condition status changed
  pkg/controllers/binding/common.go
Labels: kind/bug, release-note, approved, lgtm, size/XS

#1523 Automated cherry pick of #1513: bugfix: aggregate status to binding when work's applied condition status changed
  pkg/controllers/binding/common.go
Labels: approved, lgtm, size/XS

#1524 Automated cherry pick of #1513: bugfix: aggregate status to binding when work's applied condition status changed
  pkg/controllers/binding/common.go
Labels: approved, lgtm, size/XS

#1522 add a ut for pod.go
  pkg/util/helper/pod_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1526 Docs: Adoptions in VIPKID
  docs/adoptions/vipkid-zh.md
  docs/images/adoptions-vipkid-architecture.png
Labels: approved, size/L, kind/documentation, lgtm

#1519 bump alpine base image from v3.7 to v3.15.1
  cluster/images/karmada-agent/Dockerfile
  cluster/images/karmada-aggregated-apiserver/Dockerfile
  cluster/images/karmada-controller-manager/Dockerfile
  cluster/images/karmada-descheduler/Dockerfile
  cluster/images/karmada-interpreter-webhook-example/Dockerfile
  cluster/images/karmada-scheduler-estimator/Dockerfile
  cluster/images/karmada-scheduler/Dockerfile
  cluster/images/karmada-webhook/Dockerfile
  hack/local-up-karmada.sh
Labels: size/S, approved, lgtm, kind/cleanup, release-note-none

#1527 Add cluster proxy rbac for admin when deploy Karmada control plane
  artifacts/deploy/cluster-proxy-admin-rbac.yaml
  hack/deploy-karmada.sh
Labels: kind/feature, size/S, approved, lgtm

#1506 refactor the selectclusters process
  go.mod
  go.sum
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/group_clusters_test.go
  pkg/scheduler/core/spreadconstraint/select_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters_test.go
  pkg/scheduler/core/spreadconstraint/util.go
  pkg/util/spreadstate.go
  vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm, release-note-none

#1533 Tidy workflow of images publishment
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#1478 Enable `karmadactl get` command to leverage aggregated API
  pkg/karmadactl/get.go
  pkg/karmadactl/get_flags.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#1536 Build and push release image to SWR and DockerHub
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/swr-released-image.yml
  Makefile
Labels: approved, lgtm, size/M, kind/cleanup

#1537 Build and push release image to SWR and DockerHub
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/swr-released-image.yml
  Makefile
Labels: approved, lgtm, size/M, kind/cleanup

#1538 improve test coverage
  pkg/util/names/names_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1542 add ut for node helper
  pkg/util/helper/node_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1400 add e2etest for aggregated api endpoint
  test/e2e/aggregatedapi_test.go
  test/e2e/framework/rbac.go
  test/e2e/suite_test.go
  test/helper/request.go
  test/helper/resource.go
Labels: approved, size/L, lgtm

#1543 update the judgement for setting completions with job
  pkg/controllers/binding/common.go
Labels: size/S, approved, lgtm, kind/cleanup

#1539 Docs: adoption case from VIPKID
  docs/README.md
  docs/adoptions/vipkid-en.md
  docs/adoptions/vipkid-zh.md
  docs/images/adoptions-vipkid-architecture-en.png
  docs/images/adoptions-vipkid-architecture-zh.png
Labels: approved, size/L, kind/documentation, lgtm

#1334 add plugin clusterLocality to favor cluster
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go
  pkg/scheduler/framework/plugins/registry.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, release-note, approved, lgtm, size/M

#1548 [E2E] fix failing e2e case for namespace not found
  test/e2e/aggregatedapi_test.go
Labels: approved, lgtm, size/XS, kind/failing-test

#1182 update binding's labels when it's policy has been deleted
  pkg/detector/detector.go
Labels: approved, lgtm, size/M, kind/cleanup

#1549 Update owner file as owner changed his name.
  charts/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#703 add proposal of Dependencies Automatically Propagation
  docs/proposals/dependencies-automatically-propagation/README.md
  docs/proposals/dependencies-automatically-propagation/dependenciesOfDeployment.png
  docs/proposals/dependencies-automatically-propagation/propagateDeps.png
Labels: approved, size/L, lgtm, kind/design

#1360 add hpa proposal draft
  docs/proposals/hpa/federated-hpa.md
  docs/proposals/hpa/statics/karmadafederatedhpa-arch.drawio
  docs/proposals/hpa/statics/karmadafederatedhpa-arch.drawio.png
Labels: approved, size/L, lgtm, release-note-none

#1559 Add output information when no resource is found
  pkg/karmadactl/get.go
  pkg/karmadactl/promote.go
Labels: kind/feature, approved, lgtm, size/M

#487 cleanup propagated resources
  docs/keps/cleanup-propagated-resources.md
Labels: kind/feature, approved, size/L, lgtm

#1562 [fix] Add a log reminder for creating a cluster
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#1558 Add documents about controllers inherited from kubernetes.
  docs/userguide/configure-controllers.md
Labels: approved, kind/documentation, lgtm, size/M

#1561 English meeting start to propose
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1566 [fix] Add docker existence check
  hack/local-up-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#1547 helm: add cluster proxy rbac for admin when deploy Karmada control plane
  charts/README.md
  charts/templates/cluster-proxy-admin-rbac.yaml
Labels: kind/feature, approved, size/L, lgtm

#1565 add parallelizer and benchmark test in estimator for performance
  cmd/scheduler-estimator/app/options/options.go
  pkg/estimator/server/nodes/filter.go
  pkg/estimator/server/server.go
  pkg/estimator/server/server_test.go
  pkg/util/lifted/parallelism.go
  test/helper/resource.go
Labels: kind/feature, approved, size/L, lgtm

#1550 karmadactl init: add cluster proxy rbac for admin when deploy Karmada control plane
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/rbac.go
  pkg/karmadactl/cmdinit/utils/rbac.go
Labels: kind/feature, approved, size/L, lgtm
