Repository karmada-io/karmada, pull requests merged in 2022-11, with the labels that each got.

#2709 improve predicate.go
  pkg/util/helper/predicate.go
  pkg/util/helper/predicate_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2700 add ut for resource.go
  pkg/util/resource.go
  pkg/util/resource_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2715 clean up proxy repeating code
  pkg/registry/cluster/storage/proxy.go
  pkg/registry/cluster/storage/proxy_test.go
  pkg/registry/cluster/storage/storage.go
  pkg/search/proxy/framework/plugins/cluster/cluster.go
  pkg/search/proxy/framework/plugins/cluster/cluster_test.go
  pkg/search/proxy/framework/plugins/karmada/karmada_test.go
  pkg/util/proxy/proxy.go
  pkg/util/proxy/proxy_test.go
  pkg/util/testing/mock_responder.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2717 replace the ioutil by the os and io
  hack/tools/genkarmadactldocs/gen_karmadactl_docs.go
  hack/tools/preferredimports/preferredimports.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/karmadactl/register.go
  pkg/search/proxy/framework/plugins/cluster/cluster.go
  pkg/search/proxy/framework/plugins/cluster/cluster_test.go
  pkg/webhook/interpreter/http.go
Labels: approved, lgtm, size/M, kind/cleanup

#2716 Add UT for imageoverride
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/overridemanager/imageoverride_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2706 [ut] add ut for cache.go, mcs.go, and improve DeleteEndpointSlice
  pkg/util/helper/cache_test.go
  pkg/util/helper/mcs.go
  pkg/util/helper/mcs_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2726 modify README.md for Kubernetes compatibility
  README.md
Labels: size/S, approved, lgtm, kind/cleanup

#2714 fix bugs of nodeMaxAvailableReplica
  pkg/estimator/server/estimate.go
Labels: kind/bug, approved, lgtm, size/XS

#2724 Fix and unify `CreateOrUpdateXXX` functions for karmadactl
  pkg/karmadactl/addons/descheduler/descheduler.go
  pkg/karmadactl/addons/estimator/estimator.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/addons/utils/idempotency.go
  pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
  pkg/karmadactl/cmdinit/utils/configmap.go
  pkg/karmadactl/cmdinit/utils/rbac.go
  pkg/karmadactl/register.go
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
  pkg/karmadactl/util/idempotency.go
  pkg/karmadactl/util/idempotency_test.go
  pkg/util/secret.go
  pkg/util/secret_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2725 add ut for policy priority
  pkg/detector/compare.go
  pkg/detector/compare_test.go
  pkg/detector/detector.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2708 Add code coverage badge to provide quick insight
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#2729 optimize error message for collectClusterID
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2730 Fix karmadactl token that can't set `--kubeconfig`
  pkg/karmadactl/token.go
Labels: kind/bug, approved, lgtm, size/M

#2707 karmadactl token：print correct register command according to the karm…
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/register.go
  pkg/karmadactl/token.go
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
Labels: kind/bug, size/S, approved, lgtm

#2734 Disable the preemption matching of pp/cpp priority
  pkg/detector/detector.go
  pkg/detector/policy.go
Labels: kind/bug, approved, size/L, lgtm

#2738 Automated cherry pick of #2734: Disable the preemption matching of pp/cpp priority
  pkg/detector/detector.go
  pkg/detector/policy.go
Labels: approved, size/L, lgtm

#2739 Automated cherry pick of #2734: Disable the preemption matching of pp/cpp priority
  pkg/detector/detector.go
  pkg/detector/policy.go
Labels: approved, size/L, lgtm

#2740 Automated cherry pick of #2734: Disable the preemption matching of pp/cpp priority
  pkg/detector/detector.go
  pkg/detector/policy.go
Labels: approved, size/L, lgtm

#2741 Increase codecov successful uploads
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#2745 Make event messages more readable
  pkg/descheduler/descheduler.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2742 Stop update krew for release 1.2.x
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#2747 Stop update krew for release 1.1.x
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#2749 add Garrybest as descheduler owner
  cmd/descheduler/OWNERS
  pkg/descheduler/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#2748 reuse context for controller-manager base-context
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/certificate/cert_rotation_controller.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: kind/feature, approved, lgtm, size/M, kind/cleanup

#2673 Add arges check for karmadactl deinit
  pkg/karmadactl/deinit.go
Labels: kind/feature, approved, lgtm, size/XS

#2694 karmadactl promote uses factory to access cluster
  pkg/karmadactl/get.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/promote.go
  test/e2e/karmadactl_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/cleanup

#2719 Resource Interpreter Framework cache and reorganize configurations
  pkg/resourceinterpreter/configurableinterpreter/configmanager/accessor.go
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/configurableinterpreter/configurable.go
  pkg/resourceinterpreter/interpreter.go
Labels: kind/feature, approved, size/L, lgtm

#2752 karmadactl join/unjoin use factory to access control plane
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/karmadactl/addons/init/disable_option.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/addons/init/global.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/kubeclient.go
  pkg/karmadactl/config.go
  pkg/karmadactl/deinit.go
  pkg/karmadactl/get.go
  pkg/karmadactl/get_flags.go
  pkg/karmadactl/join.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/register.go
  pkg/karmadactl/unjoin.go
  pkg/karmadactl/util/apiclient/apiclient.go
  test/e2e/aggregatedapi_test.go
  test/e2e/federatedresourcequota_test.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/cleanup

#2744 Automated cherry pick of #2707 on release-1.3.
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/register.go
  pkg/karmadactl/token.go
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
Labels: size/S, approved, lgtm

#2731 Resource Interpreter framework introduce Lua runtime layer
  go.mod
  go.sum
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_convert.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go
  pkg/util/lifted/lua_oslib_safe.go
  vendor/github.com/yuin/gopher-lua/.travis.yml
  vendor/github.com/yuin/gopher-lua/LICENSE
  vendor/github.com/yuin/gopher-lua/Makefile
  vendor/github.com/yuin/gopher-lua/README.rst
  vendor/github.com/yuin/gopher-lua/_state.go
  vendor/github.com/yuin/gopher-lua/_vm.go
  vendor/github.com/yuin/gopher-lua/alloc.go
  vendor/github.com/yuin/gopher-lua/ast/ast.go
  vendor/github.com/yuin/gopher-lua/ast/expr.go
  vendor/github.com/yuin/gopher-lua/ast/misc.go
  vendor/github.com/yuin/gopher-lua/ast/stmt.go
  vendor/github.com/yuin/gopher-lua/ast/token.go
  vendor/github.com/yuin/gopher-lua/auxlib.go
  vendor/github.com/yuin/gopher-lua/baselib.go
  vendor/github.com/yuin/gopher-lua/channellib.go
  vendor/github.com/yuin/gopher-lua/compile.go
  vendor/github.com/yuin/gopher-lua/config.go
  vendor/github.com/yuin/gopher-lua/coroutinelib.go
  vendor/github.com/yuin/gopher-lua/debuglib.go
  vendor/github.com/yuin/gopher-lua/function.go
  vendor/github.com/yuin/gopher-lua/iolib.go
  vendor/github.com/yuin/gopher-lua/linit.go
  vendor/github.com/yuin/gopher-lua/loadlib.go
  vendor/github.com/yuin/gopher-lua/mathlib.go
  vendor/github.com/yuin/gopher-lua/opcode.go
  vendor/github.com/yuin/gopher-lua/oslib.go
  vendor/github.com/yuin/gopher-lua/package.go
  vendor/github.com/yuin/gopher-lua/parse/Makefile
  vendor/github.com/yuin/gopher-lua/parse/lexer.go
  vendor/github.com/yuin/gopher-lua/parse/parser.go
  vendor/github.com/yuin/gopher-lua/parse/parser.go.y
  vendor/github.com/yuin/gopher-lua/pm/pm.go
  vendor/github.com/yuin/gopher-lua/state.go
  vendor/github.com/yuin/gopher-lua/stringlib.go
  vendor/github.com/yuin/gopher-lua/table.go
  vendor/github.com/yuin/gopher-lua/tablelib.go
  vendor/github.com/yuin/gopher-lua/utils.go
  vendor/github.com/yuin/gopher-lua/value.go
  vendor/github.com/yuin/gopher-lua/vm.go
  vendor/layeh.com/gopher-json/LICENSE
  vendor/layeh.com/gopher-json/README.md
  vendor/layeh.com/gopher-json/doc.go
  vendor/layeh.com/gopher-json/json.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#2688 Add the CreateExecutionSpaceSucceed and RemoveExecutionSpaceSucceed event
  pkg/apis/cluster/v1alpha1/events.go
  pkg/controllers/cluster/cluster_controller.go
Labels: kind/feature, size/S, approved, lgtm

#2760 karmadactl uncordon add dryrun
  pkg/karmadactl/cordon.go
Labels: kind/feature, approved, lgtm, size/XS

#2764 Add override policy apply event
  cmd/controller-manager/app/controllermanager.go
  pkg/apis/work/v1alpha2/events.go
  pkg/detector/detector.go
  pkg/util/overridemanager/overridemanager.go
Labels: kind/feature, size/S, approved, lgtm

#2763 fix wrong description for "dry-run" option.
  pkg/karmadactl/register.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2759 remove overridepolicy trigger on cluster_resource_binding_controller
  pkg/controllers/binding/cluster_resource_binding_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2756 lifted-gen.go add flag parse
  hack/tools/lifted-gen/lifted-gen.go
Labels: size/S, approved, lgtm, kind/cleanup

#2562 allow to update the resourceSelector of PropagationPolicy/ClusterPropagationPolicy
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
  pkg/util/helper/policy.go
  pkg/util/label.go
  pkg/util/label_test.go
  pkg/webhook/clusterpropagationpolicy/validating.go
  pkg/webhook/propagationpolicy/validating.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/framework/clusterpropagationpolicy.go
  test/e2e/framework/deployment.go
  test/e2e/framework/propagationpolicy.go
  test/e2e/framework/rbac.go
  test/e2e/propagationpolicy_test.go
Labels: kind/feature, approved, size/XL, lgtm

#2684 New Factory global flags merge function
  pkg/karmadactl/apply.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/taint.go
  pkg/karmadactl/token.go
  pkg/karmadactl/unjoin.go
Labels: kind/feature, approved, size/L, lgtm

#2765 Add limitReader to io.ReadAll
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/webhook/interpreter/http.go
Labels: kind/bug, size/S, approved, lgtm

#2664 Package subcommands of karmadactl to make it clearer
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/karmadactl/addons/addons.go
  pkg/karmadactl/apply/apply.go
  pkg/karmadactl/cordon/cordon.go
  pkg/karmadactl/deinit/deinit.go
  pkg/karmadactl/describe/describe.go
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/get/get.go
  pkg/karmadactl/join/join.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs/logs.go
  pkg/karmadactl/promote/promote.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/taint/taint.go
  pkg/karmadactl/taint/taint_test.go
  pkg/karmadactl/token/token.go
  pkg/karmadactl/unjoin/unjoin.go
  test/e2e/aggregatedapi_test.go
  test/e2e/federatedresourcequota_test.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2774 Automated cherry pick of #2765: Add limitReader to io.ReadAll
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/webhook/interpreter/http.go
Labels: size/S, approved, lgtm

#2776 Automated cherry pick of #2765: Add limitReader to io.ReadAll
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/webhook/interpreter/http.go
Labels: size/S, approved, lgtm

#2758 Introduce priority to PropagationPolicy
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_helper.go
  pkg/apis/policy/v1alpha1/propagation_helper_test.go
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#2770 Add reflectStatusToWork and InterpretHealth event
  pkg/apis/work/v1alpha1/events.go
  pkg/controllers/status/workstatus_controller.go
Labels: kind/feature, size/S, approved, lgtm

#2300 chart: add descheduler name suffix of chart deployment manifest
  charts/karmada/README.md
  charts/karmada/templates/karmada-descheduler.yaml
Labels: kind/bug, approved, lgtm, size/M

#2771 Fix overridepolicy with nil resource selector could not work
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/overridepolicy_test.go
Labels: kind/bug, approved, size/L, lgtm

#2505 fix namespace already exist
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/namespace.go
  pkg/karmadactl/util/idempotency.go
Labels: approved, size/L, lgtm

#2761 refactor util.BuildClusterConfig
  pkg/search/proxy/client_factory.go
  pkg/search/proxy/client_factory_test.go
  pkg/search/proxy/controller.go
  pkg/util/membercluster_client.go
Labels: approved, size/L, lgtm, kind/cleanup

#2788 Automated cherry pick of #2771: fix overridepolicy with nil resource selector could not work
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/overridepolicy_test.go
Labels: approved, size/L, lgtm

#2793 optimize ParseIP
  pkg/karmadactl/cmdinit/utils/ip.go
Labels: kind/feature, size/S, approved, lgtm

#2798 Automated cherry pick of #2771: fix overridepolicy with nil resource selector could not work
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/framework/clusteroverridepolicy.go
  test/e2e/overridepolicy_test.go
  test/helper/policy.go
Labels: approved, size/L, lgtm

#2800 Automated cherry pick of #2771: fix overridepolicy with nil resource selector could not work
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/framework/clusteroverridepolicy.go
  test/e2e/overridepolicy_test.go
  test/helper/policy.go
Labels: approved, size/L, lgtm

#2802 fix etcd sts name hardcode
  pkg/karmadactl/addons/search/search.go
Labels: approved, lgtm, size/XS

#2767 Implement priority of PropagationPolicy
  pkg/detector/compare.go
  pkg/detector/compare_test.go
  pkg/detector/detector.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
  test/helper/policy.go
Labels: kind/feature, approved, size/XXL, lgtm

#2805 [e2e] decrease the number of replicas when updating the number of statefulset replicas
  test/e2e/suite_test.go
Labels: approved, lgtm, size/XS, kind/flake

#2775 Automated cherry pick of #2765: Add limitReader to io.ReadAll
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/webhook/interpreter/http.go
Labels: size/S, approved, lgtm

#2797 fix error when convert from empty lua table
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_convert.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_convert_test.go
Labels: kind/bug, approved, size/L, lgtm

#2803 improve decodeValue for Lua
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go
Labels: kind/bug, approved, size/L, lgtm

#2795 Download images from dockerhub by default
  Makefile
  artifacts/agent/karmada-agent.yaml
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-search.yaml
  artifacts/deploy/karmada-webhook.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml
  hack/docker.sh
  hack/local-up-karmada.sh
  hack/pre-run-e2e.sh
  pkg/karmadactl/addons/enable.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/utils/examples.go
  pkg/karmadactl/register/register.go
Labels: approved, lgtm, size/M, kind/cleanup

#2772 Fix random errors occur during binary compilation
  Makefile
Labels: approved, lgtm, size/XS, kind/failing-test

#2808 Fix PP/CPP e2e probabilistic failure
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: approved, lgtm, size/M, kind/flake

#2778 Put Poor12 onto chart owner list
  charts/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#2777 chart: optimize pod startup order
  charts/karmada/templates/karmada-controller-manager.yaml
Labels: approved, lgtm, size/XS

#2807 Refactor and organize events in unison
  pkg/apis/cluster/v1alpha1/events.go
  pkg/apis/work/v1alpha1/events.go
  pkg/apis/work/v1alpha2/events.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/descheduler/descheduler.go
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/events/events.go
  pkg/scheduler/scheduler.go
  pkg/util/helper/workstatus.go
  pkg/util/overridemanager/overridemanager.go
Labels: approved, size/L, lgtm, kind/cleanup

#2746 Resource Aggregation Proxy: make multi cluster ResourceVersion string stable
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
Labels: kind/bug, approved, size/L, lgtm

#2796 Add SyncImpersonationConfig event
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/events/events.go
Labels: kind/feature, approved, lgtm, size/XS

#2785 Put wuyingjun-lucky onto karmadactl addons owner list
  pkg/karmadactl/addons/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#2790 Fix some call errors of `idempotency.go`
  pkg/karmadactl/util/idempotency.go
Labels: kind/bug, approved, lgtm, size/XS

#2786 [bugfix] ignore resource that do not match with policy before apply policy
  pkg/detector/policy.go
Labels: kind/bug, size/S, approved, lgtm

#2811 [e2e] mark test case `Test clusterOverridePolicy with nil resourceSelectors` as serial
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/overridepolicy_test.go
Labels: approved, lgtm, size/XS, kind/flake

#2794 Resource Interpreter implements the interfaces
  pkg/resourceinterpreter/configurableinterpreter/configmanager/accessor.go
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/configurableinterpreter/configurable.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go
  pkg/resourceinterpreter/interpreter.go
Labels: kind/feature, approved, size/L, lgtm

#2813 Automated cherry pick of #2786: ignore resource that do not match with policy before apply
  pkg/detector/policy.go
Labels: size/S, approved, lgtm

#2814 Automated cherry pick of #2786: ignore resource that do not match with policy before apply
  pkg/detector/policy.go
Labels: size/S, approved, lgtm

#2815 Automated cherry pick of #2786: ignore resource that do not match with policy before apply
  pkg/detector/policy.go
Labels: size/S, approved, lgtm

#2816 Automated cherry pick of #2746: make multi cluster ResourceVersion string stable
  pkg/search/proxy/store/util.go
Labels: approved, lgtm, size/M

#2817 karmadactl: add liveness probe into kube-controller-manager
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/feature, size/S, approved, lgtm

#2655 introduce `--private-image-registry` flag to `karmadactl init`
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
Labels: kind/feature, approved, size/L, lgtm

#2820 Automated cherry pick of #2811: mark test case as serial
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/overridepolicy_test.go
Labels: approved, lgtm, size/XS

#2821 Automated cherry pick of #2811: mark test case as serial
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/overridepolicy_test.go
Labels: approved, lgtm, size/XS

#2801 optimize initAPIService
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/util/idempotency.go
Labels: size/S, approved, lgtm

#2819 e2e: wait till the informer's cache is synced in karmada-controller
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: approved, lgtm, size/M, kind/flake

#2833 karmadactl init: fix MutatingWebhookConfig and ValidateWebhookConfig aren't updated
  pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap.go
  pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration_test.go
  pkg/karmadactl/cmdinit/utils/rbac.go
  pkg/karmadactl/util/idempotency.go
Labels: kind/bug, approved, size/L, lgtm, kind/cleanup

#2607 add ut for util/metrics
  pkg/util/metrics/metrics.go
  pkg/util/metrics/metrics_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2829 [E2E] add test case for resource interpreter customization
  pkg/resourceinterpreter/configurableinterpreter/configurable.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/defaultinterpreter/default.go
  pkg/resourceinterpreter/interpreter.go
  test/e2e/framework/resourceinterpretercustomization.go
  test/e2e/resourceinterpreter_test.go
  test/helper/config.go
  test/helper/resource.go
Labels: kind/feature, approved, size/L, lgtm

#2823 unify namespace and name style
  pkg/controllers/certificate/cert_rotation_controller.go
  pkg/karmadactl/util/idempotency.go
  pkg/util/namespace.go
  pkg/util/rbac.go
  test/e2e/search_test.go
Labels: approved, lgtm, size/M

#2836 Automated cherry pick of #2277: fix kube controller manager restart all the time
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/templates/kube-controller-manager.yaml
Labels: approved, lgtm, size/XS

#2826 Improve karmadactl command description
  pkg/karmadactl/addons/addons.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cordon/cordon.go
  pkg/karmadactl/deinit/deinit.go
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/get/get.go
  pkg/karmadactl/join/join.go
  pkg/karmadactl/promote/promote.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/taint/taint.go
  pkg/karmadactl/unjoin/unjoin.go
Labels: approved, lgtm, size/M, kind/cleanup

#2750 add interpret command
  pkg/karmadactl/interpret/check.go
  pkg/karmadactl/interpret/execute.go
  pkg/karmadactl/interpret/interpret.go
  pkg/karmadactl/interpret/rule.go
  pkg/karmadactl/karmadactl.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
Labels: kind/feature, approved, size/XL, lgtm

#2827 refactor assign replicas strategy
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/generic_scheduler.go
Labels: approved, size/L, lgtm, kind/cleanup

#2832 karmadactl register add args check
  pkg/karmadactl/register/register.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2848 support users can define multiple resourceinterpretercustomization
  pkg/resourceinterpreter/configurableinterpreter/configmanager/accessor.go
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager_test.go
Labels: kind/feature, approved, size/L, lgtm

#2852 Build release-1.3 with go1.18.8
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#2853 Build release-1.2 with go1.17.13
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#2854 Build release-1.1 with go1.17.13
  .github/workflows/ci.yml
  .github/workflows/image.yml
  .github/workflows/release.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#2844 Fix deploy karmada-apiserver error by loadBalancer
  hack/deploy-karmada.sh
  hack/util.sh
Labels: kind/bug, approved, lgtm, size/XS

#2855 fix descheduler estimator connection error
  pkg/descheduler/descheduler.go
Labels: kind/bug, size/S, approved, lgtm

#2857 Update Golang version from v1.18.3 to v1.19.3
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
  README.md
  go.mod
  hack/util.sh
  pkg/apis/cluster/validation/validation.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/printers/tablegenerator.go
  pkg/sharedcli/commandusage.go
  pkg/util/helper/job.go
  pkg/util/lifted/deployment.go
  pkg/util/lifted/requestinfo.go
  pkg/util/lifted/visitpod.go
  test/e2e/scheduling_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2830 Add events for MCS
  pkg/controllers/mcs/service_import_controller.go
  pkg/events/events.go
Labels: kind/feature, approved, lgtm, size/M

#2825 Add more logs and delete some redundant code
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/idempotency.go
  pkg/karmadactl/util/idempotency_test.go
  pkg/util/namespace.go
  pkg/util/namespace_test.go
  pkg/util/rbac.go
  pkg/util/rbac_test.go
  pkg/util/serviceaccount.go
  pkg/util/serviceaccount_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2496 Add metrics for cluster
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/metrics/cluster.go
  pkg/metrics/cluster_test.go
Labels: kind/feature, approved, size/L, lgtm

#2861 Fix karmadactl register failed to read kubeconfig file
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/apiclient/apiclient.go
Labels: kind/bug, size/S, approved, lgtm

#2867 fix karmadactl interpret panic
  pkg/karmadactl/interpret/rule.go
Labels: kind/bug, approved, lgtm, size/XS

#2849 validate cluster fields
  pkg/apis/cluster/validation/validation.go
  pkg/apis/cluster/validation/validation_test.go
Labels: kind/feature, kind/api-change, approved, lgtm, size/M

#2865 Add gofmt script
  .golangci.yml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  hack/update-all.sh
  hack/update-gofmt.sh
  hack/verify-all.sh
  hack/verify-gofmt.sh
Labels: approved, size/L, lgtm, kind/cleanup

#2851 [e2e] Refactor InterpreterOperation retain test with resourceinterpreter
  test/e2e/framework/workload.go
  test/e2e/resourceinterpreter_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2866 fix dirty is not added in docker image tag
  Makefile
  hack/build.sh
  hack/util.sh
  hack/version.sh
Labels: kind/bug, size/S, approved, lgtm

#2870 do not propagate finalizers to member cluster
  pkg/resourceinterpreter/defaultinterpreter/prune/prune.go
Labels: kind/bug, approved, lgtm, size/XS

#2856 [E2E] add test case for resource interpreter customization
  test/e2e/resourceinterpreter_test.go
Labels: kind/feature, approved, lgtm, size/M

#2858 fix setting resource selector default namespace for policy
  pkg/webhook/overridepolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: kind/bug, size/S, approved, lgtm

#2872 Automated cherry pick of #2858: fix setting resource selector default namespace for policy
  pkg/webhook/overridepolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: size/S, approved, lgtm

#2873 Automated cherry pick of #2858: fix setting resource selector default namespace for policy
  pkg/webhook/overridepolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: size/S, approved, lgtm

#2874 Automated cherry pick of #2858: fix setting resource selector default namespace for policy
  pkg/webhook/overridepolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: size/S, approved, lgtm

#2824 add execute mod for interpret command
  go.mod
  pkg/karmadactl/interpret/execute.go
  pkg/karmadactl/interpret/interpret.go
  pkg/karmadactl/interpret/rule.go
  pkg/karmadactl/util/genericresource/builder.go
  pkg/karmadactl/util/genericresource/doc.go
  pkg/karmadactl/util/genericresource/interface.go
  pkg/karmadactl/util/genericresource/result.go
  pkg/karmadactl/util/genericresource/visitor.go
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/configurableinterpreter/configurable.go
Labels: kind/feature, approved, size/XL, lgtm

#2835 Add events for graceful eviction controller
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
  pkg/events/events.go
  pkg/util/helper/binding.go
Labels: kind/feature, approved, size/L, lgtm

#2875 evolute PropagateDeps FeatureGate to Beta and enable it by default
  artifacts/deploy/karmada-controller-manager.yaml
  pkg/features/features.go
Labels: kind/feature, kind/api-change, approved, lgtm, size/XS

#2864 improve lua vm executing with pool
  pkg/resourceinterpreter/configurableinterpreter/configurable.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go
  pkg/util/fixedpool/fixedpool.go
  pkg/util/fixedpool/fixedpool_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2868 Add metrics for resource
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/metrics/resource.go
Labels: kind/feature, approved, size/L, lgtm

#2869 Update ResourceInterpreterCustomization comments according to implementation
  charts/karmada/_crds/bases/config.karmada.io_resourceinterpretercustomizations.yaml
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, size/L, lgtm, kind/cleanup

#2846 fix strategy chart format
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/templates/kube-controller-manager.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#2876 Evolute Failover/GracefulEviction FeatureGate to beta version and enable it by default
  artifacts/deploy/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  pkg/features/features.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/api-change, approved, lgtm, size/XS

#2755 Implement ResourceInterpreterCustomization ValidatingAdmission
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  cmd/webhook/app/webhook.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/interpret/execute.go
  pkg/karmadactl/interpret/interpret.go
  pkg/util/interpreter/matcher.go
  pkg/util/interpreter/matcher_test.go
  pkg/util/interpreter/rule.go
  pkg/webhook/resourceinterpretercustomization/helper.go
  pkg/webhook/resourceinterpretercustomization/helper_test.go
  pkg/webhook/resourceinterpretercustomization/validating.go
Labels: kind/feature, approved, size/XL, lgtm

#2877 Evolute CustomizedClusterResourceModeling to Beta and enable it by default
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-scheduler.yaml
  pkg/features/features.go
Labels: kind/api-change, approved, lgtm, size/XS

#2773 Add getDependencies and syncScheduleResultToDependencies event
  cmd/controller-manager/app/controllermanager.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/events/events.go
Labels: kind/feature, size/S, approved, lgtm

#2886 Add karmadactl interpret examples
  examples/customresourceinterpreter/README.md
  examples/karmadactlinterpret/README.md
  examples/karmadactlinterpret/desired-deploy-nginx.yaml
  examples/karmadactlinterpret/observed-deploy-nginx.yaml
  examples/karmadactlinterpret/resourceinterpretercustomization.yaml
  examples/karmadactlinterpret/status-file.yaml
Labels: kind/feature, approved, size/L, kind/documentation, lgtm

#2889 Add v1.3.0 changelog
  docs/CHANGELOG/CHANGELOG-1.3.md
Labels: approved, size/L, kind/documentation, lgtm
