Repository karmada-io/karmada, pull requests merged in 2022-05, with the labels that each got.

#1699 bump default alpine image of karmadactl init from v3.14.3 to v3.15.1
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1701 [fix] add execute permission to hack/version.sh
  hack/version.sh
Labels: approved, lgtm, size/XS

#1702 Correct the function name error in the comment
  docs/proposals/caching/README.md
  pkg/resourceinterpreter/customizedinterpreter/configmanager/accessor.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1705 fix wehbhook error
  docs/working-with-gatekeeper.md
Labels: approved, lgtm, size/XS, kind/cleanup

#1711 Automated cherry pick of #1701: add execute permission to hack/version.sh
  hack/version.sh
Labels: approved, lgtm, size/XS

#1708 update UserName of kubeconfig with clusterNmae perfix
  pkg/karmadactl/cmdinit/options/global.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1714 Clear global resources while undeploy cluster
  hack/undeploy-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#1686 [Docs]Add overridepolicy guide for users
  docs/override-policy.md
Labels: approved, size/L, kind/documentation, lgtm

#1727 Add namespace propagated waiting check in the SynchronizedBeforeSuite
  test/e2e/aggregatedapi_test.go
  test/e2e/porting_workloads_test.go
  test/e2e/suite_test.go
Labels: size/S, approved, lgtm

#1684 [Docs]: Add Propagate Dependencies user guide
  docs/userguide/propagate-dependencies.md
Labels: approved, size/L, kind/documentation, lgtm

#1707 code optimization : use make build instead of go build on docker multi-stage build
  .github/workflows/ci.yml
  cluster/images/karmada-agent/Dockerfile
  cluster/images/karmada-aggregated-apiserver/Dockerfile
  cluster/images/karmada-controller-manager/Dockerfile
  cluster/images/karmada-descheduler/Dockerfile
  cluster/images/karmada-interpreter-webhook-example/Dockerfile
  cluster/images/karmada-scheduler-estimator/Dockerfile
  cluster/images/karmada-scheduler/Dockerfile
  cluster/images/karmada-webhook/Dockerfile
  hack/docker.sh
Labels: approved, lgtm, size/M

#1656 Add time zone interpretation for local-up-karmada.sh
  hack/local-up-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#1676 Creating Loadbalancer Type Service by Installing the Metallb
  examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml
  examples/customresourceinterpreter/webhook-configuration.yaml
  hack/deploy-karmada.sh
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
Labels: approved, lgtm, size/M, kind/cleanup

#1670 Update judge work contains serviceExport with .spec.workload.manifests
  pkg/controllers/mcs/service_export_controller.go
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/M, kind/cleanup

#1674 Add a CRD for the cached member cluster and resource scope.
  charts/_crds/bases/search.karmada.io_resourceregistries.yaml
  hack/update-codegen.sh
  hack/update-crdgen.sh
  pkg/apis/search/v1alpha1/cache_types.go
  pkg/apis/search/v1alpha1/doc.go
  pkg/apis/search/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/search/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/search/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/search/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/search/v1alpha1/fake/fake_resourceregistry.go
  pkg/generated/clientset/versioned/typed/search/v1alpha1/fake/fake_search_client.go
  pkg/generated/clientset/versioned/typed/search/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/search/v1alpha1/resourceregistry.go
  pkg/generated/clientset/versioned/typed/search/v1alpha1/search_client.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/search/interface.go
  pkg/generated/informers/externalversions/search/v1alpha1/interface.go
  pkg/generated/informers/externalversions/search/v1alpha1/resourceregistry.go
  pkg/generated/listers/search/v1alpha1/expansion_generated.go
  pkg/generated/listers/search/v1alpha1/resourceregistry.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, approved, size/XXL, lgtm, tide/merge-method-squash

#1726 verify crdgen and codegen for examples directory
  hack/verify-codegen.sh
  hack/verify-crdgen.sh
Labels: approved, lgtm, size/M, kind/cleanup

#1731 codegen will update in repository
  hack/update-codegen.sh
  hack/util.sh
Labels: kind/bug, approved, lgtm, size/M

#1675 [Docs]Add karmada-kyverno-guide for users
  docs/working-with-gatekeeper.md
  docs/working-with-kyverno.md
Labels: kind/feature, approved, size/L, kind/documentation, lgtm

#1743 [fix] delete work status 'Resource' field
  pkg/controllers/status/workstatus_controller.go
Labels: kind/feature, approved, lgtm, size/XS

#1732 Bump controller-tools to v0.8.0
  charts/_crds/bases/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  charts/_crds/bases/networking.karmada.io_multiclusteringresses.yaml
  charts/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/_crds/bases/policy.karmada.io_federatedresourcequotas.yaml
  charts/_crds/bases/policy.karmada.io_overridepolicies.yaml
  charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/_crds/bases/search.karmada.io_resourceregistries.yaml
  charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/_crds/bases/work.karmada.io_resourcebindings.yaml
  charts/_crds/bases/work.karmada.io_works.yaml
  examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
  hack/update-crdgen.sh
Labels: approved, size/L, lgtm, kind/cleanup

#1756 revert time zone interpretation for local-up-karmada.sh
  hack/local-up-karmada.sh
Labels: kind/feature, approved, lgtm, size/XS

#1737 [e2e]add e2e for jobStatus,daemonSetStatus,statefulSetStatus collection
  test/e2e/framework/daemonSet.go
  test/e2e/framework/statefulSet.go
  test/e2e/resource_test.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm, kind/cleanup

#1757 fix: update README to fix minor spelling and grammar mistakes.
  README.md
Labels: approved, kind/documentation, lgtm, size/M

#1748 Add --context for karmadactl init
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/kubeclient.go
Labels: kind/feature, size/S, approved, lgtm

#1721 Unify usage example template of karmadactl
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/logs.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/taint.go
  pkg/karmadactl/unjoin.go
Labels: approved, size/L, lgtm, kind/cleanup

#1706 fix empty resource selectors which result to policy will not be consi…
  pkg/util/overridemanager/overridemanager.go
  pkg/util/overridemanager/overridemanager_test.go
Labels: kind/bug, approved, lgtm, size/M

#1733 Skip reflect work status when resource has empty status
  pkg/controllers/status/workstatus_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1740 speed up docker build
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .gitignore
  Makefile
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  cluster/images/karmada-agent/Dockerfile
  cluster/images/karmada-aggregated-apiserver/Dockerfile
  cluster/images/karmada-controller-manager/Dockerfile
  cluster/images/karmada-descheduler/Dockerfile
  cluster/images/karmada-interpreter-webhook-example/Dockerfile
  cluster/images/karmada-scheduler-estimator/Dockerfile
  cluster/images/karmada-scheduler/Dockerfile
  cluster/images/karmada-webhook/Dockerfile
  hack/build.sh
  hack/docker.sh
  hack/local-up-karmada.sh
  hack/util.sh
Labels: kind/feature, approved, size/XL, lgtm

#1759 fixed a panic which due to nil annotation during promote resources to Karmada
  pkg/karmadactl/promote.go
Labels: kind/bug, approved, lgtm, size/XS

#1771 fix docker hub push failed
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: kind/bug, approved, lgtm, size/XS

#1774 fix readonly variable error in `docker.sh`
  hack/docker.sh
Labels: kind/bug, approved, lgtm, size/XS

#1775 modify variable format using hump
  pkg/karmadactl/promote.go
Labels: approved, lgtm, size/XS, kind/flake

#1768 Fix occasionally TestAggregateJobStatus time error
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
Labels: kind/bug, size/S, approved, lgtm

#1682 add update-lifted and verify-lifted
  .github/workflows/ci.yml
  go.mod
  go.sum
  hack/tools/lifted-gen/lifted-gen.go
  hack/update-all.sh
  hack/update-lifted.sh
  hack/verify-all.sh
  hack/verify-lifted.sh
  pkg/util/lifted/corehelpers.go
  pkg/util/lifted/corev1helpers.go
  pkg/util/lifted/corevalidation.go
  pkg/util/lifted/deployment.go
  pkg/util/lifted/discovery.go
  pkg/util/lifted/discovery_test.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/logs.go
  pkg/util/lifted/nodeselector.go
  pkg/util/lifted/objectwatcher.go
  pkg/util/lifted/podtemplate.go
  pkg/util/lifted/requestinfo.go
  pkg/util/lifted/resourcename.go
  pkg/util/lifted/retain.go
  pkg/util/lifted/taint.go
  pkg/util/lifted/validateclustertaints.go
  pkg/util/lifted/visitpod.go
  vendor/github.com/mattn/go-runewidth/.travis.yml
  vendor/github.com/mattn/go-runewidth/LICENSE
  vendor/github.com/mattn/go-runewidth/README.md
  vendor/github.com/mattn/go-runewidth/go.test.sh
  vendor/github.com/mattn/go-runewidth/runewidth.go
  vendor/github.com/mattn/go-runewidth/runewidth_appengine.go
  vendor/github.com/mattn/go-runewidth/runewidth_js.go
  vendor/github.com/mattn/go-runewidth/runewidth_posix.go
  vendor/github.com/mattn/go-runewidth/runewidth_table.go
  vendor/github.com/mattn/go-runewidth/runewidth_windows.go
  vendor/github.com/olekukonko/tablewriter/.gitignore
  vendor/github.com/olekukonko/tablewriter/.travis.yml
  vendor/github.com/olekukonko/tablewriter/LICENSE.md
  vendor/github.com/olekukonko/tablewriter/README.md
  vendor/github.com/olekukonko/tablewriter/csv.go
  vendor/github.com/olekukonko/tablewriter/table.go
  vendor/github.com/olekukonko/tablewriter/table_with_color.go
  vendor/github.com/olekukonko/tablewriter/util.go
  vendor/github.com/olekukonko/tablewriter/wrap.go
  vendor/github.com/rivo/uniseg/LICENSE.txt
  vendor/github.com/rivo/uniseg/README.md
  vendor/github.com/rivo/uniseg/doc.go
  vendor/github.com/rivo/uniseg/grapheme.go
  vendor/github.com/rivo/uniseg/properties.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#1778 use member-cluster-context correctly
  hack/deploy-scheduler-estimator.sh
Labels: kind/bug, approved, lgtm, size/XS

#1766 fixed a bug where not-namespaced resource could not be promoted
  pkg/karmadactl/promote.go
Labels: kind/bug, approved, lgtm, size/M

#1782 compatible with mac os
  hack/build.sh
  hack/util.sh
Labels: kind/bug, approved, lgtm, size/M

#1792 fix karmadactl init examples
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup

#1785 add ut for IsControllerEnabled and update configure-controllers.md
  docs/userguide/configure-controllers.md
  pkg/controllers/context/context_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1764 feature_1753:support kube-image-mirror-country and kube-image-registry
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
Labels: kind/feature, approved, lgtm, size/M

#1787 fix 1769 karmada-agent build twice when execute local-up-karmada.sh
  hack/deploy-karmada-agent.sh
Labels: kind/bug, size/S, approved, lgtm

#1793 Set timeout configs flexible when run e2e before
  test/e2e/suite_test.go
Labels: kind/bug, size/S, approved, lgtm, kind/cleanup

#1803 update crd version
  docs/installation/installation.md
Labels: approved, lgtm, size/XS, kind/cleanup

#1795 Enable `karmadactl promote` command to support AA
  pkg/karmadactl/get.go
  pkg/karmadactl/promote.go
Labels: kind/feature, approved, lgtm, size/M

#1790 fix test fail on arm64 mac `panic: permission denied`, removing gomonkey
  go.mod
  go.sum
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/group_clusters_test.go
  pkg/scheduler/core/spreadconstraint/util.go
  pkg/scheduler/core/util.go
  vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/modules.txt
Labels: kind/bug, approved, size/XL, lgtm

#1805 Remove karmada binary in .gitignore
  .gitignore
Labels: size/S, approved, lgtm, kind/cleanup

#1808 log format
  pkg/resourceinterpreter/interpreter.go
Labels: approved, lgtm, size/XS

#1801 Add karmadactl e2e test
  test/e2e/framework/deployment.go
  test/e2e/framework/namespace.go
  test/e2e/karmadactl_test.go
  test/e2e/unjoin_test.go
Labels: kind/feature, approved, size/L, lgtm

#1810 Update notes for Pull mode cluster in AA document
  docs/userguide/aggregated-api-endpoint.md
Labels: approved, kind/documentation, lgtm, size/XS

#1781 enhance cluster lifecycle management: add taints for the clusters which are unhealthy for a period of time
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/apis/cluster/v1alpha1/well_known_taints.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/context/context.go
  pkg/controllers/unifiedauth/ensure_impersonation_secret.go
  pkg/util/cluster.go
  pkg/util/helper/taint.go
  pkg/util/helper/taint_test.go
  pkg/util/lifted/validateclustertaints.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: kind/feature, approved, size/XXL, lgtm

#1818 Update default version
  charts/README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#1799 optimize the validating webhook for spreadconstraint
  pkg/util/helper/policy.go
Labels: size/S, approved, lgtm, kind/flake

#1820 Modify karmadactl logs example
  pkg/karmadactl/logs.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1806 fix when the type of svc is nodeport. resourcebindings FULLYAPPLIED field is False
  pkg/util/helper/workstatus.go
Labels: kind/bug, size/S, approved, lgtm

#1337 karmadactl add deinit subcommand
  pkg/karmadactl/deinit.go
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, approved, size/L, lgtm, release-note-none

#1796 Add exec and describe function to karmadactl
  go.mod
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs.go
Labels: kind/feature, approved, size/XL, lgtm

#1830 add comment for value.yaml
  charts/values.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#1811 add e2e for nodePort service status collection
  test/e2e/resource_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#1825 fix karmadactl taint failed
  pkg/karmadactl/taint.go
Labels: kind/bug, approved, lgtm, size/XS

#1833 Correct prompt in makefile
  Makefile
Labels: kind/bug, approved, kind/documentation, lgtm, size/XS

#1835 fix syntax error
  docs/multi-cluster-ingress.md
Labels: approved, kind/documentation, lgtm, size/XS

#1735 Add a script to undeploy karmada agent from a member cluster
  hack/undeploy-karmada-agent.sh
Labels: kind/feature, approved, lgtm, size/M

#1840 Clear confusing comments
  pkg/util/informermanager/keys/keys.go
  pkg/util/informermanager/single-cluster-manager.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1837 Automated cherry pick of #1825: fix karmadactl taint failed
  pkg/karmadactl/taint.go
Labels: approved, lgtm, size/XS

#1838 Automated cherry pick of #1825: fix karmadactl taint failed
  pkg/karmadactl/taint.go
Labels: approved, lgtm, size/XS

#1751 Update ROADMAP for 2022
  ROADMAP.md
Labels: approved, lgtm, size/M, kind/cleanup

#1843 Collect pull mode cluster logs for E2E
  hack/run-e2e.sh
Labels: approved, lgtm, size/XS, kind/flake

#1819 setup talks and references
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1839 Discard unused param in cmd functions
  cmd/agent/app/agent.go
  cmd/aggregated-apiserver/app/aggregated-apiserver.go
  cmd/controller-manager/app/controllermanager.go
  cmd/descheduler/app/descheduler.go
  cmd/karmada-search/app/karmada-search.go
  cmd/karmadactl/karmadactl.go
  cmd/kubectl-karmada/kubectl-karmada.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/scheduler.go
  cmd/webhook/app/webhook.go
  examples/customresourceinterpreter/webhook/app/webhook.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/deinit.go
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/taint.go
  pkg/karmadactl/unjoin.go
  pkg/version/sharedcommand/sharedcommand.go
  test/e2e/federatedresourcequota_test.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#1846 [refactor] add release to Makefile
  .github/workflows/release.yml
  Makefile
  hack/release.sh
Labels: approved, lgtm, size/M, kind/flake

#1832 update the value in readme
  charts/README.md
Labels: kind/feature, approved, size/L, lgtm, kind/cleanup

#1861 karmada agent can't find context of karmada-apiserver.config
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: kind/bug, approved, lgtm, size/XS

#1869 Removed Deprecated karmada-config flag
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  charts/templates/karmada-aggregated-apiserver.yaml
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/XS

#1871 Update fromsource.md
  docs/installation/fromsource.md
Labels: size/S, approved, lgtm, kind/cleanup

#1867 add readiness for aa
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  charts/templates/karmada-aggregated-apiserver.yaml
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/bug, approved, lgtm, size/M

#1829 Add cluster failure threshold
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/context/context.go
  pkg/controllers/status/cluster_condition_cache.go
  pkg/controllers/status/cluster_condition_cache_test.go
  pkg/controllers/status/cluster_status_controller.go
Labels: kind/feature, approved, size/L, lgtm

#1877 Add InterpretStatus for supportedInterpreterOperation
  pkg/webhook/configuration/validating.go
Labels: kind/feature, approved, lgtm, size/XS

#1834 remove deprecated flags for karmada-aggregated-apiserver
  cmd/aggregated-apiserver/app/options/options.go
Labels: kind/feature, approved, lgtm, size/XS, kind/cleanup

#1885 Update SearchRegistry API
  pkg/apis/search/searchregistry_types.go
  pkg/apis/search/v1alpha1/searchregistry_types.go
  pkg/apis/search/v1alpha1/zz_generated.conversion.go
  pkg/apis/search/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/search/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/search/controller.go
Labels: approved, lgtm, size/M, kind/cleanup

#1845 Put Tingtal on owner list
  docs/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#1886 Adds BackendStore to SearchRegistry API
  pkg/apis/search/searchregistry_types.go
  pkg/apis/search/v1alpha1/searchregistry_types.go
  pkg/apis/search/v1alpha1/zz_generated.conversion.go
  pkg/apis/search/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/search/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/L, lgtm

#1896 move override-policy.md to userguide folder
  docs/userguide/override-policy.md
Labels: approved, lgtm, size/XS, kind/cleanup

#1878 Optimize deinit according former comments
  pkg/karmadactl/deinit.go
Labels: approved, lgtm, size/M, kind/cleanup

#1891 Support karmada-search component search interface
  cmd/karmada-search/app/options/options.go
  pkg/registry/search/storage/cache.go
  pkg/registry/search/storage/opensearch.go
  pkg/registry/search/storage/requestinfo.go
  pkg/registry/search/storage/search.go
  pkg/search/apiserver.go
Labels: kind/feature, approved, size/L, lgtm

#1900 docs/work-with-flux
  docs/working-with-flux.md
Labels: approved, size/L, kind/documentation, lgtm

#1901 [doc] upgrade from v1.1 to v1.2
  docs/upgrading/README.md
  docs/upgrading/v1.1-v1.2.md
Labels: approved, kind/documentation, lgtm, size/M

#1904 Add install development environment to installation docs
  docs/installation/installation.md
Labels: approved, kind/documentation, lgtm, size/M

#1903 support install karmada-search with helm chart
  charts/README.md
  charts/templates/_helpers.tpl
  charts/templates/_karmada_apiservice.tpl
  charts/templates/karmada-search.yaml
  charts/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#1906 Add karmada-search API swagger documents
  api/openapi-spec/swagger.json
  hack/tools/swagger/generateswagger.go
  pkg/util/gclient/gclient.go
Labels: kind/feature, approved, size/XXL, lgtm

#1905 Add package helm chart scripts
  Makefile
  hack/release-helm-chart.sh
  hack/util.sh
Labels: approved, lgtm, size/M, kind/cleanup

#1890 Add livenes for karmada-scheduler
  artifacts/deploy/karmada-scheduler.yaml
  charts/templates/karmada_scheduler.yaml
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/M, kind/cleanup

#1909 delete unused parameter
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
Labels: size/S, approved, lgtm, kind/cleanup

#1894 add livenessProbe for descheduler
  artifacts/deploy/karmada-descheduler.yaml
  charts/templates/karmada_descheduler.yaml
Labels: kind/bug, size/S, approved, lgtm, kind/cleanup

#1848 [E2E] log more err info when wait resource exist on member clusters
  test/e2e/framework/deployment.go
  test/e2e/framework/job.go
  test/e2e/framework/namespace.go
  test/e2e/framework/pod.go
  test/e2e/framework/resourcequota.go
  test/e2e/framework/secret.go
  test/e2e/framework/service.go
  test/e2e/framework/workload.go
  test/e2e/resource_test.go
Labels: approved, lgtm, size/M, kind/cleanup, kind/flake

#1895 add livenessProbe for scheduler-estimator
  artifacts/deploy/karmada-scheduler-estimator.yaml
  charts/templates/karmada_scheduler_estimator.yaml
Labels: kind/bug, size/S, approved, lgtm, kind/cleanup

#1911 fix implicit issue for event filter
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: kind/bug, approved, lgtm, size/M

#1720 feat: allow propagate workload to cluster but replicas is zero
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
  pkg/scheduler/core/util_test.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, size/L, lgtm

#1920 doc fix: update flux integration doc to remove legacy repos links and fix minor spelling and grammar mistakes.
  docs/working-with-flux.md
Labels: approved, kind/documentation, lgtm, size/M

#1908 add the manual of strategy in chart
  charts/README.md
  charts/values.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#1926 update perl image for latest image run err
  test/helper/resource.go
Labels: approved, lgtm, size/XS, kind/flake

#1921 fix add annotation when annotation is nil
  pkg/registry/search/storage/cache.go
Labels: kind/bug, approved, lgtm, size/XS
