Repository karmada-io/karmada, pull requests merged in 2022-07, with the labels that each got.

#2022 remove useless function in the get_flags.go file
  pkg/karmadactl/get_flags.go
Labels: approved, size/L, lgtm, kind/cleanup

#2070 sync status of pvc
  docs/userguide/customizing-resource-interpreter.md
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
  pkg/util/helper/unstructured.go
Labels: kind/feature, approved, size/L, lgtm

#2100 fix import error
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/service_export_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#2093 Add misspell in golangci
  .golangci.yml
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/search/controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#2040 [doc] Improve docs/working-with-anp.md
  docs/working-with-anp.md
Labels: approved, kind/documentation, lgtm, size/M

#2081 avoid required label override by overridepolicy
  pkg/controllers/binding/common.go
Labels: kind/bug, approved, lgtm, size/XS

#2108 Revert PR 2082
  Makefile
Labels: approved, lgtm, size/XS, kind/cleanup

#2112 fix comments error in hack
  hack/deploy-scheduler-estimator.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#2109 Put ikaven1024 onto the hack owner list
  hack/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#2094 Add gci to seperate goimports to three parts
  .golangci.yml
  pkg/karmadactl/cmdinit/kubernetes/rbac.go
Labels: size/S, approved, lgtm, kind/cleanup

#2086 fix binding reference key hash collision
  pkg/util/helper/binding.go
  pkg/util/helper/work.go
  pkg/util/helper/workstatus.go
Labels: kind/bug, approved, lgtm, size/M

#2016 feature: `deinit` add param of `force`
  pkg/karmadactl/deinit.go
Labels: kind/feature, approved, lgtm, size/XS

#1992 [E2E] support pull mode cluster for Retain testing
  test/e2e/resourceinterpreter_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#2122 Extend the waiting time for CI cluster unjoin
  test/e2e/federatedresourcequota_test.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2117 Fix nil pointer and err formatting problems in updateConfiguration
  pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
Labels: kind/bug, approved, lgtm, size/XS

#2115 improve aggregated-api-endpoint
  docs/userguide/aggregated-api-endpoint.md
Labels: size/S, approved, lgtm, kind/cleanup

#2120 Use custom mux instead of DefaultServeMux
  cmd/descheduler/app/descheduler.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/scheduler.go
Labels: size/S, approved, lgtm, kind/cleanup

#2127 Automated cherry pick of #2117: Fix nil problem in updateConfiguration
  pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
Labels: kind/bug, approved, lgtm, size/XS

#2126 Automated cherry pick of #2117: Fix nil problem in updateConfiguration
  pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
Labels: kind/bug, approved, lgtm, size/XS

#2103 chart: support global image pull secrets
  charts/karmada/README.md
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/etcd.yaml
  charts/karmada/templates/karmada-agent.yaml
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#2130 Upgrade default karmada-apiserver from v1.22.10 to v1.23.8
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: size/S, approved, lgtm, kind/cleanup

#2132 karmadactl:modify the usage of cluster-namespace
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/unjoin.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2062 Remove unused check in detector resource Eventifilter
  pkg/detector/detector.go
Labels: size/S, approved, lgtm, kind/cleanup

#2133 `karmada-controller-manager`/`karmada-agent` : fixed panic issue when dumps error infos.
  pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
  pkg/util/helper/unstructured.go
Labels: kind/bug, size/S, approved, lgtm

#2123 Update kubernetes compatibility in README.md
  README.md
Labels: size/S, approved, kind/documentation, lgtm

#2008 Add pprof for karmada components
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/aggregated-apiserver/app/options/options.go
  cmd/aggregated-apiserver/app/options/validation.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  cmd/descheduler/app/descheduler.go
  cmd/descheduler/app/options/options.go
  cmd/descheduler/app/options/validation_test.go
  cmd/karmada-search/app/options/options.go
  cmd/scheduler-estimator/app/options/options.go
  cmd/scheduler-estimator/app/options/validation_test.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/validation_test.go
  cmd/scheduler/app/scheduler.go
  cmd/webhook/app/options/options.go
  cmd/webhook/app/options/validation_test.go
  cmd/webhook/app/webhook.go
  pkg/sharedcli/profileflag/profileflag.go
Labels: kind/feature, approved, size/XL, lgtm

#2147 [E2E] Fix check whether deployment propagated to member cluster
  test/e2e/karmadactl_test.go
Labels: kind/bug, approved, lgtm, size/XS

#2143 fix document format and spelling errors for guestbooks example
  samples/guestbook/README.md
  samples/guestbook/guestbooks-clusterpropagationpolicy.yaml
Labels: approved, lgtm, size/XS

#2124 improve karmadactl description
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/deinit.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2145 Fixed dockerfile line feed problem
  hack/util.sh
Labels: kind/bug, approved, lgtm, size/XS

#2113 cleanup federated resource quota
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/util/helper/binding.go
  pkg/util/helper/mcs.go
Labels: approved, lgtm, size/M, kind/cleanup, ok-to-test

#2140 karmadactl:modify the cluster parameter from lowercase to uppercase
  pkg/karmadactl/promote.go
Labels: size/S, approved, lgtm, kind/cleanup

#2150 Automated cherry pick of #2147: Fix check whether deployment propagated to member cluster
  test/e2e/karmadactl_test.go
Labels: approved, lgtm, size/XS

#1990 feat: agent report secret
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  pkg/karmadactl/join.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
  pkg/util/clusterrole.go
  pkg/util/credential.go
  pkg/util/credential_test.go
  pkg/util/secret.go
Labels: kind/feature, approved, size/XXL, lgtm

#2158 Fixed misleading or outdate comments about --cluster-namespace flag
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/unjoin.go
Labels: size/S, approved, lgtm, kind/cleanup

#2144 Upgrade default karmada-apiserver from v1.23.8 to v1.24.2
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/README.md
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/values.yaml
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  test/e2e/aggregatedapi_test.go
  test/helper/request.go
Labels: approved, lgtm, size/M, kind/cleanup

#2141 Add pprof doc for Karmada
  docs/contributors/devel/profiling-karmada.md
Labels: approved, kind/documentation, lgtm, size/M

#2092 use kubectl exec to implement karmadactl exec and introduce the `--namespace` flag
  go.mod
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
  pkg/karmadactl/logs.go
  pkg/karmadactl/promote.go
  vendor/k8s.io/kubectl/pkg/cmd/apiresources/apiresources.go
  vendor/k8s.io/kubectl/pkg/cmd/apiresources/apiversions.go
  vendor/k8s.io/kubectl/pkg/cmd/exec/exec.go
  vendor/k8s.io/kubectl/pkg/util/completion/completion.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#2148 allow to read namespace from the context field of karmada config when use the karmadactl get command
  pkg/karmadactl/get.go
Labels: kind/feature, size/S, approved, lgtm

#2152 feat: add cluster agent register flag
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  pkg/karmadactl/join.go
Labels: kind/feature, size/S, approved, lgtm

#2161 fix: fix applyPatch when patch and patchType is nil
  pkg/resourceinterpreter/customizedinterpreter/customized.go
Labels: kind/bug, approved, lgtm, size/XS

#2017 [Proposal] Adoption of ClusterID
  docs/proposals/clusterid/README.md
Labels: kind/feature, approved, size/L, lgtm

#2171 Fix karmadactl get -C error
  pkg/karmadactl/get.go
Labels: kind/bug, size/S, approved, lgtm

#2175 karmadactl exec: check if --cluster specify
  pkg/karmadactl/exec.go
Labels: approved, lgtm, size/XS

#2098 use kubectl logs to implement karmadactl logs
  pkg/karmadactl/logs.go
  vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go
  vendor/k8s.io/kubectl/pkg/util/apply.go
  vendor/k8s.io/kubectl/pkg/util/pod_port.go
  vendor/k8s.io/kubectl/pkg/util/service_port.go
  vendor/k8s.io/kubectl/pkg/util/umask.go
  vendor/k8s.io/kubectl/pkg/util/umask_windows.go
  vendor/k8s.io/kubectl/pkg/util/util.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#2177 [E2E] fix flake e2e case: Karmadactl unjoin testing
  test/e2e/karmadactl_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#2163 improve karmadactl command line description
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/taint.go
  pkg/version/sharedcommand/sharedcommand.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2183 Remove unnecessary package alias
  pkg/search/backendstore/defaultstore.go
  pkg/search/backendstore/opensearch.go
  pkg/search/backendstore/store.go
  pkg/search/controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#2191 Modify the default storage type of etcd to hostPath
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: kind/bug, approved, lgtm, size/XS

#2178 enable addition of [flags] to the usage line
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
Labels: kind/feature, size/S, approved, lgtm

#2190 remove unused flag for karmadactl get
  pkg/karmadactl/get.go
Labels: kind/bug, approved, lgtm, size/XS

#2184 add ut for binding/common
  pkg/controllers/binding/common_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2181 remove unused lifted codes
  pkg/util/lifted/doc.go
  pkg/util/lifted/logs.go
  pkg/util/lifted/logs_test.go
Labels: kind/feature, approved, size/L, lgtm

#2146 sync pod failded and succeeded status
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
Labels: kind/feature, approved, size/L, lgtm

#2203 improve karmadactl promte -h
  pkg/karmadactl/promote.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2193 remove unused flag for karmadactl promote
  pkg/karmadactl/promote.go
  test/e2e/karmadactl_test.go
Labels: kind/bug, size/S, approved, lgtm

#2179 [ut] add ut for pkg/utils/namespace
  pkg/util/namespace_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2199 Automated cherry pick of #1972: auto create secret when sa not create
  pkg/util/secret.go
  pkg/util/serviceaccount.go
Labels: size/S, approved, lgtm

#2198 Automated cherry pick of #1972: auto create secret when sa not create
  pkg/util/secret.go
  pkg/util/serviceaccount.go
Labels: size/S, approved, lgtm

#2200 Automated cherry pick of #1972: auto create secret when sa not create
  pkg/util/secret.go
  pkg/util/serviceaccount.go
Labels: size/S, approved, lgtm

#1945 add NoExecute taint manager
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/apis/cluster/mutation/mutation.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/common.go
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/context/context.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/descheduler/core/filter.go
  pkg/registry/cluster/strategy.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/util/binding.go
  pkg/util/binding_test.go
  pkg/util/helper/policy.go
  pkg/util/helper/taint.go
  pkg/util/worker.go
Labels: kind/feature, approved, size/XL, lgtm

#2170 Rename scheduler plugin name
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
  pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go
  pkg/scheduler/framework/plugins/registry.go
  pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
Labels: approved, lgtm, size/M, kind/cleanup

#2206 remove useless field from CommandGetOptions
  pkg/karmadactl/get.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2214 use the existing utilerrors.AggregateGoroutines func to collect each cluster's replicas concurrently
  pkg/estimator/client/accurate.go
  pkg/util/error.go
  pkg/util/error_test.go
Labels: kind/feature, approved, lgtm, size/M

#2219 fix inaccurate code comment in pkg/estimator/client/general.go
  pkg/estimator/client/general.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2210 fix wrong GO_LDFLAGS when the git tree status is dirty
  hack/util.sh
Labels: kind/bug, approved, lgtm, size/XS

#2187 Add a New Type cachedRESTMapper
  cmd/controller-manager/app/controllermanager.go
  pkg/util/restmapper/restmapper.go
  pkg/util/restmapper/restmapper_test.go
Labels: kind/feature, approved, size/L, lgtm

#2235 Apply cachedRESTMapper for other Karmada components
  cmd/agent/app/agent.go
  pkg/karmadactl/promote.go
  pkg/search/controller.go
Labels: kind/feature, approved, lgtm, size/XS

#2229 descheduler docs: increase the readability and reusability of documents
  docs/descheduler.md
Labels: size/S, approved, kind/documentation, lgtm

#2233 Group the subcommands of karmadactl
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, approved, lgtm, size/M

#2220 fix karmada init help crd version
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: kind/bug, approved, lgtm, size/XS

#2238 Cleanup ClusterClientSetFunc field in execution-controller
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/execution/execution_controller.go
Labels: approved, lgtm, size/M, kind/cleanup

#1854 feat: use taint instead of condition to filter cluster
  pkg/apis/cluster/v1alpha1/events.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/scheduler/core/generic_scheduler.go
Labels: kind/feature, approved, lgtm, size/M

#2237 Extend the timeout period of webhook to 10s
  artifacts/deploy/webhook-configuration.yaml
Labels: size/S, approved, lgtm, kind/failing-test

#2153 karmadactl describe support the --namespace flag
  pkg/karmadactl/describe.go
Labels: kind/feature, approved, lgtm, size/XS

#2227 karmada-search cannot query a single namespace
  pkg/registry/search/storage/requestinfo.go
  pkg/registry/search/storage/requestinfo_test.go
Labels: kind/bug, size/S, approved, lgtm

#2129 karmadactl-example:print example by templates like kubectl
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/deinit.go
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/logs.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/taint.go
  pkg/karmadactl/unjoin.go
  pkg/version/sharedcommand/sharedcommand.go
Labels: approved, size/L, lgtm, kind/cleanup

#2162 karmadactl pretty-print the error and exit with an error
  cmd/karmadactl/karmadactl.go
  cmd/kubectl-karmada/kubectl-karmada.go
Labels: kind/feature, size/S, approved, lgtm

#2244 chore: simplify build scripts for kubectl apply when handling kustomization resources
  charts/karmada/templates/post-install-job.yaml
  docs/upgrading/README.md
  hack/deploy-karmada.sh
Labels: approved, lgtm, size/XS, kind/flake

#2201 Automated cherry-pick: Merge pull request #2171 :Fix karmadactl get -C error
  pkg/karmadactl/get.go
Labels: kind/bug, size/S, approved, lgtm

#2241 Fix: ArgoCD can not assess Deployment health status.
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
Labels: kind/bug, approved, lgtm, size/XS

#2232 charts: add nodeSelector for etcd in charts
  charts/karmada/README.md
  charts/karmada/templates/etcd.yaml
  charts/karmada/values.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#2256 Automated cherry pick of #2241: Fix: ArgoCD can not assess Deployment health status.
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
Labels: approved, lgtm, size/XS

#2250 Comment should start with a whitespace and Uppercase
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/options/options.go
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2192 karmadactl allow users to select one or many member clusters to propagate resources.
  pkg/karmadactl/apply.go
Labels: kind/feature, approved, lgtm, size/M

#2249 Make sure to update resource status
  pkg/resourceinterpreter/defaultinterpreter/default.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/helper/job.go
Labels: kind/bug, size/S, approved, lgtm

#2136 karmadactl:modify join and unjoin validation
  pkg/karmadactl/join.go
  pkg/karmadactl/unjoin.go
Labels: approved, lgtm, size/M, kind/cleanup

#2252 Fixed Argo CD can not assess StatefulSet and DaemonSet health status issue
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
Labels: kind/bug, size/S, approved, lgtm

#2264 Automated cherry pick of #2252: Fixed Argo CD can not assess StatefulSet and DaemonSet health
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
Labels: size/S, approved, lgtm

#2230 Reduce the number of reconciliations on update in detector
  pkg/detector/detector.go
  pkg/detector/eventfilter.go
  pkg/detector/eventfilter_test.go
Labels: kind/feature, approved, size/L, lgtm

#2164 take iostreams as a func parameter
  pkg/karmadactl/apply.go
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs.go
Labels: kind/feature, approved, lgtm, size/M

#2268 Introduce RemoveCluster helper method for RB/CRB
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/apis/work/v1alpha2/binding_types_helper_test.go
  pkg/controllers/cluster/taint_manager.go
  pkg/util/binding.go
Labels: approved, lgtm, size/M, kind/cleanup

#2258 fix: create cluster apiservice in post install job
  charts/karmada/templates/post-install-job.yaml
Labels: approved, lgtm, size/XS

#2274 Automated cherry pick of #2227: karmada-search cannot query a single namespace
  pkg/registry/search/storage/requestinfo.go
  pkg/registry/search/storage/requestinfo_test.go
Labels: approved, size/L, lgtm

#2243 docs: add clearer documentation for multiple cluster services
  docs/multi-cluster-service.md
Labels: approved, size/L, kind/documentation, lgtm

#2263 support ClusterOverridePolicy in namespaces_sync_controller
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/binding/common.go
  pkg/controllers/namespace/namespace_sync_controller.go
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/framework/clusteroverridepolicy.go
  test/helper/policy.go
Labels: kind/feature, approved, size/L, lgtm

#2276 Add overrider description for overridePolicy API
  api/openapi-spec/swagger.json
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2285 Put carlory onto the karmadactl owner list
  pkg/karmadactl/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#2280 support CRD category
  charts/karmada/_crds/bases/networking.karmada.io_multiclusteringresses.yaml
  charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_federatedresourcequotas.yaml
  charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_works.yaml
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/work/v1alpha1/binding_types.go
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha2/binding_types.go
Labels: kind/feature, approved, lgtm, size/M

#2253 docs: add clearer documentation for multiple cluster ingress
  docs/multi-cluster-ingress.md
Labels: approved, kind/documentation, lgtm, size/M
