Repository karmada-io/karmada, pull requests merged in 2022-09, with the labels that each got.

#2404 bump ci runner to ubuntu-20.04 as ubuntu-18.04 is deprecated.
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/fossa.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#2456 Automated cherry pick of #2404: bump ci runner to ubuntu-20.04 as ubuntu-18.04 is deprecated.
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/fossa.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm

#2455 Automated cherry pick of #2404: bump ci runner to ubuntu-20.04 as ubuntu-18.04 is deprecated.
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/fossa.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm

#2458 Automated cherry pick of #2404: bump ci runner to ubuntu-20.04 as ubuntu-18.04 is deprecated.
  .github/workflows/ci.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/fossa.yml
  .github/workflows/image.yml
  .github/workflows/release.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm

#2454 upgrade karmada version
  charts/index.yaml
  charts/karmada/README.md
Labels: size/S, approved, lgtm, kind/cleanup

#2431 [e2e] add e2e for cluster status
  test/e2e/framework/cluster.go
  test/e2e/framework/customresourcedefine.go
  test/e2e/karmadactl_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#2462 update cfssl version to v1.6.2
  hack/deploy-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#2466 Add default path prompt for deinit to delete etcd data
  pkg/karmadactl/deinit.go
Labels: approved, kind/documentation, lgtm, size/XS

#2202 introduce factory interface for karmadactl
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs.go
  pkg/karmadactl/util/factory.go
Labels: kind/feature, approved, size/L, lgtm

#2342 improve karmada init help output
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: approved, lgtm, size/M, kind/cleanup

#2474 do not switch context when deploy karmada
  hack/deploy-agent-and-estimator.sh
  hack/deploy-karmada-agent.sh
  hack/deploy-karmada-opensearch.sh
  hack/deploy-karmada.sh
  hack/deploy-scheduler-estimator.sh
  hack/local-up-karmada.sh
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
  hack/remote-up-karmada.sh
  hack/run-e2e.sh
  hack/undeploy-karmada-agent.sh
  hack/undeploy-karmada.sh
  hack/util.sh
  test/e2e/federatedresourcequota_test.go
  test/e2e/framework/cluster.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
  test/e2e/suite_test.go
Labels: kind/feature, approved, size/L, lgtm

#2470 karmadactl exec uses factory to access member cluster
  pkg/karmadactl/exec.go
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, approved, lgtm, size/M

#2475 Update RandomStrLength from 3 to 5 in E2E test
  test/e2e/suite_test.go
Labels: approved, lgtm, size/XS, kind/failing-test

#2469 add cache source annotation for objects returned by proxy
  pkg/search/proxy/cluster_proxy.go
  pkg/search/proxy/cluster_proxy_test.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/util.go
  test/e2e/search_test.go
Labels: kind/feature, approved, size/L, lgtm

#2298 disable flags in use line
  pkg/karmadactl/addons/disable.go
  pkg/karmadactl/addons/enable.go
  pkg/karmadactl/addons/list.go
  pkg/karmadactl/apply.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cordon.go
  pkg/karmadactl/deinit.go
  pkg/karmadactl/describe.go
  pkg/karmadactl/exec.go
  pkg/karmadactl/get.go
  pkg/karmadactl/join.go
  pkg/karmadactl/logs.go
  pkg/karmadactl/promote.go
  pkg/karmadactl/register.go
  pkg/karmadactl/taint.go
  pkg/karmadactl/token.go
  pkg/karmadactl/unjoin.go
Labels: kind/feature, approved, size/L, lgtm

#2485 Add repo index for 1.2.1 and 1.2.2
  charts/index.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#2483 fix concurrent map writes panic while list via proxy
  pkg/search/proxy/store/multi_cluster_cache.go
Labels: kind/bug, size/S, approved, lgtm

#2490 [e2e] add wait for proxy ready
  test/e2e/search_test.go
Labels: kind/bug, approved, lgtm, size/M

#2481 add native resource metrics in proxy
  pkg/search/proxy/controller.go
Labels: kind/feature, size/S, approved, lgtm

#2482 fix deploy-scheduler-estimator.sh cannot generate correct kubeconfig file problem
  hack/deploy-scheduler-estimator.sh
Labels: size/S, approved, lgtm

#2489 Fixed pod can not be collected issue when building resource summary
  pkg/util/fedinformer/transform.go
  pkg/util/fedinformer/transform_test.go
Labels: kind/bug, size/S, approved, lgtm

#2491 fix MEMBER_CLUSTER_NAME command usage
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: approved, kind/documentation, lgtm, size/XS, kind/cleanup

#2471 karmadactl describe uses factory to access member cluster
  pkg/karmadactl/describe.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs.go
Labels: kind/feature, approved, lgtm, size/M

#2500 Automated cherry pick of #2489: fix pod lister only list a pod
  pkg/util/fedinformer/transform.go
  pkg/util/fedinformer/transform_test.go
Labels: size/S, approved, lgtm

#2498 [E2E] fix flaking test: karmadactl uncordon taint check
  test/e2e/karmadactl_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#2508 chart: fix labels of components `schedulerEstimator` and `search`
  charts/karmada/charts/common-1.17.1.tgz
  charts/karmada/values.yaml
Labels: kind/bug, approved, lgtm, size/XS

#2501 [E2E] fix flaking test: search proxy get node report not found
  test/e2e/aggregatedapi_test.go
  test/e2e/framework/workload.go
  test/e2e/search_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#2497 cmdinit prohibit passing in additional parameters
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: kind/feature, approved, lgtm, size/M

#2515 Fix that the ServiceExport can't be reported to control plane by karmada-agent
  pkg/karmadactl/cmdinit/karmada/rbac.go
Labels: kind/bug, approved, lgtm, size/XS

#2514 Automated cherry pick of #2469: add cache source annotation for objects returned by proxy #2483: fix concurrent map writes panic while list via proxy #2490: add wait for proxy ready #2501: fix flaking test: search proxy get node report not found
  pkg/search/proxy/cluster_proxy.go
  pkg/search/proxy/cluster_proxy_test.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/util.go
  test/e2e/aggregatedapi_test.go
  test/e2e/framework/workload.go
  test/e2e/search_test.go
Labels: approved, size/XL, lgtm

#2450 fix karmadactl init pending when k8s is in ipv6 mode
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/ip.go
  pkg/karmadactl/cmdinit/utils/ip_test.go
Labels: approved, lgtm, size/M

#2089 Adopt transform func to save memory
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/descheduler/descheduler.go
  pkg/estimator/server/server.go
  pkg/scheduler/event_handler.go
  pkg/search/controller.go
Labels: kind/feature, approved, lgtm, size/M

#2517 Automated cherry pick of #2515: Fix that the ServiceExport can't be reported to control plane
  pkg/karmadactl/cmdinit/karmada/rbac.go
Labels: approved, lgtm, size/XS

#2516 Use Cluster secret ref namespace in unified-auth-controller when generate ClusterRoleBinding
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/util/rbac.go
  test/e2e/aggregatedapi_test.go
Labels: kind/bug, approved, size/L, lgtm

#2511 karmada-controller-manager removes unnecessary permissions
  artifacts/deploy/clusterrole.yaml
  artifacts/deploy/clusterrolebinding.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  hack/deploy-karmada.sh
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/rbac.go
  pkg/karmadactl/deinit.go
Labels: kind/feature, approved, size/L, lgtm

#2523 remove service accounts for karmada components except for karmada-agent
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-etcd.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-webhook.yaml
  artifacts/deploy/kube-controller-manager.yaml
  artifacts/deploy/serviceaccount.yaml
  charts/karmada/templates/etcd.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  hack/deploy-karmada.sh
  pkg/karmadactl/addons/descheduler/manifests.go
  pkg/karmadactl/addons/estimator/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/serviceaccount.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
Labels: kind/feature, approved, size/L, lgtm

#2520 Automated cherry pick of #2450: fix karmadactl init pending when k8s is in ipv6 mode
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/ip.go
  pkg/karmadactl/cmdinit/utils/ip_test.go
Labels: approved, lgtm, size/M

#2529 Automated cherry pick of #2450: fix karmadactl init pending when k8s is in ipv6 mode
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/ip.go
  pkg/karmadactl/cmdinit/utils/ip_test.go
Labels: approved, lgtm, size/M

#2535 Automated cherry pick of #2450: fix karmadactl init pending when k8s is in ipv6 mode
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/ip.go
  pkg/karmadactl/cmdinit/utils/ip_test.go
Labels: approved, lgtm, size/M

#2530 Automated cherry pick of #2516: Use Cluster secret ref namespace in
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/util/rbac.go
  test/e2e/aggregatedapi_test.go
Labels: approved, size/L, lgtm

#2531 Automated cherry pick of #2516: Use Cluster secret ref namespace in
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/util/rbac.go
  test/e2e/aggregatedapi_test.go
Labels: approved, size/L, lgtm

#2533 fix a gramma that is not accepted by GNU `sed` command
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#2536 Add user-specific cluster name support
  hack/local-up-karmada.sh
Labels: kind/bug, approved, lgtm, size/XS

#2524 propagate dependencies support propagate sa
  pkg/dependenciesdistributor/dependencies_distributor.go
  test/e2e/dependenciesdistributor_test.go
  test/e2e/framework/deployment.go
  test/e2e/framework/rbac.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: kind/bug, approved, size/L, lgtm

#2522 Update slack address in badge
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#2538 Automated cherry pick of #2516: Use Cluster secret ref namespace in
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/util/rbac.go
Labels: approved, lgtm, size/M

#2545 Fix a typo(Registeration) in CLI #2543
  pkg/karmadactl/karmadactl.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2547 Delete service-account for karmada-controller-manager
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/bug, approved, lgtm, size/XS

#2552 [E2E] replace gomeme.Eventually with wait when logic has assertions
  test/e2e/failover_test.go
  test/e2e/karmadactl_test.go
  test/e2e/porting_workloads_test.go
  test/e2e/rescheduling_test.go
  test/e2e/resource_test.go
  test/e2e/scheduling_test.go
Labels: approved, size/L, lgtm, kind/failing-test, kind/cleanup

#2540 `karmadactl`: Fixed options of `deinit` can not be shown issue.
  pkg/karmadactl/deinit.go
Labels: kind/feature, approved, lgtm, size/XS

#2551 Update kind to 0.15 to support deploy k8s 1.25 environment
  .github/workflows/ci.yml
  artifacts/kindClusterConfig/general-config.yaml
  artifacts/kindClusterConfig/member1.yaml
  artifacts/kindClusterConfig/member2.yaml
  hack/deploy-karmada.sh
  hack/local-up-karmada.sh
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
Labels: approved, lgtm, size/M, kind/cleanup

#2548 karmadactl: Fix karmada-data directory not inilization isssue
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: kind/bug, approved, lgtm, size/M

#2559 Update kind dependency to get ready for testing against kubernetes v1.25
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/types.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/waitforready/waitforready.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeadm/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/paths.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/loadbalancer/const.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/nodeutils/util.go
  vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/types.go
Labels: approved, size/L, lgtm, kind/cleanup

#2563 Automated cherry pick of #2548: Fix bugs about karmada-data dir lost
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: approved, lgtm, size/M

#2560 Disable webhook-mode for metallb
  hack/post-run-e2e.sh
  hack/pre-run-e2e.sh
Labels: size/S, approved, lgtm

#2566 Automated cherry pick of #2540: deinit help fix
  pkg/karmadactl/deinit.go
Labels: approved, lgtm, size/XS

#2567 Automated cherry pick of #2540: deinit help fix
  pkg/karmadactl/deinit.go
Labels: approved, lgtm, size/XS

#2565 Add a new env var `DOCKER_BUILD_ARGS`
  hack/docker.sh
Labels: kind/feature, size/S, approved, lgtm

#2503 chart: cleanup chart helper template
  charts/karmada/templates/_helpers.tpl
Labels: approved, lgtm, size/XS, kind/cleanup

#2334 stop publish duplicated event
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/detector/detector.go
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/M, kind/cleanup

#2539 Update karmada's k8s components to 1.25.2
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: kind/feature, size/S, approved, lgtm

#2549 replace colon with point in the rbac resource name
  pkg/util/names/names.go
  pkg/util/names/names_test.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/framework/rbac.go
  test/e2e/propagationpolicy_test.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: kind/bug, kind/feature, approved, size/XL, lgtm

#2580 Add livenesProbe for karmada-aggregated-apiserver
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/M, kind/cleanup

#2575 Upload code coverage to Codecov
  .github/workflows/ci.yml
  Makefile
Labels: size/S, approved, lgtm, kind/cleanup

#2581 add ut for pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2574 Support Deploy karmada-scheduler-estimator in Physical Machine
  hack/util.sh
  pkg/descheduler/descheduler.go
  pkg/estimator/client/cache.go
  pkg/estimator/client/service.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, lgtm, size/M

#2593 [E2E] fix flaking-test: cordon cluster taint check
  test/e2e/karmadactl_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2550 introduce karmada-apiserver-advertise-address
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/node.go
Labels: kind/feature, size/S, approved, lgtm

#2554 Remove redundant type conversions
  pkg/util/lifted/corev1helpers.go
  pkg/util/lifted/doc.go
Labels: kind/feature, approved, lgtm, size/XS

#2590 [UT]Add ut for lifted codes
  pkg/util/lifted/doc.go
  pkg/util/lifted/nodeselector_test.go
  pkg/util/lifted/parallelism_test.go
  pkg/util/lifted/requestinfo.go
  pkg/util/lifted/requestinfo_test.go
  pkg/util/lifted/retain_test.go
  pkg/util/lifted/visitpod_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#2601 using helper function of client-go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: size/S, approved

#2267 add implicit priority for PP
  pkg/detector/detector.go
  pkg/util/selector.go
Labels: kind/feature, approved, lgtm, size/M

#2555 Fix the issue that incomingBindingMetrics ignores the ClusterChanged event
  pkg/scheduler/event_handler.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/scheduler_metrics_test.go
Labels: approved, size/L, lgtm, kind/cleanup
