Repository karmada-io/karmada, pull requests merged in 2022-12, with the labels that each got.

#2845 refactor static weight strategy
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/assignment_test.go
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/division_algorithm_test.go
  pkg/util/helper/binding.go
Labels: approved, size/XL, lgtm, kind/cleanup

#2894 Set image tag to v1.4.0
  charts/karmada/values.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#2893 Use errors.Is to check for a specific error
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/karmadactl/util/genericresource/visitor.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2882 Move to registry.k8s.io
  api/openapi-spec/swagger.json
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/karmada-etcd.yaml
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/README.md
  charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
  charts/karmada/values.yaml
  hack/util.sh
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/util/imageparser/parser.go
  pkg/util/overridemanager/imageoverride_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2895 fix ut: HasSynced error
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#2885 go1.19: change some atomic.Value to atomic.Bool
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
Labels: size/S, approved, lgtm, kind/cleanup

#2898 Remove redundant pointer use of atomic types
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
Labels: size/S, approved, lgtm, kind/cleanup

#2897 Automated cherry pick of #2895: fix ut: HasSynced error
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#2901 Add helm index for 1.4
  charts/index.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#2902 Fix that karmada-agent don't have permission to delete `work` resources
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: kind/bug, approved, lgtm, size/XS

#2903 Modify the error log output
  pkg/controllers/execution/execution_controller.go
  pkg/karmadactl/addons/descheduler/manifests.go
  pkg/karmadactl/addons/estimator/manifests.go
  pkg/karmadactl/addons/search/manifests.go
  pkg/util/fedinformer/keys/keys_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2609 add implicit priority for OP and COP
  pkg/util/overridemanager/overridemanager.go
  pkg/util/overridemanager/overridemanager_test.go
Labels: kind/feature, approved, lgtm, size/M

#2883 add metrics for pool
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/metrics/pool.go
  pkg/metrics/pool_test.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
  pkg/util/fixedpool/fixedpool.go
Labels: approved, size/L, lgtm, kind/cleanup

#2904 Automated cherry pick of #2902: Fix that karmada-agent don't have permission to delete work
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: approved, lgtm, size/XS

#2905 Automated cherry pick of #2902: Fix that karmada-agent don't have permission to delete work
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: approved, lgtm, size/XS

#2909 Update Golang version from v1.18.8 to v1.18.9
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#2908 Build with Go patch release 1.19.4
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#2913 Cherry pick from #2908: Build with Go patch release 1.19.4
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#2880 namespace_sync_controller: buildWorks parallel sync namespace
  pkg/controllers/namespace/namespace_sync_controller.go
Labels: kind/feature, approved, lgtm, size/M

#2911 generate PolicyRules from given subjects for impersonation deduplicate
  pkg/util/rbac.go
  pkg/util/rbac_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2915 fix that validating for resourceinterpreterwebhookconfigurations does…
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: kind/bug, approved, lgtm, size/XS

#2916 fix resourceinterpretercustomizations webhook
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: kind/bug, approved, lgtm, size/XS

#2923 Cherry pick #2915 to release-1.3: fix that validating for resourceinterpreterwebhookconfigurations
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: kind/bug, approved, lgtm, size/XS

#2924 Automated cherry pick of #2915 upstream release 1.4
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: kind/bug, approved, lgtm, size/XS

#2918 [UT] Add unstructed helper uinttest
  pkg/util/helper/unstructured_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2929 move legacy keps into proposals
  docs/proposals/cleanup-propagated-resources/README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#2871 add kube lib for lua
  examples/karmadactlinterpret/observed-deploy-nginx.yaml
  examples/karmadactlinterpret/resourceinterpretercustomization.yaml
  pkg/resourceinterpreter/configurableinterpreter/luavm/kube.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_convert.go
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go
Labels: kind/feature, approved, size/L, lgtm

#2919 Replace colon with point in the rbac resource name
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: kind/bug, size/S, approved, lgtm

#2933 Automated cherry pick of #2919: replace colon with point in the rbac resource name
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: approved, lgtm, size/M

#2931 Automated cherry pick of #2919: replace colon with point in the rbac resource name
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: size/S, approved, lgtm

#2930 Fix work status not sync to control plane when apiserver failed and recovered soon
  pkg/controllers/status/cluster_status_controller.go
  test/e2e/resource_test.go
Labels: kind/bug, approved, size/L, lgtm

#2932 Automated cherry pick of #2919: replace colon with point in the rbac resource name
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: approved, lgtm, size/M

#2942 need return after ch <-
  pkg/controllers/namespace/namespace_sync_controller.go
Labels: kind/bug, approved, lgtm, size/XS

#2928 Fix misjudgment of deployment and statefuleset health status
  pkg/resourceinterpreter/defaultinterpreter/healthy.go
  pkg/resourceinterpreter/defaultinterpreter/healthy_test.go
Labels: kind/bug, approved, size/L, lgtm

#2944 Automated cherry pick of #2928: Fix misjudgment of deployment and statefuleset health status
  pkg/resourceinterpreter/defaultinterpreter/healthy.go
  pkg/resourceinterpreter/defaultinterpreter/healthy_test.go
Labels: approved, size/L, lgtm

#2945 Automated cherry pick of #2928: Fix misjudgment of deployment and statefuleset health status
  pkg/resourceinterpreter/defaultinterpreter/healthy.go
  pkg/resourceinterpreter/defaultinterpreter/healthy_test.go
Labels: approved, size/L, lgtm

#2937 Automated cherry pick of #2930: fix work status not sync to control plane
  pkg/controllers/status/cluster_status_controller.go
  test/e2e/resource_test.go
Labels: kind/bug, approved, size/L, lgtm

#2938 Automated cherry pick of #2930: fix work status not sync to control plane
  pkg/controllers/status/cluster_status_controller.go
  test/e2e/framework/deployment.go
  test/e2e/resource_test.go
Labels: approved, size/L, lgtm

#2939 Automated cherry pick of #2930: fix work status not sync to control plane
  pkg/controllers/status/cluster_status_controller.go
  test/e2e/framework/deployment.go
  test/e2e/propagationpolicy_test.go
  test/e2e/resource_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm

#2884 Support multiple dependencyInterpreter lua script for one gvk
  pkg/resourceinterpreter/configurableinterpreter/configmanager/accessor.go
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/configurableinterpreter/configmanager/manager_test.go
  pkg/resourceinterpreter/configurableinterpreter/configurable.go
  pkg/resourceinterpreter/configurableinterpreter/dependencyset.go
  pkg/resourceinterpreter/configurableinterpreter/dependencyset_test.go
  pkg/webhook/resourceinterpretercustomization/helper.go
  pkg/webhook/resourceinterpretercustomization/helper_test.go
  test/e2e/resourceinterpreter_test.go
Labels: kind/feature, approved, size/XL, lgtm

#2912 fix a corner case that re-schedule be skipped in case of the cluster becomes not fit.
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler.go
  test/e2e/framework/cluster.go
  test/e2e/rescheduling_test.go
Labels: kind/bug, approved, size/L, lgtm

#2947 fix failing test of editing policy resourceSelectors
  pkg/detector/detector.go
Labels: approved, lgtm, kind/failing-test, size/M

#2954 fix post-delete job of chart
  charts/karmada/templates/post-delete-job.yaml
Labels: approved, lgtm, size/XS

#2955 Automated cherry pick of #2912: fix a corner case that re-schedule be skipped in case of the cluster becomes not fit
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler.go
  test/e2e/framework/cluster.go
  test/e2e/rescheduling_test.go
Labels: approved, size/L, lgtm

#2934 Automated cherry pick of #2552: replace gomeme.Eventually with wait when logic has assertions
  test/e2e/failover_test.go
  test/e2e/karmadactl_test.go
  test/e2e/porting_workloads_test.go
  test/e2e/rescheduling_test.go
  test/e2e/resource_test.go
  test/e2e/scheduling_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#2879 move validation funcs into util/validation
  pkg/util/helper/policy.go
  pkg/util/helper/policy_test.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
  pkg/webhook/clusterpropagationpolicy/validating.go
  pkg/webhook/propagationpolicy/validating.go
Labels: approved, size/L, lgtm, kind/cleanup

#2949 CommandUnjoinOption wait must be a positive duration
  pkg/karmadactl/unjoin/unjoin.go
Labels: kind/bug, approved, lgtm, size/XS

#2958 Introduce generic hashset to simplify code
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/resourceinterpreter/configurableinterpreter/configurable.go
  pkg/resourceinterpreter/configurableinterpreter/dependencyset.go
  pkg/resourceinterpreter/configurableinterpreter/dependencyset_test.go
  pkg/util/hashset/hashset.go
  pkg/util/hashset/hashset_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2959 Automated cherry pick of #2912: fix a corner case that re-schedule be skipped in case of the cluster becomes not fit
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/scheduler.go
  test/e2e/framework/cluster.go
  test/e2e/rescheduling_test.go
Labels: approved, size/L, lgtm

#2957 Add detailed information about the taint
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2899 clean up metrics for scheduler, descheduler and estimator
  .golangci.yml
  cmd/agent/main.go
  cmd/controller-manager/controller-manager.go
  cmd/descheduler/app/descheduler.go
  cmd/descheduler/main.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler-estimator/main.go
  cmd/scheduler/app/scheduler.go
  cmd/scheduler/main.go
  pkg/estimator/server/metrics/metrics.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/scheduler.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm, kind/cleanup

#2953 add karmada operator apis
  hack/update-codegen.sh
  hack/update-crdgen.sh
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/doc.go
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.register.go
  operator/pkg/generated/clientset/versioned/clientset.go
  operator/pkg/generated/clientset/versioned/doc.go
  operator/pkg/generated/clientset/versioned/fake/clientset_generated.go
  operator/pkg/generated/clientset/versioned/fake/doc.go
  operator/pkg/generated/clientset/versioned/fake/register.go
  operator/pkg/generated/clientset/versioned/scheme/doc.go
  operator/pkg/generated/clientset/versioned/scheme/register.go
  operator/pkg/generated/clientset/versioned/typed/operator/v1alpha1/doc.go
  operator/pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/doc.go
  operator/pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/fake_karmada.go
  operator/pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/fake_operator_client.go
  operator/pkg/generated/clientset/versioned/typed/operator/v1alpha1/generated_expansion.go
  operator/pkg/generated/clientset/versioned/typed/operator/v1alpha1/karmada.go
  operator/pkg/generated/clientset/versioned/typed/operator/v1alpha1/operator_client.go
  operator/pkg/generated/informers/externalversions/factory.go
  operator/pkg/generated/informers/externalversions/generic.go
  operator/pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  operator/pkg/generated/informers/externalversions/operator/interface.go
  operator/pkg/generated/informers/externalversions/operator/v1alpha1/interface.go
  operator/pkg/generated/informers/externalversions/operator/v1alpha1/karmada.go
  operator/pkg/generated/listers/operator/v1alpha1/expansion_generated.go
  operator/pkg/generated/listers/operator/v1alpha1/karmada.go
Labels: kind/feature, approved, size/XXL, lgtm

#2960 Stop update krew for release 1.3.x
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#2946 refactor dynamic schedule
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/assignment_test.go
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/division_algorithm_test.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
  pkg/scheduler/core/util_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#2840 introduce kube-image-tag flag to karmadactl init
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: kind/feature, size/S, approved, lgtm

#2963 fix: helm template missing directive marker to separate apiservice re…
  charts/karmada/templates/_karmada_apiservice.tpl
Labels: approved, lgtm, size/XS

#2971 fix failed to apply Label/Annotation Overriders
  pkg/util/overridemanager/labelannotationoverrider.go
  pkg/util/overridemanager/labelannotationoverrider_test.go
Labels: kind/bug, approved, lgtm, size/M

#2972 Automated cherry pick of #2971: fix failed to apply Label/Annotation Overriders
  pkg/util/overridemanager/labelannotationoverrider.go
  pkg/util/overridemanager/labelannotationoverrider_test.go
Labels: approved, lgtm, size/M

#2966 fix RB may not be created when delete and create the same object immediately
  pkg/detector/detector.go
Labels: kind/bug, size/S, approved, lgtm

#2974 update .import-aliases
  hack/.import-aliases
Labels: approved, lgtm, size/XS, kind/cleanup

#2970 Fix charts installation with component mode
  charts/karmada/README.md
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/_karmada_apiservice.tpl
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/values.yaml
Labels: kind/bug, approved, size/L, lgtm

#2961 Add a script to remove the karmada started by local-up-karmada.sh
  hack/local-down-karmada.sh
Labels: kind/feature, approved, lgtm, size/M

#2977 docs: fix typos in federated-hpa proposal
  docs/proposals/hpa/federated-hpa.md
Labels: size/S, approved, kind/documentation, lgtm

#2980 Setup github token for action protoc
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#2983 Update the wrong message info in the e2e
  test/e2e/framework/rbac.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2984 Grant karmada-agent permission to access resourceinterpretercustomizations
  pkg/karmadactl/cmdinit/karmada/rbac.go
Labels: kind/bug, approved, lgtm, size/XS

#2986 Automated cherry pick of #2984: Grant karmada-agent permission to access resourceinterpretercustomizations
  pkg/karmadactl/cmdinit/karmada/rbac.go
Labels: approved, lgtm, size/XS

#2973 add operator skeleton
  .golangci.yml
  operator/cmd/operator/app/operator.go
  operator/cmd/operator/app/options/options.go
  operator/cmd/operator/operator.go
  operator/pkg/controller/context/context.go
  operator/pkg/controller/karmada/karmada_controller.go
  operator/pkg/scheme/scheme.go
  vendor/k8s.io/component-base/config/options/leaderelectionconfig.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XL, lgtm

#2964 refactor dispense replicas for job completions
  pkg/controllers/binding/common.go
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/division_algorithm_test.go
  pkg/util/binding.go
  pkg/util/binding_test.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2956 Karmadactl join: default use current context
  hack/local-up-karmada.sh
  pkg/karmadactl/join/join.go
Labels: kind/feature, size/S, approved, lgtm

#2975 [bugfix]when replicaDivisionPreference is Weighted and WeightPreference is nil
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters.go
  test/e2e/framework/cluster.go
  test/e2e/spread_by_region_test.go
Labels: kind/bug, approved, size/L, lgtm

#2993 fix: karmada-agent helm template strategy indentation
  charts/karmada/templates/karmada-agent.yaml
Labels: approved, lgtm, size/XS

#2988 Check if the resource exists before creating it
  pkg/util/namespace.go
  pkg/util/namespace_test.go
  pkg/util/serviceaccount.go
  pkg/util/serviceaccount_test.go
Labels: kind/bug, approved, size/L, lgtm

#2996 default interpreter sub-tests to run in parallel
  pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
  pkg/resourceinterpreter/defaultinterpreter/healthy_test.go
  pkg/resourceinterpreter/defaultinterpreter/reflectstatus_test.go
  pkg/resourceinterpreter/defaultinterpreter/revisereplica_test.go
Labels: approved, lgtm, size/M

#3000 Uniform klog output starts with uppercase
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  cmd/webhook/app/webhook.go
  examples/customresourceinterpreter/webhook/app/webhook.go
  operator/cmd/operator/app/operator.go
  pkg/aggregatedapiserver/apiserver.go
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/check.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/node.go
  pkg/karmadactl/join/join.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
  pkg/modeling/modeling.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/spreadconstraint/select_clusters.go
  pkg/search/backendstore/opensearch.go
  pkg/search/controller.go
  pkg/search/proxy/controller.go
  pkg/util/cluster.go
  pkg/util/clusterlease.go
  pkg/util/clusterrole.go
  pkg/util/helper/workstatus.go
  pkg/util/lifted/discovery.go
  pkg/util/secret.go
  pkg/webhook/interpreter/http.go
Labels: approved, size/L, lgtm, kind/cleanup

#2935 Delete the redundant logic in func GenerateExecutionSpaceName
  cmd/agent/app/agent.go
  pkg/controllers/binding/common.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/util/names/names.go
  pkg/util/names/names_test.go
  test/e2e/karmadactl_test.go
  test/e2e/resourceinterpreter_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3002 Automated cherry pick of #2988: Check if the resource exists before creating it
  pkg/util/namespace.go
  pkg/util/namespace_test.go
  pkg/util/serviceaccount.go
  pkg/util/serviceaccount_test.go
Labels: approved, size/L, lgtm

#3003 Fix log output errors
  pkg/controllers/mcs/service_export_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3008 Remove unnecessary fmt.Sprintf for logging
  test/e2e/mcs_test.go
  test/e2e/resourceinterpreter_test.go
  test/e2e/scheduling_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3001 build karmada operator image
  Makefile
  hack/util.sh
Labels: kind/feature, approved, lgtm, size/XS
