Repository karmada-io/karmada, pull requests merged in 2022-08, with the labels that each got.

#2292 add event error msg when failed to apply policy
  pkg/detector/detector.go
Labels: kind/feature, approved, lgtm, size/XS

#2180 Add ID to Cluster API
  api/openapi-spec/swagger.json
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, lgtm, size/M

#2275 fix webhook svc chart temp
  charts/karmada/templates/karmada-webhook.yaml
Labels: kind/bug, approved, lgtm, size/XS

#2293 update istio-on-nonflat-network doc
  docs/working-with-istio-on-non-flat-network.md
Labels: approved, size/L, kind/documentation, lgtm

#2303 add ut for binding/common
  pkg/controllers/binding/common_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2305 Optimize code to reduce redundancy
  pkg/util/resource.go
  pkg/util/resource_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2134 Add karmadactl addons subcommand
  pkg/karmadactl/addons/addons.go
  pkg/karmadactl/addons/descheduler/descheduler.go
  pkg/karmadactl/addons/descheduler/manifests.go
  pkg/karmadactl/addons/disable.go
  pkg/karmadactl/addons/enable.go
  pkg/karmadactl/addons/estimator/estimator.go
  pkg/karmadactl/addons/estimator/manifests.go
  pkg/karmadactl/addons/init/addon.go
  pkg/karmadactl/addons/init/disable_option.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/addons/init/global.go
  pkg/karmadactl/addons/init/list_option.go
  pkg/karmadactl/addons/install/install.go
  pkg/karmadactl/addons/list.go
  pkg/karmadactl/addons/search/manifests.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/addons/utils/idempotency.go
  pkg/karmadactl/addons/utils/template.go
  pkg/karmadactl/cmdinit/karmada/check.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/karmadactl.go
  pkg/util/names/names.go
Labels: kind/feature, approved, size/XXL, lgtm

#2273 Extend Binding API for graceful eviction
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#2284 add default tolerations for pp and cpp
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
  pkg/util/helper/taint.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: kind/feature, approved, lgtm, size/M

#2205 fix karmadactl apply help
  pkg/karmadactl/apply.go
Labels: kind/bug, approved, lgtm, size/XS

#2035 Propagate dependencies add support propagate ServiceAccount
  docs/userguide/propagate-dependencies.md
  pkg/resourceinterpreter/defaultinterpreter/dependencies.go
  pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
Labels: kind/feature, approved, lgtm, size/M

#2310 Put wuyingjun-lucky onto karmadactl addons owner list
  pkg/karmadactl/addons/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#2314 cleanup event in execution_controller
  pkg/controllers/execution/execution_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#2311 optimize unstructured convert methods
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/estimator/server/replica/replica.go
  pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
  pkg/resourceinterpreter/defaultinterpreter/dependencies.go
  pkg/resourceinterpreter/defaultinterpreter/prune/prune.go
  pkg/resourceinterpreter/defaultinterpreter/reflectstatus.go
  pkg/resourceinterpreter/defaultinterpreter/replica.go
  pkg/resourceinterpreter/defaultinterpreter/retain.go
  pkg/util/helper/unstructured.go
  pkg/util/overridemanager/imageoverride.go
Labels: approved, size/L, lgtm, kind/cleanup

#2295 docs: changed the way to get the kubeconfig path in aggregation api
  docs/userguide/aggregated-api-endpoint.md
Labels: size/S, approved, kind/documentation, lgtm

#2315 stop update status if Work object in terminating state
  pkg/controllers/status/workstatus_controller.go
Labels: kind/feature, approved, lgtm, size/XS

#2325 update import aliases
  hack/.import-aliases
  pkg/search/backendstore/opensearch.go
  pkg/search/backendstore/store.go
  pkg/search/controller.go
  pkg/util/gclient/gclient.go
Labels: approved, lgtm, size/M, kind/cleanup

#2324 Put Lease to default SkippedResourceConfig
  pkg/util/apigroup.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2332 Clear conflict between variable `delete` and builtin function
  pkg/search/backendstore/opensearch.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2331 opensearch: fixed panic issue when dumps error infos
  pkg/search/backendstore/opensearch.go
Labels: kind/bug, approved, lgtm, size/XS

#2330 patch resourcebinding instead of update and update observed generation.
  pkg/scheduler/scheduler.go
  pkg/util/helper/patch.go
  pkg/util/helper/patch_test.go
Labels: kind/feature, approved, size/L, lgtm

#2328 fix karmada-agent can not ensure default namespace issue
  pkg/karmadactl/join.go
  pkg/util/credential.go
Labels: kind/bug, size/S, approved, lgtm

#2269 Adjust the order of kubeconfig loadingRules
  pkg/karmadactl/cmdinit/utils/kubeclient.go
  pkg/karmadactl/config.go
Labels: kind/bug, approved, lgtm, size/XS

#1403 add docs: binary install karmada
  docs/installation/install-binary.md
  docs/installation/installation.md
Labels: release-note, approved, size/XXL, kind/documentation, lgtm

#2339 Make changes to binding-controller to adopt graceful eviction
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/util/helper/binding.go
  pkg/util/helper/workstatus.go
  pkg/util/helper/workstatus_test.go
Labels: kind/feature, approved, size/L, lgtm

#2340 Introduce graceful eviction feature gate and mark feature in alpha state
  pkg/features/features.go
Labels: kind/feature, size/S, approved, lgtm

#2333 Automated cherry pick of #2331: fixed panic issue when dumps error infos
  pkg/search/backendstore/opensearch.go
Labels: approved, lgtm, size/XS

#2344 add ut for spreadconstraint
  pkg/scheduler/core/spreadconstraint/util_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2299 helm support option --cluster-api-endpoint
  charts/karmada/README.md
  charts/karmada/templates/karmada-agent.yaml
  charts/karmada/values.yaml
Labels: kind/bug, approved, lgtm, size/XS

#2289 disabled search APIService chart resource by default
  charts/karmada/templates/_karmada_apiservice.tpl
Labels: kind/bug, approved, lgtm, size/XS

#2262 use kubectl describe to implement karmadactl describe
  pkg/karmadactl/describe.go
  vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm

#2347 Rename interpreter operation health
  docs/proposals/resource-interpreter-webhook/README.md
  pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
  pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
Labels: size/S, approved, lgtm, kind/cleanup

#2346 Enable graceful eviction in taint manager
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/apis/work/v1alpha2/binding_types_helper_test.go
  pkg/controllers/cluster/taint_manager.go
Labels: kind/feature, approved, size/L, lgtm

#1653 Add warnings when config cluster-namespace as karmada-system
  pkg/karmadactl/join.go
Labels: kind/bug, approved, lgtm, size/XS

#2352 rename and re-organize the informermanager
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/clusterdiscovery/clusterapi/handler.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/context/context.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/detector/handler.go
  pkg/estimator/server/server.go
  pkg/registry/search/storage/search.go
  pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/interpreter.go
  pkg/search/apiserver.go
  pkg/search/controller.go
  pkg/util/fedinformer/genericmanager/multi-cluster-manager.go
  pkg/util/fedinformer/genericmanager/single-cluster-manager.go
  pkg/util/fedinformer/handlers.go
  pkg/util/fedinformer/keys/keys.go
  pkg/util/fedinformer/keys/keys_test.go
  pkg/util/helper/binding.go
  pkg/util/helper/cache.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, size/L, lgtm, kind/cleanup

#2345 patch resourcebinding instead of update and update observed generation.
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, approved, size/L, lgtm

#2359 Revert picture in readme.md
  docs/images/Karmada-logo-horizontal-color.png
  docs/images/architecture.png
  docs/images/cncf-logo.png
  docs/images/karmada-resource-relation.png
  docs/images/sample-nginx.svg
Labels: approved, lgtm, size/XS, kind/cleanup

#2350 Add typed shared informer
  pkg/util/fedinformer/typedManager/multi-cluster-manager.go
  pkg/util/fedinformer/typedManager/single-cluster-manager.go
Labels: kind/feature, approved, size/L, lgtm

#2118 propagate dependencies support propagate pvc
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/resourceinterpreter/defaultinterpreter/dependencies.go
  pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
  test/e2e/dependenciesdistributor_test.go
  test/e2e/framework/persistentvolumeclaim.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: kind/feature, approved, size/L, lgtm

#2329 implement InterpretHealth for resource interpreter
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/defaultinterpreter/default.go
  pkg/resourceinterpreter/defaultinterpreter/healthy.go
  pkg/resourceinterpreter/defaultinterpreter/healthy_test.go
  pkg/resourceinterpreter/interpreter.go
  pkg/webhook/configuration/validating.go
Labels: kind/feature, approved, size/L, lgtm

#2360 update the dynamic informer in cluster status controller with typed informer
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/status/cluster_status_controller.go
Labels: kind/feature, approved, size/L, lgtm

#2355 add ut for binding
  pkg/util/helper/binding_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2313 add ID the unique identifier for push and pull mode's cluster
  cmd/agent/app/agent.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/karmadactl/join.go
  pkg/util/cluster.go
Labels: kind/feature, approved, lgtm, size/M

#2228 [E2E] add karmada-search e2e test
  test/e2e/framework/resourceregistry.go
  test/e2e/search_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2319 Add grace-eviction-controller to evict cluster workload
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/context/context.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Labels: kind/feature, approved, size/XL, lgtm

#2376 improve ut for taint
  pkg/util/helper/taint_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2377 Rename package name of typedmanager
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/util/fedinformer/typedmanager/multi-cluster-manager.go
  pkg/util/fedinformer/typedmanager/single-cluster-manager.go
Labels: size/S, approved, lgtm, kind/cleanup

#2373 remove TargetCluster when cluster is terminating
  cmd/controller-manager/app/controllermanager.go
  pkg/apis/cluster/v1alpha1/events.go
  pkg/apis/cluster/v1alpha1/well_known_constants.go
  pkg/controllers/cluster/cluster_controller.go
Labels: kind/feature, approved, lgtm, size/M

#2382 Add a feature gate for cluster resource custom modeling
  pkg/features/features.go
Labels: kind/feature, size/S, approved, lgtm

#2353 switch CODE_OF_CONDUCT to CNCF COC
  CODE_OF_CONDUCT.md
Labels: approved, kind/documentation, lgtm, size/M

#2348 Update karmada charts to support Support set `global.imageRegistry` of all components image repo
  charts/karmada/README.md
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, lgtm, size/M

#2058 Add proxy proposal
  docs/proposals/resource-aggregation-proxy/Alternatives-before-API-server-Architecture.drawio
  docs/proposals/resource-aggregation-proxy/Alternatives-before-API-server-Architecture.svg
  docs/proposals/resource-aggregation-proxy/Design-Details-Architecture.drawio
  docs/proposals/resource-aggregation-proxy/Design-Details-Architecture.svg
  docs/proposals/resource-aggregation-proxy/README.md
  docs/proposals/resource-aggregation-proxy/cache.drawio
  docs/proposals/resource-aggregation-proxy/cache.svg
  docs/proposals/resource-aggregation-proxy/user-story-service-discovery.drawio
  docs/proposals/resource-aggregation-proxy/user-story-service-discovery.svg
  docs/proposals/resource-aggregation-proxy/with-karmada.drawio
  docs/proposals/resource-aggregation-proxy/with-karmada.svg
  docs/proposals/resource-aggregation-proxy/without-karmada.drawio
  docs/proposals/resource-aggregation-proxy/without-karmada.svg
Labels: approved, size/L, lgtm, kind/design

#2387 Introduce `--enable-cluster-resource-modeling` to customize resource modeling feature
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/controllers/context/context.go
  pkg/controllers/status/cluster_status_controller.go
Labels: kind/feature, approved, size/L, lgtm

#2366 add proxy skeleton
  cmd/karmada-search/app/options/options.go
  pkg/apis/search/register.go
  pkg/apis/search/searchregistry_types.go
  pkg/apis/search/v1alpha1/searchregistry_types.go
  pkg/apis/search/v1alpha1/zz_generated.conversion.go
  pkg/apis/search/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/search/v1alpha1/zz_generated.register.go
  pkg/apis/search/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/search/storage/proxy.go
  pkg/search/apiserver.go
  pkg/search/proxy/cache_proxy.go
  pkg/search/proxy/cluster_proxy.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/karmada_proxy.go
  pkg/search/proxy/store/cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/resource_cache.go
  pkg/util/proxy/proxy.go
Labels: kind/feature, kind/api-change, approved, size/XL, lgtm

#2097 Standardize the generation and management of certificates
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/karmada-cert-secret.yaml
  artifacts/deploy/karmada-etcd.yaml
  artifacts/deploy/karmada-search.yaml
  artifacts/deploy/kube-controller-manager.yaml
  artifacts/deploy/secret.yaml
  examples/README.md
  hack/deploy-karmada.sh
  hack/pre-run-e2e.sh
  hack/util.sh
Labels: kind/feature, approved, size/L, lgtm

#2386 Add cluster resource modeling api
  api/openapi-spec/swagger.json
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, size/XL, lgtm

#2297 Standardize the generation of certificates for karmadactl init
  pkg/karmadactl/addons/search/manifests.go
  pkg/karmadactl/cmdinit/cert/cert.go
  pkg/karmadactl/cmdinit/cert/cert_test.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
  pkg/karmadactl/cmdinit/options/global.go
Labels: kind/feature, approved, size/L, lgtm

#2312 Set open cluster-info to distribute root CA certificates
  go.mod
  pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/utils/configmap.go
  pkg/karmadactl/cmdinit/utils/rbac.go
Labels: kind/feature, approved, size/L, lgtm

#2370 add default interpreter for interpretHealth
  pkg/resourceinterpreter/defaultinterpreter/healthy.go
  pkg/resourceinterpreter/defaultinterpreter/healthy_test.go
Labels: kind/feature, approved, size/L, lgtm

#2369 avoid joining the same cluster repeatedly
  cmd/agent/app/agent.go
  pkg/karmadactl/join.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
Labels: kind/bug, approved, lgtm, size/M

#2390 Set default model for cluster
  api/openapi-spec/swagger.json
  cmd/aggregated-apiserver/app/options/options.go
  pkg/apis/cluster/mutation/mutation.go
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/features/features.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/cluster/strategy.go
Labels: kind/feature, approved, size/L, lgtm

#2351 add health field in the binding and work api
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_works.yaml
  pkg/apis/work/v1alpha1/binding_types_conversion.go
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, approved, size/L, lgtm

#2395 fix: sync cluster level resource status
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
  pkg/util/constants.go
Labels: kind/feature, approved, size/L, lgtm

#2401 fix: remove unexpected validate webhook in configuration
  charts/karmada/templates/_karmada_webhook_configuration.tpl
Labels: size/S, approved, lgtm

#2391 remove Failover from scheduler
  artifacts/deploy/karmada-scheduler.yaml
  pkg/scheduler/event_handler.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/scheduler.go
  test/e2e/failover_test.go
  test/e2e/framework/constant.go
Labels: kind/feature, approved, size/L, lgtm

#2357 Set the required RBAC to enable the certificate signing request
  pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/feature, approved, size/L, lgtm

#2389 add proxy cache
  cmd/karmada-search/app/options/options.go
  go.mod
  pkg/search/proxy/cache_proxy.go
  pkg/search/proxy/cache_proxy_test.go
  pkg/search/proxy/cluster_proxy.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/cluster_cache.go
  pkg/search/proxy/store/conversion.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/resource_cache.go
  pkg/search/proxy/store/store.go
  pkg/search/proxy/store/util.go
Labels: kind/feature, approved, size/XXL, lgtm

#2363 fix opensearch mapper_parsing_exception
  pkg/search/backendstore/opensearch.go
Labels: kind/bug, approved, size/L, lgtm

#2407 Fix it occur error when `karmada-agent` is restarted
  cmd/agent/app/agent.go
Labels: kind/bug, approved, lgtm, size/XS

#2399 Implement karmadactl token command to manage bootstrap tokens
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/token.go
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
  pkg/util/lifted/pubkeypin/pubkeypin.go
  pkg/util/lifted/pubkeypin/pubkeypin_test.go
  pkg/util/secret.go
  vendor/k8s.io/cluster-bootstrap/util/secrets/secrets.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#2398 add cluster resource model check
  pkg/apis/cluster/mutation/mutation.go
  pkg/apis/cluster/mutation/mutation_test.go
  pkg/apis/cluster/validation/validation.go
  pkg/apis/cluster/validation/validation_test.go
  pkg/registry/cluster/strategy.go
Labels: kind/feature, approved, size/L, lgtm

#2367 Cluster resource modeling
  go.mod
  go.sum
  pkg/modeling/modeling.go
  pkg/modeling/modeling_test.go
  vendor/github.com/emirpasic/gods/LICENSE
  vendor/github.com/emirpasic/gods/containers/containers.go
  vendor/github.com/emirpasic/gods/containers/enumerable.go
  vendor/github.com/emirpasic/gods/containers/iterator.go
  vendor/github.com/emirpasic/gods/containers/serialization.go
  vendor/github.com/emirpasic/gods/trees/redblacktree/iterator.go
  vendor/github.com/emirpasic/gods/trees/redblacktree/redblacktree.go
  vendor/github.com/emirpasic/gods/trees/redblacktree/serialization.go
  vendor/github.com/emirpasic/gods/trees/trees.go
  vendor/github.com/emirpasic/gods/utils/comparator.go
  vendor/github.com/emirpasic/gods/utils/sort.go
  vendor/github.com/emirpasic/gods/utils/utils.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#2317 add e2e test for InterpretStatus
  examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
  examples/customresourceinterpreter/apis/workload/v1alpha1/workload_types.go
  examples/customresourceinterpreter/apis/workload/v1alpha1/zz_generated.deepcopy.go
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  test/e2e/resourceinterpreter_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2388 Implement `karmdactl register` for joining clusters with PULL mode
  go.mod
  go.sum
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/register.go
  pkg/util/rbac.go
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go
  vendor/gopkg.in/square/go-jose.v2/.gitcookies.sh.enc
  vendor/gopkg.in/square/go-jose.v2/.gitignore
  vendor/gopkg.in/square/go-jose.v2/.travis.yml
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/CONTRIBUTING.md
  vendor/gopkg.in/square/go-jose.v2/LICENSE
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/gopkg.in/square/go-jose.v2/asymmetric.go
  vendor/gopkg.in/square/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/square/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/square/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/square/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/square/go-jose.v2/crypter.go
  vendor/gopkg.in/square/go-jose.v2/doc.go
  vendor/gopkg.in/square/go-jose.v2/encoding.go
  vendor/gopkg.in/square/go-jose.v2/json/LICENSE
  vendor/gopkg.in/square/go-jose.v2/json/README.md
  vendor/gopkg.in/square/go-jose.v2/json/decode.go
  vendor/gopkg.in/square/go-jose.v2/json/encode.go
  vendor/gopkg.in/square/go-jose.v2/json/indent.go
  vendor/gopkg.in/square/go-jose.v2/json/scanner.go
  vendor/gopkg.in/square/go-jose.v2/json/stream.go
  vendor/gopkg.in/square/go-jose.v2/json/tags.go
  vendor/gopkg.in/square/go-jose.v2/jwe.go
  vendor/gopkg.in/square/go-jose.v2/jwk.go
  vendor/gopkg.in/square/go-jose.v2/jws.go
  vendor/gopkg.in/square/go-jose.v2/opaque.go
  vendor/gopkg.in/square/go-jose.v2/shared.go
  vendor/gopkg.in/square/go-jose.v2/signing.go
  vendor/gopkg.in/square/go-jose.v2/symmetric.go
  vendor/k8s.io/cluster-bootstrap/token/jws/jws.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#2413 fix some problems in proxy
  pkg/search/proxy/cluster_proxy.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/store/multi_cluster_cache.go
Labels: kind/bug, approved, lgtm, size/M

#2412 fix etcd livenessProbe to result to etcd restart
  artifacts/deploy/karmada-etcd.yaml
Labels: kind/bug, approved, lgtm, size/XS

#2410 Reflect health status for recording the healthy state of the current resource
  pkg/controllers/status/workstatus_controller.go
  pkg/resourceinterpreter/defaultinterpreter/default.go
  pkg/util/helper/workstatus.go
Labels: kind/feature, size/S, approved, lgtm

#2418 add CustomizedClusterResourceModeling feature gate
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-scheduler.yaml
Labels: kind/feature, approved, lgtm, size/XS

#2422 Automated cherry pick of #2401: fix: remove unexpected validate webhook in configuration #2258: fix: create cluster apiservice in post install job
  charts/templates/_karmada_webhook_configuration.tpl
  charts/templates/post-install-job.yaml
Labels: approved, lgtm, size/M

#2421 Automated cherry pick of #2401: fix: remove unexpected validate webhook in configuration #2258: fix: create cluster apiservice in post install job
  charts/templates/_karmada_webhook_configuration.tpl
  charts/templates/post-install-job.yaml
Labels: approved, lgtm, size/M

#2420 Automated cherry pick of #2401: fix: remove unexpected validate webhook in configuration #2258: fix: create cluster apiservice in post install job
  charts/templates/_karmada_webhook_configuration.tpl
  charts/templates/post-install-job.yaml
Labels: approved, lgtm, size/M

#2402 Make changes to cluster-status-controller to adopt cluster resource models
  pkg/controllers/status/cluster_status_controller.go
Labels: kind/feature, approved, size/L, lgtm

#2416 add e2e test for InterpretHealth
  test/e2e/resourceinterpreter_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#2414 [e2e] add proxy e2e test
  test/e2e/framework/cluster.go
  test/e2e/framework/dynamic.go
  test/e2e/search_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#2409 Optimize `karmadactl init` to output example
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/examples.go
  pkg/karmadactl/cmdinit/utils/examples_test.go
Labels: kind/feature, approved, lgtm, size/M

#2426 Fix broken links in cherry-pick script
  hack/cherry_pick_pull.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#2415 retain PersistentVolume fields
  pkg/resourceinterpreter/defaultinterpreter/retain.go
Labels: kind/bug, size/S, approved, lgtm

#2428 [bugfix] fix error of reflectStatus failed when call resourceInterpreter
  pkg/controllers/status/workstatus_controller.go
Labels: kind/bug, approved, lgtm, size/XS, kind/failing-test

#2425 Perceiving the health status of cluster scheduling results in graceful evictions
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Labels: kind/feature, approved, size/L, lgtm

#2429 Automated cherry pick of #2428: fix error of reflectStatus failed when call
  pkg/controllers/status/workstatus_controller.go
Labels: approved, lgtm, size/XS

#2397 Schedule based on cluster resource model
  artifacts/agent/karmada-agent.yaml
  cmd/agent/app/options/options.go
  pkg/estimator/client/general.go
Labels: kind/feature, approved, size/L, lgtm

#2427 Add NotReady taint to the new cluster
  pkg/controllers/cluster/cluster_controller.go
Labels: kind/feature, size/S, approved, lgtm

#2301 Reschedule ResourceBinding when adding a cluster
  pkg/scheduler/event_handler.go
  test/e2e/rescheduling_test.go
Labels: kind/feature, approved, size/L, lgtm

#2436 Automated cherry pick of #1691: fix karmada-apiserver pending when helm upgrade
  charts/values.yaml
Labels: size/S, approved, lgtm

#2437 Automated cherry pick of #1691: fix karmada-apiserver pending when helm upgrade
  charts/values.yaml
Labels: size/S, approved, lgtm

#2294 No need to propagate ttlsecondsafterfinished
  pkg/resourceinterpreter/defaultinterpreter/prune/prune.go
  pkg/webhook/work/mutating.go
Labels: kind/feature, size/S, approved, lgtm

#2423 fix karmada chart kube-controller cluster-signing config error
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/templates/pre-install-job.yaml
Labels: kind/bug, approved, lgtm, size/XS

#2424 karmada controller-plane supports the ability to issue certificates via csr
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/templates/kube-controller-manager.yaml
Labels: kind/feature, approved, lgtm, size/XS

#2449 [karmada-scheduler] don't consider the older cluster when filtering with taint_toleration
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-webhook.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/runtime/framework.go
  test/e2e/rescheduling_test.go
Labels: kind/feature, approved, lgtm, size/M

#2451 [bugfix] when replicaDivisionPreference is Weighted and WeightPreference is nil
  pkg/scheduler/core/spreadconstraint/group_clusters.go
Labels: kind/bug, approved, lgtm, size/XS

#2453 Automated cherry pick of #2451: fix bug of #2447: when replicaDivisionPreference is Weighted
  pkg/scheduler/core/spreadconstraint/group_clusters.go
Labels: approved, lgtm, size/XS
