Repository karmada-io/karmada, pull requests merged in 2022-01, with the labels that each got.

#1205 add code comments for the karmada-controller-manager options
  cmd/controller-manager/app/options/options.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1207 Fix karmadactl init not found v1alpha1.cluster.karmada.io object
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/bug, approved, lgtm, size/M

#1206 remove unreachable code
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1211 Comment should start with a whitespace
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/karmadactl/cmdinit/utils/kubeclient.go
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/karmadactl/cmdinit/utils/util_test.go
Labels: size/S, approved, lgtm

#1212 installation document correction.
  docs/installation/installation.md
Labels: approved, kind/documentation, lgtm, size/XS

#1218 organize `karmadactl init` code
  pkg/karmadactl/cmdinit/cert/cert.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/check.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/rbac.go
  pkg/karmadactl/cmdinit/kubernetes/secret.go
  pkg/karmadactl/cmdinit/kubernetes/serviceaccount.go
  pkg/karmadactl/cmdinit/options/global.go
Labels: approved, lgtm, size/M, kind/cleanup

#1221 Make verify-codegen.sh script works properly on GitHub Action
  .github/workflows/ci.yml
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M, kind/flake

#1224 add error message when wait file exist timeout
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#1216 add script and doc for cherry_pick_pull
  docs/userguide/cherry-picks.md
  hack/cherry_pick_pull.sh
Labels: kind/feature, approved, size/L, kind/documentation, lgtm

#1223 add comments for internal Cluster API
  pkg/apis/cluster/types.go
Labels: approved, size/L, lgtm, kind/cleanup

#1213 Add Resource Interpreter Examples Document
  examples/README.md
Labels: approved, size/L, kind/documentation, lgtm

#1198 fix --cluster-namespace misleading description
  pkg/karmadactl/join.go
  pkg/karmadactl/options/global.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1200 add docs: Deploy a simplest multi-cluster Deployment
  docs/README.md
  docs/userguide/resource-propagating.md
Labels: approved, size/L, kind/documentation, lgtm

#1230 Orgnize documents about cherry-picks
  docs/README.md
  docs/contributors/devel/cherry-picks.md
  hack/cherry_pick_pull.sh
Labels: size/S, approved, kind/documentation, lgtm

#1229 Automated cherry pick of #1207: Fix karmadactl init not found v1alpha1.cluster.karmada.io
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/M

#1226 Retry on status update conflict
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/detector/aggregate_status.go
Labels: approved, lgtm, size/M, kind/cleanup

#1201 aggregatedapiserver support openapi
  cmd/aggregated-apiserver/app/options/options.go
  hack/update-codegen.sh
  pkg/apis/cluster/v1alpha1/doc.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, approved, size/XXL, lgtm

#1225 fix bug of resource computing
  pkg/util/helper/binding.go
  pkg/util/resource.go
Labels: kind/bug, approved, lgtm, size/M

#1234 Replace all the retry.DefaultBackoff with retry.DefaultRetry
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/status/workstatus_controller.go
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/XS, kind/cleanup

#1231 Add docs: Deploy deployment into a specified set of target clusters
  docs/userguide/resource-propagating.md
Labels: approved, size/L, kind/documentation, lgtm

#1238 mark override policy spec.targetCluster and spec.overriders deprecated
  charts/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/_crds/bases/policy.karmada.io_overridepolicies.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/util/overridemanager/overridemanager.go
  pkg/util/validation/validation.go
Labels: approved, lgtm, size/M, kind/deprecation

#1242 Focus on the functions syncWorkStatus and reflectStatus, modify comments and rename variable names
  pkg/controllers/status/workstatus_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#1240 Add documents for installing Karmada in Kind
  docs/installation/installation.md
Labels: size/S, approved, kind/documentation, lgtm

#1241 Complete missing step for working-with-anp
  docs/working-with-anp.md
Labels: size/S, approved, kind/documentation, lgtm

#1246 Improve register document
  docs/userguide/cluster-registration.md
Labels: size/S, approved, kind/documentation, lgtm

#1254 [scheduler]fix a defer execution sequence problem
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS

#1256 Bump base cluster from v1.21.1 to v1.22.0
  hack/local-up-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#1152 add validation for cluster api and remove validating webhook
  artifacts/deploy/webhook-configuration.yaml
  charts/templates/_karmada_webhook_configuration.tpl
  cmd/agent/app/options/validation.go
  cmd/webhook/app/webhook.go
  pkg/apis/cluster/validation/kubevalidation.go
  pkg/apis/cluster/validation/validation.go
  pkg/apis/cluster/validation/validation_test.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/karmadactl/join.go
  pkg/registry/cluster/strategy.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
  pkg/webhook/cluster/validating.go
Labels: kind/feature, approved, size/XL, lgtm

#1257 Put prodanlabs to owner list
  pkg/karmadactl/cmdinit/OWNERS
Labels: approved, kind/documentation, lgtm, size/XS

#1264 Update Kubernetes compatibilities for v1.22 and v1.23
  README.md
Labels: size/S, approved, kind/documentation, lgtm

#1267 fix event type of apply policy
  pkg/detector/detector.go
Labels: kind/bug, release-note, approved, lgtm, size/XS

#1268 Automated cherry pick of #1267: fix event type of apply policy
  pkg/detector/detector.go
Labels: release-note, approved, lgtm, size/XS

#1266 [optimize]split the code about resource event into event_handler.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, size/XL, lgtm

#1271 Update first in RetryOnConflict
  pkg/controllers/mcs/service_import_controller.go
Labels: size/S, approved, lgtm, kind/cleanup, release-note-none

#1253 Implementing the AggregateStatus hook
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  pkg/apis/config/v1alpha1/interpretercontext_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/detector/aggregate_status.go
  pkg/detector/detector.go
  pkg/resourceinterpreter/customizedinterpreter/webhook/attributes.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/default.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/helper/job.go
  pkg/util/helper/unstructured.go
  pkg/webhook/configuration/validating.go
Labels: kind/feature, approved, size/XL, lgtm

#1269 Update HookEnabled interface with resourceinterpreter
  pkg/controllers/binding/common.go
  pkg/detector/detector.go
  pkg/resourceinterpreter/customizedinterpreter/customized.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/interpreter/rules.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1281 modify log type to Error when err ocurs
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1145 fix ensureWork cyclomatic complexity
  pkg/controllers/binding/common.go
Labels: kind/feature, approved, lgtm, size/M

#1287 Fix documentation mistake of cluster registration #1279
  docs/userguide/cluster-registration.md
Labels: approved, lgtm, size/XS, release-note-none

#1278 introduce --tls-min-version flag to karmada-webhook
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
Labels: kind/feature, release-note, size/S, approved, lgtm

#1282 Add resource interpreter document
  docs/README.md
  docs/userguide/customizing-resource-interpreter.md
Labels: approved, size/L, kind/documentation, lgtm, release-note-none

#1265 stop resync for controllers
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup

#1292 karmada init: add more message for easy debug when nodePort exist
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: approved, lgtm, size/XS, release-note-none

#1295 Automated cherry pick of #1265: set resync period to 0
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
Labels: release-note, approved, lgtm, size/XS

#1270 Optimize karmadactl get to output more information
  pkg/karmadactl/get.go
Labels: kind/feature, release-note, approved, size/L, lgtm

#1297 Fix typo in the test log
  pkg/detector/compare_test.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1284 print pod's log when waiting pod ready timeout
  hack/util.sh
Labels: kind/feature, approved, lgtm, size/XS, release-note-none

#1288 Nominate resource interpreter framework owners
  pkg/resourceinterpreter/OWNERS
Labels: approved, kind/documentation, lgtm, size/XS, release-note-none

#1298 Fix ignore log error when error is isnotfound
  pkg/util/helper/binding.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1283 Enable multi replicas in CI
  artifacts/agent/karmada-agent.yaml
  artifacts/deploy/controller-manager.yaml
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-webhook.yaml
Labels: kind/feature, size/S, approved, lgtm, release-note-none

#1263 add proto interface for descheduler
  hack/update-estimator-protobuf.sh
  pkg/estimator/pb/generated.pb.go
  pkg/estimator/pb/generated.proto
  pkg/estimator/pb/service.pb.go
  pkg/estimator/pb/service.proto
  pkg/estimator/pb/types.go
  pkg/estimator/server/server.go
Labels: kind/api-change, approved, size/XXL, lgtm

#1286 Add e2e test for the AggregateStatus hook
  test/e2e/framework/workload.go
  test/e2e/resourceinterpreter_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#1290 add github-workflow doc
  docs/contributors/guide/git_workflow.png
  docs/contributors/guide/github-workflow.md
Labels: approved, size/L, kind/documentation, lgtm, release-note-none

#1199 bugfix: resource binding is not created when creating resources and propagation policies at the same time
  pkg/detector/detector.go
Labels: kind/bug, priority/important-soon, approved, size/L, lgtm, kind/flake

#1289 os.Exit will not wait for the defer function
  cmd/scheduler/main.go
Labels: kind/bug, release-note, size/S, approved, lgtm

#1308 Update first in RetryOnConflict
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1307 Add documents about karmada controllers
  docs/README.md
  docs/userguide/configure-controllers.md
Labels: approved, kind/documentation, lgtm, size/M, release-note-none

#1261 Introduce `--resync-period` flag to specify reflector resync period
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
Labels: kind/feature, release-note, size/S, approved, lgtm

#1312 Fix log in detector
  pkg/detector/detector.go
Labels: approved, lgtm, size/XS, kind/cleanup, release-note-none

#1311 Update first in RetryOnConflict
  pkg/controllers/execution/execution_controller.go
Labels: kind/feature, size/S, approved, lgtm, release-note-none

#1314 bug: agent's os.Exit will not wait for the defer function
  cmd/agent/app/agent.go
  cmd/agent/main.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#1315 bug: aggregated-apiserver's os.Exit will not wait for the defer function
  cmd/aggregated-apiserver/app/options/options.go
  cmd/aggregated-apiserver/main.go
Labels: kind/bug, size/S, approved, lgtm, release-note-none

#1316 bug: controller-manager's os.Exit will not wait for the defer function
  cmd/controller-manager/controller-manager.go
Labels: kind/bug, size/S, approved, lgtm, release-note-none

#1293 Revised command output info
  docs/userguide/resource-propagating.md
Labels: size/S, approved, kind/documentation, lgtm, release-note-none

#1327 Update first in RetryOnConflict
  pkg/controllers/status/workstatus_controller.go
Labels: size/S, approved, lgtm, kind/cleanup, release-note-none

#1328 Update first in RetryOnConflict
  pkg/controllers/status/cluster_status_controller.go
Labels: size/S, approved, lgtm, kind/cleanup, release-note-none

#1317 bug: karmadactl's os.Exit will not wait for the defer function
  cmd/karmadactl/karmadactl.go
Labels: kind/bug, size/S, approved, lgtm, release-note-none

#1304 fixed apiEnablements unordered issue
  pkg/controllers/status/cluster_status_controller.go
Labels: release-note, size/S, approved, lgtm, kind/cleanup

#1318 bug: kubectl karmada's os.Exit will not wait for the defer function
  cmd/kubectl-karmada/kubectl-karmada.go
Labels: kind/bug, size/S, approved, lgtm, release-note-none
