Repository karmada-io/karmada, pull requests merged in 2023-01, with the labels that each got.

#3012 cleanup pkg import in main function
  .golangci.yml
  cmd/agent/main.go
  cmd/aggregated-apiserver/main.go
  cmd/controller-manager/controller-manager.go
  cmd/descheduler/main.go
  cmd/karmada-search/main.go
  cmd/scheduler-estimator/main.go
  cmd/scheduler/main.go
  cmd/webhook/main.go
  examples/customresourceinterpreter/webhook/main.go
  operator/cmd/operator/operator.go
Labels: approved, size/L, lgtm, kind/cleanup

#3009 built-in interpreter support statefulset
  pkg/resourceinterpreter/defaultinterpreter/replica.go
  pkg/resourceinterpreter/defaultinterpreter/revisereplica.go
  pkg/resourceinterpreter/defaultinterpreter/revisereplica_test.go
Labels: kind/feature, approved, lgtm, size/M

#3010 search filter out not ready cluster
  pkg/search/controller.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
Labels: kind/bug, size/S, approved, lgtm

#3019 Automated cherry pick of #3010: search filter out not ready cluster
  pkg/search/controller.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
Labels: size/S, approved, lgtm

#3018 Automated cherry pick of #3010: search filter out not ready cluster
  pkg/search/controller.go
Labels: approved, lgtm, size/XS

#3015 Check for err judgments by `==` and fix it
  pkg/karmadactl/util/genericresource/builder.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3016 Automated cherry pick of #3010: search filter out not ready cluster
  pkg/search/controller.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
Labels: size/S, approved, lgtm

#3006 avoid calling apiserver when scheduling result has no changes
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS, kind/cleanup

#2997 support PodDisruptionBudget resource in default interpreter
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
  pkg/resourceinterpreter/defaultinterpreter/healthy.go
  pkg/resourceinterpreter/defaultinterpreter/healthy_test.go
  pkg/resourceinterpreter/defaultinterpreter/reflectstatus.go
  pkg/resourceinterpreter/defaultinterpreter/reflectstatus_test.go
  pkg/util/constants.go
  test/e2e/framework/poddisruptionbudget.go
  test/e2e/resource_test.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: kind/feature, approved, size/L, lgtm

#3025 Update protoc setup token
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3014 fix: Validate replicaSchedulingType and replicaDivisionPreference
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/util/helper/policy.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: kind/bug, size/S, approved, lgtm

#3027 stop proxy cache asynchronously
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/resource_cache.go
Labels: kind/bug, size/S, approved, lgtm

#2831 add edit mode for karmadactl interpreter command
  pkg/karmadactl/interpret/edit.go
  pkg/karmadactl/interpret/interpret.go
  pkg/util/interpreter/rule.go
Labels: kind/feature, approved, size/XL, lgtm

#3030 Automated cherry pick of #3027: stop proxy cache asynchronously
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/resource_cache.go
Labels: size/S, approved, lgtm

#3034 Automated cherry pick of #2980: Setup github token for action protoc #3025: Update protoc setup token
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS

#3031 Automated cherry pick of #3027: stop proxy cache asynchronously
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/resource_cache.go
Labels: size/S, approved, lgtm

#3035 Automated cherry pick of #2980: Setup github token for action protoc #3025: Update protoc setup token
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS

#3036 Automated cherry pick of #2980: Setup github token for action protoc #3025: Update protoc setup token
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS

#3039 modify description for flag usage
  cmd/scheduler-estimator/app/options/options.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3042 add UT for ApplyOverridePolicies
  pkg/util/overridemanager/overridemanager_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3043 add UT for SetDefaultClusterResourceModels
  pkg/apis/cluster/mutation/mutation_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3040 UpdateOrCreateToken get secrets err handling optimization
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3037 fix: OverridePolicy of labels/annotations with composed-labels
  pkg/util/overridemanager/labelannotationoverrider.go
  pkg/util/overridemanager/labelannotationoverrider_test.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: kind/bug, approved, size/L, lgtm

#3041 use k8s.io/utils/env GetString get env
  pkg/karmadactl/util/apiclient/apiclient.go
  vendor/k8s.io/utils/env/doc.go
  vendor/k8s.io/utils/env/env.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm

#3047 Automated cherry pick of #3037: fix: OverridePolicy of labels/annotations with
  pkg/util/overridemanager/labelannotationoverrider.go
  pkg/util/overridemanager/labelannotationoverrider_test.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: approved, size/L, lgtm

#3045 upgrade the alpine base image
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
Labels: approved, lgtm, size/XS

#3056 fix typo mistake
  docs/proposals/scheduling/697-descheduler/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#3052 fix that the InterpretDependency operation is absent in the validatin…
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  pkg/webhook/configuration/validating.go
  test/e2e/resourceinterpreter_test.go
  test/helper/resource.go
Labels: kind/bug, approved, lgtm, size/M

#3057 Fix syntax errors in the document
  docs/CHANGELOG/CHANGELOG-0.10.md
  docs/CHANGELOG/CHANGELOG-1.3.md
  docs/proposals/cleanup-propagated-resources/README.md
  docs/proposals/hpa/federated-hpa.md
  docs/proposals/proposal-template/proposal-template.md
  docs/proposals/resource-aggregation-proxy/README.md
  docs/proposals/resource-quota/README.md
  docs/proposals/scheduling/521-scheduler-estimator/README.md
Labels: approved, kind/documentation, lgtm, size/M

#3060 Add ut for deployments.go
  pkg/karmadactl/cmdinit/kubernetes/deployments_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3062 simplify context tests
  pkg/controllers/context/context_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3065 Add v1.4.0 changelog
  docs/CHANGELOG/CHANGELOG-1.4.md
Labels: approved, size/L, kind/documentation, lgtm

#3068 fix wrong note for webhook --metrics-bind-address
  cmd/webhook/app/options/options.go
Labels: approved, lgtm, size/XS, kind/cleanup, kind/flake

#3070 update alpine version to /etc/apk/repositories
  hack/util.sh
Labels: kind/feature, approved, lgtm, size/XS, kind/cleanup

#3066 Add ut for cluster registry
  cmd/aggregated-apiserver/app/options/options.go
  pkg/aggregatedapiserver/apiserver.go
  pkg/apis/cluster/scheme/regiser.go
  pkg/registry/cluster/strategy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3071 fix typo note for pkg/sharedcli/profileflag/profileflag.go
  pkg/sharedcli/profileflag/profileflag.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3074 Automated cherry pick of #3052: fix that the InterpretDependency operation is absent in the
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  pkg/webhook/configuration/validating.go
  test/e2e/resourceinterpreter_test.go
  test/helper/resource.go
Labels: approved, lgtm, size/M

#3076 Automated cherry pick of #3052: fix that the InterpretDependency operation is absent in the
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  pkg/webhook/configuration/validating.go
  test/e2e/resourceinterpreter_test.go
  test/helper/resource.go
Labels: approved, lgtm, size/M

#3077 Automated cherry pick of #3052: fix that the InterpretDependency operation is absent in the
  examples/customresourceinterpreter/webhook-configuration.yaml
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  pkg/webhook/configuration/validating.go
  test/e2e/resourceinterpreter_test.go
  test/helper/resource.go
Labels: approved, lgtm, size/M

#3073 Update wrong usage for flag --metrics-bind-address
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/options/options.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3061 Add ut for node.go
  pkg/karmadactl/cmdinit/kubernetes/check.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/node.go
  pkg/karmadactl/cmdinit/kubernetes/node_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3075 Add ut for service.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/services.go
  pkg/karmadactl/cmdinit/kubernetes/services_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3067 Build with Go patch release 1.19.5
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup
