Repository karmada-io/karmada, pull requests merged in 2023-02, with the labels that each got.

#3026 Support multiple schedulers
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/detector/detector.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#3088 feat: Retain the labels added to resources by member clusters
  pkg/util/annotation.go
  pkg/util/annotation_test.go
  pkg/util/label.go
  pkg/util/label_test.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/feature, approved, size/L, lgtm

#3093 Add schedulerName validation
  cmd/scheduler/app/options/validation.go
  cmd/scheduler/app/options/validation_test.go
  pkg/webhook/clusterpropagationpolicy/validating.go
  pkg/webhook/propagationpolicy/validating.go
Labels: kind/feature, approved, lgtm, size/M

#3100 Automated cherry pick of #3098: support pod subresource (attach, exec, port-forward) through
  pkg/search/proxy/framework/plugins/cluster/cluster.go
Labels: approved, lgtm, size/XS

#3096 Added the statement for disabling metrics
  cmd/agent/app/options/options.go
  cmd/controller-manager/app/options/options.go
  cmd/webhook/app/options/options.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3104 Clean up unused variable
  cmd/controller-manager/app/controllermanager.go
  pkg/detector/detector.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3110 [UT] add ut for kubernetes/secret.go
  pkg/karmadactl/cmdinit/kubernetes/secret_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3107 Create /usr/local/bin if it doesn't exists when install cli
  hack/install-cli.sh
Labels: kind/bug, approved, lgtm, size/XS

#3111 [ut] improve ut coverage for node.go
  pkg/karmadactl/cmdinit/kubernetes/node_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#3116 Automated cherry pick of #3098: support pod subresource (attach, exec, port-forward) through
  pkg/search/proxy/cluster_proxy.go
Labels: approved, lgtm, size/XS

#3055 Add Codecov configuration
  .codecov.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3121 Use http constants instead of string
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/registry/cluster/storage/proxy_test.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/framework/plugins/cache/cache_test.go
  pkg/search/proxy/framework/plugins/cluster/cluster_test.go
  pkg/search/proxy/framework/plugins/karmada/karmada_test.go
  pkg/util/proxy/proxy_test.go
  test/helper/request.go
Labels: size/S, approved, lgtm, kind/cleanup

#3115 Replace Hashsets with Sets
  pkg/resourceinterpreter/configurableinterpreter/configurable.go
  pkg/util/hashset/hashset.go
  pkg/util/hashset/hashset_test.go
Labels: approved, size/L, lgtm, kind/deprecation

#3120 karmada-search install by helm support specify external etcd
  charts/karmada/templates/karmada-search.yaml
Labels: kind/feature, approved, lgtm, size/XS

#3127 Fix aggregate pod status when aggregateStatusItems are empty
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3117 [ut] add ut for utils/rbac.go
  pkg/karmadactl/cmdinit/utils/rbac_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3114 Detector watch pp fields changed other than resource selector
  pkg/detector/detector.go
  pkg/detector/policy.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/framework/clusterpropagationpolicy.go
  test/e2e/propagationpolicy_test.go
Labels: kind/feature, approved, size/L, lgtm

#3129 feat: default interpreter supports cronJob aggregate status
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
  pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
Labels: kind/feature, approved, size/L, lgtm

#3139 Add schedulerName for event
  pkg/scheduler/event_handler.go
Labels: kind/feature, approved, lgtm, size/XS

#3137 [UT] add ut for cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/cmdinit_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#3132 Modify unit tests that never fail
  pkg/registry/cluster/strategy_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#3135 Update default kind version and testing against v1.26.0
  .github/workflows/ci.yml
  .github/workflows/lint-chart.yaml
  hack/create-cluster.sh
  hack/local-up-karmada.sh
Labels: size/S, approved, lgtm, kind/cleanup

#3099 feat: support for removing annotations/labels propagated through karmada
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/util/annotation.go
  pkg/util/annotation_test.go
  pkg/util/helper/work.go
  pkg/util/label.go
  pkg/util/label_test.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/feature, approved, size/XL, lgtm

#3136 [bug-fix] update clueter-cluster shell
  artifacts/kindClusterConfig/general-config.yaml
  hack/create-cluster.sh
Labels: size/S, approved, lgtm, kind/cleanup

#2702 Add placement for bindingSpec
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/detector/detector.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: kind/api-change, approved, size/XXL, lgtm

#3138 chart: Support custom labels variable for etcd
  charts/karmada/README.md
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/etcd.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, lgtm, size/M

#3141 Replace "" with NamespaceAll.
  pkg/descheduler/descheduler.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/cmdinit/kubernetes/services.go
  pkg/karmadactl/get/get.go
  pkg/scheduler/event_handler.go
Labels: size/S, approved, lgtm, kind/cleanup

#3148 [UT] add ut for cmdinit/kubeconfig.go
  pkg/karmadactl/cmdinit/utils/kubeconfig_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3145 [UT] add ut for utils/template.go
  pkg/karmadactl/addons/utils/template_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3105 Propose preferred cluster
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/XL, lgtm

#3150 remove code for collecting clusterID under upgrading
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/M, kind/cleanup

#3160 Fix UpdateOrCreateToken get secrets err handling optimization
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
Labels: kind/bug, priority/important-soon, approved, lgtm, size/XS

#3163 Add SchedulerObservedAffinityName to RB/CRB
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, size/S, approved, lgtm

#3155 [UT] improve test for kubeconfig.go
  pkg/karmadactl/cmdinit/utils/kubeconfig_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#3172 Simply OrderedClusterAffinities API name
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/L, lgtm

#3165 Refactor scheduler interfaces
  pkg/detector/detector.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go
  pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/framework_test.go
  pkg/scheduler/framework/testing/mock_interface.go
Labels: approved, size/L, lgtm, kind/cleanup

#3164 add validation for ClusterAffinities
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
  pkg/webhook/clusterpropagationpolicy/validating.go
  pkg/webhook/propagationpolicy/validating.go
Labels: kind/feature, approved, size/L, lgtm

#3177 [UT] increase test coverage for core/assignment.go
  pkg/scheduler/core/assignment_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3156 Make the validity period of cert configurable
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: kind/feature, approved, lgtm, size/XS

#3157 Make the result unique for GenerateBindingReferenceKey function
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: size/S, approved, lgtm

#3126 Add multiple scheduling group proposal
  docs/proposals/scheduling/multi-scheduling-group/README.md
Labels: kind/feature, approved, size/L, kind/documentation, lgtm

#3179 [UT] Add ut for utils/format.go
  pkg/karmadactl/cmdinit/utils/format_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3193 feat: validates the fieldSelector of overridepolicy
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
  pkg/webhook/clusteroverridepolicy/validating.go
  pkg/webhook/overridepolicy/validating.go
Labels: kind/feature, approved, size/L, lgtm

#3182 Refactor execution_controller.go and objectwatcher.go
  pkg/controllers/execution/execution_controller.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, lgtm, size/M, kind/cleanup

#3209 Add bindingStatus in the schedule algorithm interface
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/framework_test.go
  pkg/scheduler/framework/testing/mock_interface.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, size/L, lgtm

#3201 fix the bug that the work object may contain uppercase characters
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: kind/bug, approved, lgtm, size/XS

#3211 Modify judgement of placement changed and consider clusteraffinities
  pkg/scheduler/helper.go
  pkg/scheduler/helper_test.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, size/L, lgtm

#3210 Update the RB condition is updated only after scheduling
  pkg/scheduler/scheduler.go
  pkg/util/helper/workstatus.go
Labels: kind/bug, approved, size/L, lgtm, kind/cleanup

#3213 Automated cherry pick of #3201: fix the bug that the work object may contain uppercase
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: size/S, approved, lgtm

#3214 Automated cherry pick of #3201: fix the bug that the work object may contain uppercase
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: size/S, approved, lgtm

#3215 Automated cherry pick of #3201: fix the bug that the work object may contain uppercase
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: approved, lgtm, size/XS

#3181 Invoke multi times with clusterAffinities when reschedule ResourceBinding
  pkg/scheduler/event_handler.go
  pkg/scheduler/helper.go
  pkg/scheduler/helper_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, approved, size/XL, lgtm

#3219 Add e2e for schedule with clusterAffinities when replica scheduling type is Duplicated
  test/e2e/clusteraffinities_test.go
  test/e2e/framework/clusterpropagationpolicy.go
  test/e2e/framework/propagationpolicy.go
  test/e2e/propagationpolicy_test.go
Labels: kind/feature, approved, size/L, lgtm

#3224 Set image tag for release 1.5
  charts/karmada/values.yaml
Labels: size/S, approved, lgtm, kind/cleanup
