Repository karmada-io/karmada, pull requests merged in 2023-07, with the labels that each got.

#3729 feat: Support CronFederatedHPA
  artifacts/deploy/webhook-configuration.yaml
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  cmd/controller-manager/app/controllermanager.go
  cmd/webhook/app/webhook.go
  go.mod
  go.sum
  pkg/apis/autoscaling/v1alpha1/well_known_constants.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
  pkg/util/apigroup.go
  pkg/util/helper/cronfederatedhpa.go
  pkg/webhook/cronfederatedhpa/validation.go
  vendor/github.com/adhocore/gronx/.editorconfig
  vendor/github.com/adhocore/gronx/.gitignore
  vendor/github.com/adhocore/gronx/.goreleaser.yml
  vendor/github.com/adhocore/gronx/CHANGELOG.md
  vendor/github.com/adhocore/gronx/LICENSE
  vendor/github.com/adhocore/gronx/README.md
  vendor/github.com/adhocore/gronx/VERSION
  vendor/github.com/adhocore/gronx/batch.go
  vendor/github.com/adhocore/gronx/checker.go
  vendor/github.com/adhocore/gronx/gronx.go
  vendor/github.com/adhocore/gronx/next.go
  vendor/github.com/adhocore/gronx/prev.go
  vendor/github.com/adhocore/gronx/validator.go
  vendor/github.com/go-co-op/gocron/.gitignore
  vendor/github.com/go-co-op/gocron/.golangci.yaml
  vendor/github.com/go-co-op/gocron/CODE_OF_CONDUCT.md
  vendor/github.com/go-co-op/gocron/CONTRIBUTING.md
  vendor/github.com/go-co-op/gocron/LICENSE
  vendor/github.com/go-co-op/gocron/Makefile
  vendor/github.com/go-co-op/gocron/README.md
  vendor/github.com/go-co-op/gocron/SECURITY.md
  vendor/github.com/go-co-op/gocron/executor.go
  vendor/github.com/go-co-op/gocron/gocron.go
  vendor/github.com/go-co-op/gocron/job.go
  vendor/github.com/go-co-op/gocron/locker.go
  vendor/github.com/go-co-op/gocron/scheduler.go
  vendor/github.com/go-co-op/gocron/time_helper.go
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem.go
  vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem_1.11.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#3742 fix: AdminKubeconfigSecretName function name
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/tasks/deinit/kubeconfig.go
  operator/pkg/tasks/init/upload.go
  operator/pkg/util/naming.go
Labels: size/S, approved, lgtm, kind/cleanup

#3748 Nominate FederatedHPA feature owner
  cmd/metrics-adapter/OWNERS
  pkg/controllers/federatedhpa/OWNERS
  pkg/metricsadapter/OWNERS
Labels: size/S, approved, lgtm, kind/cleanup

#3636 add proposal for MultiClusterService
  docs/proposals/networking/multiclusterservice.md
  docs/proposals/networking/statics/service-discovery.png
  docs/proposals/networking/statics/service-exposure.png
Labels: approved, size/L, lgtm, kind/design

#3757 Update set-output command in lint-chart ci
  .github/workflows/lint-chart.yaml
Labels: kind/feature, size/S, approved, lgtm

#3759 Use SetOut and/or SetErr instead SetOutput
  pkg/karmadactl/options/options.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3756 Promote code owners as per community membership
  OWNERS
  pkg/controllers/OWNERS
  pkg/resourceinterpreter/OWNERS
  pkg/resourceinterpreter/default/thirdparty/OWNERS
  pkg/scheduler/OWNERS
Labels: size/S, approved, lgtm, kind/cleanup

#3761 Delete unnecessary symbols in the execution script
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#3764 Automated cherry pick of #3123: Avoid multiple executions after rlock in concurrent scenarios
  pkg/util/fedinformer/genericmanager/multi-cluster-manager.go
  pkg/util/fedinformer/genericmanager/single-cluster-manager.go
  pkg/util/fedinformer/typedmanager/multi-cluster-manager.go
  pkg/util/fedinformer/typedmanager/single-cluster-manager.go
Labels: approved, lgtm, size/M

#3765 Automated cherry pick of #3123: Avoid multiple executions after rlock in concurrent scenarios
  pkg/util/fedinformer/genericmanager/multi-cluster-manager.go
  pkg/util/fedinformer/genericmanager/single-cluster-manager.go
  pkg/util/fedinformer/typedmanager/multi-cluster-manager.go
  pkg/util/fedinformer/typedmanager/single-cluster-manager.go
Labels: approved, lgtm, size/M

#3766 Automated cherry pick of #3739: fix: when application failover is enabled but propagateDeps
  pkg/util/validation/validation.go
Labels: approved, lgtm, size/XS

#3768 karmada operator: add karmada operator chart to dockerhub
  Makefile
  hack/package-helm-chart.sh
Labels: kind/feature, size/S, approved, lgtm

#3754 add cronfederatedhpa webhook for karmadactl and karmada-operator
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: approved, lgtm, size/M

#3776 Update maintainers affiliation
  MAINTAINERS.md
Labels: size/S, approved, lgtm, kind/cleanup

#3775 cleanup: Adapt metrics-adapter deploying script to more generic scenario
  hack/deploy-metrics-adapter.sh
Labels: approved, lgtm, size/M, kind/cleanup

#3777 chart: fix karmada search external etcd no volume mount
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-search.yaml
Labels: kind/bug, size/S, approved, lgtm

#3778 karmada operator: avoid invalid reconclie for karmada cr
  operator/pkg/controller/karmada/controller.go
Labels: kind/feature, approved, lgtm, size/M

#3779 add validation for MultiClusterService
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  cmd/webhook/app/webhook.go
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/validatingmcs.go
  pkg/webhook/multiclusterservice/validating.go
Labels: kind/feature, approved, size/L, lgtm

#3784 Automated cherry pick of #3777: chart: fix karmada search external etcd no volume mount
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-search.yaml
Labels: size/S, approved, lgtm

#3785 Automated cherry pick of #3777: chart: fix karmada search external etcd no volume mount
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-search.yaml
Labels: size/S, approved, lgtm

#3781 feat: Change the port of MCS to required.
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
  docs/proposals/networking/multiclusterservice.md
  pkg/apis/networking/v1alpha1/service_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, size/S, approved, lgtm, kind/cleanup

#3786 Update Kubernetes compatibility
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  README.md
Labels: size/S, approved, lgtm, kind/cleanup

#3788 Proposing PropagationPolicy Preemption API
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#3797 add MultiClusterService API to api swagger doc
  api/openapi-spec/swagger.json
  hack/tools/swagger/generateswagger.go
  pkg/apis/networking/v1alpha1/service_types.go
Labels: approved, size/XXL, kind/documentation, lgtm

#3795 fix: reduce the number of metrics by merging entries
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/metrics/resource.go
Labels: approved, lgtm, size/M, kind/cleanup, kind/deprecation

#3796 Add e2e coverage of the features doc
  test/e2e/coverage_docs/E2E_coverage.md
  test/e2e/coverage_docs/namespace_test.md
  test/e2e/coverage_docs/resource_test.md
Labels: size/S, approved, lgtm, kind/cleanup

#3741 feat: optimize scheduling condition semantics
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/helper.go
  pkg/scheduler/helper_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: approved, size/L, lgtm

#3631 Implement proxy headers of cluster API
  pkg/util/membercluster_client.go
  pkg/util/round_trippers.go
Labels: kind/feature, approved, lgtm, size/M

#3613 update lifted files to k8s 1.26
  pkg/util/lifted/corehelpers.go
  pkg/util/lifted/corehelpers_test.go
  pkg/util/lifted/corev1helpers.go
  pkg/util/lifted/corev1helpers_test.go
  pkg/util/lifted/corevalidation.go
  pkg/util/lifted/corevalidation_test.go
  pkg/util/lifted/deployment.go
  pkg/util/lifted/deployment_test.go
  pkg/util/lifted/discovery.go
  pkg/util/lifted/discovery_test.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/genutils.go
  pkg/util/lifted/genutils_test.go
  pkg/util/lifted/lua_oslib_safe.go
  pkg/util/lifted/nodeaffinity.go
  pkg/util/lifted/nodeaffinity_test.go
  pkg/util/lifted/podtemplate.go
  pkg/util/lifted/pubkeypin/pubkeypin.go
  pkg/util/lifted/requestinfo_test.go
  pkg/util/lifted/resourcename.go
  pkg/util/lifted/scheduler/cache/cache.go
  pkg/util/lifted/scheduler/cache/interface.go
  pkg/util/lifted/scheduler/cache/node_tree.go
  pkg/util/lifted/scheduler/cache/snapshot.go
  pkg/util/lifted/scheduler/framework/listers.go
  pkg/util/lifted/scheduler/framework/parallelize/parallelism.go
  pkg/util/lifted/scheduler/framework/parallelize/parallelism_test.go
  pkg/util/lifted/scheduler/framework/types.go
  pkg/util/lifted/scheduler/util/pod_resources.go
  pkg/util/lifted/taint.go
  pkg/util/lifted/taint_test.go
  pkg/util/lifted/validateclustertaints.go
  pkg/util/lifted/validatingmci_test.go
  pkg/util/lifted/visitpod.go
  pkg/util/lifted/visitpod_test.go
  pkg/util/selector.go
Labels: approved, size/XL, lgtm, kind/cleanup

#3791 e2e: Add e2e for CronFederatedHPA
  hack/deploy-karmada.sh
  hack/local-up-karmada.sh
  test/e2e/cronfederatedhpa_test.go
  test/e2e/framework/cronfederatedhpa.go
  test/e2e/framework/deployment.go
  test/e2e/framework/federatedhpa.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm, kind/cleanup

#3810 Add conflict resolution API to PP and CPP
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/L, lgtm

#3801 add e2e test when cluster join, update, karmada need to reconcile search cache
  test/e2e/search_test.go
  test/e2e/suite_test.go
Labels: approved, size/L, lgtm

#3684 Add policy preemption proposal
  docs/proposals/scheduling/policy-preemption/README.md
  docs/proposals/scheduling/policy-preemption/preemption_process.PNG
  docs/proposals/scheduling/policy-preemption/priority_update.PNG
Labels: approved, size/L, lgtm, kind/design

#3819 build cached restmapper based on Kubernetes restmapper
  pkg/util/restmapper/restmapper.go
  pkg/util/restmapper/restmapper_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3780 proposal: seamless cluster migration
  docs/proposals/migration/design-of-seamless-cluster-migration-scheme.md
  docs/proposals/migration/statics/karmada-seamless migration.drawio.xml
  docs/proposals/migration/statics/pic1.png
  docs/proposals/migration/statics/pic2.png
  docs/proposals/migration/statics/pic3.png
  docs/proposals/migration/statics/pic4.png
Labels: approved, size/XXL, kind/documentation, lgtm, kind/design

#3826 feat: allow custom metrics configuration of FederatedHPA
  pkg/util/lifted/corehelpers.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/validatingfhpa.go
Labels: kind/feature, approved, size/L, lgtm

#3828 Add feature gate for policy preemption
  pkg/features/features.go
Labels: kind/feature, approved, lgtm, size/XS

#3831 feat: add more validation for CronFederatedHPA
  pkg/webhook/cronfederatedhpa/validation.go
Labels: kind/feature, approved, lgtm, size/M

#3821 feat: realization of ConflictResolution in PP
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/detector/detector.go
  pkg/util/annotation.go
  pkg/util/annotation_test.go
  pkg/util/helper/work.go
Labels: kind/feature, approved, size/L, lgtm

#3837 feat: implement propagation policy priority preemption
  pkg/detector/detector.go
  pkg/detector/preemption.go
  pkg/util/helper/binding.go
  pkg/util/names/names.go
Labels: kind/feature, approved, size/L, lgtm

#3848 fix: when the PP is deleted, the propagationpolicy.karmada.io/name label in the resource template's labels is not removed.
  pkg/detector/policy.go
Labels: kind/bug, approved, lgtm, size/XS

#3851 Automated cherry pick of #3848: fix: When the PP is deleted, the
  pkg/detector/policy.go
Labels: approved, lgtm, size/XS

#3818 fix: can not upgrade karmada controller manager deployment with helm upgrade
  charts/karmada/templates/karmada-controller-manager.yaml
Labels: kind/bug, approved, lgtm, size/XS

#3853 feat: avoid calculating available replicas for non-workload
  pkg/scheduler/core/util.go
Labels: kind/feature, approved, lgtm, size/XS

#3839 feat: Add label on the namespace created by karmada
  pkg/karmadactl/register/register.go
  pkg/util/credential.go
  pkg/util/namespace.go
  pkg/util/namespace_test.go
Labels: kind/feature, approved, size/L, lgtm

#3862 fix ut in TestMultiClusterCache watch
  pkg/search/proxy/store/multi_cluster_cache_test.go
Labels: kind/bug, size/S, approved, lgtm

#3838 test: add e2e test for seamless migration
  test/e2e/seamless_migration_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#3863 fix: fix bugs about validation of targetMinReplicas<=targetMaxReplicas and CronFederatedHPA status record
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
  pkg/webhook/cronfederatedhpa/validation.go
Labels: kind/bug, approved, lgtm, size/XS

#3836 color unit-test output
  .github/workflows/ci.yml
  Makefile
Labels: kind/feature, size/S, approved, lgtm

#3815 Fix charts installation when certs mode is custom
  charts/karmada/templates/pre-install-job.yaml
Labels: kind/bug, approved, size/L, lgtm

#3833 etcd:Update version to 3.5.9
  artifacts/deploy/karmada-etcd.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: size/S, approved, lgtm

#3855 ut: add cron-fhpa validation unit-test
  pkg/webhook/cronfederatedhpa/validating_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3845 feat: implement preemption between propagation policies
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/detector/preemption.go
Labels: kind/feature, approved, lgtm, size/M

#3865 Updated Golang version from v1.20.4 to v1.20.6
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup
