Repository karmada-io/karmada, pull requests merged in 2023-08, with the labels that each got.

#3827 Make some cleanup in dependencies distributor
  cmd/controller-manager/app/controllermanager.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3874 use ClusterCacheSyncTimeout for resources on fed control plane as well
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/util/constants.go
Labels: kind/feature, approved, lgtm, size/XS

#3872 Update release notes of release-1.4,release-1.5,release-1.6
  docs/CHANGELOG/CHANGELOG-1.4.md
  docs/CHANGELOG/CHANGELOG-1.5.md
  docs/CHANGELOG/CHANGELOG-1.6.md
Labels: approved, size/L, kind/documentation, lgtm

#3867 feat: add metrics and events for policy preemption
  pkg/detector/preemption.go
  pkg/events/events.go
  pkg/metrics/resource.go
Labels: kind/feature, approved, lgtm, size/M

#3868 fix: fix dependent resources being created and deleted repeatedly when the dependent resource has a status field.
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/util/eventfilter/eventfilter.go
  pkg/util/eventfilter/eventfilter_test.go
Labels: kind/bug, approved, lgtm, size/M

#3885 Add a Ingress to the default dependencinterpreter
  pkg/resourceinterpreter/default/native/dependencies.go
Labels: kind/feature, size/S, approved, lgtm

#3852 cleanup: remove old version hpa controller
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/hpa/hpa_controller.go
Labels: approved, size/L, lgtm, kind/deprecation

#2736 Refactor the func and event of taint cluster
  pkg/controllers/cluster/cluster_controller.go
  pkg/events/events.go
  pkg/util/helper/taint.go
  pkg/util/helper/taint_test.go
  test/e2e/failover_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3887 Upgrade a7ul/tar-action to v1.1.3
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/deprecation

#3881 Update release notes on release-1.4 branch
  docs/CHANGELOG/CHANGELOG-1.4.md
Labels: approved, size/L, kind/documentation, lgtm

#3882 Update release notes on release-1.5 branch
  docs/CHANGELOG/CHANGELOG-1.4.md
  docs/CHANGELOG/CHANGELOG-1.5.md
Labels: approved, size/L, kind/documentation, lgtm

#3883 Update release notes on release-1.6 branch
  docs/CHANGELOG/CHANGELOG-1.4.md
  docs/CHANGELOG/CHANGELOG-1.5.md
  docs/CHANGELOG/CHANGELOG-1.6.md
Labels: approved, size/L, kind/documentation, lgtm

#3888 Update v1.5.3 release notes
  docs/CHANGELOG/CHANGELOG-1.5.md
Labels: approved, kind/documentation, lgtm, size/M

#3889 feat: update policy preemption proposals
  docs/proposals/scheduling/policy-preemption/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#3890 Automated cherry pick of #3888: Update v1.5.3 release notes
  docs/CHANGELOG/CHANGELOG-1.5.md
Labels: approved, lgtm, size/M

#3879 fix bug: avoid updating directly cached resource template
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/helper/binding.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: kind/bug, approved, lgtm, size/M

#3894 Automated cherry pick of #3879: avoid updating directly cached resource template for clean up
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/helper/binding.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: approved, lgtm, size/M

#3895 Automated cherry pick of #3879: avoid updating directly cached resource template for clean up
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/helper/binding.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: approved, lgtm, size/M

#3901 docs: Add talks from KubeDay and KubeCon
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#3893 Automated cherry pick of #3879: avoid updating directly cached resource template for clean up
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/helper/binding.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: approved, lgtm, size/M

#3900 doc: Fix grammar and markdown syntax
  README.md
Labels: size/S, approved, kind/documentation, lgtm

#3896 ut: add mcs validation ut
  pkg/webhook/multiclusterservice/validating_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3909 update validate-resourceinterpretercustomization webhook timeout from 3s to 10s
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: approved, lgtm, size/XS, kind/flake

#3913 Update kind to v0.20.0
  .github/workflows/lint-chart.yaml
  go.mod
  go.sum
  hack/cli-testing-environment.sh
  hack/create-cluster.sh
  hack/local-up-karmada.sh
  vendor/modules.txt
  vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/types.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/delete/delete.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/read.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/write.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/loadbalancer/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/loadbalancer/const.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/logs/logs.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/OWNERS
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/network.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/provider.go
  vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
  vendor/sigs.k8s.io/kind/pkg/fs/fs.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/convert_v1alpha4.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/encoding/load.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/types.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/validate.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/zz_generated.deepcopy.go
Labels: approved, size/L, lgtm, kind/cleanup

#3908 fix unable to sync list
  pkg/util/fedinformer/transform.go
Labels: kind/bug, approved, lgtm, size/M

#3904 test: add e2e test to cover PropagationPolicy
  test/e2e/framework/configmap.go
  test/e2e/propagationpolicy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3920 docs: Add adopter refrence
  ADOPTERS.md
Labels: size/S, approved, kind/documentation, lgtm

#3811 feat: Introduce a LabelSelector field to DependentObjectReference
  pkg/apis/config/v1alpha1/interpretercontext_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
Labels: kind/feature, kind/api-change, approved, size/XL, lgtm

#3915 grant clusterrole admin with karamda resource permission
  artifacts/deploy/admin-clusterrole-aggregation.yaml
  artifacts/deploy/kube-controller-manager.yaml
  hack/deploy-karmada.sh
Labels: kind/feature, approved, size/L, lgtm

#3876 feat: add pod replica interpreter
  pkg/resourceinterpreter/default/native/replica.go
Labels: kind/feature, size/S, approved, lgtm

#3911 Add helm index for v1.6.1 and v1.6.2
  charts/index.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#3925 [1.6] Bump k8s.io dependencies to v0.26.4
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
  go.mod
  go.sum
  pkg/generated/openapi/zz_generated.openapi.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/registry/rest/rest.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/ready.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: approved, size/XL, lgtm, kind/cleanup

#3928 Add e2e coverage analysis
  test/e2e/aggregatedapi_test.go
  test/e2e/coverage_docs/E2E_coverage.md
  test/e2e/coverage_docs/aggregatedapi_test.md
  test/e2e/coverage_docs/cronfederatedhpa_test.md
  test/e2e/coverage_docs/namespace_test.md
  test/e2e/coverage_docs/resource_test.md
  test/e2e/coverage_docs/seamless_migration_test.md
  test/e2e/coverage_docs/spread_by_region_test.md
  test/e2e/cronfederatedhpa_test.go
  test/e2e/spread_by_region_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3934 changed sigs.k8s.io/cluster-api v1.5.0-rc.0 to v1.5.0
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/api/v1beta1/machineset_webhook.go
  vendor/sigs.k8s.io/cluster-api/util/labels/format/helpers.go
Labels: size/S, approved, lgtm, kind/cleanup

#3922 fix federated-hpa plain metric calc
  pkg/controllers/federatedhpa/replica_calculator.go
Labels: kind/bug, approved, lgtm, size/XS

#3919 karmada operator: fixed karmada label beinging overwritten
  operator/pkg/controller/karmada/controller.go
Labels: kind/feature, approved, lgtm, size/XS

#3942 Upgraded alpine base image
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
Labels: approved, lgtm, size/XS, kind/cleanup

#3593 feat: introducing a karmadactl top command
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/top/metrics_printer.go
  pkg/karmadactl/top/metrics_sorter.go
  pkg/karmadactl/top/top.go
  pkg/karmadactl/top/top_pods.go
  vendor/k8s.io/kubectl/pkg/metricsutil/metrics_printer.go
  vendor/k8s.io/kubectl/pkg/metricsutil/metrics_resource_adder.go
  vendor/k8s.io/kubectl/pkg/metricsutil/metrics_sorter.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/clientset.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/podmetrics.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#3910 [karmadactl get] judge with label on the resources determine whether resource is adopted by Karmada
  pkg/karmadactl/get/get.go
Labels: approved, size/L, lgtm, kind/cleanup

#3931 automatic modify image version in helm chart when releasing
  charts/karmada/values.yaml
  hack/package-helm-chart.sh
Labels: size/S, approved, lgtm, kind/flake

#3943 improve overridemanager test
  pkg/util/overridemanager/overridemanager_test.go
Labels: approved, lgtm, size/XS, kind/flake

#3694 proposal for native service discovery
  docs/proposals/service-discovery/README.md
Labels: approved, size/L, lgtm, kind/design, tide/merge-method-squash

#3951 add http limit for the Slowloris attack
  cmd/descheduler/app/descheduler.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/scheduler.go
  pkg/sharedcli/profileflag/profileflag.go
Labels: approved, lgtm, size/M, kind/cleanup

#3950 ResourceSummary add check index for -1
  pkg/modeling/modeling.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3705 Add proposal for remove derived mcs
  docs/proposals/mcs/additional-dns-server.jpg
  docs/proposals/mcs/remove-derived-in-controller.jpg
  docs/proposals/mcs/remove-derived-mcs.md
  docs/proposals/mcs/remove-derived-mcs.png
Labels: approved, size/L, lgtm, kind/design

#3944 update operator default timeout
  operator/pkg/karmadaresource/webhookconfiguration/webhookconfiguration.go
  operator/pkg/tasks/init/apiserver.go
  operator/pkg/tasks/init/etcd.go
  operator/pkg/tasks/init/karmadaresource.go
  operator/pkg/tasks/init/wait.go
  operator/pkg/util/apiclient/idempotency.go
  operator/pkg/util/endpoint.go
Labels: approved, lgtm, size/M

#3947 Proxy connect get cluster impersonator secret use secretLister
  cmd/aggregated-apiserver/app/options/options.go
  pkg/aggregatedapiserver/apiserver.go
  pkg/registry/cluster/storage/proxy.go
  pkg/registry/cluster/storage/proxy_test.go
  pkg/registry/cluster/storage/storage.go
Labels: approved, lgtm, size/M, kind/cleanup

#3808 only update object in member cluster by execution controller
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/context/context.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/execution/execution_controller_test.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/resourceinterpreter/fake/fake.go
  pkg/util/fedinformer/handlers.go
  pkg/util/lifted/objectwatcher.go
  pkg/util/memberclusterinformer/memberclusterinformer.go
  pkg/util/memberclusterinformer/memberclusterinformer_test.go
  pkg/util/objectwatcher/objectwatcher.go
  pkg/util/objectwatcher/objectwatcher_test.go
  test/helper/resource.go
Labels: kind/feature, approved, size/XXL, lgtm

#3957 Feat: Add karmada resource clusterrole for helm install
  charts/karmada/templates/karmada-resource-clusterrole.yaml
Labels: kind/feature, approved, size/L, lgtm

#3856 doc: add dependency-update for helm chart of operator
  operator/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#3948 repair the cluster_status_controller_test
  pkg/controllers/status/cluster_status_controller_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3933 Extend Cluster API to support multiple zones
  api/openapi-spec/swagger.json
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, lgtm, size/M

#3966 fix addAnnotationWithClusterName crash
  pkg/registry/search/storage/cache.go
Labels: kind/bug, size/S, approved, lgtm

#3955 helm: support PodDisruptionBudget for resources
  charts/karmada/templates/karmada-agent.yaml
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#3939 feat: Refactor the mechanism for propagating serviceexport derived svc and eps.
  pkg/resourceinterpreter/default/native/dependencies.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
  pkg/util/helper/policy.go
  pkg/util/helper/policy_test.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: kind/feature, approved, size/L, lgtm

#3949 feat: add cron federated hpa metrics
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
  pkg/metrics/resource.go
Labels: kind/feature, approved, lgtm, size/M

#3976 Automated cherry pick of #3966: fix addAnnotationWithClusterName crash
  pkg/registry/search/storage/cache.go
Labels: size/S, approved, lgtm

#3977 Automated cherry pick of #3966: fix addAnnotationWithClusterName crash
  pkg/registry/search/storage/cache.go
Labels: size/S, approved, lgtm

#3978 Automated cherry pick of #3966: fix addAnnotationWithClusterName crash
  pkg/registry/search/storage/cache.go
Labels: size/S, approved, lgtm

#3732 karmada operator: install karmada metrics adapter addon
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/constants/constants.go
  operator/pkg/controlplane/metricsadapter/mainfests.go
  operator/pkg/controlplane/metricsadapter/metricsadapter.go
  operator/pkg/karmadaresource/apiservice/apiservice.go
  operator/pkg/karmadaresource/apiservice/manifest.go
  operator/pkg/tasks/init/component.go
  operator/pkg/tasks/init/karmadaresource.go
  operator/pkg/tasks/init/wait.go
  operator/pkg/util/apiclient/wait.go
  operator/pkg/util/naming.go
Labels: kind/feature, approved, size/XL, lgtm

#3979 rename metrics
  pkg/metrics/resource.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3965 Response to priority change of PropagationPolicy
  pkg/detector/detector.go
  pkg/detector/preemption.go
Labels: kind/feature, approved, lgtm, size/M

#3987 Standardize metrics help message
  pkg/metrics/resource.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/scheduler_metrics_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#3990 Response to priority change of ClusterPropagationPolicy
  pkg/detector/detector.go
  pkg/detector/preemption.go
Labels: kind/feature, approved, lgtm, size/M

#3992 Remove the execute permission from the directory
  operator/pkg/tasks/init/crd.go
  operator/pkg/util/util.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
  pkg/karmadactl/cmdinit/utils/util.go
Labels: size/S, approved, lgtm, kind/cleanup

#3983 transform zone to zones
  pkg/apis/cluster/mutation/mutation.go
  pkg/apis/cluster/mutation/mutation_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3975 Add validation for zones
  pkg/apis/cluster/validation/validation.go
  pkg/apis/cluster/validation/validation_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3996 feat: adapt zones check in spread constraint plugin
  pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
Labels: kind/feature, approved, lgtm, size/XS

#3995 feat: deprecate cluster-zone flag and introduce cluster-zones flag
  cmd/agent/app/agent.go
  pkg/karmadactl/join/join.go
  pkg/util/cluster.go
Labels: kind/feature, approved, lgtm, size/M, kind/cleanup

#3991 cleanup: do not reconcile when the resoruce generation doesn't change
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
Labels: approved, lgtm, size/XS

#3937 feat: karmadactl init: grant clusterrole admin with karamda resource permission
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/karmada/rbac_test.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/utils/rbac.go
  pkg/karmadactl/cmdinit/utils/rbac_test.go
Labels: kind/feature, approved, size/L, lgtm

#3972 feat: add performance metrics for FederatedHPA
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/client.go
  pkg/metrics/resource.go
Labels: approved, lgtm, size/M

#4007 feature: Add the UID of the owner resource in labels and include the details in annotations.
  pkg/apis/policy/v1alpha1/well_known_constants.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/execution/execution_controller_test.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/detector/detector.go
  pkg/detector/preemption.go
  pkg/util/annotation.go
  pkg/util/memberclusterinformer/memberclusterinformer_test.go
  test/helper/resource.go
Labels: kind/feature, approved, size/L, lgtm

#4002 feat: adopt zones in scheduler spread by constraints
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#4009 fix helm install clusterrole to wrong cluster
  charts/karmada/templates/_karmada-clusterrole.tpl
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: kind/bug, approved, lgtm, size/XS

#3958 Refine the native service discovery proposal
  docs/proposals/service-discovery/README.md
  docs/proposals/service-discovery/statics/access.png
  docs/proposals/service-discovery/statics/design-01.png
  docs/proposals/service-discovery/statics/design-02.png
  docs/proposals/service-discovery/statics/design-03.png
  docs/proposals/service-discovery/statics/user-operation-01.png
  docs/proposals/service-discovery/statics/user-operation-02.png
Labels: approved, size/L, kind/documentation, lgtm, kind/design

#4015 harmonize code of conduct to the primary one
  CODE_OF_CONDUCT.md
Labels: approved, kind/documentation, lgtm, size/XS

#4016 Revert "Merge pull request #3808 from ctripcloud/refactor-execution-workstatus"
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/context/context.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/execution/execution_controller_test.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/resourceinterpreter/fake/fake.go
  pkg/util/fedinformer/handlers.go
  pkg/util/lifted/objectwatcher.go
  pkg/util/memberclusterinformer/memberclusterinformer.go
  pkg/util/memberclusterinformer/memberclusterinformer_test.go
  pkg/util/objectwatcher/objectwatcher.go
  pkg/util/objectwatcher/objectwatcher_test.go
  test/helper/resource.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#4017 Update 1.7.0 release notes
  docs/CHANGELOG/CHANGELOG-1.7.md
Labels: approved, size/L, kind/documentation, lgtm
