Repository karmada-io/karmada, pull requests merged in 2023-09, with the labels that each got.

#4020 karmadactl exec command not work with clusters that enabled proxy
  go.mod
  pkg/util/proxy/proxy.go
  pkg/util/proxy/upgrade_dialer.go
  pkg/util/proxy/upgrader.go
Labels: kind/bug, size/XL, lgtm

#4018 fix spelling errors
  cmd/controller-manager/app/controllermanager.go
  docs/proposals/service-discovery/README.md
  operator/pkg/certs/store.go
  operator/pkg/constants/constants.go
  operator/pkg/tasks/init/cert.go
  operator/pkg/tasks/init/etcd.go
  operator/pkg/tasks/init/karmadaresource.go
  operator/pkg/tasks/init/upload.go
  operator/pkg/tasks/init/wait.go
  operator/pkg/util/apiclient/idempotency.go
  operator/pkg/util/apiclient/wait.go
  operator/pkg/util/patcher/pather.go
  operator/pkg/util/util.go
  pkg/apis/cluster/v1alpha1/well_known_constants.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/karmadactl/addons/disable.go
  pkg/karmadactl/addons/enable.go
  pkg/karmadactl/addons/init/global.go
  pkg/karmadactl/addons/list.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/utils/util_test.go
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/get/get.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/factory.go
  pkg/modeling/modeling.go
  pkg/resourceinterpreter/default/native/healthy_test.go
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/search/backendstore/defaultstore.go
  pkg/util/cluster.go
  pkg/util/helper/work_test.go
  pkg/util/interpreter/rule_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4023 stop update krew for release 1.6
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3898 karmadactl init with external etcd
  pkg/karmadactl/addons/search/manifests.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/cmdinit/cert/cert.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/feature, do-not-merge/hold, approved, size/L, lgtm

#4021 Automated cherry pick of #4020: fix karmada can not execute exec command with proxy url and
  go.mod
  pkg/util/proxy/proxy.go
  pkg/util/proxy/upgrade_dialer.go
  pkg/util/proxy/upgrader.go
Labels: approved, size/XL, lgtm

#4027 fix depndencies lua scrpit bug
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
  pkg/util/interpreter/rule.go
  pkg/util/interpreter/rule_test.go
  pkg/webhook/resourceinterpretercustomization/helper_test.go
  test/e2e/resourceinterpreter_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#4026 remove insecureSkipTLSVerify in local-up-karmada script
  artifacts/deploy/karmada-aggregated-apiserver-apiservice.yaml
  artifacts/deploy/karmada-metrics-adapter-apiservice.yaml
  artifacts/deploy/karmada-metrics-adapter.yaml
  artifacts/deploy/karmada-search-apiservice.yaml
  hack/deploy-karmada.sh
  hack/deploy-metrics-adapter.sh
Labels: kind/feature, approved, lgtm, size/M

#4041 Update release notes for v1.4.5
  docs/CHANGELOG/CHANGELOG-1.4.md
Labels: approved, kind/documentation, lgtm, size/M

#4042 Update release notes for v1.5.4
  docs/CHANGELOG/CHANGELOG-1.4.md
  docs/CHANGELOG/CHANGELOG-1.5.md
Labels: approved, kind/documentation, lgtm, size/M

#4043 Update release notes for v1.6.3
  docs/CHANGELOG/CHANGELOG-1.4.md
  docs/CHANGELOG/CHANGELOG-1.5.md
  docs/CHANGELOG/CHANGELOG-1.6.md
Labels: approved, size/L, kind/documentation, lgtm

#4040 Update release notes for v1.4.5, v1.5.4, 1.6.3
  docs/CHANGELOG/CHANGELOG-1.4.md
  docs/CHANGELOG/CHANGELOG-1.5.md
  docs/CHANGELOG/CHANGELOG-1.6.md
Labels: approved, size/L, kind/documentation, lgtm

#4033 remove insecureSkipTLSVerify in helm chart
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/_karmada_apiservice.tpl
  charts/karmada/templates/pre-install-job.yaml
Labels: kind/feature, size/S, approved, lgtm

#4052 Don't send an event when the object not matched any propagation policy
  pkg/detector/policy.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4056 uninstall metrics adapter when karmada cluster remove
  operator/pkg/tasks/deinit/component.go
Labels: kind/bug, approved, lgtm, size/XS

#4062 remove insecureSkipTLSVerify in UT test
  pkg/controllers/status/cluster_status_controller_test.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/util/membercluster_client_test.go
Labels: kind/feature, approved, size/L, lgtm

#4060 Automated cherry pick of #4056: uninstall metrics adapter when karmada cluster remove
  operator/pkg/tasks/deinit/component.go
Labels: approved, lgtm, size/XS

#4059 support config karmada components resources
  operator/pkg/controller/karmada/planner.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/metricsadapter/metricsadapter.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/util/patcher/pather.go
Labels: kind/feature, approved, lgtm, size/M

#4071 Enable preemption feature in development environment karmada-controller-manager.yaml
  artifacts/deploy/karmada-controller-manager.yaml
Labels: approved, lgtm, size/XS

#4069 make pull cluster to be able to register with zones
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  pkg/karmadactl/register/register.go
Labels: kind/feature, size/S, approved, lgtm

#4064 aggregate the HPA status from member clusters into control plane
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/resourceinterpreter/default/native/aggregatestatus_test.go
  pkg/resourceinterpreter/default/native/reflectstatus.go
  pkg/resourceinterpreter/default/native/reflectstatus_test.go
Labels: kind/feature, approved, size/L, lgtm

#4051 helm: index 1.7
  charts/index.yaml
Labels: kind/bug, size/S, approved, lgtm

#3789 karmada-operator: add karmada apiserver kubeconfig to karmada status
  operator/pkg/controller/karmada/planner.go
  operator/pkg/controlplane/apiserver/mainfests.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/metricsadapter/mainfests.go
  operator/pkg/controlplane/webhook/mainfests.go
  operator/pkg/tasks/init/upload.go
Labels: kind/feature, approved, lgtm, size/M

#3802 KEP: Resource deletion protection proposal
  docs/proposals/resource-deletion-protection/README.md
  docs/proposals/resource-deletion-protection/statics/user-story-1.drawio
  docs/proposals/resource-deletion-protection/statics/user-story-1.drawio.svg
Labels: kind/feature, approved, size/L, lgtm

#4076 make pull cluster to be able to register with proxy-server
  pkg/karmadactl/register/register.go
Labels: kind/feature, approved, lgtm, size/XS

#4072 add replicas syncer for resources with HPA
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller_test.go
  vendor/k8s.io/client-go/scale/fake/client.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XL, lgtm

#4078 retain for hpa controlled Deployment resource (labels method)
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
  pkg/controllers/hpareplicassyncer/hpa_scale_ref_worker.go
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/resourceinterpreter/default/native/retain.go
  pkg/resourceinterpreter/default/native/retain_test.go
  pkg/util/constants.go
Labels: kind/feature, approved, size/L, lgtm

#4082 use status.DesiredReplicas instead of status.CurrentReplicas of HPA to update resource scale
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller_test.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
Labels: size/S, approved, lgtm, kind/cleanup
