Repository karmada-io/karmada, pull requests merged in 2023-03, with the labels that each got.

#3225 Add release notes for 1.5
  docs/CHANGELOG/CHANGELOG-1.5.md
Labels: approved, size/L, kind/documentation, lgtm

#3222 Automated cherry pick of #2524: propagate dependencies support propagate sa
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
  test/e2e/dependenciesdistributor_test.go
  test/e2e/framework/deployment.go
  test/e2e/framework/rbac.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm

#3226 Add helm index for 1.5
  charts/index.yaml
  charts/karmada/Chart.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#3234 Fixed the system namespace to "karmada-system".
  charts/karmada/templates/_karmada_apiservice.tpl
  charts/karmada/templates/_karmada_system_namespace.tpl
  charts/karmada/values.yaml
Labels: kind/bug, size/S, approved, lgtm

#3229 add unit tests for dependency interpretation
  pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#3228 fix: customize etcd's anti-affinity and disable apiserver's host network.
  charts/karmada/README.md
  charts/karmada/templates/etcd.yaml
  charts/karmada/values.yaml
Labels: kind/bug, size/S, approved, lgtm

#3102 karmada-operator: add init workflow
  operator/cmd/operator/app/operator.go
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/config/samples/karmada.yaml
  operator/pkg/apis/operator/v1alpha1/helper.go
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/certs/certs.go
  operator/pkg/certs/store.go
  operator/pkg/constants/constants.go
  operator/pkg/controller/karmada/controller.go
  operator/pkg/controller/karmada/planner.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/apiserver/mainfests.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/etcd/mainfests.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/webhook/mainfests.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/init.go
  operator/pkg/karmadaresource/apiservice/apiservice.go
  operator/pkg/karmadaresource/apiservice/manifest.go
  operator/pkg/karmadaresource/webhookconfiguration/mainfests.go
  operator/pkg/karmadaresource/webhookconfiguration/webhookconfiguration.go
  operator/pkg/tasks/init/apiserver.go
  operator/pkg/tasks/init/cert.go
  operator/pkg/tasks/init/component.go
  operator/pkg/tasks/init/crd.go
  operator/pkg/tasks/init/data.go
  operator/pkg/tasks/init/etcd.go
  operator/pkg/tasks/init/karmadaresource.go
  operator/pkg/tasks/init/namespace.go
  operator/pkg/tasks/init/upload.go
  operator/pkg/tasks/init/wait.go
  operator/pkg/util/apiclient/idempotency.go
  operator/pkg/util/apiclient/wait.go
  operator/pkg/util/kubeconfig.go
  operator/pkg/util/name.go
  operator/pkg/util/template.go
  operator/pkg/util/util.go
  operator/pkg/workflow/job.go
  operator/pkg/workflow/task.go
Labels: kind/feature, approved, size/XXL, lgtm

#3079 ci: Cancel when there is a new change
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3236 add a new schedule workflow to run e2e test
  .github/workflows/ci-schedule.yml
Labels: approved, lgtm, size/M, kind/cleanup

#3202 Add bindingstatus controller
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/controllers/status/common.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/rb_status_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
  pkg/util/helper/work.go
  pkg/util/helper/workstatus.go
Labels: kind/feature, approved, size/XL, lgtm, kind/cleanup

#3232 fix bug that spreadconstraints are not validated correctly
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: kind/feature, approved, lgtm, size/M, kind/cleanup

#3242 Add more comments about filed selector in cluster affinity
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, size/L, lgtm, kind/cleanup

#3244 reduce the number of kubernetes version support in CI E2E
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3240 Add controllers config for karmada-controller-manager
  charts/karmada/README.md
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/values.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3251 Stop update krew for release 1.4.x
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3254 docs: update Kubernetes compatibility
  README.md
Labels: size/S, approved, kind/documentation, lgtm

#3241 Increase `.metadata.generation` once desired state of the `Cluster` object is changed.
  pkg/registry/cluster/strategy.go
  pkg/registry/cluster/strategy_test.go
  pkg/scheduler/event_handler.go
Labels: kind/feature, approved, lgtm, size/M

#3256 feat: Add a lua string and math lib to the resource interpreter.
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
Labels: kind/feature, approved, lgtm, size/XS

#3255 Add controllers config for karmada-controller-manager
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/values.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#3237 karmadactl: add image pull secret flags for karmadactl init
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
Labels: kind/feature, size/S, approved, lgtm

#3239 merge labels when building RB/CRB by ClusterPropagationPolicy
  pkg/detector/detector.go
Labels: kind/bug, approved, lgtm, size/XS

#3270 Push karmada-operator to image registry
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  Makefile
Labels: approved, lgtm, size/XS, kind/cleanup

#3264 fixed karmada controller flag
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler.yaml
Labels: kind/bug, size/S, approved, lgtm

#3269 Delete redundance code for pkg/karmadactl/get/get.go
  pkg/karmadactl/get/get.go
Labels: size/S, approved, lgtm, kind/cleanup

#3274 add prune test
  pkg/resourceinterpreter/defaultinterpreter/prune/prune_test.go
Labels: approved, size/L, lgtm, kind/failing-test, kind/cleanup

#3245 karmada operator: add deinit workflow
  operator/pkg/constants/constants.go
  operator/pkg/controller/karmada/controller.go
  operator/pkg/controller/karmada/planner.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/webhook/mainfests.go
  operator/pkg/deinit.go
  operator/pkg/init.go
  operator/pkg/tasks/deinit/cert.go
  operator/pkg/tasks/deinit/component.go
  operator/pkg/tasks/deinit/data.go
  operator/pkg/tasks/deinit/kubeconfig.go
  operator/pkg/tasks/init/component.go
  operator/pkg/tasks/init/upload.go
  operator/pkg/util/apiclient/idempotency.go
  operator/pkg/util/name.go
  operator/pkg/util/naming.go
  operator/pkg/workflow/task.go
Labels: kind/feature, approved, size/XL, lgtm

#3276 Install golangci-lint binary instead of from source
  hack/verify-staticcheck.sh
Labels: size/S, approved, lgtm, kind/cleanup

#3278 remove redundant conversion functions
  pkg/resourceinterpreter/defaultinterpreter/prune/prune_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#3282 Automated cherry pick of #3256: feat: add string and math lib for lua
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
Labels: approved, lgtm, size/XS

#3268 Add helm variable extraCommandArgs to controllerManager
  charts/karmada/README.md
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/values.yaml
Labels: kind/feature, size/S, approved, lgtm

#3221 check deployment statefulset rollout not use check pod ready
  pkg/karmadactl/addons/descheduler/descheduler.go
  pkg/karmadactl/addons/enable.go
  pkg/karmadactl/addons/estimator/estimator.go
  pkg/karmadactl/addons/init/disable_option.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/cmdinit/kubernetes/check.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/options/global.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/check.go
Labels: approved, size/L, lgtm, kind/cleanup

#3285 Fix wrong logs for pkg/scheduler/event_handler.go
  pkg/scheduler/event_handler.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3279 implementing search proxy unifiedauth
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller_test.go
  pkg/util/rbac.go
Labels: kind/feature, approved, size/L, lgtm

#3288 bugfix: runtime.Object apiVersion/kind is empty
  pkg/util/fedinformer/keys/keys.go
  pkg/util/fedinformer/keys/keys_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#3168 Add e2e for karmadactl init
  .github/workflows/cli.yaml
  artifacts/kindClusterConfig/general-config.yaml
  hack/cli-testing-environment.sh
Labels: approved, size/L, lgtm, kind/cleanup

#3298 Fixed unable to view the options for karmadactl addons enable/disable
  pkg/karmadactl/addons/disable.go
  pkg/karmadactl/addons/enable.go
Labels: kind/bug, approved, lgtm, size/XS

#3301 Automated cherry pick of #3256: feat: add string and math lib for lua
  pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
Labels: approved, lgtm, size/XS

#3303 [e2e] Fix trigger rescheduling when replicaSchedulingType is duplicated
  test/e2e/scheduling_test.go
Labels: approved, lgtm, size/XS, kind/failing-test

#3306 Automated cherry pick of #3298: Fixed unable to view the options for karmadactl addons
  pkg/karmadactl/addons/disable.go
  pkg/karmadactl/addons/enable.go
Labels: approved, lgtm, size/XS

#3305 Automated cherry pick of #3298: Fixed unable to view the options for karmadactl addons
  pkg/karmadactl/addons/disable.go
  pkg/karmadactl/addons/enable.go
Labels: approved, lgtm, size/XS

#3307 Automated cherry pick of #3298: Fixed unable to view the options for karmadactl addons
  pkg/karmadactl/addons/disable.go
  pkg/karmadactl/addons/enable.go
Labels: approved, lgtm, size/XS

#3316 Fix: remove the setTransitionTime from cluster status controller.
  pkg/controllers/status/cluster_status_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#3290 Fix cluster_locality plugin when replicaScheduling is nil
  pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3310 feat(chart): add annotations to apiserver service; add tolerations and nodeSelector to job.
  charts/karmada/README.md
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: approved, lgtm, size/M

#3312 response actual resource list from search api
  pkg/registry/search/storage/cache.go
  pkg/registry/search/storage/search.go
  pkg/search/apiserver.go
Labels: kind/feature, size/S, approved, lgtm

#3320 correct context name.
  hack/create-cluster.sh
Labels: size/S, approved, lgtm, kind/cleanup

#3325 chore: improve some format
  pkg/karmadactl/addons/search/search.go
Labels: size/S, approved, lgtm, kind/cleanup

#3324 Set aggregatedapiserver owners
  cmd/aggregated-apiserver/OWNERS
  pkg/aggregatedapiserver/OWNERS
  pkg/registry/OWNERS
Labels: size/S, approved, lgtm, kind/cleanup

#3297 Add UT for deploy.go and statefulset.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3317 BuildClusterConfig：use rest.Config and check ca exist
  pkg/util/membercluster_client.go
Labels: kind/feature, size/S, approved, lgtm

#3323 Fix potential failure in CLI workflow.
  hack/cli-testing-environment.sh
  hack/util.sh
Labels: approved, lgtm, kind/failing-test, size/M

#3338 Support to run karmadactl init within a pod
  pkg/karmadactl/util/apiclient/apiclient.go
Labels: kind/feature, size/S, approved, lgtm

#3340 Optimize code directory structure for resourceInterpreter
  pkg/karmadactl/interpret/check.go
  pkg/karmadactl/interpret/execute.go
  pkg/karmadactl/promote/promote.go
  pkg/resourceinterpreter/customized/declarative/configmanager/accessor.go
  pkg/resourceinterpreter/customized/declarative/configmanager/manager.go
  pkg/resourceinterpreter/customized/declarative/configmanager/manager_test.go
  pkg/resourceinterpreter/customized/declarative/configurable.go
  pkg/resourceinterpreter/customized/declarative/luavm/kube.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert_test.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
  pkg/resourceinterpreter/customized/webhook/configmanager/accessor.go
  pkg/resourceinterpreter/customized/webhook/configmanager/manager.go
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/resourceinterpreter/customized/webhook/request/attributes.go
  pkg/resourceinterpreter/customized/webhook/request/resourceinterpretercontext.go
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/resourceinterpreter/default/native/aggregatestatus_test.go
  pkg/resourceinterpreter/default/native/default.go
  pkg/resourceinterpreter/default/native/dependencies.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
  pkg/resourceinterpreter/default/native/healthy.go
  pkg/resourceinterpreter/default/native/healthy_test.go
  pkg/resourceinterpreter/default/native/prune/prune.go
  pkg/resourceinterpreter/default/native/prune/prune_test.go
  pkg/resourceinterpreter/default/native/reflectstatus.go
  pkg/resourceinterpreter/default/native/reflectstatus_test.go
  pkg/resourceinterpreter/default/native/replica.go
  pkg/resourceinterpreter/default/native/retain.go
  pkg/resourceinterpreter/default/native/revisereplica.go
  pkg/resourceinterpreter/default/native/revisereplica_test.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/interpreter/rule.go
  pkg/webhook/resourceinterpretercustomization/helper.go
  pkg/webhook/work/mutating.go
Labels: approved, size/L, lgtm, kind/cleanup

#3292 Add arg to specify cluster domain
  pkg/karmadactl/addons/enable.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/addons/search/manifests.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
  pkg/karmadactl/options/global.go
Labels: kind/feature, approved, lgtm, size/M

#3259 region selection algorithm optimization
  pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_region_test.go
  pkg/scheduler/core/spreadconstraint/select_groups.go
  pkg/scheduler/core/spreadconstraint/select_groups_test.go
  pkg/scheduler/core/spreadconstraint/util.go
  pkg/scheduler/core/spreadconstraint/util_test.go
Labels: kind/feature, approved, size/XL, lgtm
