Repository karmada-io/karmada, pull requests merged in 2023-06, with the labels that each got.

#3596 add chart lint ci step for karmada-operaoter chart
  .github/workflows/lint-chart.yaml
Labels: kind/feature, approved, lgtm, size/XS

#3607 Automated cherry pick of #3591: Change the length of modelSortings array for panic of index
  pkg/modeling/modeling.go
  pkg/modeling/modeling_test.go
Labels: approved, lgtm, size/M

#3608 Automated cherry pick of #3591: Change the length of modelSortings array for panic of index
  pkg/modeling/modeling.go
  pkg/modeling/modeling_test.go
Labels: approved, lgtm, size/M

#3620 api: delete the useless Scheme.AddUnversionedTypes code
  pkg/apis/cluster/scheme/regiser.go
  pkg/apis/search/scheme/register.go
Labels: size/S, approved, lgtm, kind/cleanup

#3615 Add v1.6 release notes
  docs/CHANGELOG/CHANGELOG-1.6.md
Labels: approved, size/L, lgtm, kind/cleanup

#3618 fix typos
  ROADMAP.md
  operator/README.md
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/certs/certs.go
  operator/pkg/constants/constants.go
  operator/pkg/controller/karmada/planner.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/init.go
  operator/pkg/tasks/init/apiserver.go
  operator/pkg/tasks/init/crd.go
  operator/pkg/tasks/init/data.go
  operator/pkg/tasks/init/etcd.go
  operator/pkg/tasks/init/karmadaresource.go
  operator/pkg/tasks/init/upload.go
  operator/pkg/tasks/init/wait.go
  operator/pkg/workflow/job.go
  operator/pkg/workflow/task.go
  pkg/karmadactl/cmdinit/cert/cert.go
Labels: approved, size/L, lgtm, kind/cleanup

#3629 Stop update-krew for release-1.5.x
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3622 Add printcolumn for FederatedHPA
  charts/karmada/_crds/bases/autoscaling.karmada.io_federatedhpas.yaml
  pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go
Labels: kind/api-change, size/S, approved, lgtm

#3574 feat: supports aggregating the status of a pod's initContainer
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/resourceinterpreter/default/native/aggregatestatus_test.go
Labels: kind/feature, approved, lgtm, size/M

#3621 Add ut for `pkg/controllers/applicationfailover` and `pkg/controllers/status`
  pkg/controllers/applicationfailover/common_test.go
  pkg/controllers/applicationfailover/crb_application_failover_controller_test.go
  pkg/controllers/applicationfailover/rb_application_failover_controller_test.go
  pkg/controllers/status/crb_status_controller_test.go
  pkg/controllers/status/rb_status_controller_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#3641 Automated cherry pick of #3496: fix When EnableEmptyWorkloadPropagation flag is false zero
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
  test/e2e/scheduling_test.go
Labels: size/S, approved, lgtm

#3642 Automated cherry pick of #3496: fix When EnableEmptyWorkloadPropagation flag is false zero
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
  test/e2e/scheduling_test.go
Labels: size/S, approved, lgtm

#3645 Fix verify-crdgen.sh do not verify operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  hack/verify-crdgen.sh
Labels: approved, lgtm, size/M, kind/cleanup

#3639 Add index for 1.6
  charts/index.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#3651 Setup operator API owners
  operator/pkg/apis/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#3630 doc: Add the limitations of search proxy
  docs/proposals/caching/README.md
  docs/proposals/resource-aggregation-proxy/README.md
Labels: size/S, approved, kind/documentation, lgtm

#3647 metrics-adapter: when different clusters have the same pod name, the annotations of different metrics have the same value
  pkg/apis/autoscaling/v1alpha1/well_known_constants.go
  pkg/metricsadapter/provider/resourcemetrics.go
Labels: kind/bug, approved, size/L, lgtm

#3659 feat: Release crds.tar.gz in release workflow
  .github/workflows/release.yml
Labels: kind/feature, size/S, approved, lgtm

#3660 cleanup the ci about interpreter-interpret-health test
  test/e2e/framework/deployment.go
  test/e2e/resourceinterpreter_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3658 cleanup: rename suppported to supported.
  pkg/search/proxy/store/store.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3654 Fixed small typos in the Karmada operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
Labels: approved, kind/documentation, lgtm, size/XS

#3554 Upgrade cluster-api to v1beta1 for v1alpha3/v1alpha4 deprecated
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/util/gclient/gclient.go
  vendor/github.com/gobuffalo/flect/.gitignore
  vendor/github.com/gobuffalo/flect/.gometalinter.json
  vendor/github.com/gobuffalo/flect/LICENSE
  vendor/github.com/gobuffalo/flect/Makefile
  vendor/github.com/gobuffalo/flect/README.md
  vendor/github.com/gobuffalo/flect/SHOULDERS.md
  vendor/github.com/gobuffalo/flect/acronyms.go
  vendor/github.com/gobuffalo/flect/camelize.go
  vendor/github.com/gobuffalo/flect/capitalize.go
  vendor/github.com/gobuffalo/flect/custom_data.go
  vendor/github.com/gobuffalo/flect/dasherize.go
  vendor/github.com/gobuffalo/flect/flect.go
  vendor/github.com/gobuffalo/flect/humanize.go
  vendor/github.com/gobuffalo/flect/ident.go
  vendor/github.com/gobuffalo/flect/lower_upper.go
  vendor/github.com/gobuffalo/flect/ordinalize.go
  vendor/github.com/gobuffalo/flect/pascalize.go
  vendor/github.com/gobuffalo/flect/plural_rules.go
  vendor/github.com/gobuffalo/flect/pluralize.go
  vendor/github.com/gobuffalo/flect/rule.go
  vendor/github.com/gobuffalo/flect/singular_rules.go
  vendor/github.com/gobuffalo/flect/singularize.go
  vendor/github.com/gobuffalo/flect/titleize.go
  vendor/github.com/gobuffalo/flect/underscore.go
  vendor/github.com/gobuffalo/flect/version.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/cluster_phase_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/cluster_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/clusterclass_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/common_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/condition_consts.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/condition_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/conversion.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/doc.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/groupversion_info.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machine_phase_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machine_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machinedeployment_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machinehealthcheck_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/machineset_types.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/zz_generated.conversion.go
  vendor/sigs.k8s.io/cluster-api/api/v1alpha4/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api/util/annotations/helpers.go
  vendor/sigs.k8s.io/cluster-api/util/contract/contract.go
  vendor/sigs.k8s.io/cluster-api/util/contract/doc.go
  vendor/sigs.k8s.io/cluster-api/util/conversion/conversion.go
  vendor/sigs.k8s.io/cluster-api/util/retry.go
  vendor/sigs.k8s.io/cluster-api/util/util.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#3549 Delete redundant deepcopy
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/util/helper/workstatus.go
Labels: size/S, approved, lgtm, kind/cleanup

#3671 upgrade the alpine base image
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
Labels: approved, lgtm, size/XS, kind/cleanup

#3130 unjoin cluster check namespace reduce cluster enqueue
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3652 feat: Fix version parse
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/register/register.go
  pkg/version/release.go
  pkg/version/release_test.go
Labels: kind/feature, approved, size/L, lgtm

#3434 Sign images
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  hack/docker.sh
Labels: size/S, approved, lgtm

#3638 feat: support custom metrics for metrics adapter
  artifacts/deploy/karmada-metrics-adapter-apiservice.yaml
  cmd/metrics-adapter/app/options/options.go
  pkg/metricsadapter/adapter.go
  pkg/metricsadapter/controller.go
  pkg/metricsadapter/multiclient/client.go
  pkg/metricsadapter/provider/custommetrics.go
Labels: kind/feature, approved, size/L, lgtm

#3648 Karmada metrics adapter deployment script
  hack/deploy-metrics-adapter.sh
Labels: kind/feature, approved, lgtm, size/M

#3668 Fix cached RESTMapper when pass no versions
  pkg/util/restmapper/restmapper.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3665 karmadactl init add timeout flag
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/options/global.go
Labels: kind/feature, size/S, approved, lgtm

#3650 feat: Add script to deploy k8s metrics-server in member cluster
  hack/deploy-k8s-metrics-server.sh
Labels: kind/feature, approved, lgtm, size/M

#3683 fix panic when printing log when lastSuccessfulTime of cronjob is nil
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/resourceinterpreter/default/native/aggregatestatus_test.go
Labels: kind/bug, approved, lgtm, size/XS

#3682 fix: repair flaking test job of setup e2e test environment
  .github/workflows/ci.yml
  hack/local-up-karmada.sh
  hack/util.sh
Labels: approved, lgtm, size/M, kind/flake

#3673 hpa-controller supports custom metrics
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/replica_calculator.go
Labels: kind/feature, approved, size/L, lgtm

#3691 ignoring codecov errors in ci
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/failing-test

#3577 Karmada Operator: support disable karmada cascading deletion
  operator/pkg/controller/karmada/controller.go
Labels: kind/feature, approved, lgtm, size/M

#3699 upgrade CI ubuntu image
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-chart.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-chart.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/fossa.yml
  .github/workflows/lint-chart.yaml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: approved, lgtm, size/M, kind/flake

#3692 Adding CronFederatedHPA API
  charts/karmada/_crds/bases/autoscaling.karmada.io_cronfederatedhpas.yaml
  pkg/apis/autoscaling/v1alpha1/cronfederatedhpa_types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/cronfederatedhpa.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_autoscaling_client.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_cronfederatedhpa.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/generated_expansion.go
  pkg/generated/informers/externalversions/autoscaling/v1alpha1/cronfederatedhpa.go
  pkg/generated/informers/externalversions/autoscaling/v1alpha1/interface.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/autoscaling/v1alpha1/cronfederatedhpa.go
  pkg/generated/listers/autoscaling/v1alpha1/expansion_generated.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/XXL, lgtm

#3614 feat: Support modification synchronization of custom resources as dependency
  cmd/controller-manager/app/controllermanager.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
  test/e2e/resourceinterpreter_test.go
Labels: kind/feature, approved, size/XL, lgtm

#3702 upgrade CI ubuntu image
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-chart.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-chart.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/fossa.yml
  .github/workflows/lint-chart.yaml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: approved, lgtm, size/M, kind/flake

#3704 upgrade CI ubuntu image
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/fossa.yml
  .github/workflows/lint-chart.yaml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/flake

#3700 e2e: should be queried on member clusters rather than the control plane
  test/e2e/propagationpolicy_test.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3709 fix the Applied of ResourceBinding is always true
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/bug, approved, lgtm, size/XS

#3712 cleanup FederatedHPA API
  charts/karmada/_crds/bases/autoscaling.karmada.io_federatedhpas.yaml
  pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, lgtm, size/M, kind/cleanup

#3716 fix: update karmada operator crd karmadaDescheduler field
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
Labels: kind/bug, approved, size/L, lgtm

#3715 Optimize download percentage log
  operator/pkg/util/util.go
Labels: kind/bug, approved, lgtm, size/XS

#3723 Automated cherry pick of #3709: fix the Applied of ResourceBinding is always true
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, lgtm, size/XS

#3722 Add cherry-pick issue template
  .github/ISSUE_TEMPLATE/cherry-pick.md
Labels: approved, lgtm, size/M, kind/cleanup

#3724 Automated cherry pick of #3709: fix the Applied of ResourceBinding is always true
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, lgtm, size/XS

#3721 spilt karmada-config ConfigMap in helm chart and split crd yaml into group files
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  charts/karmada/_crds/bases/multicluster/multicluster.x-k8s.io_serviceexports.yaml
  charts/karmada/_crds/bases/multicluster/multicluster.x-k8s.io_serviceimports.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  charts/karmada/_crds/kustomization.yaml
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  hack/update-crdgen.sh
Labels: approved, size/L, lgtm, kind/cleanup

#3726 fix scheme filename typo
  pkg/apis/cluster/scheme/register.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3718 update karmada operator default karmada version
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
Labels: kind/feature, size/S, approved, lgtm

#3644 add MultiClusterService API
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
  charts/karmada/_crds/kustomization.yaml
  pkg/apis/networking/v1alpha1/service_types.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/networking/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/fake/fake_multiclusterservice.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/fake/fake_networking_client.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/multiclusterservice.go
  pkg/generated/clientset/versioned/typed/networking/v1alpha1/networking_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/networking/v1alpha1/interface.go
  pkg/generated/informers/externalversions/networking/v1alpha1/multiclusterservice.go
  pkg/generated/listers/networking/v1alpha1/expansion_generated.go
  pkg/generated/listers/networking/v1alpha1/multiclusterservice.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/XXL, lgtm

#3717 feat: karmadactl adds a karmada-metrics-adapter addons.
  pkg/karmadactl/addons/addons.go
  pkg/karmadactl/addons/enable.go
  pkg/karmadactl/addons/init/addon.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/addons/install/install.go
  pkg/karmadactl/addons/metricsadapter/manifests.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter.go
Labels: kind/feature, approved, size/L, lgtm

#3711 update operator readme.md
  operator/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#3576 karmada operator: add conditions to karmada cr
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/helper.go
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/controller/karmada/controller.go
  operator/pkg/controller/karmada/planner.go
Labels: kind/feature, approved, lgtm, size/M

#3701 Karmada Operator: support custom arguments and featureGates
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/init.go
  operator/pkg/tasks/init/apiserver.go
  operator/pkg/tasks/init/component.go
  operator/pkg/tasks/init/data.go
  operator/pkg/util/patcher/pather.go
Labels: kind/feature, approved, size/L, lgtm

#3739 fix: when application failover is enabled but propagateDeps is set to false, the failover has no effect
  pkg/util/validation/validation.go
Labels: kind/bug, approved, lgtm, size/XS

#3733 Karmada Operator: Add Leader Elect to Manifests
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/manifests.go
Labels: size/S, approved, lgtm
