Repository karmada-io/karmada, pull requests merged in 2023-11, with the labels that each got.

#4201 Update chart-testing-action to v2.6.0 and cosigin-installer to v3.1.1
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/lint-chart.yaml
Labels: priority/important-soon, approved, lgtm, size/XS, kind/cleanup

#4202 [1.7] Automated cherry pick of #4201: * Update chart-testing-action to v2.6.0
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/lint-chart.yaml
Labels: approved, lgtm, size/XS

#4203 Adjust the case of the aggregatedApiServer field in the karmada chart…
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
Labels: kind/feature, size/S, approved, lgtm

#4193 set MinVersion to VersionTLS13 for tlsconfig in karmada-search and karmada-metrics-adapter
  pkg/karmadactl/addons/metricsadapter/manifests.go
  pkg/karmadactl/addons/search/manifests.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4207 [1.7] Automated cherry pick of #4130: Operator support work with crds v1.7.0
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  operator/pkg/tasks/init/karmadaresource.go
  operator/pkg/util/testdata/testa.yaml
  operator/pkg/util/testdata/testb.yaml
  operator/pkg/util/util.go
  operator/pkg/util/util_test.go
Labels: approved, lgtm, size/M

#4205 publish karmada operator helm chart archive
  .github/workflows/release.yml
Labels: kind/feature, approved, lgtm, size/XS

#3926 karmada operator: support install karmada on remote cluster
  operator/pkg/controller/karmada/planner.go
  operator/pkg/deinit.go
  operator/pkg/init.go
  operator/pkg/util/kubeconfig.go
Labels: kind/feature, approved, size/L, lgtm

#4100 feat: Add proposal for promote-dependencies-automatically
  docs/proposals/promote-dependencies-automatically/README.md
  docs/proposals/promote-dependencies-automatically/statics/architecture.drawio.svg
  docs/proposals/promote-dependencies-automatically/statics/dependenciesOfDeployment.drawio.svg
  docs/proposals/promote-dependencies-automatically/statics/native-approach.png
  docs/proposals/promote-dependencies-automatically/statics/our-approach.png
  docs/proposals/promote-dependencies-automatically/statics/port-forward.drawio.svg
  docs/proposals/promote-dependencies-automatically/statics/webhook-interpret.png
Labels: approved, size/L, lgtm, kind/design

#4210 fix karmada instance aggregated service externalName error
  operator/pkg/karmadaresource/apiservice/apiservice.go
  operator/pkg/karmadaresource/apiservice/manifest.go
  operator/pkg/tasks/init/component.go
  operator/pkg/tasks/init/karmadaresource.go
Labels: kind/bug, approved, lgtm, size/M

#4214 fix libprotoc version validation error
  hack/update-estimator-protobuf.sh
Labels: kind/bug, approved, lgtm, size/XS

#4206 fix: fix exec failure with karamada-aggregated-apiserver
  pkg/util/proxy/proxy.go
  test/e2e/framework/karmadactl.go
  test/e2e/karmadactl_test.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm

#4212 karmada-search: Fix lock race affects watch RestChan not close, causing client watch api to hang.
  pkg/search/proxy/store/util.go
Labels: kind/bug, approved, lgtm, size/M

#4226 only update necessary part of binding status
  pkg/util/helper/workstatus.go
Labels: kind/bug, size/S, approved, lgtm

#4229 e2e: adjust karmadactl e2e to use real command
  test/e2e/karmadactl_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#4234 Automated cherry pick of #4226: only update necessary part of binding status
  pkg/util/helper/workstatus.go
Labels: size/S, approved, lgtm

#4235 Automated cherry pick of #4226: only update necessary part of binding status
  pkg/util/helper/workstatus.go
Labels: size/S, approved, lgtm

#4236 Automated cherry pick of #4226: only update necessary part of binding status
  pkg/util/helper/workstatus.go
Labels: size/S, approved, lgtm

#4239 cherry pick of #4212: Fix lock race affects watch RestChan not close, causing client watch api to hang.
  pkg/search/proxy/store/util.go
Labels: approved, lgtm, size/M

#4241 cherry pick of #4212: Fix lock race affects watch RestChan not close, causing client watch api to hang.
  pkg/search/proxy/store/util.go
Labels: approved, lgtm, size/M

#4243 sh: verify operator code generation
  hack/verify-codegen.sh
Labels: size/S, approved, lgtm, kind/cleanup

#4223 add cluster flags for karmadactl top pod
  pkg/karmadactl/get/get.go
  pkg/karmadactl/top/top.go
  pkg/karmadactl/top/top_pods.go
  pkg/karmadactl/util/validate.go
  pkg/karmadactl/util/validate_test.go
Labels: kind/feature, approved, size/L, lgtm

#4244 e2e: adjust all karmadactl e2e to use real karmadactl command
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4242 cherry pick of #4212: Fix lock race affects watch RestChan not close, causing client watch api to hang.
  pkg/search/proxy/store/util.go
Labels: approved, lgtm, size/M

#4238 fix test env timeout of APIServer compatibility
  .github/workflows/ci-schedule-compatibility.yaml
Labels: approved, lgtm, size/XS, kind/failing-test

#4219 implementation : divide replicas by static weight evenly
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/assignment_test.go
  pkg/scheduler/core/division_algorithm.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
Labels: kind/feature, approved, size/L, lgtm

#4237 Restrict “configmap/extension-apiserver-authentication” object from being distributed to member clusters
  pkg/detector/detector.go
  pkg/detector/detector_test.go
Labels: kind/feature, approved, lgtm, size/M

#4245 ensure resource template be un-claimed when deleting policy
  pkg/detector/detector.go
Labels: kind/bug, approved, lgtm, size/M, kind/cleanup

#4198 set MinVersion to VersionTLS13 for tlsconfig
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/karmada-metrics-adapter.yaml
  artifacts/deploy/karmada-search.yaml
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-search.yaml
  operator/pkg/controlplane/apiserver/mainfests.go
  operator/pkg/controlplane/metricsadapter/mainfests.go
Labels: size/S, approved, lgtm, kind/cleanup

#4160 Remove label of job for kubernetes 1.27
  pkg/resourceinterpreter/default/native/prune/prune.go
Labels: size/S, approved, lgtm

#4263 Automated cherry pick of #4160: Prune job label for kubernetes 1.27,prefix with
  pkg/resourceinterpreter/default/native/prune/prune.go
Labels: size/S, approved, lgtm

#4280 doc: Add KubeCon talks to readme
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#4253 set golang's secure cipher suites as etcd's cipher suites
  artifacts/deploy/karmada-etcd.yaml
  charts/karmada/templates/etcd.yaml
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/etcd/mainfests.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
Labels: approved, lgtm, size/M, kind/cleanup

#4194 Added MCS Kubernetes native implementation details
  docs/proposals/service-discovery/README.md
Labels: approved, size/L, kind/documentation, lgtm, kind/design

#4286 update etcd/mainfests.go
  operator/pkg/controlplane/etcd/mainfests.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4218 proposal: divide replicas by static weight evenly
  docs/proposals/scheduling/replicas-assign/divide-replicas-by-static-weight-evenly.md
Labels: approved, size/L, kind/documentation, lgtm, kind/design

#4296 sh: make cluster version configuration unified
  hack/cli-testing-environment.sh
  hack/create-cluster.sh
  hack/local-up-karmada.sh
  hack/util.sh
Labels: size/S, approved, lgtm, kind/cleanup

#4264 [1.5] Automated cherry pick of #4160: Prune job label for kubernetes 1.27,prefix with
  pkg/resourceinterpreter/defaultinterpreter/prune/prune.go
Labels: size/S, approved, lgtm

#4265 [1.6] Automated cherry pick of #4160: Prune job label for kubernetes 1.27,prefix with
  pkg/resourceinterpreter/default/native/prune/prune.go
Labels: size/S, approved, lgtm

#4254 feat: Cross-cluster unified query
  cmd/aggregated-apiserver/app/options/options.go
  pkg/aggregatedapiserver/apiserver.go
  pkg/registry/cluster/storage/aggregate.go
  pkg/registry/cluster/storage/proxy.go
  pkg/registry/cluster/storage/storage.go
  pkg/util/proxy/proxy.go
Labels: kind/feature, approved, size/L, lgtm

#4293 Expose assignReplicas and selectClusters function to external schedulers
  pkg/scheduler/core/common.go
  pkg/scheduler/core/generic_scheduler.go
Labels: kind/feature, approved, size/L, lgtm

#4199 feat: add resource id label
  go.mod
  pkg/apis/policy/v1alpha1/well_known_constants.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/detector/preemption.go
  pkg/util/helper/work.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: kind/feature, approved, size/L, lgtm

#4135 feat: support promote dependent resources automatically
  pkg/karmadactl/promote/promote.go
Labels: approved, size/L, lgtm

#4308 fix a typo
  hack/local-up-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#4307 resourceModels supports extended resources
  pkg/apis/cluster/mutation/mutation.go
  pkg/apis/cluster/mutation/mutation_test.go
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  pkg/apis/cluster/validation/validation.go
  pkg/apis/cluster/validation/validation_test.go
  pkg/controllers/status/cluster_status_controller_test.go
  pkg/estimator/client/general.go
  pkg/modeling/modeling.go
  pkg/modeling/modeling_test.go
  pkg/registry/cluster/strategy_test.go
Labels: kind/feature, approved, size/L, lgtm

#4303 feat: support install metrics adapter with chart
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/_karmada_apiservice.tpl
  charts/karmada/templates/karmada-metrics-adapter.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#4290 api: define API for MultiClusterService
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
  pkg/apis/networking/v1alpha1/service_types.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/webhook/multiclusterservice/validating.go
  pkg/webhook/multiclusterservice/validating_test.go
Labels: kind/api-change, approved, size/L, lgtm

#4295 create cluster script support MacOS
  hack/create-cluster.sh
Labels: kind/feature, approved, lgtm, size/XS

#4312 Fix local-up-karmada.sh is not working.
  hack/util.sh
Labels: kind/bug, approved, lgtm, size/XS

#4318 karmada-operator: fixed operator manifests format
  operator/pkg/controlplane/apiserver/mainfests.go
  operator/pkg/controlplane/metricsadapter/mainfests.go
Labels: kind/bug, approved, lgtm, size/XS

#4320 karmada-operator: resolve resource version conflict when updating serivce
  operator/pkg/util/apiclient/idempotency.go
Labels: kind/bug, size/S, approved, lgtm

#4327 Correct DNSNames of karmada-apiserver certificate in operator installation mode
  operator/pkg/certs/certs.go
Labels: kind/bug, approved, lgtm, size/XS

#4334 upgrade golang version to v1.20.11
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4323 feat: List&watch mcs and service, reconcile the work in execution namespace
  cmd/controller-manager/app/controllermanager.go
  pkg/apis/networking/v1alpha1/service_types.go
  pkg/apis/networking/v1alpha1/well_known_constants.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/events/events.go
  pkg/util/constants.go
  pkg/util/helper/mcs.go
Labels: kind/feature, approved, size/L, lgtm

#4335 feat: add webhook for multiclusterservice to add the permanentid
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: kind/feature, approved, lgtm, size/M

#4333 e2e: add mcs e2e with CrossCluster type
  test/e2e/framework/mcs.go
  test/e2e/mcs_test.go
  test/e2e/suite_test.go
  test/helper/resource.go
Labels: approved, size/XL, lgtm, kind/cleanup

#4343 feat: clean the endpointslice if the current cluster is not in the mcs consumption clusters
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/util/constants.go
  pkg/util/helper/mcs.go
Labels: kind/feature, approved, size/L, lgtm

#4347 Add MultiClusterService FeatureGate
  artifacts/agent/karmada-agent.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/features/features.go
  pkg/util/constants.go
  test/e2e/mcs_test.go
Labels: kind/feature, approved, size/L, lgtm

#4346 cleanup: change MultiClusterService corresponding label
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/util/constants.go
  test/e2e/mcs_test.go
Labels: size/M, kind/cleanup

#4336 Add changelog of release-1.8
  docs/CHANGELOG/CHANGELOG-1.8.md
Labels: approved, size/L, kind/documentation, lgtm

#4348 fix wrong featuregate writing with MultiClusterService
  cmd/controller-manager/app/controllermanager.go
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup
