Repository karmada-io/karmada, pull requests merged in 2023-05, with the labels that each got.

#3471 setup English community meeting
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#3489 Upgrade kube version
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: kind/bug, size/S, approved, lgtm, kind/cleanup

#3475 fix: graceful-eviction still works after an unexpected restart of karmada-controller-manager
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Labels: kind/bug, size/S, approved, lgtm

#3490 Automated cherry pick of #3475: fix: graceful-eviction still works after an unexpected
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Labels: size/S, approved, lgtm

#3488 add customizations for helm.toolkit.fluxcd.io/v2beta1/HelmRelease
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/desired-helmrelease.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/observed-helmrelease.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3484 add customizations for source.toolkit.fluxcd.io/v1beta2/HelmRepository
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/desired-helmrepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/observed-helmrepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3486 add customizations for source.toolkit.fluxcd.io/v1beta2/HelmChart
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/desired-helmchart.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/observed-helmchart.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3481 add customizations for source.toolkit.fluxcd.io/v1/GitRepository
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/desired-gitrepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/observed-gitrepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3487 add customizations for kustomize.toolkit.fluxcd.io/v1/Kustomization
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/desired-kustomization.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/observed-kustomization.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3493 karmada operator: support custom labels and annotations
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/tasks/init/component.go
  operator/pkg/util/patcher/pather.go
Labels: kind/feature, approved, lgtm, size/M

#3485 add customizations for source.toolkit.fluxcd.io/v1beta2/Bucket
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/desired-bucket.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/observed-bucket.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3482 add customizations for source.toolkit.fluxcd.io/v1beta2/OCIRepository
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/desired-ocirepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/observed-ocirepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3461 Add application failover controller
  cmd/controller-manager/app/controllermanager.go
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/apis/work/v1alpha2/binding_types_helper_test.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/controllers/applicationfailover/common.go
  pkg/controllers/applicationfailover/common_test.go
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
  pkg/controllers/cluster/taint_manager.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/scheduler/framework/plugins/clustereviction/cluster_eviction.go
  pkg/util/helper/cluster.go
  pkg/util/helper/cluster_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#3500 Fix application failover
  pkg/controllers/applicationfailover/common.go
  pkg/controllers/applicationfailover/common_test.go
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
Labels: kind/feature, approved, size/L, lgtm

#3501 karmada-search: improve opensearch backend logs
  pkg/search/backendstore/opensearch.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3506 karmada operator: fixed adding altName to certification
  operator/pkg/certs/certs.go
Labels: kind/bug, approved, lgtm, size/XS

#3508 Revert preConditions and blockPredecessorSeconds in failover
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: kind/api-change, approved, size/L, lgtm

#3505 Fix:search http response add content-type header
  pkg/registry/search/storage/cache.go
Labels: kind/bug, approved, lgtm, size/XS

#3512 Update application failover proposal
  docs/proposals/failover/application-failover.md
Labels: size/S, approved, kind/documentation, lgtm

#3514 Automated cherry pick of #3505: fix:search http response add content-type header
  pkg/registry/search/storage/cache.go
Labels: approved, lgtm, size/XS

#3515 Automated cherry pick of #3505: fix:search http response add content-type header
  pkg/registry/search/storage/cache.go
Labels: approved, lgtm, size/XS

#3520 Fix DeepEqual in federated-resource-quota-status-controller;
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3497 add GroupResource
  pkg/search/proxy/store/resource_cache.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3510 karmada operator: implement installing karmada descheduler
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/constants/constants.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/tasks/deinit/component.go
  operator/pkg/tasks/init/component.go
  operator/pkg/util/naming.go
Labels: kind/feature, approved, size/L, lgtm

#3513 Automated cherry pick of #3505: fix:search http response add content-type header
  pkg/registry/search/storage/cache.go
Labels: approved, lgtm, size/XS

#3262 add managed-by label to resources created by karmada controllers
  pkg/controllers/binding/common.go
  pkg/controllers/certificate/cert_rotation_controller.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/hpa/hpa_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/util/constants.go
Labels: kind/feature, size/S, approved, lgtm, tide/merge-method-squash

#3523 fix: add missing federatedresourcequota validate config
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  operator/pkg/karmadaresource/webhookconfiguration/mainfests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: kind/bug, approved, lgtm, size/M

#3509 Add application failover e2e
  test/e2e/failover_test.go
Labels: approved, size/L, lgtm, kind/flake

#3516 add validation for MultiClusterIngress
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  cmd/webhook/app/webhook.go
  operator/pkg/karmadaresource/webhookconfiguration/mainfests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/validatingmci.go
  pkg/util/lifted/validatingmci_test.go
  pkg/webhook/multiclusteringress/validating.go
Labels: kind/feature, approved, size/XL, lgtm

#3440 Support Karmada installed by script to use karmadactl register
  artifacts/deploy/bootstrap-token-configuration.yaml
  artifacts/deploy/karmada-apiserver.yaml
  hack/deploy-karmada.sh
Labels: kind/feature, approved, size/L, lgtm

#3492 check thirdparty resources
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/AdvancedCronJob/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/BroadcastJob/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/desired-ocirepository.yaml
  pkg/resourceinterpreter/default/thirdparty/thirdparty_test.go
Labels: approved, size/L, lgtm, kind/flake

#3504 Add UT for pkg/util/lifted
  pkg/util/lifted/deployment_test.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/lua_oslib_safe_test.go
  pkg/util/lifted/objectwatcher_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#3473 fix(chart): helm uninstall clear deployment {{name}}-controller-manager
  charts/karmada/templates/post-delete-job.yaml
Labels: approved, lgtm, size/XS

#3494 Allow user decide whether to automatically generate Propagation-policy and its name when promote
  pkg/karmadactl/promote/promote.go
  test/e2e/karmadactl_test.go
Labels: kind/feature, approved, size/L, lgtm

#3498 add customizations for kyverno.io/v1/Policy
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/desired-policy.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/observed-policy.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3499 add customizations for kyverno.io/v1/ClusterPolicy
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/testdata/desired-clusterpolicy.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/testdata/observed-clusterpolicy.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3507 karmada operator: add karmada operator readme
  operator/README.md
Labels: kind/feature, approved, size/L, lgtm

#3533 Fix overridePolicy do not work when failed to process one of the matched binding
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  test/e2e/failover_test.go
  test/e2e/framework/deployment.go
Labels: approved, lgtm, kind/failing-test, size/M

#3530 Add the helmrealesa name prefix to the external etcd secret
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-cert.yaml
Labels: approved, lgtm, size/XS

#3543 fix: Fixed typo
  pkg/karmadactl/interpret/check.go
Labels: approved, lgtm, size/XS

#3511 enable concurrency for pp and cpp
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/detector/detector.go
Labels: kind/feature, approved, lgtm, size/M

#3537 fix: When suppression and graciously Tasks coexist in the GracefulEvictionTask queue, the graciously task cannot work.
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
Labels: kind/bug, approved, lgtm, size/M

#3398 Fix inspection errors
  examples/customresourceinterpreter/webhook/app/options/validation.go
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  operator/pkg/apis/operator/v1alpha1/helper.go
  operator/pkg/controller/karmada/planner.go
  operator/pkg/tasks/init/cert.go
  operator/pkg/tasks/init/upload.go
  pkg/clusterdiscovery/clusterapi/clusterapi.go
  pkg/controllers/certificate/cert_rotation_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/estimator/client/general.go
  pkg/karmadactl/apply/apply.go
  pkg/karmadactl/cmdinit/karmada/rbac_test.go
  pkg/karmadactl/cmdinit/kubernetes/services.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
  pkg/karmadactl/get/get.go
  pkg/karmadactl/interpret/edit.go
  pkg/karmadactl/interpret/execute.go
  pkg/karmadactl/interpret/interpret.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/taint/taint.go
  pkg/karmadactl/taint/taint_test.go
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
  pkg/karmadactl/util/testing/fake.go
  pkg/modeling/modeling.go
  pkg/modeling/modeling_test.go
  pkg/printers/interface.go
  pkg/printers/storage/storage.go
  pkg/printers/tablegenerator_test.go
  pkg/registry/cluster/storage/storage.go
  pkg/registry/cluster/strategy.go
  pkg/registry/search/storage/cache.go
  pkg/registry/search/storage/opensearch.go
  pkg/registry/search/storage/resourceregistry.go
  pkg/registry/search/strategy.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
  pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/framework/plugins/cache/cache.go
  pkg/search/proxy/framework/plugins/karmada/karmada.go
  pkg/search/proxy/framework/runtime/registry_test.go
  pkg/util/membercluster_client.go
  pkg/util/worker_test.go
  pkg/webhook/clusteroverridepolicy/validating.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/clusterpropagationpolicy/validating.go
  pkg/webhook/configuration/validating.go
  pkg/webhook/federatedresourcequota/validating.go
  pkg/webhook/overridepolicy/mutating.go
  pkg/webhook/overridepolicy/validating.go
  pkg/webhook/propagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/validating.go
  pkg/webhook/work/mutating.go
Labels: approved, size/L, lgtm, kind/cleanup

#3491 fix error example for addons enable
  pkg/karmadactl/addons/enable.go
Labels: approved, lgtm, size/XS

#3567 Update golangci-lint to v1.52.2
  .golangci.yml
  hack/tools/swagger/lib/storage.go
  hack/verify-staticcheck.sh
  pkg/karmadactl/cmdinit/cert/cert_test.go
  pkg/karmadactl/cmdinit/utils/examples_test.go
  pkg/webhook/multiclusteringress/validating.go
Labels: approved, lgtm, size/M, kind/cleanup

#3565 Update Golang version from v1.19.5 to v1.20.4
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
  README.md
  go.mod
  hack/util.sh
Labels: approved, lgtm, size/M, kind/cleanup

#3535 Add UT for pkg/controllers/status/cluster_status_controller_test.go
  pkg/controllers/status/cluster_status_controller_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#3547 Add UT for pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/binding_controller_test.go
  pkg/util/testing/mock_manager.go
  test/helper/manager.go
Labels: approved, size/L, lgtm, kind/cleanup

#3527 Support namespace filter in RR for search proxy
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/resource_cache.go
  pkg/search/proxy/store/store.go
  pkg/search/proxy/store/store_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
  pkg/search/proxy/testing/mock_store.go
Labels: kind/feature, approved, size/XXL, lgtm

#3438 add customizations for argoproj.io/v1alpha1/Workflow
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/argoproj.io/v1alpha1/Workflow/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/argoproj.io/v1alpha1/Workflow/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/argoproj.io/v1alpha1/Workflow/testdata/desired-workflow.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/argoproj.io/v1alpha1/Workflow/testdata/observed-workflow.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3568 Add UT for pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#3524 karmada operator: add karmada operator chart
  .gitignore
  charts/karmada-operator/.helmignore
  charts/karmada-operator/Chart.lock
  charts/karmada-operator/Chart.yaml
  charts/karmada-operator/README.md
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  charts/karmada-operator/templates/NOTES.txt
  charts/karmada-operator/templates/_helpers.tpl
  charts/karmada-operator/templates/karmada-operator-clusterrole.yaml
  charts/karmada-operator/templates/karmada-operator-clusterrolebinding.yaml
  charts/karmada-operator/templates/karmada-operator-deployment.yaml
  charts/karmada-operator/templates/karmada-operator-serviceaccount.yaml
  charts/karmada-operator/values.yaml
  hack/update-crdgen.sh
Labels: kind/feature, approved, size/XXL, lgtm

#3575 remove ci todo annotation of adopt Node16
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3563 fix_deploy_sh_base64_usage
  hack/deploy-karmada.sh
Labels: approved, lgtm, size/M

#3580 Fix doc of operator README for install crds
  operator/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#3548 Add centralized HPA api
  charts/karmada/_crds/bases/autoscaling.karmada.io_federatedhpas.yaml
  hack/update-codegen.sh
  hack/update-crdgen.sh
  pkg/apis/autoscaling/v1alpha1/doc.go
  pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.register.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, approved, size/XXL, lgtm

#3581 operator cleanup
  operator/cmd/operator/app/options/options.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/deinit.go
  operator/pkg/init.go
Labels: approved, lgtm, size/M, kind/cleanup

#3536 Support Karmada installed by helm to use karmadactl register
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/_karmada_bootstrap_token_configuration.tpl
  charts/karmada/templates/_karmada_cluster_proxy_admin_rbac.tpl
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#3545 Rename mainfests.go to manifests.go
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
Labels: kind/bug, approved, lgtm, size/XS

#3595 cleanup: genertate the necessary code for federatedhpa and fix typo
  charts/karmada/_crds/bases/autoscaling.karmada.io_federatedhpas.yaml
  hack/update-codegen.sh
  pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_autoscaling_client.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_federatedhpa.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/federatedhpa.go
  pkg/generated/clientset/versioned/typed/autoscaling/v1alpha1/generated_expansion.go
  pkg/generated/informers/externalversions/autoscaling/interface.go
  pkg/generated/informers/externalversions/autoscaling/v1alpha1/federatedhpa.go
  pkg/generated/informers/externalversions/autoscaling/v1alpha1/interface.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/autoscaling/v1alpha1/expansion_generated.go
  pkg/generated/listers/autoscaling/v1alpha1/federatedhpa.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, size/XL, lgtm, kind/cleanup

#3552 Add tokencleaner controller for karmada installed by script
  artifacts/deploy/kube-controller-manager.yaml
Labels: kind/feature, approved, lgtm, size/XS

#3599 Setup automation process of release karmada-metrics-adaptor to DockerHub
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#3468 Add kubebuilder shortName for work
  charts/karmada/_crds/bases/work.karmada.io_works.yaml
  pkg/apis/work/v1alpha1/work_types.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3602 karmada-metrics-adapter only handles clusters in Push mode
  pkg/metricsadapter/controller.go
Labels: kind/bug, size/S, approved, lgtm

#3589 Add federatedHpa controller
  api/openapi-spec/swagger.json
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/_crds/bases/autoscaling.karmada.io_federatedhpas.yaml
  charts/karmada/_crds/kustomization.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  cmd/webhook/app/webhook.go
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go
  pkg/controllers/context/context.go
  pkg/controllers/federatedhpa/config/types.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/client.go
  pkg/controllers/federatedhpa/metrics/interfaces.go
  pkg/controllers/federatedhpa/metrics/utilization.go
  pkg/controllers/federatedhpa/metrics/utilization_test.go
  pkg/controllers/federatedhpa/monitor/metrics.go
  pkg/controllers/federatedhpa/monitor/monitor.go
  pkg/controllers/federatedhpa/replica_calculator.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/util/fedinformer/transform.go
  pkg/util/fedinformer/transform_test.go
  pkg/util/gclient/gclient.go
  pkg/util/helper/pod.go
  pkg/util/lifted/federatedhpa.go
  pkg/util/lifted/federatedhpa_test.go
  pkg/util/lifted/selectors/bimultimap.go
  pkg/util/lifted/selectors/bimultimap_test.go
  pkg/util/membercluster_client.go
  pkg/webhook/federatedhpa/mutating.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/register.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/podmetrics.go
  vendor/k8s.io/metrics/pkg/client/custom_metrics/converter.go
  vendor/k8s.io/metrics/pkg/client/custom_metrics/discovery.go
  vendor/k8s.io/metrics/pkg/client/custom_metrics/interfaces.go
  vendor/k8s.io/metrics/pkg/client/custom_metrics/multi_client.go
  vendor/k8s.io/metrics/pkg/client/custom_metrics/scheme/register.go
  vendor/k8s.io/metrics/pkg/client/custom_metrics/versioned_client.go
  vendor/k8s.io/metrics/pkg/client/external_metrics/client.go
  vendor/k8s.io/metrics/pkg/client/external_metrics/interfaces.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#3600 feat: Add validation for FederatedHPA
  artifacts/deploy/karmada-metrics-adapter-apiservice.yaml
  artifacts/deploy/karmada-metrics-adapter.yaml
  artifacts/deploy/webhook-configuration.yaml
  cmd/webhook/app/webhook.go
  pkg/metricsadapter/provider/resourcemetrics.go
  pkg/util/lifted/corehelpers.go
  pkg/util/lifted/doc.go
  pkg/util/lifted/validatingfhpa.go
  pkg/webhook/federatedhpa/validation.go
Labels: kind/feature, approved, size/L

#3416 feat: Proposal for FederatedHPA
  docs/proposals/hpa/federatedhpa-v2.md
  docs/proposals/hpa/statics/federatedhpa-custom-metrics.png
  docs/proposals/hpa/statics/federatedhpa-native-metrics.png
  docs/proposals/hpa/statics/multicluster-metrics-store.png
Labels: kind/feature, approved, size/L, lgtm

#3496 Fix zero deployment can still propagate to member clusters when EnableEmptyWorkloadPropagation flag is false
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
  test/e2e/scheduling_test.go
Labels: kind/bug, size/S, approved, lgtm

#3609 Set image tag to v1.6.0
  charts/karmada/values.yaml
Labels: size/S, approved, lgtm, kind/cleanup
