Repository karmada-io/karmada, pull requests merged in 2023-10, with the labels that each got.

#4088 update swagger json
  api/openapi-spec/swagger.json
  hack/tools/swagger/generateswagger.go
  hack/update-codegen.sh
  pkg/apis/autoscaling/v1alpha1/well_known_constants.go
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, size/XXL, kind/documentation, lgtm

#4085 fix fhpa panic when SelectPolicy is nil
  pkg/controllers/federatedhpa/federatedhpa_controller.go
Labels: kind/bug, approved, lgtm, size/XS

#4106 clean ci runner disk space
  .github/workflows/ci.yml
Labels: size/S, approved, lgtm, kind/flake

#4092 Fix interactive checks in one-click installations
  hack/install-cli.sh
Labels: kind/bug, approved, lgtm, size/XS

#4096 Fix to validate spec.types of MultiClusterService Webhook
  pkg/webhook/multiclusterservice/validating.go
Labels: kind/bug, approved, lgtm, size/XS

#4103 fix: fix fhpa controller panic when SelectPolicy is nil
  pkg/controllers/federatedhpa/federatedhpa_controller.go
Labels: approved, lgtm, size/XS

#4113 Update CI with 1.28
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#4105 schedulerOptions add support for RateLimiterOptions
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, size/S, approved, lgtm

#4080 remove unnecessary maxRetry for AsyncWorker
  go.mod
  pkg/util/worker.go
  pkg/util/worker_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#4117 clean ci runner disk space
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
Labels: size/S, approved, lgtm, kind/flake

#4121 Automated cherry pick of #4106: clean ci runner disk space
  .github/workflows/ci.yml
Labels: size/S, approved, lgtm

#4119 Automated cherry pick of #4106: clean ci runner disk space
  .github/workflows/ci.yml
Labels: size/S, approved, lgtm

#4118 Automated cherry pick of #4106: clean ci runner disk space
  .github/workflows/ci.yml
Labels: size/S, approved, lgtm

#4124 Fix incorrect comments in unjoin command
  pkg/karmadactl/unjoin/unjoin.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4112 APIServer compatibility for release-1.7
  .github/workflows/ci-schedule-compatibility.yaml
Labels: approved, lgtm, size/XS

#4127 update karmada operator default karmada version
  operator/pkg/constants/constants.go
Labels: kind/feature, approved, lgtm, size/XS

#4131 Refine resource deletion protection proposal
  docs/proposals/resource-deletion-protection/README.md
Labels: approved, size/L, kind/documentation, lgtm

#4123 CI: add image scanning
  .github/workflows/ci-image-scanning.yaml
Labels: approved, lgtm, size/M

#4139 EnqueueAffectedBindings and enqueueAffectedCRBs add schedulerNameFilter
  pkg/scheduler/event_handler.go
Labels: kind/bug, size/S, approved, lgtm

#4074 [Feat] Resource Deletion Protection
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  cmd/webhook/app/webhook.go
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/webhook/cronfederatedhpa/validating.go
  pkg/webhook/federatedhpa/validating.go
  pkg/webhook/resourcedeletionprotection/validating.go
Labels: kind/feature, approved, size/L, lgtm

#4147 ci: upload trivy scan results to GitHub Security tab
  .github/workflows/ci-image-scanning.yaml
Labels: approved, lgtm, size/XS

#4146 Update release notes for v1.6.4, v1.7.1
  docs/CHANGELOG/CHANGELOG-1.6.md
  docs/CHANGELOG/CHANGELOG-1.7.md
Labels: approved, kind/documentation, lgtm, size/M

#4150 Automated cherry pick of #4139: enqueueAffectedBindings and enqueueAffectedCRBs add
  pkg/scheduler/event_handler.go
Labels: size/S, approved, lgtm

#4149 Automated cherry pick of #4139: enqueueAffectedBindings and enqueueAffectedCRBs add
  pkg/scheduler/event_handler.go
Labels: size/S, approved, lgtm

#4140 Enable unit test for operator and upload coverage to CODECOV
  .github/workflows/ci.yml
  Makefile
Labels: approved, lgtm, size/XS, kind/cleanup

#4144 fix: cannot access ResourceRegistry with its singularName
  pkg/registry/search/storage/resourceregistry.go
Labels: size/S, approved, lgtm

#4155 Automated cherry pick of #4144: fix: cannot access ResourceRegistry with its singularName
  pkg/registry/search/storage/resourceregistry.go
Labels: approved, lgtm, size/XS

#4157 Automated cherry pick of #4144: fix: cannot access ResourceRegistry with its singularName
  pkg/registry/search/storage/resourceregistry.go
Labels: approved, lgtm, size/XS

#4153 Automated cherry pick of #4144: fix: cannot access ResourceRegistry with its singularName
  pkg/registry/search/storage/resourceregistry.go
Labels: size/S, approved, lgtm

#4163 Revert "fix: cannot access ResourceRegistry with its singularName"
  pkg/registry/search/storage/resourceregistry.go
Labels: approved, lgtm, size/XS

#4164 Revert "fix: cannot access ResourceRegistry with its singularName"
  pkg/registry/search/storage/resourceregistry.go
Labels: approved, lgtm, size/XS

#4165 Revert "fix: cannot access ResourceRegistry with its singularName"
  pkg/registry/search/storage/resourceregistry.go
Labels: size/S, approved, lgtm

#4161 Update Release notes for v1.6.4
  docs/CHANGELOG/CHANGELOG-1.6.md
Labels: approved, kind/documentation, lgtm, size/M

#4162 Update release notes for v1.7.1
  docs/CHANGELOG/CHANGELOG-1.7.md
Labels: size/S, approved, kind/documentation, lgtm

#4158 Introduced leaderElection options including: `--leader-elect-lease-duration`, `--leader-elect-renew-deadline`, `--leader-elect-retry-period`
  cmd/scheduler/app/options/options.go
Labels: kind/feature, size/S, approved, lgtm

#4145 Fix: karmada-controller-manager: panic: runtime error: index out of range
  pkg/controllers/status/cluster_status_controller.go
  pkg/modeling/modeling.go
  pkg/modeling/modeling_test.go
Labels: approved, size/L, lgtm

#4133 fix: karmada-operator install default version karmada
  operator/cmd/operator/app/operator.go
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/constants/constants.go
  operator/pkg/init.go
Labels: kind/bug, approved, lgtm, size/M

#4138 fix: Sync workload's status.observedGeneration if it's updated
  pkg/controllers/status/common.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/rb_status_controller.go
Labels: kind/bug, approved, lgtm, size/M

#4169 Updated Golang version from v1.20.6 to v1.20.10
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4170 ci: fix uploading chart assests multiple times
  .github/workflows/release.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4174 ci: image-scanning increases results display
  .github/workflows/ci-image-scanning.yaml
Labels: approved, lgtm, size/XS

#4171 fix: resourceregistry is incompatible in the upgrade scenario
  pkg/registry/search/storage/resourceregistry.go
Labels: size/S, approved, lgtm

#4061 remove insecureSkipTLSVerify in karmadactl
  pkg/karmadactl/addons/metricsadapter/manifests.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter.go
  pkg/karmadactl/addons/search/manifests.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/cmdinit/cert/cert.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/options/global.go
  pkg/karmadactl/options/global.go
Labels: kind/feature, approved, lgtm, size/M

#4177 fix space at line 154 from pre-install-job.yaml to avoid helm templat…
  .github/workflows/lint-chart.yaml
  charts/karmada/templates/pre-install-job.yaml
Labels: approved, lgtm, size/XS, tide/merge-method-squash

#4178 helm: index 1.7.1
  charts/index.yaml
Labels: kind/feature, size/S, approved, lgtm

#4183 feat: Add ca to check the validation of the member clusters' server certificate
  pkg/registry/cluster/storage/proxy_test.go
  pkg/registry/cluster/storage/storage.go
  pkg/util/proxy/proxy.go
  pkg/util/proxy/proxy_test.go
Labels: kind/feature, approved, size/L, lgtm

#4181 set MinVersion to VersionTLS13 for tlsconfig in karmada-apiserver
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4063 remove insecureSkipTLSVerify in operator
  cmd/agent/app/agent.go
  operator/pkg/controlplane/metricsadapter/mainfests.go
  operator/pkg/karmadaresource/apiservice/apiservice.go
  operator/pkg/karmadaresource/apiservice/manifest.go
  operator/pkg/tasks/init/component.go
  operator/pkg/tasks/init/karmadaresource.go
  pkg/karmadactl/join/join.go
Labels: kind/feature, approved, lgtm, size/M

#4156 [e2e] add resource deletion protection e2e test
  test/e2e/framework/deployment.go
  test/e2e/framework/namespace.go
  test/e2e/resource_deletion_protection_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4189 update type in api definition
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  docs/proposals/resource-interpreter-webhook/README.md
  pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
  pkg/apis/search/v1alpha1/searchregistry_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: size/S, approved, lgtm, kind/cleanup

#4192 gen certs remove ip 10.254.0.1
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3998 fix: The PULL mode cluster cannot be deleted immediately
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/M

#4188 fix: helm podDisruptionBudget for controller-manager
  charts/karmada/templates/karmada-controller-manager.yaml
Labels: kind/bug, approved, lgtm, size/XS

#4095 fix spell error in test and docs
  docs/proposals/dependencies-automatically-propagation/README.md
  docs/proposals/hpa/cronfederatedhpa.md
  docs/proposals/mcs/remove-derived-mcs.md
  docs/proposals/migration/design-of-seamless-cluster-migration-scheme.md
  docs/proposals/resource-interpreter-webhook/README.md
  docs/proposals/scheduling/521-scheduler-estimator/README.md
  docs/proposals/scheduling/697-descheduler/README.md
  docs/proposals/scheduling/multi-scheduling-group/README.md
  test/e2e/aggregatedapi_test.go
  test/e2e/federatedresourcequota_test.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
  test/e2e/search_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#4196 bump golang.org/grpc to v1.56.3 to address CVE concerns
  go.mod
  go.sum
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/idle.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/buffer/unbounded.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/observability.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/serviceconfig/duration.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/manual/manual.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup

#4136 e2e: add test case for hpa replicas syncer
  test/e2e/framework/hpa.go
  test/e2e/hpareplicassyncer_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm, kind/failing-test
