Repository karmada-io/karmada, pull requests merged in 2023-04, with the labels that each got.

#3351 add placement helper
  pkg/apis/policy/v1alpha1/propagation_helper.go
  pkg/apis/policy/v1alpha1/propagation_helper_test.go
  pkg/descheduler/core/filter.go
  pkg/util/helper/policy.go
  pkg/util/helper/policy_test.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: approved, size/L, lgtm, kind/cleanup

#3353 Automated cherry pick of #3348: Fixed the control plane endpointslice cannot be deleted.
  pkg/util/helper/mcs.go
Labels: size/S, approved, lgtm

#3354 Automated cherry pick of #3348: Fixed the control plane endpointslice cannot be deleted.
  pkg/util/helper/mcs.go
Labels: size/S, approved, lgtm

#3350 Add UT for deploy.go
  pkg/controllers/status/cluster_condition_cache_test.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3339 Add a function getPodDependencies for InterpretDependency operation
  pkg/resourceinterpreter/customized/declarative/luavm/kube.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
  pkg/resourceinterpreter/default/native/dependencies.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
  pkg/util/helper/pod.go
  pkg/util/helper/pod_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#3346 [Performance] Do not schedule when status/metadata of binding update
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler_metrics_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3363 fix an issue where DeepEqual becomes invalid in aggregate binding status
  pkg/util/helper/workstatus.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3345 Support specify global image registry for enable addons
  pkg/karmadactl/addons/descheduler/descheduler.go
  pkg/karmadactl/addons/enable.go
  pkg/karmadactl/addons/estimator/estimator.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/addons/search/search.go
Labels: kind/feature, approved, lgtm, size/M

#3326 feat: add --purge-namespace flags for `karmadactl deinit`, and default not delete namespace
  pkg/karmadactl/deinit/deinit.go
Labels: kind/feature, size/S, approved, lgtm

#3321 Do not revise replicas when strategy is duplicated
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3357 fix that multiple same spread constraints are allowed
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3315 parseSingle: add test
  pkg/util/apigroup_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3123 Avoid multiple executions after rlock in concurrent scenarios
  pkg/util/fedinformer/genericmanager/multi-cluster-manager.go
  pkg/util/fedinformer/genericmanager/single-cluster-manager.go
  pkg/util/fedinformer/typedmanager/multi-cluster-manager.go
  pkg/util/fedinformer/typedmanager/single-cluster-manager.go
Labels: kind/bug, approved, lgtm, size/M

#3364 use patch helper instead of jsonpatch
  pkg/scheduler/scheduler.go
  pkg/util/helper/patch.go
  pkg/util/helper/patch_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3371 Unify the assign replicas when duplicated
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/assignment_test.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/scheduler.go
Labels: approved, size/L, lgtm, kind/cleanup

#2768 feat: predefined configurableInterpreter
  pkg/resourceinterpreter/default/thirdparty/manager.go
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/embed.go
  pkg/resourceinterpreter/default/thirdparty/thirdparty.go
  pkg/resourceinterpreter/interpreter.go
Labels: kind/feature, approved, size/L, lgtm

#3387 Automated cherry pick of #3376: if start many watcher to watch pod. pod resourceVersion will
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/util.go
Labels: size/S, approved, lgtm

#3391 Automated cherry pick of #3376: if start many watcher to watch pod. pod resourceVersion will
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/util.go
Labels: size/S, approved, lgtm

#3133 Add “Application failover mechanism“ proposal
  docs/proposals/failover/application-failover.md
Labels: approved, size/XL, kind/documentation, lgtm

#3349 karmada operator: support etcd high availability
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/config/deploy/karmada-operator.yaml
  operator/config/samples/karmada.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/etcd/mainfests.go
  operator/pkg/init.go
Labels: kind/feature, approved, size/L, lgtm

#3397 fix: validate predicate path for imageOverride.
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/validation/validation.go
Labels: kind/bug, approved, lgtm, size/M

#3342 Add failover APIs in policy
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/XL, lgtm

#3405 Setup interpreter owners
  pkg/resourceinterpreter/default/thirdparty/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#3337 Add customizations for apps.krusie.io/v1alpha1/CloneSet
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/desired-cloneset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/observed-cloneset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3400 karmada operator: optimize karmada aggregated apiserver startup
  operator/pkg/init.go
  operator/pkg/tasks/init/apiserver.go
  operator/pkg/tasks/init/etcd.go
  operator/pkg/tasks/init/wait.go
Labels: kind/feature, approved, size/L

#3352 add customizations for apps.krusie.io/v1beta1/StatefulSet
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/desired-statefulset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/observed-statefulset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3358 add customizations for apps.krusie.io/v1alpha1/DaemonSet
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/desired-daemonset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/observed-daemonset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3368 add customizations for apps.krusie.io/v1alpha1/AdvancedCronJob
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CronJob/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CronJob/testdata/desired-acj-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CronJob/testdata/observed-acj-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CronJob/testdata/status-file.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#3409 fix(chart): fix agent.tolerations type
  charts/karmada/values.yaml
Labels: approved, lgtm, size/XS

#3374 karmada operator: add defaults for karmada cr
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/apis/operator/v1alpha1/doc.go
  operator/pkg/apis/operator/v1alpha1/register.go
  operator/pkg/constants/constants.go
  operator/pkg/controller/karmada/controller.go
  operator/pkg/init.go
  operator/pkg/karmadaresource/apiservice/apiservice.go
Labels: kind/feature, approved, size/L, lgtm

#3392 add unit test for pkg/resourceinterpreter/default/native/dependencies.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
  pkg/util/helper/pod.go
Labels: approved, size/XL, lgtm, kind/cleanup

#3412 add an example for examples/karmadactlinterpret/README.md
  examples/karmadactlinterpret/README.md
  examples/karmadactlinterpret/resourceinterpretercustomization.yaml
Labels: size/S, approved, kind/documentation, lgtm

#3414 feat: CommandArgsOverrider supports Job
  pkg/util/overridemanager/commandargsoverride.go
Labels: kind/feature, approved, lgtm, size/XS

#3411 cleanup:cluster controller log missing clustername
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3393 Avoid accidental impact for WeightPreference on the cache
  pkg/scheduler/scheduler.go
Labels: kind/bug, approved, lgtm, size/XS

#3399 Binding API modification adaptation to implement application failover
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/L, lgtm

#3428 Automated cherry pick of #3393: Avoid accidental impact for rb/crb's pointer on the cache
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS

#3373 feat: Allows setting wildcards for SkippedPropagatingNamespaces
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/validation.go
  pkg/controllers/context/context.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/detector/detector.go
  pkg/detector/detector_test.go
Labels: kind/feature, approved, size/L, lgtm

#3330 Add a workflow for conducting compatibility testing.
  .github/workflows/ci-schedule-compatibility.yaml
Labels: kind/feature, approved, lgtm, size/M

#3425 Fix func retainPodFields not include initContainer'volumesMounts bug
  pkg/resourceinterpreter/default/native/retain.go
Labels: kind/bug, approved, lgtm, size/XS

#3432 Add draft of 2023 roadmap
  ROADMAP.md
Labels: approved, lgtm, size/M, kind/cleanup

#2999 Support Connection to ResourceInterpretWebhook without DNS Service
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/resourceinterpreter/interpreter.go
  vendor/k8s.io/apimachinery/pkg/api/meta/table/table.go
  vendor/k8s.io/apiserver/pkg/util/proxy/proxy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/install/install.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/validation/validation.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiservice_controller.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_apis.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/resolvers.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/scheme/scheme.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/cache.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/priority.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/etcd/etcd.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/rest/storage_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/strategy.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/walker.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#3407 Add validation for failover
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: kind/api-change, approved, size/L, lgtm, kind/cleanup

#3433 feat: allows users to propagate resources under the Kubernetes reserved namespace.
  cmd/controller-manager/app/options/options.go
  pkg/util/names/names.go
  pkg/util/names/names_test.go
Labels: kind/feature, size/S, approved, lgtm

#3439 karmada operator: fixed karmada-aggregated-apiserver name
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/config/samples/karmada.yaml
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/constants/constants.go
  operator/pkg/controller/karmada/controller.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/karmadaresource/apiservice/apiservice.go
  operator/pkg/tasks/deinit/component.go
  operator/pkg/tasks/init/apiserver.go
  operator/pkg/util/naming.go
Labels: kind/bug, approved, size/L, lgtm

#3402 fix paging list in karmada search proxy
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
Labels: kind/bug, approved, size/L, lgtm

#3449 Automated cherry pick of #3402: fill cluster rv in proxying list
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
Labels: approved, size/L, lgtm

#3452 Cleanup the rbac that has been removed in hack/undeploy-karmada.sh
  hack/undeploy-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#3450 Automated cherry pick of #3402: fill cluster rv in proxying list
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
Labels: approved, size/L, lgtm

#3437 Add GracePeriodSeconds for GracefulEvictionTask
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/detector/detector.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/helper/policy.go
  pkg/util/helper/policy_test.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: kind/api-change, approved, size/L, lgtm, kind/design

#3395 Add UT for workstatus.go and taint.go and rule.go
  pkg/util/helper/taint_test.go
  pkg/util/helper/workstatus_test.go
  pkg/util/interpreter/rule_test.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#3451 Automated cherry pick of #3402: fill cluster rv in proxying list
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
Labels: approved, size/XL, lgtm

#3442 fix: affinityName can be set to an empty string
  charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/util/validation/validation.go
Labels: kind/bug, size/S, approved, lgtm

#3462 rename advancedcronjob directory
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/AdvancedCronJob/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/AdvancedCronJob/testdata/desired-acj-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/AdvancedCronJob/testdata/observed-acj-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/AdvancedCronJob/testdata/status-file.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/BroadcastJob/customizations.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#3431 Add more detail comments for AggregatedStatus field
  pkg/apis/config/v1alpha1/interpretercontext_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, kind/documentation, lgtm, size/XS

#3457 add e2e to test dependency distribution base on ClusterPropagationPolicy
  test/e2e/dependenciesdistributor_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#3456 Correct the issue of adding duplicate eviction tasks
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/apis/work/v1alpha2/binding_types_helper_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#3283 Avoid the same cluster appearing in both spec.clusters and spec.gracefulEvictionTasks
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#3465 Fixing probability of failure in CLI workflow
  hack/cli-testing-environment.sh
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/failing-test

#3381 flake: [ClusterAffinities] propagation testing
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler.go
Labels: approved, size/L, lgtm, kind/failing-test

#3455 Ensure the latest schedulerObservedGeneration if do not need to schedule
  pkg/scheduler/scheduler.go
Labels: kind/bug, size/S, approved, lgtm

#3477 Automated cherry pick of #3455: fix generation inconsistent
  pkg/scheduler/scheduler.go
Labels: size/S, approved, lgtm

#3476 fix: Chinese to English term
  api/openapi-spec/swagger.json
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, kind/documentation, lgtm, size/XS

#3469 Add a clusterEviction plugin
  pkg/scheduler/framework/plugins/clustereviction/cluster_eviction.go
  pkg/scheduler/framework/plugins/registry.go
  pkg/util/helper/cluster.go
  pkg/util/helper/cluster_test.go
  test/e2e/failover_test.go
Labels: kind/feature, approved, size/L, lgtm

#3378 karmada operator: add nodeport service type for apiserver
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/certs/certs.go
  operator/pkg/constants/constants.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/apiserver/mainfests.go
  operator/pkg/init.go
  operator/pkg/tasks/init/apiserver.go
  operator/pkg/tasks/init/cert.go
  operator/pkg/tasks/init/data.go
  operator/pkg/tasks/init/upload.go
  operator/pkg/util/apiclient/idempotency.go
  operator/pkg/util/endpoint.go
Labels: kind/feature, approved, size/L, lgtm

#3480 Fix: cleanup ResourceRegistry controller logs
  pkg/search/controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#3478 karmada-search: ResourceRegistry controller can't handle DeletedFinalStateUnknown it gets from controller framework
  pkg/search/controller.go
Labels: kind/bug, approved, lgtm, size/M, ok-to-test
