Repository karmada-io/karmada, pull requests merged in 2023-12, with the labels that each got.

#4344 correct the license in the lifted directory
  pkg/util/lifted/deployment_test.go
  pkg/util/lifted/federatedhpa.go
  pkg/util/lifted/federatedhpa_test.go
  pkg/util/lifted/lua_oslib_safe.go
  pkg/util/lifted/validatingfhpa.go
  pkg/util/lifted/validatingmci_test.go
Labels: kind/bug, size/S, approved, lgtm

#4352 e2e: make FederatedResourceQuota e2e as serial to avoid affecting other e2e
  test/e2e/federatedresourcequota_test.go
Labels: approved, lgtm, size/XS, kind/flake

#4354 cleanup: cleanup e2e of mcs
  test/e2e/mcs_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm, kind/cleanup

#4324 Add e2e coverage analysis docs
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/coverage_docs/clusteroverridepolicy_test.md
  test/e2e/coverage_docs/clusterpropagationpolicy_test.md
  test/e2e/coverage_docs/dependenciesdistributor_test.md
  test/e2e/coverage_docs/failover_test.md
  test/e2e/coverage_docs/namespace_test.md
  test/e2e/coverage_docs/propagationpolicy_test.md
  test/e2e/coverage_docs/resource_deletion_protection_test.md
  test/e2e/dependenciesdistributor_test.go
  test/e2e/failover_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/resource_deletion_protection_test.go
Labels: approved, size/L, kind/documentation, lgtm

#4355 cleanup: make the name unified of mcs
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#4300 doc: make the chart installation doc easier to understand.
  charts/karmada/README.md
Labels: size/S, approved, kind/documentation, lgtm

#4361 Automated cherry pick of #4344: correct the license in the lifted directory
  pkg/util/lifted/deployment_test.go
  pkg/util/lifted/federatedhpa.go
  pkg/util/lifted/federatedhpa_test.go
  pkg/util/lifted/lua_oslib_safe.go
  pkg/util/lifted/validatingfhpa.go
  pkg/util/lifted/validatingmci_test.go
Labels: size/S, approved, lgtm

#4359 Delete the unused integration package in the test package
  test/integration/suite_test.go
  test/integration/work_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#4349 Update helm index to v1.8.0 and add the karmada-operator chart
  charts/index.yaml
Labels: kind/feature, approved, lgtm, size/M

#4363 e2e: Fix the occasional failure of mcs e2e
  test/e2e/search_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4366 Delete k8s v1.21 and v1.22 from CI Schedule Workflow.
  .github/workflows/ci-schedule.yml
Labels: approved, lgtm, size/XS, kind/failing-test

#4360 feat: sync mcs work when cluster joined or unjoin
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/util/helper/mcs.go
Labels: kind/feature, approved, lgtm, size/M

#4356 feat: dispatch eps to the newly joined consumption clusters
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/util/constants.go
Labels: kind/feature, approved, lgtm, size/M

#4373 fix estimator license
  hack/verify-license.sh
  pkg/estimator/pb/types.go
  pkg/estimator/service/doc.go
  pkg/estimator/service/mock_EstimatorClient.go
  pkg/estimator/service/service.proto
Labels: approved, lgtm, size/M, kind/cleanup

#4377 update karmada-version to 1.8 in CI
  .github/workflows/ci-schedule-compatibility.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#4376 bump alpine to 3.18.5 to address CVE concerns
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#4375 make metrics-adapter chart installation optional
  charts/karmada/templates/karmada-metrics-adapter.yaml
Labels: kind/bug, approved, lgtm, size/XS

#4379 Automated cherry pick of #4376: bump alpine to 3.18.5 to address CVE concerns
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: size/S, approved, lgtm

#4381 Automated cherry pick of #4376: bump alpine to 3.18.5 to address CVE concerns
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: size/S, approved, lgtm

#4382 Automated cherry pick of #4376: bump alpine to 3.18.5 to address CVE concerns
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: approved, lgtm, size/XS

#4378 Fix wrong reference website for docs.
  .github/ISSUE_TEMPLATE/question.md
  ADOPTERS.md
  docs/proposals/resource-aggregation-proxy/README.md
  samples/guestbook/README.md
Labels: size/S, approved, lgtm, kind/cleanup

#2066 Add additionalPrinterColumns `KIND` for Work CRD
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  pkg/apis/work/v1alpha1/work_types.go
Labels: kind/feature, approved, lgtm, size/XS

#4094 Use Patch() when binding-status controller update workload's status
  pkg/controllers/status/common.go
  pkg/util/helper/patch.go
  pkg/util/helper/patch_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4390 Let cli testing based on current source code
  hack/cli-testing-environment.sh
Labels: size/S, approved, lgtm, kind/failing-test

#3891 add resources to webhook chart
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-webhook.yaml
Labels: approved, lgtm, size/XS, tide/merge-method-squash

#4371 fix(util/proxy): fix tls.config when secret.spec.caBundle is nil
  pkg/util/proxy/proxy.go
Labels: kind/bug, size/S, approved, lgtm

#4391 Automated cherry pick of #4371: fix(util/proxy): fix tls.config when secret.spec.caBundle is
  pkg/util/proxy/proxy.go
Labels: size/S, approved, lgtm

#4358 make estimator config in helm values as a list
  charts/karmada/README.md
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#4389 add test for static weight random remainder.
  pkg/scheduler/core/generic_scheduler_test.go
Labels: approved, size/L, lgtm

#4399 Automated cherry pick of #4363: e2e: Fix the occasional failure of mcs e2e
  test/e2e/search_test.go
Labels: approved, size/L, lgtm

#4252 e2e: add e2e test for command karmadactl top pod
  test/e2e/framework/constant.go
  test/e2e/framework/pod.go
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm

#4394 [release-1.5] Bump Golang to v1.19.13
  .github/workflows/ci.yml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4316 feat: support install karmada search with operator
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/constants/constants.go
  operator/pkg/controlplane/search/mainfests.go
  operator/pkg/controlplane/search/search.go
  operator/pkg/karmadaresource/apiservice/apiservice.go
  operator/pkg/karmadaresource/apiservice/manifest.go
  operator/pkg/tasks/deinit/component.go
  operator/pkg/tasks/init/component.go
  operator/pkg/util/naming.go
Labels: kind/feature, approved, size/L, lgtm

#4315 generate Embedded ObjectMeta in the CRDs
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  hack/update-crdgen.sh
  operator/config/crds/operator.karmada.io_karmadas.yaml
Labels: kind/bug, approved, lgtm, size/M

#4400 add expand replicas test about even distribution of replicas
  pkg/scheduler/core/generic_scheduler_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4415 Update sandbox to incubation.
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#4409 fix: generate the code in correct path
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#4414 feat: fix resource(work/resource in member clusters) conflicting between PP and MCS.
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
  pkg/apis/networking/v1alpha1/service_types.go
  pkg/apis/networking/v1alpha1/well_known_constants.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/detector/detector.go
  pkg/events/events.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/scheduler/event_handler.go
  pkg/util/constants.go
  pkg/util/helper/mcs.go
  pkg/util/names/names.go
  pkg/webhook/multiclusterservice/validating.go
  pkg/webhook/multiclusterservice/validating_test.go
  test/e2e/mcs_test.go
  test/helper/resource.go
Labels: kind/feature, kind/api-change, approved, size/XL, lgtm

#4422 skip recreating resources that is not supposed to be propagated
  pkg/controllers/status/work_status_controller.go
Labels: kind/bug, approved, lgtm, size/XS

#4423 fix: Update RB once new clusters are added to trigger the propagation of service to these new clusters
  pkg/controllers/multiclusterservice/mcs_controller.go
Labels: kind/bug, approved, lgtm, size/XS

#4393 make hook-delete-policy in helm job configurable
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: kind/feature, size/S, approved, lgtm

#4395 [release-1.6] Bump Golang to go1.20.12
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4392 Put Xiao Zhang to the maintainer list
  MAINTAINERS.md
Labels: approved, kind/documentation, lgtm, size/XS

#4396 [release-1.7] Bump Golang to v1.20.12
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4397 [release-1.8] Bump Golang to v1.20.12
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: approved, lgtm, size/M, kind/cleanup

#4419 add scale down test for even distribution of replicas
  pkg/scheduler/core/generic_scheduler_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#4427 prevent CI from fast fail when just one k8s version e2e failed
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
Labels: approved, lgtm, size/XS, kind/flake

#4387 ensure resource template be un-claimed when deleting cluster policy
  pkg/detector/detector.go
Labels: kind/bug, approved, lgtm, size/XS

#4438 fix typo
  charts/karmada/values.yaml
  docs/proposals/service-discovery/README.md
  hack/install-cli.sh
  hack/util.sh
  operator/pkg/init.go
  operator/pkg/tasks/deinit/component.go
  operator/pkg/util/apiclient/idempotency.go
  operator/pkg/util/util.go
  pkg/controllers/hpareplicassyncer/hpa_scale_ref_worker.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/karmadactl/addons/install/install.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/format_test.go
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/karmadactl/interpret/edit.go
  pkg/karmadactl/promote/promote.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/factory.go
  pkg/metricsadapter/provider/custommetrics.go
  pkg/metricsadapter/provider/resourcemetrics.go
  pkg/resourceinterpreter/customized/webhook/request/resourceinterpretercontext.go
  pkg/search/proxy/framework/plugins/cluster/cluster.go
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4424 Add release notes of v1.5.5
  .github/workflows/ci.yml
  docs/CHANGELOG/CHANGELOG-1.5.md
Labels: approved, kind/documentation, lgtm, size/M

#4425 Add release notes of v1.6.5
  docs/CHANGELOG/CHANGELOG-1.6.md
Labels: approved, kind/documentation, lgtm, size/M

#4428 Add release notes of v1.7.2
  docs/CHANGELOG/CHANGELOG-1.7.md
Labels: approved, kind/documentation, lgtm, size/M

#4429 Add release notes of v1.8.1
  docs/CHANGELOG/CHANGELOG-1.8.md
Labels: size/S, approved, kind/documentation, lgtm

#4444 Add release notes of v1.5.5, v1.6.5, v1.7.2, v1.8.1
  docs/CHANGELOG/CHANGELOG-1.5.md
  docs/CHANGELOG/CHANGELOG-1.6.md
  docs/CHANGELOG/CHANGELOG-1.7.md
  docs/CHANGELOG/CHANGELOG-1.8.md
Labels: approved, size/L, kind/documentation, lgtm

#4448 fix: clean the finalizer of mcs if the ExposureType transforms from CrossCluster to LoadBalancer
  pkg/controllers/multiclusterservice/mcs_controller.go
Labels: kind/bug, size/S, approved, lgtm

#4433 feat: report event when the service doesn't exist/when endpointslice api is disabled
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/events/events.go
  pkg/util/constants.go
  pkg/util/helper/mcs.go
Labels: kind/feature, approved, size/L, lgtm

#4452 fix: ignore reconcile the mcs(triggered by svc/cluster) if the mcs is not CrossCluster
  pkg/controllers/multiclusterservice/mcs_controller.go
Labels: kind/bug, approved, lgtm, size/M

#4453 execute InterpretHealth even if statusRaw is nil
  pkg/controllers/status/work_status_controller.go
Labels: kind/bug, approved, lgtm, size/XS

#4454 feat: prevent updates to mcs.types or when multiple types are involved.
  pkg/webhook/multiclusterservice/validating.go
  pkg/webhook/multiclusterservice/validating_test.go
Labels: kind/feature, approved, lgtm, size/M

#4340 add forType in binding status controller to inherit concurrency declared in global options
  pkg/controllers/status/common.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/rb_status_controller.go
Labels: kind/bug, size/S, approved, lgtm

#4404 register cluster install karmada-agent should set leader-elect-resouce-namespace
  pkg/karmadactl/register/register.go
Labels: kind/bug, approved, lgtm, size/XS

#4459 cleanup controllerruntime deprecated option SyncPeriod Namespace
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4464 Update karmada-apiserver&controller-manager to v1.26.12
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  operator/README.md
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: size/S, approved, lgtm, kind/cleanup

#4432 add change static weight test for even distribution of replicas
  pkg/scheduler/core/generic_scheduler_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#4461 Automated cherry pick of #4340: add forType in binding status controller to inherit
  pkg/controllers/status/common.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/rb_status_controller.go
Labels: size/S, approved, lgtm

#4460 Replace golang/mock to uber-go/mock.
  go.mod
  go.sum
  pkg/scheduler/framework/runtime/framework_test.go
  pkg/scheduler/framework/testing/mock_interface.go
  vendor/go.uber.org/mock/AUTHORS
  vendor/go.uber.org/mock/LICENSE
  vendor/go.uber.org/mock/gomock/call.go
  vendor/go.uber.org/mock/gomock/callset.go
  vendor/go.uber.org/mock/gomock/controller.go
  vendor/go.uber.org/mock/gomock/doc.go
  vendor/go.uber.org/mock/gomock/matchers.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm, kind/cleanup

#4468 Remove golang mock as it has been replaced with uber mock
  go.mod
  go.sum
  hack/tools/tools.go
  hack/update-mocks.sh
  pkg/scheduler/framework/testing/mock_interface.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/mockgen/version.1.11.go
  vendor/go.uber.org/mock/mockgen/generic_go118.go
  vendor/go.uber.org/mock/mockgen/generic_notgo118.go
  vendor/go.uber.org/mock/mockgen/mockgen.go
  vendor/go.uber.org/mock/mockgen/model/model.go
  vendor/go.uber.org/mock/mockgen/parse.go
  vendor/go.uber.org/mock/mockgen/reflect.go
  vendor/go.uber.org/mock/mockgen/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup

#4436 docs: add e2e coverage detail
  test/e2e/coverage_docs/federatedresourcequota_test.md
  test/e2e/coverage_docs/fieldselector_test.md
  test/e2e/coverage_docs/hpareplicassyncer_test.md
  test/e2e/coverage_docs/karmadactl_test.md
  test/e2e/coverage_docs/mcs_test.md
  test/e2e/coverage_docs/overridepolicy_test.md
  test/e2e/coverage_docs/porting_workloads_test.md
  test/e2e/coverage_docs/rescheduling_test.md
  test/e2e/karmadactl_test.go
  test/e2e/overridepolicy_test.go
  test/e2e/porting_workloads_test.go
  test/e2e/rescheduling_test.go
Labels: approved, size/L, kind/documentation, lgtm

#4469 test of even distribution of replicas for add cluster scenario
  pkg/scheduler/core/generic_scheduler_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#4465 Add kubernetes v1.29.0 to CI
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/lint-chart.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#4475 Nominate E2E code owners
  test/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#4472 simply optimizing the scheduler log
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/util.go
Labels: approved, lgtm, size/XS

#4470 e2e: check whether the deployment disappears in the recovered clusters
  test/e2e/failover_test.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4482 doc: fix readme typo
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#4484 Add notes for karmada resourceinterpreter webhook example README
  examples/customresourceinterpreter/README.md
Labels: approved, kind/documentation, lgtm, size/M
