Repository karmada-io/karmada, pull requests merged in 2024-12, with the labels that each got.

#5847 pkg/karmadactl: unit test describe
  pkg/karmadactl/describe/describe.go
  pkg/karmadactl/describe/describe_test.go
Labels: approved, size/L, lgtm

#5871 pkg/karmadactl: unit test join
  pkg/karmadactl/join/join.go
  pkg/karmadactl/join/join_test.go
Labels: approved, size/L, lgtm

#5768 Added unit tests for status and cronfederatedhpa helper utilities
  pkg/util/helper/cronfederatedhpa_test.go
  pkg/util/helper/status_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5903 refactor: introduce DefaultHistoryLimit constant for CronFederatedHPA
  pkg/util/helper/cronfederatedhpa.go
  pkg/util/helper/cronfederatedhpa_test.go
Labels: size/S, approved, kind/documentation, lgtm, kind/cleanup

#5901 Bump kind dependencis from v0.24.0 to v0.25.0
  go.mod
  go.sum
  hack/cli-testing-environment.sh
  hack/cli-testing-init-with-config.sh
  hack/local-up-karmada-by-operator.sh
  hack/local-up-karmada.sh
  hack/util.sh
  vendor/modules.txt
  vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/network.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provider.go
  vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
Labels: approved, lgtm, size/M, kind/cleanup

#5895 pkg/karmadactl: unit test promote
  pkg/karmadactl/promote/promote.go
  pkg/karmadactl/promote/promote_test.go
Labels: approved, size/XL, lgtm

#5819 Added unit tests for safe lua lifted libraries
  pkg/util/lifted/lua/loadlib_safe_test.go
  pkg/util/lifted/lua/oslib_safe_test.go
Labels: kind/feature, approved, size/L, lgtm

#5829 pkg/karmadactl: unit test cordon
  pkg/karmadactl/cordon/cordon_test.go
Labels: approved, size/L, lgtm

#5870 pkg/karmadactl: unit test unjoin
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/unjoin/unjoin_test.go
Labels: approved, size/L, lgtm

#5760 pkg/karmadactl/cmdinit/bootstraptoken: unit test clusterinfo
  pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
  pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo_test.go
  pkg/karmadactl/util/idempotency.go
Labels: approved, size/L, lgtm

#5864 Added unit tests for custom resource interpreter's configuration manager
  pkg/resourceinterpreter/customized/declarative/configmanager/accessor_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5898 Added unit tests for the replica package in the estimator server
  pkg/estimator/server/replica/replica_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5909 Test helm chart with the latest code
  .github/workflows/installation-chart.yaml
  .github/workflows/installation-cli.yaml
  .github/workflows/installation-operator.yaml
  hack/setup-dev-base.sh
Labels: kind/feature, approved, size/L, lgtm, kind/flake

#5772 Added unit tests for the scheduler's node tree functionality
  pkg/util/lifted/scheduler/cache/node_tree_test.go
Labels: kind/feature, approved, size/L, lgtm

#5908 cmd+hack+operator+pkg: unify addons constants
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/aggregated-apiserver/app/aggregated-apiserver.go
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  cmd/descheduler/app/descheduler.go
  cmd/descheduler/app/descheduler_test.go
  cmd/descheduler/app/options/options.go
  cmd/karmada-search/app/karmada-search.go
  cmd/metrics-adapter/app/metrics-adapter.go
  cmd/metrics-adapter/app/options/options.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/scheduler.go
  cmd/scheduler/app/scheduler_test.go
  cmd/webhook/app/webhook.go
  hack/tools/gencomponentdocs/gen_component_docs.go
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/constants/constants.go
  operator/pkg/tasks/deinit/component_test.go
  operator/pkg/tasks/init/wait.go
  pkg/descheduler/descheduler.go
  pkg/karmadactl/addons/descheduler/descheduler.go
  pkg/karmadactl/addons/descheduler/descheduler_test.go
  pkg/karmadactl/addons/estimator/estimator.go
  pkg/karmadactl/addons/init/addon.go
  pkg/karmadactl/addons/init/disable_option.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/addons/install/install.go
  pkg/karmadactl/addons/install/install_test.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter_test.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/addons/search/search_test.go
  pkg/karmadactl/cmdinit/cert/cert_test.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/join/join.go
  pkg/karmadactl/join/join_test.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/unregister/unregister.go
  pkg/karmadactl/unregister/unregister_test.go
  pkg/search/apiserver.go
  pkg/search/proxy/controller.go
  pkg/util/constants.go
  pkg/util/imageparser/parser_test.go
  pkg/util/names/names.go
Labels: approved, size/L, lgtm, kind/cleanup

#5910 Bump update kubernetes version to v1.31.3
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#5876 add shell completion code for fish
  pkg/karmadactl/completion/completion.go
Labels: kind/feature, size/S, approved, lgtm

#5923 Stop maintaining version 1.9 and maintain version 1.12
  .github/dependabot.yml
  .github/workflows/ci-image-scanning-on-schedule.yml
  .github/workflows/ci-schedule-compatibility.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5917 prevent some jobs running from forked repository
  .github/workflows/dockerhub-released-chart.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
Labels: size/S, approved, lgtm, kind/cleanup

#5832 Added unit tests for resourceinterpreter webhook configmanager
  pkg/resourceinterpreter/customized/webhook/configmanager/accessor_test.go
  pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go
Labels: kind/feature, approved, size/L, lgtm

#5933 fix flake test of KarmadactlTopPod
  test/e2e/karmadactl_test.go
Labels: size/S, approved, lgtm, kind/failing-test, kind/flake

#5932 Automated cherry pick of #5400, #5216
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
Labels: approved, lgtm, size/M

#5931 Automated cherry pick of #5400, #5216
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
Labels: approved, lgtm, size/M

#5930 Automated cherry pick of #5400, #5216
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
Labels: approved, lgtm, size/M

#5918 Bump upgrade helm chart index to v1.12.0
  charts/index.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#5869 pkg/karmadactl/util: unit test apiclient
  operator/pkg/util/kubeconfig_test.go
  pkg/controllers/binding/binding_controller_test.go
  pkg/controllers/binding/cluster_resource_binding_controller_test.go
  pkg/karmadactl/util/apiclient/apiclient.go
  pkg/karmadactl/util/apiclient/apiclient_test.go
  pkg/util/testing/helpers.go
Labels: approved, size/L, lgtm

#5913 simplify local-up-karmada.sh based on setup-dev-base.sh
  hack/local-up-karmada.sh
Labels: approved, size/L, lgtm, kind/cleanup

#5950 Automated cherry pick of #5943: Fix the problem of ResourceBinding remaining when the
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: approved, lgtm, size/XS

#5952 Automated cherry pick of #5943: Fix the problem of ResourceBinding remaining when the
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: approved, lgtm, size/XS

#5951 Automated cherry pick of #5943: Fix the problem of ResourceBinding remaining when the
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: approved, lgtm, size/XS

#5947 Disable cluster failover by default which should be explicitly enabled by administrators after a fully evaluation
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/cluster/cluster_controller_test.go
  pkg/features/features.go
Labels: approved, size/XL, lgtm

#5948 Disable cluster failover by default which should be explicitly enabled by administrators after a fully evaluation
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/cluster/cluster_controller_test.go
  pkg/features/features.go
Labels: approved, size/XL, lgtm

#5914 simplify local-up-karmada-by-operator.sh based on setup-dev-base.sh
  hack/deploy-karmada-by-operator.sh
  hack/local-up-karmada-by-operator.sh
Labels: approved, size/L, lgtm, kind/cleanup

#5953 publish release note for v1.9.10, v1.10.8, v1.11.4, v1,12.1
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, kind/documentation, lgtm

#5957 Update interface.go
  pkg/scheduler/framework/interface.go
Labels: approved, kind/documentation, lgtm, size/XS, kind/cleanup

#5960 `karmada-webhook`: Fix panic when validating ResourceInterpreterWebhookConfiguration with unspecified service port
  pkg/webhook/configuration/validating.go
  pkg/webhook/configuration/validating_test.go
Labels: kind/bug, size/S, approved, lgtm

#5862 remove the unnecessary file localization steps when karmadactl register
  pkg/karmadactl/register/register.go
Labels: approved, size/L, lgtm, kind/deprecation

#5965 Automated cherry pick of #5960: Fix panic when validating ResourceInterpreterWebhookConfiguration with unspecified service port
  pkg/webhook/configuration/validating.go
  pkg/webhook/configuration/validating_test.go
Labels: size/S, approved, lgtm

#5966 Automated cherry pick of #5960: Fix panic when validating ResourceInterpreterWebhookConfiguration with unspecified service port
  pkg/webhook/configuration/validating.go
  pkg/webhook/configuration/validating_test.go
Labels: size/S, approved, lgtm

#5967 Automated cherry pick of #5960: Fix panic when validating ResourceInterpreterWebhookConfiguration with unspecified service port
  pkg/webhook/configuration/validating.go
  pkg/webhook/configuration/validating_test.go
Labels: size/S, approved, lgtm

#5936 pkg/search/controllers_test: reduce the probability of flaky test cases by waiting for cache to sync
  pkg/search/controllers_test.go
Labels: approved, lgtm, size/M, kind/flake

#5969 Clarify interpreter webhook service discovery usage
  examples/customresourceinterpreter/README.md
Labels: approved, size/L, kind/documentation, lgtm

#5972 Fix the issue of missing workqueue metrics in the Karmada controller
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go
  vendor/k8s.io/apimachinery/pkg/api/meta/table/table.go
  vendor/k8s.io/apiserver/pkg/reconcilers/peer_endpoint_lease.go
  vendor/k8s.io/apiserver/pkg/util/proxy/doc.go
  vendor/k8s.io/apiserver/pkg/util/proxy/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/proxy/proxy.go
  vendor/k8s.io/apiserver/pkg/util/proxy/streamtranslator.go
  vendor/k8s.io/apiserver/pkg/util/proxy/streamtunnel.go
  vendor/k8s.io/apiserver/pkg/util/proxy/translatinghandler.go
  vendor/k8s.io/apiserver/pkg/util/proxy/websocket.go
  vendor/k8s.io/client-go/tools/portforward/OWNERS
  vendor/k8s.io/client-go/tools/portforward/doc.go
  vendor/k8s.io/client-go/tools/portforward/fallback_dialer.go
  vendor/k8s.io/client-go/tools/portforward/portforward.go
  vendor/k8s.io/client-go/tools/portforward/tunneling_connection.go
  vendor/k8s.io/client-go/tools/portforward/tunneling_dialer.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/install/install.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/validation/validation.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiservice_controller.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_apis.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/resolvers.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/scheme/scheme.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/cache.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/priority.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/local/local_available_controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/metrics/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/remote/remote_available_controller.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/etcd/OWNERS
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/etcd/etcd.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/rest/storage_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/strategy.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/walker.go
  vendor/k8s.io/kube-openapi/pkg/openapiconv/convert.go
  vendor/modules.txt
Labels: kind/bug, approved, size/XXL, lgtm

#5980 Automated cherry pick of #5972: fix the issue of missing workqueue metrics in the Karmada controller
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go
  vendor/k8s.io/apimachinery/pkg/api/meta/table/table.go
  vendor/k8s.io/apiserver/pkg/reconcilers/peer_endpoint_lease.go
  vendor/k8s.io/apiserver/pkg/util/proxy/doc.go
  vendor/k8s.io/apiserver/pkg/util/proxy/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/proxy/proxy.go
  vendor/k8s.io/apiserver/pkg/util/proxy/streamtranslator.go
  vendor/k8s.io/apiserver/pkg/util/proxy/streamtunnel.go
  vendor/k8s.io/apiserver/pkg/util/proxy/translatinghandler.go
  vendor/k8s.io/apiserver/pkg/util/proxy/websocket.go
  vendor/k8s.io/client-go/tools/portforward/OWNERS
  vendor/k8s.io/client-go/tools/portforward/doc.go
  vendor/k8s.io/client-go/tools/portforward/fallback_dialer.go
  vendor/k8s.io/client-go/tools/portforward/portforward.go
  vendor/k8s.io/client-go/tools/portforward/tunneling_connection.go
  vendor/k8s.io/client-go/tools/portforward/tunneling_dialer.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/install/install.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/validation/validation.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiservice_controller.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_apis.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/resolvers.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/scheme/scheme.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/cache.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/priority.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/local/local_available_controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/metrics/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/remote/remote_available_controller.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/etcd/OWNERS
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/etcd/etcd.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/rest/storage_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/strategy.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/walker.go
  vendor/k8s.io/kube-openapi/pkg/openapiconv/convert.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#5981 Automated cherry pick of #5972: fix the issue of missing workqueue metrics in the Karmada controller
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go
  vendor/k8s.io/apimachinery/pkg/api/meta/table/table.go
  vendor/k8s.io/apiserver/pkg/reconcilers/peer_endpoint_lease.go
  vendor/k8s.io/apiserver/pkg/util/proxy/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/proxy/proxy.go
  vendor/k8s.io/apiserver/pkg/util/proxy/streamtranslator.go
  vendor/k8s.io/apiserver/pkg/util/proxy/streamtunnel.go
  vendor/k8s.io/apiserver/pkg/util/proxy/translatinghandler.go
  vendor/k8s.io/apiserver/pkg/util/proxy/websocket.go
  vendor/k8s.io/client-go/tools/portforward/OWNERS
  vendor/k8s.io/client-go/tools/portforward/doc.go
  vendor/k8s.io/client-go/tools/portforward/fallback_dialer.go
  vendor/k8s.io/client-go/tools/portforward/portforward.go
  vendor/k8s.io/client-go/tools/portforward/tunneling_connection.go
  vendor/k8s.io/client-go/tools/portforward/tunneling_dialer.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/install/install.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/validation/validation.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiservice_controller.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_apis.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/resolvers.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/scheme/scheme.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/cache.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/priority.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/etcd/etcd.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/rest/storage_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/strategy.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/walker.go
  vendor/k8s.io/kube-openapi/pkg/openapiconv/convert.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#5983 Automated cherry pick of #5972: fix the issue of missing workqueue metrics in the Karmada controller
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go
  vendor/k8s.io/apimachinery/pkg/api/meta/table/table.go
  vendor/k8s.io/apiserver/pkg/reconcilers/peer_endpoint_lease.go
  vendor/k8s.io/apiserver/pkg/util/proxy/proxy.go
  vendor/k8s.io/apiserver/pkg/util/proxy/streamtranslator.go
  vendor/k8s.io/apiserver/pkg/util/proxy/translatinghandler.go
  vendor/k8s.io/apiserver/pkg/util/proxy/websocket.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/install/install.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/validation/validation.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/apiservice_controller.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_apis.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/resolvers.go
  vendor/k8s.io/kube-aggregator/pkg/apiserver/scheme/scheme.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/cache.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/priority.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/etcd/etcd.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/rest/storage_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/registry/apiservice/strategy.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
  vendor/k8s.io/kube-openapi/pkg/aggregator/walker.go
  vendor/k8s.io/kube-openapi/pkg/openapiconv/convert.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#5984 Fix verify license lint error
  hack/verify-license.sh
  operator/pkg/controller/karmada/validating_test.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go
  pkg/util/helper/index.go
  pkg/util/helper/index_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#5976 Fix ETCD PKI Provisioning Issue in Karmada Operator
  operator/pkg/certs/certs.go
  operator/pkg/init.go
  operator/pkg/tasks/init/cert.go
  operator/pkg/tasks/init/cert_test.go
  operator/pkg/tasks/init/upload.go
Labels: kind/bug, approved, lgtm, size/M

#5974 decouple suspension of propagation and resourcebinding
  api/openapi-spec/swagger.json
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/detector/detector.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, size/L, lgtm, kind/cleanup

#5989 fix rebalancer auto deleted failed
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
  test/e2e/workloadrebalancer_test.go
Labels: kind/bug, size/S, approved, lgtm

#5993 Automated cherry pick of #5989: fix rebalancer auto deleted failed
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
  test/e2e/workloadrebalancer_test.go
Labels: size/S, approved, lgtm

#5994 Automated cherry pick of #5989: fix rebalancer auto deleted failed
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
  test/e2e/workloadrebalancer_test.go
Labels: size/S, approved, lgtm

#5995 Automated cherry pick of #5989: fix rebalancer auto deleted failed
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
  test/e2e/workloadrebalancer_test.go
Labels: size/S, approved, lgtm

#5742 Added tests for pkg/util/helper/work.go
  pkg/util/helper/work_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5998 fix flake test with GetWorksByBindingID func
  pkg/util/helper/work_test.go
Labels: approved, lgtm, size/M, kind/flake
