Repository karmada-io/karmada, pull requests merged in 2024-10, with the labels that each got.

#5579 Add helm index for v1.10.0 and v1.11.0
  charts/index.yaml
  charts/karmada-operator/Chart.yaml
  charts/karmada/Chart.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#5568 Avoid treating PVC managed by VolumeClaimTemplate as dependencies
  pkg/resourceinterpreter/default/native/dependencies.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
Labels: kind/bug, approved, lgtm, size/M

#5556 fix: remove extra slash when constructing member cluster URL to adapt…
  pkg/registry/cluster/storage/aggregate.go
  pkg/registry/cluster/storage/aggregate_test.go
Labels: approved, lgtm, size/M

#5277 docs: add proposal of karmadactl init support config file
  docs/proposals/karmadactl/init-configuration-file.md
Labels: kind/feature, approved, size/XL, lgtm, kind/design, ok-to-test

#5530 skip interpret health of resources without a hook
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
Labels: approved, lgtm, size/M

#5591 feat: add fieldoverrider
  go.mod
  pkg/util/overridemanager/overridemanager.go
  pkg/util/overridemanager/overridemanager_test.go
  pkg/util/validation/validation.go
  pkg/webhook/overridepolicy/validating_test.go
  test/e2e/coverage_docs/overridepolicy_test.md
  test/e2e/overridepolicy_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5641 Added tests for pkg/scheduler/event_handler.go
  pkg/scheduler/event_handler_test.go
Labels: kind/feature, approved, size/L, lgtm

#5653 Added tests for pkg/descheduler/descheduler.go
  pkg/descheduler/descheduler_test.go
Labels: kind/feature, approved, size/L, lgtm

#5557 fix: remove extra slash when constructing member cluster URL to adapt…
  pkg/registry/cluster/storage/aggregate.go
  pkg/registry/cluster/storage/aggregate_test.go
Labels: approved, lgtm, size/M

#5642 Added tests for scheduler plugins
  pkg/scheduler/framework/plugins/apienablement/api_enablement_test.go
  pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity_test.go
  pkg/scheduler/framework/plugins/clustereviction/cluster_eviction_test.go
  pkg/scheduler/framework/plugins/clusterlocality/cluster_locality_test.go
  pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint_test.go
  pkg/scheduler/framework/plugins/tainttoleration/taint_toleration_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5542 pkg/webhook: unit test Interpreter
  pkg/webhook/interpreter/decode.go
  pkg/webhook/interpreter/decode_test.go
  pkg/webhook/interpreter/http_test.go
  pkg/webhook/interpreter/inject_test.go
  pkg/webhook/interpreter/response_test.go
  pkg/webhook/interpreter/webhook_test.go
Labels: approved, size/XXL, lgtm

#5630 operator/pkg: add test helpers
  operator/pkg/tasks/deinit/test_helpers.go
  operator/pkg/tasks/init/test_helpers.go
  operator/pkg/util/util.go
Labels: approved, size/L, lgtm, kind/cleanup

#5563 Clean up the residual annotations when resources are preempted by pp from cpp
  pkg/detector/claim.go
  pkg/detector/claim_test.go
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/detector/policy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#5319 skip cleanup when the poliy claim metadata changed
  pkg/detector/claim.go
  pkg/detector/claim_test.go
  pkg/detector/detector.go
Labels: kind/bug, approved, lgtm, size/M

#5661 operator/pkg/util: unit test endpoint
  operator/pkg/util/endpoint_test.go
Labels: approved, size/L, lgtm

#5637 Added tests for scheduler/cache
  pkg/scheduler/cache/cache_test.go
Labels: kind/feature, approved, size/L, lgtm

#5649 Added new tests and refractored old in pkg/descheduler/core
  pkg/descheduler/core/filter_test.go
  pkg/descheduler/core/helper_test.go
Labels: kind/feature, approved, size/L, lgtm

#5663 Added unit tests for FederatedHPA validation
  pkg/util/lifted/validatingfhpa_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#5667 operator/pkg/util: unit test template
  operator/pkg/util/template_test.go
Labels: approved, lgtm, size/M

#5666 operator/pkg/util: unit test naming
  operator/pkg/util/naming_test.go
Labels: approved, lgtm, size/M

#5670 Update file line terminators to LF
  .github/workflows/ci-image-scanning.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/desired-policy.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/observed-policy.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/status-file.yaml
Labels: approved, size/XL, lgtm, kind/cleanup

#5665 operator/pkg/util: unit test kubeconfig
  operator/pkg/util/kubeconfig.go
  operator/pkg/util/kubeconfig_test.go
Labels: approved, size/L, lgtm

#5646 Added tests pkg/scheduler/core/common.go
  pkg/scheduler/core/common_test.go
Labels: kind/feature, approved, size/L, lgtm

#5671 feat: validate fieldOverrider operation
  pkg/util/validation/validation.go
  pkg/webhook/overridepolicy/validating_test.go
Labels: kind/feature, approved, size/L, lgtm

#5644 Added tests for metrics and framework package of pkg/scheduler
  pkg/scheduler/framework/interface_test.go
  pkg/scheduler/framework/types_test.go
  pkg/scheduler/metrics/metrics_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5588 operator/pkg/controlplane: unit test karmada webhook
  operator/pkg/controlplane/webhook/webhook_test.go
Labels: approved, size/L, lgtm

#5590 operator/pkg/controlplane: unit test controlplane
  operator/pkg/controlplane/controlplane_test.go
Labels: approved, size/L, lgtm

#5624 operator/pkg/tasks: unit test apiserver
  operator/pkg/tasks/init/apiserver_test.go
  operator/pkg/util/apiclient/test_helpers.go
Labels: approved, size/XL, lgtm

#5643 operator/pkg/tasks/deinit: unit test cert
  operator/pkg/tasks/deinit/cert_test.go
Labels: approved, size/L, lgtm

#5686 Automated cherry pick of #5568: Avoid treating PVC managed by VolumeClaimTemplate as dependencies
  pkg/resourceinterpreter/default/native/dependencies.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
Labels: approved, lgtm, size/M

#5687 Automated cherry pick of #5568: Avoid treating PVC managed by VolumeClaimTemplate as dependencies
  pkg/resourceinterpreter/default/native/dependencies.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
Labels: approved, lgtm, size/M

#5688 Automated cherry pick of #5568: Avoid treating PVC managed by VolumeClaimTemplate as dependencies
  pkg/resourceinterpreter/default/native/dependencies.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
Labels: approved, lgtm, size/M

#5689 Update interface.go
  pkg/scheduler/framework/interface.go
Labels: approved, lgtm, size/XS

#5657 operator/pkg/tasks/init: unit test wait
  operator/pkg/tasks/init/wait.go
  operator/pkg/tasks/init/wait_test.go
Labels: approved, size/L, lgtm

#5684 Added tests for validateclustertaints.go and validatingmcs.go
  pkg/util/lifted/validateclustertaints_test.go
  pkg/util/lifted/validatingmcs_test.go
Labels: kind/feature, approved, size/L, lgtm

#5682 Added unit tests for pkg/util/lifted/podtemplate.go
  pkg/util/lifted/podtemplate_test.go
Labels: kind/feature, approved, size/L, lgtm

#5678 operator/pkg/tasks/deinit: unit test component
  operator/pkg/tasks/deinit/component.go
  operator/pkg/tasks/deinit/component_test.go
Labels: approved, size/L, lgtm

#5676 operator/pkg/tasks/deinit: unit test kubeconfig
  operator/pkg/tasks/deinit/kubeconfig_test.go
Labels: approved, size/L, lgtm

#5680 Added first part of unit tests for pkg/scheduler
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5698 Added tests for pkg/util/membercluster_client_test.go
  pkg/util/membercluster_client_test.go
Labels: kind/feature, approved, size/L, lgtm

#5695 Added first part of unit tests for pkg/util/lifted/corev1printers.go
  pkg/util/lifted/corev1printers_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5681 Added second part of unit tests for pkg/scheduler
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, approved, size/L, lgtm

#5652 operator/pkg/util: unit test patcher
  operator/pkg/util/patcher/pather_test.go
Labels: approved, size/XL, lgtm

#5560 operator/pkg/certs: mitigate potential null pointer dereference in AltNames Mutators for both the `APIServer` and `EtcdServer`
  operator/pkg/certs/certs.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5647 operator/pkg/workflow: unit test job
  operator/pkg/workflow/job_test.go
Labels: approved, size/L, lgtm

#5602 operator/pkg: depend on `aggregator.Interface` instead of `*aggregator.Clientset`
  operator/pkg/karmadaresource/apiservice/apiservice.go
  operator/pkg/util/apiclient/idempotency.go
  pkg/karmadactl/addons/init/global.go
  pkg/karmadactl/cmdinit/karmada/check.go
  pkg/karmadactl/util/apiclient/apiclient.go
  pkg/karmadactl/util/idempotency.go
  pkg/karmadactl/util/validate.go
Labels: size/S, approved, lgtm, kind/cleanup

#5659 operator/pkg/util/apiclient: unit test wait
  operator/pkg/util/apiclient/wait.go
  operator/pkg/util/apiclient/wait_test.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiservice.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#5587 operator/pkg/controlplane: unit test karmada search
  operator/pkg/controlplane/search/search_test.go
Labels: approved, size/L, lgtm

#5596 operator/pkg/karmadaresource/apiservice: unit test apiservice
  operator/pkg/karmadaresource/apiservice/apiservice_test.go
Labels: approved, size/L, lgtm

#5565 operator/pkg/controller/karmada: unit test Karmada controller
  operator/pkg/controller/karmada/planner_test.go
Labels: approved, size/L, lgtm

#5585 operator/pkg/controlplane: unit test Metrics Adapter
  operator/pkg/controlplane/metricsadapter/metricsadapter_test.go
Labels: approved, size/L, lgtm

#5603 operator/pkg/karmadaresource: unit test RBAC
  operator/pkg/karmadaresource/rbac/rbac_test.go
Labels: approved, size/L, lgtm

#5576 operator/pkg/controlplane: unit test apiserver
  operator/pkg/controlplane/apiserver/apiserver_test.go
Labels: approved, size/L, lgtm

#5583 operator/pkg/controlplane: unit test etcd
  operator/pkg/controlplane/etcd/etcd_test.go
Labels: approved, size/L, lgtm

#5705 publish release note for v1.12.0-alpha.1
  docs/CHANGELOG/CHANGELOG-1.12.md
Labels: approved, lgtm, size/M

#5708 update CHANGELOG.md to point to the changelog directory
  CHANGELOG.md
Labels: approved, kind/documentation, lgtm, size/XS

#5709 fix the error lstat /github/workspace: no such file or directory
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS

#5712 Fix InterpreterOperationAll description typo
  pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5707 chore: update image tags for Karmada components to v1.11.1
  operator/config/samples/karmada.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5561 operator/pkg/certs: validate X509 Cert key types and improve error handling
  operator/pkg/certs/certs.go
  pkg/karmadactl/cmdinit/cert/cert.go
Labels: approved, lgtm, size/M, kind/cleanup

#5472 karmada-scheduler-estimator add the support for custom DNS suffix
  pkg/estimator/client/cache.go
  pkg/estimator/client/service.go
  pkg/estimator/client/service_test.go
  pkg/util/grpcconnection/config.go
Labels: kind/feature, approved, lgtm, size/M

#5423 standardize the naming of karmada secrets in local up method
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/karmada-ca-cert-secret.yaml
  artifacts/deploy/karmada-cert-secret.yaml
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-etcd.yaml
  artifacts/deploy/karmada-key-pair-secret.yaml
  artifacts/deploy/karmada-metrics-adapter.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-search.yaml
  artifacts/deploy/karmada-webhook.yaml
  artifacts/deploy/kube-controller-manager.yaml
  examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml
  hack/deploy-karmada.sh
  hack/util.sh
Labels: approved, size/L, lgtm, kind/cleanup

#5699 External `etcd` Support for Karmada Operator - Part 1
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/constants/constants.go
  operator/pkg/controller/karmada/controller.go
Labels: kind/feature, approved, size/L, lgtm

#5710 chore(hack): upgrade Trivy to v0.56.1 for consistency with CI
  hack/scan-image-vuln.sh
Labels: approved, lgtm, size/XS

#5559 operator/pkg/certs: unit test Certificate Manager and Karmada Store
  operator/pkg/certs/certs_test.go
  operator/pkg/certs/store_test.go
  operator/pkg/util/util.go
Labels: approved, size/XL, lgtm

#5481 Added tests for cronfederatedhpa controller
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler_test.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_job_test.go
Labels: kind/feature, approved, size/XL, kind/documentation, lgtm, kind/failing-test

#5625 operator/pkg/tasks/init: unit test cert
  operator/pkg/tasks/init/cert.go
  operator/pkg/tasks/init/cert_test.go
Labels: approved, size/L, lgtm

#5636 operator/pkg/tasks/init: unit test rbac
  operator/pkg/tasks/init/rbac_test.go
Labels: approved, size/L, lgtm

#5716 operator/pkg/certs/store_test: fix flaky test `TestCertList`
  operator/pkg/certs/store_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#5662 hasResource should return whether resource is matched not cached
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/testing/mock_store.go
Labels: kind/bug, approved, size/L, lgtm

#5543 Added tests for graceful eviction controller
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller_test.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5706 Fixes incorrect resource model selection
  pkg/estimator/client/general.go
  pkg/estimator/client/general_test.go
Labels: kind/bug, approved, size/L, lgtm

#5700 Added second part of unit tests for pkg/util/lifted/corev1printers.go
  pkg/util/lifted/corev1printers_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5724 Automated cherry pick of #5685: add ResourceSummary deep copy in general-estimator
  pkg/estimator/client/general.go
Labels: approved, lgtm, size/XS

#5725 Automated cherry pick of #5685: add ResourceSummary deep copy in general-estimator
  pkg/estimator/client/general.go
Labels: approved, lgtm, size/XS

#5726 Automated cherry pick of #5685: add ResourceSummary deep copy in general-estimator
  pkg/estimator/client/general.go
Labels: approved, lgtm, size/XS

#5720 External `etcd` Support for Karmada Operator - Part 2
  operator/pkg/constants/constants.go
  operator/pkg/controller/karmada/controller.go
  operator/pkg/controller/karmada/planner_test.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/apiserver/apiserver_test.go
  operator/pkg/controlplane/apiserver/mainfests.go
  operator/pkg/controlplane/etcd/util.go
  operator/pkg/controlplane/search/mainfests.go
  operator/pkg/controlplane/search/search.go
  operator/pkg/controlplane/search/search_test.go
  operator/pkg/deinit.go
  operator/pkg/init.go
  operator/pkg/tasks/deinit/cert.go
  operator/pkg/tasks/deinit/cert_test.go
  operator/pkg/tasks/deinit/component.go
  operator/pkg/tasks/init/apiserver_test.go
  operator/pkg/tasks/init/component.go
Labels: kind/feature, approved, size/L, lgtm

#5735 Automated cherry pick of #5662: HasResource should return whether resource is registered not
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/testing/mock_store.go
Labels: approved, size/L, lgtm

#5736 Automated cherry pick of #5662: HasResource should return whether resource is registered not
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/testing/mock_store.go
Labels: approved, size/L, lgtm

#5737 Automated cherry pick of #5662: HasResource should return whether resource is registered not
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/multi_cluster_cache.go
  pkg/search/proxy/store/multi_cluster_cache_test.go
  pkg/search/proxy/testing/mock_store.go
Labels: approved, size/L, lgtm

#5717 Keep preserveResourcesOnDeletion of the dependent resource consistent with that of the primary resource
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: kind/feature, approved, lgtm, size/XS

#5739 add CA data to local up generated karmada config for enhanced security
  hack/deploy-karmada.sh
  hack/util.sh
Labels: kind/feature, size/S, approved, lgtm

#5728 Automated cherry pick of #5706: Fixes an issue where resource model grades were incorrectly
  pkg/estimator/client/general.go
  pkg/estimator/client/general_test.go
Labels: approved, size/L, lgtm

#5729 Automated cherry pick of #5706: Fixes an issue where resource model grades were incorrectly
  pkg/estimator/client/general.go
  pkg/estimator/client/general_test.go
Labels: approved, size/L, lgtm

#5519 add ci for karmada operator
  .github/workflows/operator.yaml
  hack/deploy-karmada-by-operator.sh
  hack/deploy-karmada-operator.sh
  hack/deploy-karmada.sh
  hack/local-up-karmada-by-operator.sh
  hack/util.sh
  operator/config/samples/karmada-sample.yaml
Labels: kind/feature, approved, size/XL, lgtm

#5733 Added tests for utility functions in the pkg/util
  pkg/util/context_test.go
  pkg/util/policy_test.go
  pkg/util/round_trippers_test.go
Labels: kind/feature, approved, size/L, lgtm

#5711 Added first part of unit tests for pkg/detector
  pkg/detector/detector_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#5704 operator/pkg/tasks/init: unit test crds
  operator/pkg/tasks/init/crd_test.go
Labels: approved, size/L, lgtm

#5357 Feature: karmadactl init supports deployment through configuration files
  .github/workflows/cli.yaml
  hack/verify-license.sh
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/config/config.go
  pkg/karmadactl/cmdinit/config/config_test.go
  pkg/karmadactl/cmdinit/config/types.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/meta.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm, ok-to-test

#5609 add e2e for migration rollback feature
  test/e2e/framework/work.go
  test/e2e/migration_and_rollback_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5621 Implement calc group score for divided to assign replicas evenly
  pkg/scheduler/core/spreadconstraint/group_clusters.go
Labels: kind/feature, approved, size/L, lgtm, ok-to-test

#5747 chore: unify karmada labels/annotations usage in execution controller and test
  pkg/controllers/execution/execution_controller.go
  pkg/util/constants.go
  test/e2e/migration_and_rollback_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#5740 fix operator file naming
  operator/pkg/controlplane/apiserver/manifests.go
  operator/pkg/controlplane/etcd/manifests.go
  operator/pkg/controlplane/metricsadapter/manifests.go
  operator/pkg/controlplane/search/manifests.go
  operator/pkg/controlplane/webhook/manifests.go
Labels: approved, lgtm, size/XS

#5626 support unregister cluster in karmada
  artifacts/deploy/bootstrap-token-configuration.yaml
  charts/karmada/templates/_karmada_bootstrap_token_configuration.tpl
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/unregister/unregister.go
  pkg/karmadactl/util/cluster.go
  pkg/util/secret.go
Labels: kind/feature, approved, size/XL, lgtm

#5675 operator/pkg: unit test utilities
  operator/pkg/util/util.go
  operator/pkg/util/util_test.go
Labels: approved, size/L, lgtm

#5622 Implement calc group score for duplicate to assign replicas evenly
  pkg/scheduler/core/spreadconstraint/group_clusters.go
Labels: kind/feature, approved, lgtm, size/M

#5306 Add GitHub tests for karmadactl init --config command
  .github/workflows/cli.yaml
  hack/cli-testing-init-with-config.sh
  pkg/karmadactl/cmdinit/config/config_test.go
  pkg/karmadactl/cmdinit/config/types.go
Labels: kind/feature, approved, size/L, lgtm, ok-to-test

#5620 Add unit test for group score calc to assign replicas evenly
  pkg/scheduler/core/spreadconstraint/group_clusters_test.go
Labels: kind/feature, approved, size/L, lgtm

#5594 cleanup: change *kubeclient.Clientset to kubeclient.Interface in unregister module
  pkg/karmadactl/unregister/unregister.go
  pkg/karmadactl/util/cluster.go
Labels: kind/feature, approved, lgtm, size/XS

#5628 add realted ut for unregister
  pkg/karmadactl/unregister/unregister.go
  pkg/karmadactl/unregister/unregister_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5629 minimize the rbac permissions for karmada-agent
  artifacts/deploy/bootstrap-token-configuration.yaml
Labels: kind/feature, approved, size/L, lgtm

#5751 Added unit tests for scheduler framework types
  pkg/util/lifted/scheduler/framework/types_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#5758 pkg/karmadactl/addons: unit test metrics adapter
  pkg/karmadactl/addons/init/global.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter_test.go
Labels: approved, size/L, lgtm

#5762 publish release notes for v1.12.0-beta.0
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, kind/documentation, lgtm
