Repository karmada-io/karmada, pull requests merged in 2024-03, with the labels that each got.

#4555 Optimize deprioritized policy preemption logic
  pkg/detector/preemption.go
  vendor/github.com/emirpasic/gods/lists/arraylist/arraylist.go
  vendor/github.com/emirpasic/gods/lists/arraylist/enumerable.go
  vendor/github.com/emirpasic/gods/lists/arraylist/iterator.go
  vendor/github.com/emirpasic/gods/lists/arraylist/serialization.go
  vendor/github.com/emirpasic/gods/lists/lists.go
  vendor/github.com/emirpasic/gods/queues/priorityqueue/iterator.go
  vendor/github.com/emirpasic/gods/queues/priorityqueue/priorityqueue.go
  vendor/github.com/emirpasic/gods/queues/priorityqueue/serialization.go
  vendor/github.com/emirpasic/gods/queues/queues.go
  vendor/github.com/emirpasic/gods/trees/binaryheap/binaryheap.go
  vendor/github.com/emirpasic/gods/trees/binaryheap/iterator.go
  vendor/github.com/emirpasic/gods/trees/binaryheap/serialization.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm, kind/cleanup

#4671 chore: publish helm `v1.9.0` version
  charts/index.yaml
Labels: kind/feature, size/S, approved, lgtm

#4676 Fix import alias for remedy
  hack/.import-aliases
Labels: approved, lgtm, size/XS, kind/cleanup

#4673 fix typo error for charts
  charts/karmada/README.md
Labels: size/S, approved, lgtm, kind/cleanup

#4675 Add remedy api in the swagger.json
  api/openapi-spec/swagger.json
  hack/tools/swagger/generateswagger.go
  hack/update-codegen.sh
  pkg/apis/remedy/v1alpha1/well_known_constants.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, approved, size/XXL, lgtm

#4651 Add proposal for remedy
  docs/proposals/remediation/cluster-status-based-remedy.md
Labels: approved, size/L, kind/documentation, lgtm, kind/design

#4674 fix: delete search-component failed
  operator/pkg/controlplane/search/mainfests.go
  operator/pkg/util/apiclient/idempotency.go
Labels: kind/bug, approved, lgtm, size/XS

#4679 operator: add extra annotations for service of karmada apiserver
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/controlplane/apiserver/apiserver.go
Labels: kind/feature, size/S, approved, lgtm

#4691 Update release badge to show latest release
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#4699 Add release notes of v1.6.6, v1.7.3, v1.8.2
  docs/CHANGELOG/CHANGELOG-1.6.md
  docs/CHANGELOG/CHANGELOG-1.7.md
  docs/CHANGELOG/CHANGELOG-1.8.md
Labels: approved, size/L, kind/documentation, lgtm

#4706 upgrade golang version to v1.21.8
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
  README.md
  go.mod
  go.sum
  hack/util.sh
Labels: approved, lgtm, size/M, kind/cleanup

#4707 sync deployment replicas when it is controlled by hpa
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller_test.go
  pkg/controllers/hpascaletargetmarker/hpa_scale_target_marker_controller.go
  pkg/controllers/hpascaletargetmarker/hpa_scale_target_marker_predicate.go
  pkg/controllers/hpascaletargetmarker/hpa_scale_target_marker_worker.go
  pkg/controllers/status/common.go
  test/e2e/deploymentreplicassyncer_test.go
  vendor/k8s.io/client-go/scale/fake/client.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XL, lgtm

#4686 Add UT for remedy util function and eventhandler
  pkg/controllers/remediation/eventhandlers_test.go
  pkg/controllers/remediation/remedy_controller.go
  pkg/controllers/remediation/util.go
  pkg/controllers/remediation/util_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/testing.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/unconventionallisttypecrd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/util.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#4722 fix typo for karmadactl cmdinit
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/rbac.go
Labels: size/S, approved, lgtm, kind/cleanup

#4716 add e2e test for deployment replicas syncer
  test/e2e/deploymentreplicassyncer_test.go
  test/e2e/framework/hpa.go
  test/helper/policy.go
Labels: approved, size/L, lgtm, kind/failing-test

#4717 Add more detail log for load karmada-host config and karmada-apiserver config.
  pkg/karmadactl/addons/init/global.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4726 Revert "add e2e test for deployment replicas syncer"
  test/e2e/deploymentreplicassyncer_test.go
  test/e2e/framework/hpa.go
  test/helper/policy.go
Labels: approved, size/L, lgtm, kind/flake

#4721 fix deployment replicas syncer in case deployment status changed before label added
  pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller.go
Labels: kind/bug, approved, lgtm, size/XS

#4733 chore: Update sigstore/cosign-installer to v3.4.0.
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4622 Add e2e test for lazy propogation policy: Policy created before resource
  test/e2e/lazy_activation_policy_test.go
  test/helper/policy.go
Labels: approved, lgtm, size/M, kind/cleanup

#4736 chore: bump cosigin to v2.2.3.
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4742 Update Kubernetes compatibility
  README.md
Labels: size/S, approved, lgtm, kind/cleanup

#4731 Fix replica interpreter err log format
  pkg/resourceinterpreter/default/native/replica.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4745 Automated cherry pick of #4733: chore: Update sigstore/cosign-installer to v3.4.0. #4736: chore: bump cosigin to v2.2.3.
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: approved, lgtm, size/XS

#4746 Automated cherry pick of #4733: chore: Update sigstore/cosign-installer to v3.4.0. #4736: chore: bump cosigin to v2.2.3.
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: approved, lgtm, size/XS

#4747 Automated cherry pick of #4733: chore: Update sigstore/cosign-installer to v3.4.0. #4736: chore: bump cosigin to v2.2.3.
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: approved, lgtm, size/XS

#4749 Add liangyuanpeng to approver for github workflows.
  .github/workflows/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#4718 Delete the labels of uid.
  pkg/apis/policy/v1alpha1/well_known_constants.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/binding/common.go
  pkg/detector/detector.go
  pkg/util/helper/work.go
  pkg/util/label.go
Labels: approved, lgtm, size/M, kind/cleanup

#4751 fix wrong annotation marks on resource
  pkg/detector/detector.go
  pkg/util/helper/work.go
Labels: kind/bug, approved, lgtm, size/XS

#4714 Add config for dependabot.
  .github/dependabot.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4737 Fix eps remain when karmada-controller-manager restart
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/util/constants.go
Labels: kind/bug, approved, size/L, lgtm

#4729 fix deployment replicas syncer in case that `status.replicas` haven't been collected from member cluster to template
  pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller.go
  pkg/resourceinterpreter/default/native/reflectstatus.go
Labels: kind/bug, approved, lgtm, size/M, kind/flake

#4765 Remove work label on the member cluster resource
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/bug, approved, lgtm, size/M

#4767 Stop krew update for release-1.7
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4768 Stop krew update for release-1.8
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4760 Replace engineerd/setup-kind with helm/kind-action
  .github/workflows/cli.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#4764 add e2e test for deployment replicas syncer
  test/e2e/deploymentreplicassyncer_test.go
  test/e2e/framework/hpa.go
  test/helper/policy.go
Labels: approved, size/L, lgtm, kind/failing-test

#4770 Automated cherry pick of #4751: fix wrong annotation marks on resource
  pkg/detector/detector.go
  pkg/util/helper/work.go
Labels: approved, lgtm, size/XS

#4771 Automated cherry pick of #4751: fix wrong annotation marks on resource
  pkg/detector/detector.go
  pkg/util/helper/work.go
Labels: approved, lgtm, size/XS

#4772 Automated cherry pick of #4751: fix wrong annotation marks on resource
  pkg/detector/detector.go
  pkg/util/helper/work.go
Labels: approved, lgtm, size/XS

#4774 fix bug of wrong delete endpointslice collect from member cluster
  pkg/controllers/mcs/service_export_controller.go
Labels: kind/bug, size/S, priority/important-soon, approved, lgtm

#4776 remove old MergeAnnotation func and rename ReplaceAnnotation to MergeAnnotation
  pkg/detector/detector.go
  pkg/util/annotation.go
  pkg/util/annotation_test.go
  pkg/util/helper/work.go
  pkg/util/label.go
Labels: approved, size/L, lgtm, kind/cleanup

#4777 Fixe invalid kubebuilder marker, that makes pinned plural name does not work.
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4778 Pin plural name for all APIs to avoid unexpected change
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
  pkg/apis/autoscaling/v1alpha1/cronfederatedhpa_types.go
  pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/service_types.go
  pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/remedy/v1alpha1/remedy_types.go
  pkg/apis/work/v1alpha1/binding_types.go
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha2/binding_types.go
Labels: approved, lgtm, size/M, kind/cleanup
