Repository karmada-io/karmada, pull requests merged in 2024-08, with the labels that each got.

#5283 optimize: used a unified context in cluster_controller reconcile
  pkg/controllers/cluster/cluster_controller.go
Labels: approved, lgtm, size/M, kind/cleanup

#5287 pkg: test `federatedresourcequota` webhook
  pkg/webhook/federatedresourcequota/validating_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5281 add karmada.io/system label to created clusterrole+bindings
  operator/pkg/karmadaresource/rbac/rbac.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/karmadactl/cmdinit/utils/rbac.go
  pkg/karmadactl/cmdinit/utils/rbac_test.go
Labels: kind/feature, approved, lgtm, size/M

#5293 cleanup: Remove redundant e2e testing steps
  test/e2e/karmadactl_test.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5244 test/e2e/karmadactl_test.go: test taint command
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4838 feat: cluster-level resource propagation pause and resume capabilities
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/execution/execution_controller_test.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/detector/detector.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/helper/work.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5299 cleanup: Print seconds to avoid unreadable minutes
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5304 add validation for failover api
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
Labels: size/S, approved, lgtm, kind/cleanup

#5079 Define top level Permission for cli.yml workflow
  .github/workflows/cli.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#5298 optimize: used unified context in controller
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/crb_application_failover_controller_test.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller_test.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/binding_controller_test.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/cluster_status_controller_test.go
  pkg/controllers/status/common.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/crb_status_controller_test.go
  pkg/controllers/status/rb_status_controller.go
  pkg/controllers/status/rb_status_controller_test.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller_test.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
  pkg/detector/preemption.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
  pkg/util/helper/mcs.go
  pkg/util/helper/mcs_test.go
  pkg/util/helper/work.go
  pkg/util/helper/workstatus.go
  pkg/util/objectwatcher/objectwatcher.go
  test/e2e/clusterresourcebinding_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#5068 Define top level Permission for ci-schedule-compatibility workflow
  .github/workflows/ci-schedule-compatibility.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#5078 Define top level Permission for ci.yml workflow
  .github/workflows/ci.yml
Labels: kind/feature, approved, lgtm, size/XS

#5282 work suspension: webhook validation
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: kind/feature, approved, lgtm, size/M

#5295 update left slice length in the resortAvailableClusters func
  pkg/scheduler/core/assignment.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5302 Add 100% unit test coverage for annotation and label in pkg/util
  pkg/util/annotation_test.go
  pkg/util/label_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5311 Align federated helmreleases.helm.toolkit.fluxcd.io observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/desired-helmrelease.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/observed-helmrelease.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/status-file.yaml
Labels: kind/feature, approved, size/L, lgtm

#5316 perf:make findFeasiblePaths faster
  pkg/scheduler/core/spreadconstraint/select_groups.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5324 repair the test for rb status controller
  pkg/controllers/status/crb_status_controller_test.go
  pkg/controllers/status/rb_status_controller_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#5185 Custom CRD Download Strategy Support for Karmada Operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/init.go
  operator/pkg/tasks/init/crd.go
  operator/pkg/tasks/init/data.go
  operator/pkg/tasks/init/karmadaresource.go
Labels: kind/api-change, approved, size/L, lgtm

#5317 work suspension: work status conditions
  pkg/apis/work/v1alpha1/work_types.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/execution/execution_controller_test.go
  pkg/util/helper/work.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: kind/feature, approved, size/L, lgtm

#5333 chore: remove duplicate imports
  pkg/registry/cluster/storage/aggregate.go
  pkg/util/lifted/validatingfhpa.go
  test/e2e/karmadactl_test.go
  test/e2e/mcs_test.go
Labels: size/S, approved, lgtm

#5310 Improve test coverage of pkg/controllers/context
  pkg/controllers/context/context_test.go
Labels: kind/feature, approved, lgtm, kind/failing-test, size/M

#5331 Add unit tests for common.go in pkg/util
  pkg/util/common_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5178 chore: add slsa provenance to release assets
  .github/workflows/release.yml
Labels: kind/feature, approved, size/L, lgtm

#5336 test/e2e: unfiy random string length generation
  test/e2e/federatedresourcequota_test.go
  test/e2e/karmadactl_test.go
  test/e2e/namespace_test.go
  test/e2e/rescheduling_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#5141 Fix test for corev1.LoadBalancerIngress,add IP model to VIP when ip is setting.
  test/e2e/resource_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#5332 work suspension: emit event for work dispatch status
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/execution/execution_controller_test.go
  pkg/events/events.go
  pkg/util/lifted/corev1printers.go
  pkg/util/lifted/scheduler/cache/cache.go
  pkg/util/lifted/validatingfhpa.go
  test/e2e/framework/events.go
  test/e2e/propagationpolicy_test.go
  test/helper/resource.go
Labels: kind/feature, approved, size/L, lgtm

#5342 Improve test coverage for /pkg/controllers/binding
  pkg/controllers/binding/binding_controller_test.go
  pkg/controllers/binding/cluster_resource_binding_controller_test.go
Labels: approved, size/XL, lgtm, kind/failing-test

#5343 Added unit test cluster_condition coverage : 100%
  pkg/controllers/status/cluster_condition_cache_test.go
Labels: kind/feature, approved, lgtm, kind/failing-test, size/M

#5338 Added new test cases and improved test coverage of pkg/util/eventfilter
  pkg/util/eventfilter/eventfilter_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5346 Add test coverage for revisereplica and retain in pkg/resourceinterpr…
  pkg/resourceinterpreter/default/native/retain_test.go
  pkg/resourceinterpreter/default/native/revisereplica_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5356 Automated cherry pick of #5141: Fix test for corev1.LoadBalancerIngress,add IP model to VIP
  test/e2e/resource_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#5258 flake test: daemonSet status collection testing failed
  test/e2e/resource_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#5339 Add 100% test coverage for matcher, shadow, and names.go in pkg/util
  pkg/util/interpreter/matcher_test.go
  pkg/util/names/names_test.go
  pkg/util/overridemanager/shadow_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5335 Bump golang version to 1.22.6 to address security warnings
  .go-version
  README.md
  go.mod
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#5358 Improved test coverage for replica in pkg/resourceinterpreter
  pkg/resourceinterpreter/default/native/replica_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5360 use single source for go version
  .github/workflows/ci-image-scanning.yaml
  .github/workflows/dockerhub-latest-chart.yml
  .github/workflows/dockerhub-released-chart.yml
  .github/workflows/lint-chart.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5364 Improve test coverage of pkg/descheduler
  pkg/descheduler/core/filter_test.go
  pkg/descheduler/core/helper_test.go
  pkg/descheduler/descheduler_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5245 docs: add proposal of enhancing karmadactl
  docs/proposals/karmadactl/enhance_karmadactl_maintenance_experience.md
Labels: kind/feature, approved, size/L, lgtm

#5370 Automated cherry pick of #5360: use single source for go version
  .github/workflows/ci-image-scanning.yaml
  .github/workflows/dockerhub-latest-chart.yml
  .github/workflows/dockerhub-released-chart.yml
  .github/workflows/lint-chart.yaml
Labels: size/S, approved, lgtm

#5371 Bump golang version to 1.21.13 to address security warnings
  .go-version
  go.mod
Labels: approved, lgtm, size/XS, kind/cleanup

#5362 charts/karmada: remove duplicate app label config in scheduler-estimator
  .github/workflows/lint-chart.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#5374 Bump golang version to v1.20.14
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#5354 e2e for work suspension resume
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: kind/feature, approved, size/L, lgtm

#5376 fix: allow suspended work to get deleted
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/execution/execution_controller_test.go
Labels: kind/feature, approved, lgtm, size/M

#5382 fix pdb collection testing occasional failure
  test/e2e/resource_test.go
  test/helper/resource.go
Labels: size/S, approved, lgtm, kind/failing-test

#5318 fix expected patch operations may be missed when AggregateStatus
  pkg/controllers/status/common.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/rb_status_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/util/helper/patch.go
  pkg/util/helper/patch_test.go
  pkg/util/helper/workstatus.go
  pkg/util/helper/workstatus_test.go
Labels: kind/bug, approved, size/XL, lgtm

#5383 chore: remove e2e tests for delete when suspended
  test/e2e/propagationpolicy_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#5373 Add release notes of v1.8.7, v1.9.6, v1.10.4
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.8.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, kind/documentation, lgtm

#5389 Add note about local-down-karmada.sh script to hack README
  hack/README.md
Labels: approved, kind/documentation, lgtm, size/XS, ok-to-test

#5372 Improved test coverage for default.go and other related files in pkg/resourceinterpreter
  pkg/resourceinterpreter/default/native/aggregatestatus_test.go
  pkg/resourceinterpreter/default/native/default_test.go
  pkg/resourceinterpreter/default/native/dependencies_test.go
  pkg/resourceinterpreter/default/native/healthy_test.go
  pkg/resourceinterpreter/default/native/replica_test.go
  pkg/resourceinterpreter/default/native/retain_test.go
  pkg/resourceinterpreter/default/native/revisereplica_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5254 Enhance the capabilities of the karmadactl get command
  pkg/karmadactl/get/get.go
  pkg/karmadactl/options/global.go
  test/e2e/karmadactl_test.go
Labels: kind/feature, approved, size/L, lgtm

#5369 charts/karmada: ignore the static-resource Pod in the post-install check
  charts/karmada/templates/post-install-job.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#5385 add some corner case description for dispath suspension proposal
  docs/proposals/dispatch-suspension/README.md
Labels: size/S, approved, kind/documentation, lgtm, kind/design

#4824 chore: remove unuse ghaction step and collect logs of karmadactl test.
  .github/workflows/cli.yaml
  hack/cli-testing-environment.sh
Labels: approved, lgtm, size/M, kind/cleanup

#5392 enhance karmadactl describe command
  pkg/karmadactl/describe/describe.go
  test/e2e/karmadactl_test.go
Labels: kind/feature, approved, size/L, lgtm

#5227 fix the error of cluster status old condition update will overwrite the newest condition
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/cluster_status_controller_test.go
Labels: kind/bug, approved, lgtm, kind/failing-test, size/M

#5398 enhance karmadactl exec command
  pkg/karmadactl/exec/exec.go
  test/e2e/karmadactl_test.go
Labels: kind/feature, approved, lgtm, size/M

#5379 charts/karmada: support custom cluster service CIDR
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, lgtm, size/XS

#5367 a quick fix of ca.crt not found in helm installation
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
Labels: kind/bug, approved, lgtm, size/XS

#5368 Added test for namespace controller
  pkg/controllers/namespace/namespace_sync_controller_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test, ok-to-test

#5390 Improved test coverage for handler in pkg/detector
  pkg/detector/handler_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5250 test/e2e/karmadactl_test.go: test apply command
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5274 Add some tests for `pkg/scheduler`
  pkg/scheduler/scheduler_test.go
Labels: approved, size/L, lgtm, kind/flake

#5388 Added tests in pkg/binding for condition coverage
  pkg/controllers/binding/common_test.go
Labels: kind/feature, approved, size/L, lgtm

#5409 Improved test coverage for policy in pkg/detector
  pkg/detector/policy_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5408 Added tests for pkg/servicenameresolutiondetector
  pkg/servicenameresolutiondetector/coredns/detector_test.go
  pkg/servicenameresolutiondetector/store/condition_cache_test.go
  pkg/servicenameresolutiondetector/store/node_store_test.go
Labels: kind/feature, approved, size/XXL, lgtm, kind/failing-test

#5403 fix: work status sync when work dispatching is suspended
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
Labels: kind/bug, kind/feature, approved, lgtm, size/M

#4545 e2e: add a test case when the GracePeriodSeconds is reach out
  test/e2e/coverage_docs/failover_test.md
  test/e2e/failover_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#5421 Improved test coverage for dependencies_distributor in pkg/dependenciesdistributor
  pkg/dependenciesdistributor/dependencies_distributor_test.go
Labels: kind/feature, approved, size/XXL, lgtm, kind/failing-test, ok-to-test

#5420 Added tests for operator/pkg/controller/context
  operator/pkg/controller/context/context_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#4224 karmadactl supports top node
  pkg/karmadactl/top/metrics_printer.go
  pkg/karmadactl/top/metrics_sorter.go
  pkg/karmadactl/top/top.go
  pkg/karmadactl/top/top_node.go
Labels: kind/feature, approved, size/L, lgtm

#5399 add new command karmadactl create
  pkg/karmadactl/create/create.go
  pkg/karmadactl/karmadactl.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_clusterrole.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_clusterrolebinding.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_configmap.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_cronjob.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_deployment.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_ingress.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_namespace.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_pdb.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_priorityclass.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_quota.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_role.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_rolebinding.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_secret.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_secret_docker.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_secret_tls.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_service.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_serviceaccount.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_token.go
  vendor/k8s.io/kubectl/pkg/generate/generate.go
  vendor/k8s.io/kubectl/pkg/util/hash/hash.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#5366 Added tests pkg/util/fedinformer
  pkg/util/fedinformer/handlers_test.go
  pkg/util/fedinformer/keys/keys_test.go
  pkg/util/fedinformer/typedmanager/multi-cluster-manager_test.go
  pkg/util/fedinformer/typedmanager/single-cluster-manager_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5416 Improved test coverage for policy in pkg/detector
  pkg/detector/policy_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5395 add new command karmadactl attach
  pkg/karmadactl/attach/attach.go
  pkg/karmadactl/karmadactl.go
  vendor/k8s.io/kubectl/pkg/cmd/attach/attach.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm

#5394 add new command karmadactl api-resources
  pkg/karmadactl/apiresources/apiresources.go
  pkg/karmadactl/apiresources/apiversions.go
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, approved, size/L, lgtm

#5378 charts/karmada: fix the creation condition of metrics-adapter related APIService
  charts/karmada/templates/_karmada_apiservice.tpl
Labels: kind/bug, approved, lgtm, size/XS

#5393 add new command karmadactl explain
  pkg/karmadactl/explain/explain.go
  pkg/karmadactl/karmadactl.go
  vendor/k8s.io/kubectl/pkg/cmd/explain/explain.go
  vendor/k8s.io/kubectl/pkg/explain/OWNERS
  vendor/k8s.io/kubectl/pkg/explain/explain.go
  vendor/k8s.io/kubectl/pkg/explain/field_lookup.go
  vendor/k8s.io/kubectl/pkg/explain/fields_printer.go
  vendor/k8s.io/kubectl/pkg/explain/fields_printer_builder.go
  vendor/k8s.io/kubectl/pkg/explain/formatter.go
  vendor/k8s.io/kubectl/pkg/explain/model_printer.go
  vendor/k8s.io/kubectl/pkg/explain/recursive_fields_printer.go
  vendor/k8s.io/kubectl/pkg/explain/test-recursive-swagger.json
  vendor/k8s.io/kubectl/pkg/explain/test-swagger.json
  vendor/k8s.io/kubectl/pkg/explain/typename.go
  vendor/k8s.io/kubectl/pkg/explain/v2/explain.go
  vendor/k8s.io/kubectl/pkg/explain/v2/funcs.go
  vendor/k8s.io/kubectl/pkg/explain/v2/generator.go
  vendor/k8s.io/kubectl/pkg/explain/v2/template.go
  vendor/k8s.io/kubectl/pkg/explain/v2/templates/plaintext.tmpl
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#5413 Improved test coverage for preemption in pkg/detector
  pkg/detector/preemption_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5431 add new command delete
  pkg/karmadactl/delete/delete.go
  pkg/karmadactl/karmadactl.go
Labels: kind/feature, approved, lgtm, size/M

#5273 Standardize the health probe and metrics arguments of scheduler-estimator
  artifacts/deploy/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  cmd/scheduler-estimator/app/options/options.go
  cmd/scheduler-estimator/app/options/validation.go
  cmd/scheduler-estimator/app/options/validation_test.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  pkg/karmadactl/addons/estimator/manifests.go
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: kind/feature, approved, size/L, lgtm, kind/cleanup, ok-to-test, kind/deprecation

#5412 Added UTs for proxy file 80% coverage
  pkg/registry/search/storage/proxy_test.go
Labels: kind/feature, approved, size/L, lgtm

#5427 Added tests for service file in pkg/estimator/client
  pkg/estimator/client/service_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5435 Standardize the health probe and metrics arguments of descheduler
  artifacts/deploy/karmada-descheduler.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  cmd/descheduler/app/descheduler.go
  cmd/descheduler/app/options/options.go
  cmd/descheduler/app/options/validation.go
  cmd/descheduler/app/options/validation_test.go
  operator/pkg/controlplane/manifests.go
  pkg/karmadactl/addons/descheduler/manifests.go
Labels: kind/feature, approved, size/L, lgtm, kind/cleanup, kind/deprecation

#5290 Standardize the health probe argument of karmada-controller-manager
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/validation.go
  cmd/controller-manager/app/options/validation_test.go
  operator/pkg/controlplane/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/feature, approved, lgtm, size/M, kind/cleanup, ok-to-test, kind/deprecation

#5434 add new command edit
  pkg/karmadactl/edit/edit.go
  pkg/karmadactl/karmadactl.go
  vendor/k8s.io/kubectl/pkg/cmd/edit/edit.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm

#5437 Standardize the health probe and metrics arguments of scheduler.
  artifacts/deploy/karmada-scheduler.yaml
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/validation.go
  cmd/scheduler/app/options/validation_test.go
  cmd/scheduler/app/scheduler.go
  operator/pkg/controlplane/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/feature, approved, size/L, lgtm, kind/cleanup, kind/deprecation

#5305 fix controller can't restart in helm for dependent secret not found
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-metrics-adapter.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/templates/karmada-static-resource-job.yaml
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
Labels: kind/bug, approved, lgtm, size/M

#5433 Added tests for examples/customresourceinterpreter/webhook
  examples/customresourceinterpreter/webhook/app/webhook_test.go
  examples/customresourceinterpreter/webhook/app/workloadwebhook_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5381 Improve test coverage for /pkg/controllers/certificate, with a minor optimization
  pkg/controllers/certificate/cert_rotation_controller.go
  pkg/controllers/certificate/cert_rotation_controller_test.go
Labels: approved, size/L, lgtm, kind/failing-test, kind/cleanup

#5444 skip descheduling ResourceBinding which is being deleted
  pkg/descheduler/descheduler.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5442 charts/karmada: automatically clean up the static-resource Job after it completes
  charts/karmada/templates/karmada-static-resource-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/values.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5452 enhance top pod command
  pkg/karmadactl/top/top_pods.go
  test/e2e/karmadactl_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#5432 fix: remove extra slash when constructing member cluster URL if the apiEndpoint of the cluster object ends with a slash
  pkg/registry/cluster/storage/aggregate.go
  pkg/registry/cluster/storage/aggregate_test.go
Labels: kind/bug, approved, lgtm, size/M

#5445 Added tests for cmd/descheduler
  cmd/descheduler/app/descheduler_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5454 Fix spelling errors
  charts/karmada/README.md
  cmd/scheduler-estimator/app/options/options.go
  docs/proposals/cleanup-propagated-resources/README.md
  docs/proposals/scheduling/policy-preemption/README.md
  docs/proposals/scheduling/workload-rebalancer/workload-rebalancer.md
  docs/proposals/service-discovery/README.md
  pkg/controllers/hpascaletargetmarker/hpa_scale_target_marker_controller.go
  pkg/karmadactl/edit/edit.go
  pkg/karmadactl/options/global.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go
  pkg/resourceinterpreter/default/native/retain_test.go
  test/e2e/framework/resourcebinding.go
  test/e2e/framework/workloadrebalancer.go
Labels: approved, lgtm, size/M, kind/cleanup

#5453 add new command label
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/label/label.go
  vendor/k8s.io/kubectl/pkg/cmd/label/label.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XL, lgtm

#5458 add new command annotate
  pkg/karmadactl/annotate/annotate.go
  pkg/karmadactl/karmadactl.go
  vendor/k8s.io/kubectl/pkg/cmd/annotate/annotate.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XL, lgtm

#5447 Improved test coverage for dependencies_distributor in pkg/dependenciesdistributor
  pkg/dependenciesdistributor/dependencies_distributor_test.go
Labels: kind/feature, approved, size/XXL, lgtm, kind/failing-test

#5463 add new command patch
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/patch/patch.go
  vendor/k8s.io/kubectl/pkg/cmd/patch/patch.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm

#5428 Expose metrics port for local-up installation
  artifacts/agent/karmada-agent.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-webhook.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5465 Expose metrics port for operator installation
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/webhook/mainfests.go
Labels: size/S, approved, lgtm, kind/cleanup

#5224 Only update krew index for latest stable version.
  .github/workflows/release.yml
Labels: size/S, approved, lgtm, kind/cleanup

#5029 Remove pp/cpp name length limit
  pkg/util/validation/validation.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: kind/feature, approved, size/L, lgtm

#5468 add new release note for v1.11
  docs/CHANGELOG/CHANGELOG-1.11.md
Labels: approved, size/L, kind/documentation, lgtm
