Repository karmada-io/karmada, pull requests merged in 2024-06, with the labels that each got.

#5013 Add release notes of v1.7.5, v1.8.4, v1.9.2
  docs/CHANGELOG/CHANGELOG-1.7.md
  docs/CHANGELOG/CHANGELOG-1.8.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, kind/documentation, lgtm

#5017 Stop krew update for release-1.9
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4998 fix demo for dependencyInterpretation
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/interpreter/rule.go
  pkg/util/interpreter/rule_test.go
  pkg/webhook/resourceinterpretercustomization/helper_test.go
Labels: approved, kind/documentation, lgtm, size/M, kind/cleanup

#5012 Account for unschedulable plugin result during maxreplica estimation
  pkg/estimator/server/estimate.go
  pkg/estimator/server/framework/interface.go
  pkg/estimator/server/framework/runtime/framework.go
  pkg/estimator/server/framework/runtime/framework_test.go
  pkg/scheduler/core/util.go
Labels: kind/bug, size/S, approved, lgtm

#5007 Add e2e for remedy
  test/e2e/framework/resource/karmada/remedy.go
  test/e2e/remedy_test.go
  test/e2e/suite_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#5020 Remove pp/cpp namespace/name labels
  pkg/apis/policy/v1alpha1/well_known_constants.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/detector/detector.go
  pkg/detector/policy.go
Labels: approved, lgtm, size/M, kind/cleanup

#5015 update to go 1.22
  .go-version
  README.md
  go.mod
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#5022 Add OSSF scorecard badges
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#4986 Integrate UpdateStatus function
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/remediation/remedy_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/util/helper/status.go
  pkg/util/helper/workstatus.go
Labels: kind/feature, approved, size/L, lgtm

#5026 Automated cherry pick of #5012: Account for unschedulable plugin result during maxreplica
  pkg/estimator/server/estimate.go
  pkg/estimator/server/framework/interface.go
  pkg/estimator/server/framework/runtime/framework.go
  pkg/estimator/server/framework/runtime/framework_test.go
  pkg/scheduler/core/util.go
Labels: size/S, approved, lgtm

#5027 Automated cherry pick of #5012: Account for unschedulable plugin result during maxreplica
  pkg/estimator/server/estimate.go
  pkg/estimator/server/framework/interface.go
  pkg/estimator/server/framework/runtime/framework.go
  pkg/estimator/server/framework/runtime/framework_test.go
  pkg/scheduler/core/util.go
Labels: size/S, approved, lgtm

#5039 Fix typo on concepts picture
  docs/images/karmada-resource-relation.png
Labels: approved, lgtm, size/XS, kind/cleanup

#5010 helm install karmada components in order
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-metrics-adapter.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/templates/karmada-static-resource-job.yaml
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, size/L, lgtm, kind/flake

#5030 fixes an issue where the cluster-status-controller overwrites the remedyActions field
  pkg/controllers/remediation/remedy_controller.go
  pkg/controllers/status/cluster_status_controller.go
  test/e2e/remedy_test.go
Labels: kind/bug, approved, lgtm, size/M, kind/cleanup

#5043 Automated cherry pick of #5030: fix-remedy-e2e-errors
  pkg/controllers/remediation/remedy_controller.go
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/XS

#5045 Automated cherry pick of #5030: fix-remedy-e2e-errors
  pkg/controllers/remediation/remedy_controller.go
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/XS

#5047 update ADOPTERS.md
  ADOPTERS.md
Labels: approved, kind/documentation, lgtm, size/XS

#5044 fix code inspection errors
  hack/tools/genkarmadactldocs/gen_karmadactl_docs.go
  pkg/controllers/federatedhpa/metrics/client.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/search/proxy/framework/plugins/cluster/cluster.go
  pkg/util/hash/hash.go
  pkg/util/lifted/validatingmcs.go
  pkg/util/proxy/upgrader.go
  test/e2e/framework/karmadactl.go
Labels: approved, lgtm, size/M, kind/cleanup

#5049 Add release notes of v1.9.3，v1.10.1
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, kind/documentation, lgtm, size/M

#5033 Add combined case 3 in the lazy activation policy tests
  test/e2e/lazy_activation_policy_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#5050 [License]Add foaas badge in README.md
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#4867 Align federated Deployment's observedGeneration semantics with its native
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/binding/common.go
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/resourceinterpreter/default/native/reflectstatus.go
  pkg/resourceinterpreter/default/native/status_type.go
Labels: kind/feature, approved, size/L, lgtm

#5051 Add Artifact HUB badge
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#5055 Modify OpenSSF Scorecard badge
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#5042 add work namespace/name annotations in the endpointslice resources
  pkg/controllers/mcs/endpointslice_controller.go
Labels: kind/feature, approved, lgtm, size/XS

#5054 Add CLOMonitor badge
  README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#4899 chore: let kube version of artifaces/deploy/karmada-apiserver versionsupport configuration.
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  hack/deploy-karmada.sh
Labels: size/S, approved, lgtm, kind/cleanup

#5065 Update karmada-apiserve and kube-controller-manager to v1.28.9 by default.
  charts/karmada/README.md
  charts/karmada/values.yaml
  hack/deploy-karmada.sh
  operator/README.md
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: size/S, approved, lgtm, kind/cleanup

#5016 add --as-* options to join command
  pkg/karmadactl/join/join.go
Labels: kind/feature, size/S, approved, lgtm, tide/merge-method-squash

#5040 Adding TLS Certificate Authentication to gRPC
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  cmd/descheduler/app/options/options.go
  cmd/scheduler-estimator/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  operator/pkg/controlplane/manifests.go
  pkg/descheduler/descheduler.go
  pkg/estimator/client/cache.go
  pkg/estimator/client/service.go
  pkg/estimator/server/server.go
  pkg/karmadactl/addons/descheduler/manifests.go
  pkg/karmadactl/addons/estimator/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/dial.go
  pkg/util/grpcconnection/config.go
Labels: kind/feature, approved, size/L, lgtm

#5083 Update ci 1.10
  .github/dependabot.yml
  .github/workflows/ci-schedule-compatibility.yaml
Labels: approved, lgtm, size/XS, kind/cleanup, tide/merge-method-squash

#5084 Align federated Kustomization's observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/desired-kustomization.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/observed-kustomization.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/status-file.yaml
Labels: kind/feature, approved, lgtm, size/M

#5099 rename host-as-* to karmada-as-*
  pkg/karmadactl/join/join.go
Labels: approved, lgtm, size/M, kind/cleanup

#5095 Fix the bug in interpreting the replicas of Job
  pkg/resourceinterpreter/default/native/replica.go
Labels: kind/bug, approved, lgtm, size/XS

#5108 Automated cherry pick of #5095: Fix the bug in interpreting the replicas of Job
  pkg/resourceinterpreter/default/native/replica.go
Labels: approved, lgtm, size/XS

#5106 Automated cherry pick of #5095: Fix the bug in interpreting the replicas of Job
  pkg/resourceinterpreter/default/native/replica.go
Labels: approved, lgtm, size/XS

#5107 Automated cherry pick of #5095: Fix the bug in interpreting the replicas of Job
  pkg/resourceinterpreter/default/native/replica.go
Labels: approved, lgtm, size/XS

#5100 silence the 'log.SetLogger(...) was never called' error
  cmd/agent/main.go
  operator/cmd/operator/operator.go
Labels: size/S, approved, lgtm, kind/cleanup

#5109 fix update cluster conflict error in the remedy e2e test
  test/e2e/framework/cluster.go
  test/e2e/remedy_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#5053 fix: fix the problem that local-up pull cluster cann't be managed by control plan in macos device
  artifacts/kindClusterConfig/member3.yaml
  hack/local-up-karmada.sh
Labels: kind/bug, size/S, approved, lgtm

#5094 Align federated StatefulSet's observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/desired-statefulset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/observed-statefulset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/status-file.yaml
Labels: kind/feature, approved, size/L, lgtm
