Repository karmada-io/karmada, pull requests merged in 2024-09, with the labels that each got.

#5459 Added tests for cmd/scheduler
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/scheduler_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5402 Automated cherry pick of #5227: fix error of when cluster status condition update
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/cluster_status_controller_test.go
Labels: approved, lgtm, size/M

#5401 Automated cherry pick of #5227: fix error of when cluster status condition update
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/cluster_status_controller_test.go
Labels: approved, lgtm, size/M

#5469 ci: add github token for update-krew-index
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#5473 Automated cherry pick of #5469: ci: add github token for update-krew-index
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS

#5474 chore: remove redundancy certificate configuration
  artifacts/deploy/karmada-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  operator/pkg/controlplane/apiserver/mainfests.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: size/S, approved, lgtm, kind/cleanup

#5476 add commandGroup annotation to ctl command
  hack/tools/genkarmadactldocs/gen_karmadactl_docs.go
  pkg/karmadactl/annotate/annotate.go
  pkg/karmadactl/apiresources/apiresources.go
  pkg/karmadactl/apiresources/apiversions.go
  pkg/karmadactl/attach/attach.go
  pkg/karmadactl/create/create.go
  pkg/karmadactl/delete/delete.go
  pkg/karmadactl/edit/edit.go
  pkg/karmadactl/explain/explain.go
  pkg/karmadactl/label/label.go
  pkg/karmadactl/patch/patch.go
  pkg/karmadactl/top/top.go
  pkg/karmadactl/util/command_group.go
Labels: approved, lgtm, size/M, kind/cleanup

#5483 feat: Added 's' shorthand to operation-scope flags
  pkg/karmadactl/apiresources/apiresources.go
  pkg/karmadactl/apiresources/apiversions.go
  pkg/karmadactl/attach/attach.go
  pkg/karmadactl/describe/describe.go
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/explain/explain.go
  pkg/karmadactl/get/get.go
Labels: kind/feature, size/S, approved, lgtm

#5430 fix: aggregate apiserver http method to get
  pkg/registry/cluster/storage/aggregate.go
Labels: kind/bug, approved, lgtm, size/XS

#5504 Stop updating images for release-1.8 and adding release-1.11
  .github/dependabot.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#5321 Support multiple label selection ability in EtcdNodeSelectorLabels
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset_test.go
Labels: kind/feature, approved, lgtm, size/M, ok-to-test

#5487 fix: command create cannot specify the namespace
  pkg/karmadactl/annotate/annotate.go
  pkg/karmadactl/apiresources/apiresources.go
  pkg/karmadactl/apiresources/apiversions.go
  pkg/karmadactl/apply/apply.go
  pkg/karmadactl/attach/attach.go
  pkg/karmadactl/create/create.go
  pkg/karmadactl/delete/delete.go
  pkg/karmadactl/describe/describe.go
  pkg/karmadactl/edit/edit.go
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/explain/explain.go
  pkg/karmadactl/get/get.go
  pkg/karmadactl/label/label.go
  pkg/karmadactl/logs/logs.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/patch/patch.go
  pkg/karmadactl/promote/promote.go
  pkg/karmadactl/top/top_node.go
  pkg/karmadactl/top/top_pods.go
Labels: kind/bug, approved, lgtm, size/M

#5499 pkg/webhook: unit test resource deletion protection
  pkg/webhook/resourcedeletionprotection/validating_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5492 pkg/webhook: unit test propagation policy
  pkg/webhook/propagationpolicy/mutating_test.go
  pkg/webhook/propagationpolicy/validating_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5513 Automated cherry pick of #5487: fix: command create cannot specify the namespace
  pkg/karmadactl/annotate/annotate.go
  pkg/karmadactl/apiresources/apiresources.go
  pkg/karmadactl/apiresources/apiversions.go
  pkg/karmadactl/apply/apply.go
  pkg/karmadactl/attach/attach.go
  pkg/karmadactl/create/create.go
  pkg/karmadactl/delete/delete.go
  pkg/karmadactl/describe/describe.go
  pkg/karmadactl/edit/edit.go
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/explain/explain.go
  pkg/karmadactl/get/get.go
  pkg/karmadactl/label/label.go
  pkg/karmadactl/logs/logs.go
  pkg/karmadactl/options/global.go
  pkg/karmadactl/patch/patch.go
  pkg/karmadactl/promote/promote.go
  pkg/karmadactl/top/top_node.go
  pkg/karmadactl/top/top_pods.go
Labels: approved, lgtm, size/M

#5478 Add the Ability to Specify the Namespace Used for Discovering Scheduler Estimator Services
  cmd/descheduler/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/scheduler.go
  pkg/descheduler/descheduler.go
  pkg/estimator/client/cache.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, approved, size/L, lgtm

#5515 Update karmada-apiserve and kube-controller-manager to v1.30.4 by default.
  charts/karmada/README.md
  charts/karmada/values.yaml
  hack/deploy-karmada.sh
  operator/README.md
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: size/S, approved, lgtm, kind/cleanup

#5514 chore: update ci for kubernetes 1.31 and schedule for release-1.11
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5508 pkg+test: unify the usage of policyv1alpha1 operators
  pkg/controllers/namespace/namespace_sync_controller_test.go
  pkg/util/overridemanager/commandargsoverride_test.go
  pkg/util/overridemanager/imageoverride_test.go
  pkg/util/overridemanager/overridemanager_test.go
  pkg/util/validation/validation_test.go
  test/e2e/clusteroverridepolicy_test.go
  test/e2e/failover_test.go
  test/e2e/overridepolicy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#5525 Fix occasional suspension case failed
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: approved, lgtm, kind/failing-test, size/M

#5529 Bump golang version to 1.22.7 to address security warnings
  .go-version
  go.mod
  hack/util.sh
Labels: approved, lgtm, size/XS

#5523 Fix `karmadactl addon` failed to install karmada-scheduler-estimator due to unknown flag
  cmd/scheduler-estimator/app/options/options.go
  pkg/karmadactl/addons/estimator/manifests.go
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup

#5505 Nominates Amir and Chaosi as the owners of helm chart
  charts/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#5260 Proposal: Enhance `EcternalEtcd` Configuration to Support Retrieving etcd Client Credentials from a Kubernetes Secret
  docs/proposals/karmada-operator/external-etcd-credentials-ref/README.md
Labels: approved, lgtm, kind/design, size/M

#5521 pkg/webhook: log mutating handlers in `OverridePolicy`, `ClusterPropagationPolicy`, and `MultiClusterService`
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/multiclusterservice/mutating.go
  pkg/webhook/overridepolicy/mutating.go
Labels: kind/feature, approved, lgtm, size/XS, kind/cleanup, ok-to-test

#5528 Added tests for federatedhpa controller
  pkg/controllers/federatedhpa/config/types_test.go
  pkg/controllers/federatedhpa/federatedhpa_controller_test.go
  pkg/controllers/federatedhpa/metrics/client_test.go
  pkg/controllers/federatedhpa/replica_calculator_test.go
Labels: kind/feature, approved, size/XXL, lgtm, kind/failing-test

#5532 pkg/webhook: unit test Work
  pkg/webhook/work/mutating_test.go
Labels: approved, size/L, lgtm

#5517 pkg/webhook: unit test Multi-Cluster Service
  pkg/webhook/multiclusterservice/mutating_test.go
  pkg/webhook/multiclusterservice/validating_test.go
Labels: approved, size/XL, lgtm

#5534 Remove me from resourceinterpreter OWNERS
  pkg/resourceinterpreter/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#5276 Proposal: Support to Specify Extra Volumes and Volume Mounts for Karmada Control Plane Components
  docs/proposals/karmada-operator/api-server-extra-volumes-volume-mounts/README.md
Labels: approved, lgtm, kind/design, size/M

#5509 Support to Specify Extra Volumes and Volume Mounts for Karmada API Server Component
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/util/patcher/pather.go
Labels: kind/feature, approved, size/XXL, lgtm

#5531 Automated cherry pick of #5529: bump go version to 1.22.7
  .go-version
  go.mod
  hack/util.sh
Labels: approved, lgtm, size/XS

#5535 Added tests for federatedresourcequota controller
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller_test.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5537 pkg/webhook: refactor Propagation Policy test
  pkg/webhook/propagationpolicy/mutating_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#5494 pkg/webhook: unit test cluster propagation policy
  pkg/webhook/clusterpropagationpolicy/mutating_test.go
  pkg/webhook/clusterpropagationpolicy/validating_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5400 add new cluster condition: CompleteAPIEnablements
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/controllers/status/cluster_status_controller.go
Labels: kind/feature, kind/api-change, approved, lgtm, size/M

#5546 Fix mTLS Configuration for Karmada Scheduler & Descheduler Components
  operator/pkg/controlplane/controlplane.go
Labels: kind/bug, approved, lgtm, size/M

#5550 Automated cherry pick of #5546: Set Karmada Cert Secret Used For Configurating mTLS for
  operator/pkg/controlplane/controlplane.go
Labels: approved, lgtm, size/M

#5540 publish release note for v1.11.1, v1.10.5, v1.9.7
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, kind/documentation, lgtm

#5558 fix: remove extra slash when constructing member cluster URL to adapt…
  pkg/registry/cluster/storage/aggregate.go
  pkg/registry/cluster/storage/aggregate_test.go
Labels: approved, lgtm, size/M

#5548 Remove deprecated `--bind-address` and `--secure-port` from `karmada-agent`
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
Labels: approved, lgtm, size/M, kind/cleanup, kind/deprecation

#5216 skip the filter if the cluster is already in the list of scheduling result even if the API is missed
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
Labels: kind/bug, size/S, approved, lgtm

#5549 Removed deprecated `--bind-address` and `--bind-address` from `karmada-controller-manager`
  artifacts/deploy/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
Labels: approved, lgtm, size/M, kind/cleanup

#5555 Remove deprecated `--bind-address` and `--bind-address` from `karmada-scheduler-estimator`
  artifacts/deploy/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  cmd/scheduler-estimator/app/options/options.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  pkg/karmadactl/addons/estimator/manifests.go
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: approved, lgtm, size/M, kind/cleanup, kind/deprecation

#5562 pkg/webhook: unit test ResourceInterpreterCustomization
  pkg/webhook/resourceinterpretercustomization/validation_test.go
Labels: approved, size/L, lgtm

#5533 Implementing autocompletion for karmadactl
  pkg/karmadactl/annotate/annotate.go
  pkg/karmadactl/apiresources/apiresources.go
  pkg/karmadactl/apiresources/apiversions.go
  pkg/karmadactl/apply/apply.go
  pkg/karmadactl/attach/attach.go
  pkg/karmadactl/completion/completion.go
  pkg/karmadactl/cordon/cordon.go
  pkg/karmadactl/create/create.go
  pkg/karmadactl/delete/delete.go
  pkg/karmadactl/describe/describe.go
  pkg/karmadactl/edit/edit.go
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/explain/explain.go
  pkg/karmadactl/get/get.go
  pkg/karmadactl/interpret/interpret.go
  pkg/karmadactl/join/join.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/label/label.go
  pkg/karmadactl/logs/logs.go
  pkg/karmadactl/patch/patch.go
  pkg/karmadactl/promote/promote.go
  pkg/karmadactl/taint/taint.go
  pkg/karmadactl/token/token.go
  pkg/karmadactl/top/top_node.go
  pkg/karmadactl/top/top_pods.go
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/util/completion/completion.go
Labels: kind/feature, approved, size/XL, lgtm

#5544 pkg/webhook: refactor Federated Resource Quota test
  pkg/webhook/federatedresourcequota/validating_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#5518 pkg/webhook: unit test Multi-Cluster Ingress
  pkg/webhook/multiclusteringress/validating_test.go
Labels: approved, size/L, lgtm

#5495 pkg/webhook: unit test override policy
  pkg/webhook/overridepolicy/mutating_test.go
  pkg/webhook/overridepolicy/validating_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5496 pkg/webhook: unit test cluster override policy
  pkg/webhook/clusteroverridepolicy/validating_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5497 pkg/webhook: unit test resource binding
  pkg/webhook/resourcebinding/mutating_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5498 pkg/webhook: unit test cluster resource binding
  pkg/webhook/clusterresourcebinding/mutating_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5551 Remove deprecated --bind-address and --secure-port from karmada-scheduler
  artifacts/deploy/karmada-scheduler.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  cmd/scheduler/app/options/options.go
  cmd/scheduler/app/options/options_test.go
  cmd/scheduler/app/options/validation.go
  cmd/scheduler/app/options/validation_test.go
  cmd/scheduler/app/scheduler.go
  operator/pkg/controlplane/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, size/L, lgtm, kind/cleanup, kind/deprecation

#5580 fix ut failed in federatedresourcequota
  pkg/webhook/federatedresourcequota/validating_test.go
  pkg/webhook/multiclusteringress/validating_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#5552 Remove deprecated --bind-address and --secure-port from karmada-descheduler
  artifacts/deploy/karmada-descheduler.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  cmd/descheduler/app/descheduler.go
  cmd/descheduler/app/options/options.go
  cmd/descheduler/app/options/validation_test.go
  operator/pkg/controlplane/manifests.go
  pkg/karmadactl/addons/descheduler/manifests.go
Labels: approved, lgtm, size/M, kind/cleanup

#5575 Proposing API to support migration rollback
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/L, lgtm

#5507 pkg/webhook: unit test Federated HPA
  pkg/webhook/federatedhpa/mutating_test.go
  pkg/webhook/federatedhpa/validating_test.go
Labels: approved, size/L, lgtm

#5572 `karmada-operator`: Grand proxy permission to system:admin
  operator/pkg/karmadaresource/rbac/manifest.go
  operator/pkg/karmadaresource/rbac/rbac.go
  operator/pkg/util/apiclient/idempotency.go
Labels: kind/bug, approved, lgtm, size/M

#5449 Overriding values inside JSON and YAML
  docs/proposals/structured-configuration/README.md
Labels: approved, size/XL, kind/documentation, lgtm, kind/design

#5581 Proposing structured field overrider API
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/XL, lgtm

#5593 operator/README.md: redirect users to the latest `karmada-operator` released tag
  operator/README.md
Labels: approved, kind/documentation, lgtm, size/XS

#5600 Added tests for unifiedauth controller
  pkg/controllers/unifiedauth/unified_auth_controller_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5101 docs(proposal): Migration Rollback Protection
  docs/proposals/migration-rollback-protection/README.md
  docs/proposals/migration-rollback-protection/statics/resource-delete-policy.png
Labels: approved, size/L, lgtm

#5607 operator/pkg/scheme: unit test scheme
  operator/pkg/scheme/scheme_test.go
Labels: approved, lgtm, size/M

#5595 Added tests for remediation controller
  pkg/controllers/remediation/remedy_controller_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5605 operator/pkg/karmadaresource: unit test `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration`
  operator/pkg/karmadaresource/webhookconfiguration/webhookconfiguration_test.go
Labels: approved, size/L, lgtm

#5611 Correct SuspendDispatching comments and add notes.
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  pkg/apis/work/v1alpha1/work_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: size/S, approved, lgtm, kind/cleanup

#5601 guarantee the promotion can be rolled back safely
  pkg/karmadactl/promote/promote.go
Labels: kind/feature, size/S, approved, lgtm

#5612 Show more debug logs when failed to build resource model due to `getIndex` fails
  pkg/modeling/modeling.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5606 Improved test coverage for workloadrebalancer controller
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller_test.go
Labels: kind/feature, approved, size/L, lgtm, kind/failing-test

#5616 operator+pkg: depend on `clientset.Interface` instead of `*clientset.Clientset`
  operator/pkg/util/kubeconfig.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/util/apiclient/apiclient.go
Labels: size/S, approved, lgtm

#4184 ci: add schedule image-scanning
  .github/workflows/ci-image-scanning-on-schedule.yml
Labels: approved, lgtm, size/M

#5627 Allow `hack/local-up-karmada.sh` to use latest pre-built images
  hack/local-up-karmada.sh
Labels: kind/feature, approved, lgtm, size/M
