Repository karmada-io/karmada, pull requests merged in 2024-02, with the labels that each got.

#4598 bump alpine to 3.19.1 to address CVE concerns
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#4600 Automated cherry pick of #4598: bump alpine to 3.19.1 to address CVE concerns
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: size/S, approved, lgtm

#4601 Automated cherry pick of #4598: bump alpine to 3.19.1 to address CVE concerns
  cluster/images/Dockerfile
  cluster/images/buildx.Dockerfile
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: size/S, approved, lgtm

#4609 Remove deprecated build constraints
  hack/tools/tools.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4584 Implement node/pod tableconvert
  pkg/printers/storage/storage.go
  pkg/printers/storage/storage_test.go
  pkg/search/proxy/framework/plugins/cache/cache.go
  pkg/util/lifted/corev1printers.go
  pkg/util/lifted/corev1printers_test.go
Labels: kind/feature, approved, size/XL, lgtm

#4618 Optimize the display of the hack/verify-import-aliases.sh
  hack/tools/preferredimports/preferredimports.go
  hack/verify-import-aliases.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#4640 chores(deps): support depguard rules in golang-lint
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup, tide/merge-method-squash, kind/deprecation

#4341 update work status condition when recreate failed
  pkg/controllers/status/work_status_controller.go
Labels: kind/feature, approved, lgtm, size/M

#4645 correct print info
  operator/pkg/util/apiclient/idempotency.go
Labels: kind/bug, approved, lgtm, size/XS

#4649 fix: update service failed when reconcile
  operator/pkg/util/apiclient/idempotency.go
Labels: kind/bug, approved, lgtm, size/XS

#4635 Adding remedy APIs to ClusterState-based policy orchestration solutions
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
  charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
  charts/karmada/_crds/kustomization.yaml
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  hack/.import-aliases
  hack/update-codegen.sh
  hack/update-crdgen.sh
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/zz_generated.deepcopy.go
  pkg/apis/networking/v1alpha1/ingress_types.go
  pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/remedy/v1alpha1/doc.go
  pkg/apis/remedy/v1alpha1/remedy_types.go
  pkg/apis/remedy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/remedy/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/remedy/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/remedy/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/remedy/v1alpha1/fake/fake_remedy.go
  pkg/generated/clientset/versioned/typed/remedy/v1alpha1/fake/fake_remedy_client.go
  pkg/generated/clientset/versioned/typed/remedy/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/remedy/v1alpha1/remedy.go
  pkg/generated/clientset/versioned/typed/remedy/v1alpha1/remedy_client.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/remedy/interface.go
  pkg/generated/informers/externalversions/remedy/v1alpha1/interface.go
  pkg/generated/informers/externalversions/remedy/v1alpha1/remedy.go
  pkg/generated/listers/remedy/v1alpha1/expansion_generated.go
  pkg/generated/listers/remedy/v1alpha1/remedy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/lifted/corev1printers.go
  pkg/util/lifted/corev1printers_test.go
  pkg/util/lifted/validatingmci_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#4655 Add remedy controller to reconcile with cluster status condition and remedy resource.
  api/openapi-spec/swagger.json
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/remediation/eventhandlers.go
  pkg/controllers/remediation/remedy_controller.go
  pkg/controllers/remediation/util.go
  pkg/util/gclient/gclient.go
Labels: kind/feature, approved, size/L, lgtm

#4657 fix panic when update remedy.spec.clusteraffinity to empty
  pkg/controllers/remediation/eventhandlers.go
  pkg/controllers/remediation/remedy_controller.go
Labels: kind/bug, approved, lgtm, size/M

#4646 Add service-name-resolution-detector
  cmd/service-name-resolution-detector-example/README.md
  cmd/service-name-resolution-detector-example/app/coredns.go
  cmd/service-name-resolution-detector-example/app/options/coredns.go
  cmd/service-name-resolution-detector-example/app/options/generic.go
  cmd/service-name-resolution-detector-example/app/options/options.go
  cmd/service-name-resolution-detector-example/app/service-name-resolution-detector.go
  cmd/service-name-resolution-detector-example/main.go
  cmd/service-name-resolution-detector-example/names/detector_names.go
  go.mod
  go.sum
  pkg/servicenameresolutiondetector/coredns/detector.go
  pkg/servicenameresolutiondetector/store/condition_cache.go
  pkg/servicenameresolutiondetector/store/node_store.go
  pkg/servicenameresolutiondetector/store/store.go
  vendor/k8s.io/controller-manager/LICENSE
  vendor/k8s.io/controller-manager/pkg/healthz/handler.go
  vendor/k8s.io/controller-manager/pkg/healthz/healthz.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm

#4602 Proposal of the LazyActivation preference for Policy
  docs/proposals/scheduling/activation-preference/lazy-activation-preference.md
Labels: approved, size/L, kind/documentation, lgtm, kind/design

#4663 Set enum value for operator in Remedy API
  charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
  pkg/apis/remedy/v1alpha1/remedy_types.go
  pkg/scheduler/framework/testing/mock_interface.go
Labels: kind/feature, approved, lgtm, size/XS

#4664 Add release notes of v1.9
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, kind/documentation, lgtm
