Repository karmada-io/karmada, pull requests merged in 2024-01, with the labels that each got.

#4489 bump golang.org/x/crypto to v.0.17.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS, kind/cleanup

#4493 Cleanup: enable lint of revive(superfluous-else)
  .golangci.yml
  pkg/karmadactl/util/genericresource/visitor.go
  test/e2e/framework/federatedresourcequota.go
Labels: size/S, approved, lgtm, kind/cleanup

#4407 fix(work): motify gracefulEvictionTasks sub field creationTimestamp to pointer type
  api/openapi-spec/swagger.json
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/L, lgtm

#4498 cleanup: enable revive(error-strings) checking
  .golangci.yml
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller_test.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4505 cleanup RunScorePlugins code comments
  pkg/scheduler/framework/runtime/framework.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4502 cleanup: enable revive(error-return) checking
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4508 fix: add Embedded metadata field for workload CRD
  examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
  hack/update-crdgen.sh
Labels: kind/bug, approved, lgtm, size/M

#4499 cleanup: enable revive(receiver-naming) checking
  .golangci.yml
  test/e2e/framework/karmadactl.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4503 cleanup: enable revive(package-comments) checking
  .golangci.yml
  pkg/controllers/federatedhpa/monitor/metrics.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4501 cleanup: enable revive(increment-decrement) checking
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4367 update operator/README.md
  operator/README.md
Labels: size/S, approved, kind/documentation, lgtm

#4511 cleanup: enable revive(range/error-naming) checking
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4517 clean up deprecated codes
  pkg/karmadactl/apply/apply.go
  pkg/karmadactl/describe/describe.go
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/get/get.go
  pkg/karmadactl/interpret/check_test.go
  pkg/karmadactl/interpret/execute_test.go
  pkg/karmadactl/interpret/interpret.go
  pkg/karmadactl/karmadactl.go
  pkg/karmadactl/logs/logs.go
  pkg/karmadactl/token/token.go
  pkg/karmadactl/token/token_test.go
  pkg/karmadactl/top/top.go
  pkg/karmadactl/top/top_pods.go
  pkg/metricsadapter/controller.go
  pkg/util/worker.go
Labels: approved, lgtm, size/M, kind/cleanup

#4504 cleanup: enable revive(errorf/dot-imports) checking
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4491 cleanup: enable revive(exported rule) checking
  .golangci.yml
  cmd/controller-manager/app/controllermanager.go
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/apis/operator/v1alpha1/helper.go
  operator/pkg/util/kubeconfig.go
  operator/pkg/util/util.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/client.go
  pkg/controllers/federatedhpa/metrics/interfaces.go
  pkg/controllers/federatedhpa/monitor/monitor.go
  pkg/controllers/federatedhpa/replica_calculator.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/karmadactl/top/metrics_printer.go
  pkg/karmadactl/top/metrics_sorter.go
  pkg/karmadactl/top/top.go
  pkg/karmadactl/top/top_pods.go
  pkg/karmadactl/util/validate.go
  pkg/registry/cluster/storage/aggregate.go
  pkg/registry/cluster/storage/storage.go
  pkg/scheduler/core/common.go
  pkg/util/cluster.go
  pkg/util/helper/cronfederatedhpa.go
  pkg/util/helper/mcs.go
  pkg/util/proxy/proxy.go
  pkg/util/proxy/upgrader.go
  test/e2e/framework/deployment.go
  test/e2e/framework/karmadactl.go
  test/helper/resource.go
Labels: approved, size/L, lgtm, kind/cleanup

#4524 Fix misjudgment when updating attached binding
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4492 cleanup: enable revive(var-declaration rule) checking
  .golangci.yml
  pkg/controllers/federatedhpa/federatedhpa_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4364 add cfg.Namespace.svc to apiServerAltNames in operator installation mode
  operator/pkg/certs/certs.go
Labels: kind/bug, size/S, approved, lgtm

#4495 cleanup: enable revive(blank-imports/indent-error-flow rule) checking
  .golangci.yml
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/top/top_pods.go
  pkg/webhook/cronfederatedhpa/validating.go
Labels: size/S, approved, lgtm, kind/cleanup

#4514 Add linting for unreachable code
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4496 cleanup: enable revive(var-naming rule) checking
  .golangci.yml
  pkg/controllers/status/work_status_controller_test.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/util/proxy/upgrade_dialer.go
Labels: size/S, approved, lgtm, kind/cleanup

#4522 defer RUnlock
  pkg/util/fedinformer/typedmanager/single-cluster-manager.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4533 Delete k8s v1.21 and v1.22 from workflow of APIServer compatibility.
  .github/workflows/ci-schedule-compatibility.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#4530 fix the issue of invalid protobuf execution
  hack/update-estimator-protobuf.sh
Labels: kind/bug, size/S, approved, lgtm

#4541 test of even distribution of replicas for removing cluster scenario
  pkg/scheduler/core/generic_scheduler_test.go
Labels: approved, lgtm, size/M

#4520 chore: verify whether docker is available by executing docker ps command
  hack/local-up-karmada.sh
  hack/util.sh
Labels: kind/feature, size/S, approved, lgtm

#4521 docs: Add e2e coverage detail(last part)
  test/e2e/clusteraffinities_test.go
  test/e2e/coverage_docs/clusteraffinities_test.md
  test/e2e/coverage_docs/resourceinterpreter_test.md
  test/e2e/coverage_docs/scheduling_test.md
  test/e2e/coverage_docs/search_test.md
  test/e2e/coverage_docs/tainttoleration_test.md
  test/e2e/resourceinterpreter_test.go
  test/e2e/scheduling_test.go
Labels: approved, size/L, kind/documentation, lgtm

#4512 Add linting for unused parameters
  .golangci.yml
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/search/search.go
  operator/pkg/controlplane/webhook/webhook.go
  pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/status/cluster_status_controller_test.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/karmadactl/promote/promote.go
  pkg/metricsadapter/provider/externalmetrics.go
  pkg/webhook/multiclusterservice/validating.go
Labels: size/S, approved, lgtm, kind/cleanup

#4551 collect kind log for ci-schedule workflow
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
Labels: size/S, approved, lgtm, kind/flake

#4536 Add preemption E2E test
  test/e2e/preemption_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4552 enable golangci-lint context-as-argument, context-keys-type and unexported-return checking
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4519 remove unsafe lua load library function
  pkg/resourceinterpreter/customized/declarative/luavm/lua.go
  pkg/util/lifted/lua/loadlib_safe.go
  pkg/util/lifted/lua/oslib_safe.go
  pkg/util/lifted/lua/oslib_safe_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4494 add scan-image-vuln.sh to do image-scanning with trivy
  hack/scan-image-vuln.sh
Labels: approved, size/L, lgtm, kind/cleanup

#4116 ci: fix schedule ci workflow failure
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
Labels: size/S, approved, lgtm, kind/failing-test

#4539 cleanup: remove label when pp or cpp is deleted
  pkg/detector/detector.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/coverage_docs/clusterpropagationpolicy_test.md
  test/e2e/coverage_docs/propagationpolicy_test.md
  test/e2e/framework/clusterresourcebinding.go
  test/e2e/framework/customresourcedefine.go
  test/e2e/framework/deployment.go
  test/e2e/framework/resourcebinding.go
  test/e2e/propagationpolicy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4528 Remove redundant os preload in lua vm
  pkg/resourceinterpreter/customized/declarative/luavm/lua.go
  pkg/util/lifted/lua/oslib_safe.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4534 [MVP] add resourcequota plugin in scheduler-estimator: create framework for scheulder-estimator
  charts/karmada/README.md
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/values.yaml
  cmd/scheduler-estimator/app/options/options.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  hack/verify-license.sh
  pkg/estimator/server/estimate.go
  pkg/estimator/server/framework/interface.go
  pkg/estimator/server/framework/plugins/registry.go
  pkg/estimator/server/framework/runtime/framework.go
  pkg/estimator/server/framework/runtime/framework_test.go
  pkg/estimator/server/framework/runtime/registry.go
  pkg/estimator/server/framework/runtime/registry_test.go
  pkg/estimator/server/metrics/metrics.go
  pkg/estimator/server/server.go
  pkg/estimator/server/server_test.go
Labels: approved, size/XXL, lgtm, tide/merge-method-squash

#4567 add flag -f format to scan-image-vuln.sh
  hack/scan-image-vuln.sh
Labels: size/S, approved, lgtm, kind/cleanup

#4571 Fix github action yaml format
  .github/workflows/ci-schedule.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4557 pull mode register add check cluster exists
  pkg/karmadactl/register/register.go
Labels: size/S, approved, lgtm, kind/cleanup

#4568 bump golangci-lint to v1.55.2
  .golangci.yml
  hack/verify-staticcheck.sh
  pkg/apis/cluster/validation/validation_test.go
  pkg/printers/internalversion/printers_test.go
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/spreadconstraint/select_clusters.go
  pkg/search/proxy/store/util.go
  pkg/util/binding_test.go
  pkg/util/helper/workstatus.go
  pkg/util/validation/validation.go
Labels: approved, lgtm, size/M, kind/cleanup

#4554 search add check member cluster api enable
  pkg/search/controller.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
Labels: kind/bug, approved, lgtm, size/M

#4572 Nominate Yuan peng, Zhuang, and Yan feng as new reviewers
  .github/workflows/OWNERS
  hack/OWNERS
  pkg/karmadactl/OWNERS
  pkg/search/OWNERS
Labels: approved, lgtm, size/XS, kind/cleanup

#4577 Introduced a lazy activation preference to PropagationPolicy/ClusterPropagationPolicy
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/detector/detector.go
  pkg/detector/handler.go
  pkg/detector/policy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/eventfilter/eventfilter.go
  pkg/util/fedinformer/handlers.go
  pkg/util/fedinformer/keys/keys.go
  pkg/util/policy.go
  pkg/util/worker.go
Labels: kind/feature, approved, size/L, lgtm

#4580 Support accept content type as=Table into karmada-search.
  pkg/search/proxy/framework/plugins/cache/cache.go
Labels: kind/bug, approved, lgtm, size/XS

#4566 [MVP] add resourcequota plugin in scheduler-estimator: add resourcequota plugin
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/estimator/client/accurate.go
  pkg/estimator/pb/generated.pb.go
  pkg/estimator/pb/generated.proto
  pkg/estimator/pb/types.go
  pkg/estimator/server/framework/plugins/registry.go
  pkg/estimator/server/framework/plugins/resourcequota/resourcequota.go
  pkg/estimator/server/framework/plugins/resourcequota/resourcequota_test.go
  pkg/features/features.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/helper/binding.go
Labels: approved, size/XXL, lgtm

#4588 Automated cherry pick of #4554: search add check member cluster api enable
  pkg/search/controller.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
Labels: approved, lgtm, size/M

#4589 Automated cherry pick of #4554: search add check member cluster api enable
  pkg/search/controller.go
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
Labels: approved, lgtm, size/M

#4586 fix: reschedule the replicas of the disappear clusters in PP
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/assignment_test.go
Labels: kind/bug, approved, lgtm, size/M

#4591 feat: add manager label to eps work to avoid the conflicts between mcs/serviceexport
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/util/constants.go
  test/e2e/mcs_test.go
Labels: kind/feature, approved, size/L, lgtm

#4594 Automated cherry pick of #4580: if accept set
  pkg/search/proxy/framework/plugins/cache/cache.go
Labels: approved, lgtm, size/XS

#4595 Automated cherry pick of #4580: if accept set
  pkg/search/proxy/framework/plugins/cache/cache.go
Labels: approved, lgtm, size/XS

#4596 Automated cherry pick of #4580: if accept set
  pkg/search/proxy/framework/plugins/cache/cache.go
Labels: approved, lgtm, size/XS
