Repository karmada-io/karmada, pull requests merged in 2024-05, with the labels that each got.

#4875 fix patching WorkloadRebalancer failed due to misuse of shared slices
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
Labels: kind/bug, approved, lgtm, size/M

#4902 fix the action error with no go.sum file
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#4897 chore: fix ghaction APIServer compatibility
  .github/workflows/ci-schedule-compatibility.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#4906 chore: reuse proxyutil import for proxy
  pkg/util/proxy/proxy.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4909 Bump kind to v0.22.0
  .github/workflows/cli.yaml
  .github/workflows/lint-chart.yaml
  go.mod
  go.sum
  hack/local-up-karmada.sh
  vendor/modules.txt
  vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit/init.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/common/getport.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provision.go
  vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/validate.go
Labels: approved, lgtm, size/M, kind/cleanup

#4860 feat: support update event in WorkloadRebalancer
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
Labels: kind/feature, approved, lgtm, size/M

#4883 feat: add client-go oidc auth provider
  cmd/karmadactl/karmadactl.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
  vendor/modules.txt
Labels: kind/feature, approved, size/L, lgtm

#4920 Bump Golang to v1.21.10
  .go-version
  go.mod
Labels: approved, lgtm, size/XS, kind/cleanup

#4921 Bump sigs.k8s.io/controller-runtime to v0.17.5
  go.mod
  go.sum
  pkg/util/clusterlease_test.go
  pkg/util/helper/mcs_test.go
  pkg/util/membercluster_client.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/github.com/go-logr/zapr/.golangci.yaml
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/slogzapr.go
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/github.com/go-logr/zapr/zapr_noslog.go
  vendor/github.com/go-logr/zapr/zapr_slog.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/RELEASE.md
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/delegating_by_gvk_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/restmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fieldowner.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/field/selector/utils.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/syncs/syncs.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/server/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/alias.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#4882 Use webhook to set associated labels and annotations of work
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/controllers/certificate/cert_rotation_controller.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/util/helper/work.go
  pkg/webhook/work/mutating.go
Labels: approved, size/L, lgtm, kind/cleanup

#4876 add ut for WorkloadRebalancer controller
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4903 add e2e for FederatedHPA and metrics-adapter
  test/e2e/federatedhpa_test.go
  test/e2e/suite_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4915 Clean up dangling images
  hack/local-up-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup, ok-to-test

#4928 cleanup dead code of generating Work permanent id
  pkg/util/helper/work.go
  pkg/webhook/work/mutating.go
Labels: size/S, approved, lgtm, kind/cleanup

#4939 Fix env DOCKER_BUILD_ARGS in hack/local-up-karmada.sh
  hack/local-up-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#4916 Call shutdown after being stopped
  cmd/metrics-adapter/app/options/options.go
  pkg/metricsadapter/controller.go
  pkg/scheduler/scheduler.go
Labels: kind/bug, size/S, approved, lgtm, kind/cleanup

#4924 chore: fix broken link
  hack/update-estimator-protobuf.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#4943 feat: remove `PersistentVolumeClaim` annotation `volume.kubernetes.io/selected-node`
  pkg/resourceinterpreter/default/native/prune/prune.go
  pkg/resourceinterpreter/default/native/prune/prune_test.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/component-helpers/storage/volume/pv_helpers.go
  vendor/modules.txt
Labels: kind/bug, approved, size/L, lgtm

#4944 unit test for interpreter retain (pv, pvc)
  pkg/resourceinterpreter/default/native/retain_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#4954 clean: remove duplicate util reference
  pkg/karmadactl/register/register.go
Labels: approved, lgtm, size/XS

#4947 migrate wait.PollUntil to wait.PollUntilContextCancel
  pkg/controllers/mcs/service_export_controller.go
  pkg/util/credential_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#4869 add e2e for WorkloadRebalancer
  test/e2e/framework/resourcebinding.go
  test/e2e/framework/workloadrebalancer.go
  test/e2e/suite_test.go
  test/e2e/workloadrebalancer_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm

#4957 cleanup: replace text/template with html/template
  operator/pkg/util/template.go
  pkg/karmadactl/addons/utils/template.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4934 silence gosec warning G107
  pkg/karmadactl/util/genericresource/visitor.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4940 [Cleanup] remove retain annotations logic
  pkg/resourceinterpreter/default/native/retain.go
  pkg/resourceinterpreter/default/native/retain_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#4949 cleanup dead code of generating PropagationPolicy permanent id
  pkg/detector/detector.go
Labels: approved, lgtm, size/M, kind/cleanup

#4965 fix e2e unstable failure caused by taint cluster
  test/e2e/workloadrebalancer_test.go
Labels: approved, lgtm, size/XS, kind/flake

#4946 fix: prune deployment revision annotation
  pkg/resourceinterpreter/default/native/prune/prune.go
  pkg/resourceinterpreter/default/native/prune/prune_test.go
Labels: kind/bug, approved, lgtm, size/M

#4950 cleanup dead code of generating binding permanent id
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
Labels: size/S, approved, lgtm, kind/cleanup

#4955 upgrade rsa key size from 2048 to 3072
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
  hack/util.sh
  operator/pkg/certs/certs.go
  pkg/karmadactl/cmdinit/cert/cert.go
  pkg/karmadactl/register/register.go
  pkg/util/lifted/pubkeypin/pubkeypin_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4966 fix golint issue introduced by #4950
  pkg/detector/detector.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4956 cleanup: adjust log print content when delete token by karmadactl
  pkg/karmadactl/token/token.go
Labels: size/S, approved, lgtm, kind/cleanup

#4959 [Cleanup] Add empty judgment for placement in taint-manager
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#4960 cleanup: grant the correct permissions when creating a file
  hack/tools/genkarmadactldocs/gen_karmadactl_docs.go
  hack/tools/lifted-gen/lifted-gen.go
  operator/pkg/util/util.go
  pkg/karmadactl/cmdinit/utils/format.go
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/util/constants.go
Labels: size/S, approved, lgtm, kind/cleanup

#4912 Update roadmap of 2024
  ROADMAP.md
Labels: size/S, approved, lgtm, kind/cleanup

#3921 migrate wait.PollImmediate to wait.PollUntilContextTimeout
  operator/pkg/util/apiclient/wait.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/karmadactl/cmdinit/karmada/check.go
  pkg/karmadactl/util/check.go
  test/e2e/clusteraffinities_test.go
  test/e2e/failover_test.go
  test/e2e/framework/cluster.go
  test/e2e/mcs_test.go
  test/e2e/namespace_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/resourceinterpreter_test.go
  test/e2e/scheduling_test.go
  test/e2e/suite_test.go
  test/helper/request.go
Labels: approved, size/L, lgtm, kind/cleanup

#4961 add more e2e for WorkloadRebalancer
  test/e2e/workloadrebalancer_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4964 Add validation on policy permanent ID
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/clusterpropagationpolicy/validating.go
  pkg/webhook/propagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/validating.go
Labels: kind/feature, size/S, approved, lgtm

#4967 Removed deprecated --cluster-zone from karmadactl join command
  pkg/karmadactl/join/join.go
  pkg/util/cluster.go
Labels: size/S, approved, lgtm, kind/deprecation

#4932 chore: support auto bump container images with dependabot.
  .github/dependabot.yml
Labels: size/S, approved, lgtm, kind/cleanup

#4978 [1.7] chore: skip push event for branches of dependabot.
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/fossa.yml
  .github/workflows/lint-chart.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#4977 [1.8] chore: skip push event for branches of dependabot.
  .github/workflows/ci-image-scanning.yaml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/fossa.yml
  .github/workflows/lint-chart.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#4698 Proposal of introducing a rebalance mechanism to actively trigger rescheduling of resource
  docs/proposals/scheduling/workload-rebalancer/workload-rebalancer.md
Labels: approved, size/L, lgtm, kind/design

#4970 ci: add kubernetes 1.30
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#4980 cleanup: update relate binding name and comments for ease of understanding
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4983 add binding dependencies distributor finalizer to the independent binding
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/util/constants.go
Labels: kind/feature, approved, lgtm, size/M

#4985 Skip schedule deleting bindings
  pkg/scheduler/scheduler.go
Labels: kind/feature, size/S, approved, lgtm

#4894 support auto delete WorkloadRebalancer when time up
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml
  pkg/apis/apps/v1alpha1/workloadrebalancer_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller_test.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/e2e/framework/workloadrebalancer.go
  test/e2e/workloadrebalancer_test.go
Labels: kind/feature, approved, size/L, lgtm

#4988 [1.9] karmadactl init: set default value of imagePullPolicy to IfNotPresent
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: size/S, approved, lgtm

#2723 Bump cfssl
  hack/deploy-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#4976 [1.9] chore: skip push event for branches of dependabot.
  .github/workflows/ci-image-scanning.yaml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/fossa.yml
  .github/workflows/lint-chart.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#4719 Cleanup the deprecated package of k8s.io/utils/pointer.
  examples/customresourceinterpreter/webhook/app/workloadwebhook.go
  operator/pkg/apis/operator/v1alpha1/defaults.go
  pkg/apis/policy/v1alpha1/propagation_helper_test.go
  pkg/apis/work/v1alpha2/binding_types_helper_test.go
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller_test.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
  pkg/karmadactl/get/get.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go
  pkg/util/eventfilter/eventfilter_test.go
  pkg/util/helper/mcs_test.go
  pkg/util/helper/policy.go
  pkg/util/helper/policy_test.go
  pkg/util/lifted/deployment_test.go
  pkg/util/lifted/federatedhpa.go
  pkg/util/lifted/federatedhpa_test.go
  pkg/util/lifted/retain_test.go
  pkg/util/lifted/validatingmci_test.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
  pkg/webhook/cronfederatedhpa/validating.go
  pkg/webhook/cronfederatedhpa/validating_test.go
  test/e2e/cronfederatedhpa_test.go
  test/e2e/deploymentreplicassyncer_test.go
  test/e2e/failover_test.go
  test/e2e/federatedhpa_test.go
  test/e2e/lazy_activation_policy_test.go
  test/e2e/preemption_test.go
  test/e2e/propagationpolicy_test.go
  test/e2e/rescheduling_test.go
  test/e2e/resourceinterpreter_test.go
  test/e2e/scheduling_test.go
  test/e2e/workloadrebalancer_test.go
  test/helper/resource.go
Labels: approved, size/L, lgtm, kind/cleanup

#4992 Enable deprecation check and bump golangci-lint to v1.59.0
  .golangci.yml
  hack/verify-staticcheck.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#4989 Fix depended-by label value exceed 63 characters in dependencies-distributor
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: kind/feature, size/S, approved, lgtm

#4997 remove unused id label in the dependencise distributor
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: approved, lgtm, size/XS, kind/cleanup, kind/deprecation

#5004 fix upgrade error with #5003
  pkg/util/helper/work.go
  pkg/webhook/work/mutating.go
Labels: kind/bug, size/S, approved, lgtm, kind/cleanup

#5005 fix register cluster creates agent missing --cluster-namespace parameter
  pkg/karmadactl/register/register.go
Labels: kind/bug, approved, lgtm, size/XS

#4981 Add release notes of v1.10
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, kind/documentation, lgtm
