Repository karmada-io/karmada, pull requests merged in 2024-04, with the labels that each got.

#4783 Corrected poll timeout example
  test/e2e/suite_test.go
Labels: approved, kind/documentation, lgtm, size/XS

#4782 docs: fix too many karmada relases in Kubernetes compatibility list
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#4784 labels cannot be deleted via Karmada propagation
  pkg/util/helper/work.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: kind/bug, approved, size/L, lgtm

#4786 add pprof option to metrics-adapter
  cmd/metrics-adapter/app/options/options.go
Labels: kind/feature, approved, lgtm, size/XS

#4108 Update apiserver&controller-manager to v1.27 by default
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  operator/README.md
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: size/S, approved, lgtm, kind/cleanup

#4780 Update controller-gen to v0.13.0
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
  hack/update-crdgen.sh
  operator/config/crds/operator.karmada.io_karmadas.yaml
Labels: approved, size/L, lgtm, kind/cleanup

#4797 Automated cherry pick of #4784: labels cannot be deleted via Karmada propagation
  pkg/util/helper/work.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: approved, size/L, lgtm

#4791 Automated cherry pick of #4784: labels cannot be deleted via Karmada propagation
  pkg/util/helper/work.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: approved, size/L, lgtm

#4795 when controller return error is non-nil not need to set Result.Requeue
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/binding_controller_test.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/certificate/cert_rotation_controller.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/cluster_status_controller_test.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/rb_status_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: approved, size/L, lgtm, kind/cleanup

#4793 Use merge strategy to avoid work.karmada.io/permanent-id changes
  pkg/util/helper/work.go
Labels: kind/bug, approved, lgtm, size/XS

#4796 karmada-metrics-adapter: reduce memory usage
  pkg/metricsadapter/adapter.go
  pkg/metricsadapter/controller.go
  pkg/metricsadapter/provider/resourcemetrics.go
Labels: kind/bug, kind/feature, approved, size/L, lgtm

#4807 rename the use of kubectl-karmada
  cmd/kubectl-karmada/kubectl-karmada.go
Labels: kind/bug, approved, lgtm, size/XS, kind/cleanup

#4740 add e2e test for lazy propagation policy
  test/e2e/framework/deployment.go
  test/e2e/framework/propagationpolicy.go
  test/e2e/lazy_activation_policy_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4814 Use RetryOnConflict for applying CRB
  pkg/detector/detector.go
Labels: approved, lgtm, size/M, kind/cleanup

#4762 ci: fix dependabot can not access the secrets
  .github/workflows/ci-image-scanning.yaml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/fossa.yml
  .github/workflows/lint-chart.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#4818 Fix the bug of mcs binding losing resourcebinding.karmada.io/permanent-id label
  pkg/controllers/multiclusterservice/mcs_controller.go
Labels: kind/bug, approved, lgtm, size/XS

#4800 Rename a function to match with updated behavior
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#4820 Automated cherry pick of #4793: Use merge strategy to avoid work.karmada.io/permanent-id
  pkg/util/helper/work.go
Labels: approved, lgtm, size/XS

#4819 Automated cherry pick of #4793: Use merge strategy to avoid work.karmada.io/permanent-id
  pkg/util/helper/work.go
Labels: approved, lgtm, size/XS

#4821 chore: refactor `prune.RemoveIrrelevantField` to allow for more kind …
  pkg/resourceinterpreter/default/native/prune/prune.go
Labels: approved, lgtm, size/M, kind/cleanup

#4794 use single source for go version
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/cli.yaml
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
  .go-version
  go.mod
Labels: size/S, approved, lgtm, kind/cleanup

#4815 Add image-pull-policy flag for karmada init cmd
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: kind/feature, approved, lgtm, size/M

#4811 Deprecate key labels of rb/crb
  pkg/apis/work/v1alpha1/well_known_constants.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
  pkg/util/helper/work.go
  pkg/util/helper/workstatus.go
Labels: kind/feature, approved, size/L, lgtm

#4822 Automated cherry pick of #4818: Fix the bug of mcs binding losing
  pkg/controllers/multiclusterservice/mcs_controller.go
Labels: approved, lgtm, size/XS

#4766 propagate `Secret` of type `kubernetes.io/service-account-token`
  pkg/detector/detector.go
  pkg/resourceinterpreter/default/native/prune/prune.go
  pkg/resourceinterpreter/default/native/prune/prune_test.go
  pkg/resourceinterpreter/default/native/retain.go
  pkg/resourceinterpreter/default/native/retain_test.go
  pkg/util/constants.go
Labels: kind/feature, approved, size/L, lgtm

#4829 feat: upgrade karmada chart dependency
  charts/karmada/Chart.lock
  charts/karmada/Chart.yaml
Labels: kind/feature, approved, lgtm, size/XS

#4827 make DeepEqual judgments more efficient
  pkg/util/cluster.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4656 fix: avoid delete the key with empty value in object (lua table)
  go.mod
  go.sum
  pkg/karmadactl/interpret/execute_test.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert_test.go
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/logo.png
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/github.com/tidwall/sjson/LICENSE
  vendor/github.com/tidwall/sjson/README.md
  vendor/github.com/tidwall/sjson/logo.png
  vendor/github.com/tidwall/sjson/sjson.go
  vendor/modules.txt
Labels: kind/bug, approved, size/XXL, lgtm

#4809 feat: Add QPS related parameters to control the request rate of metrics-adapter to member clusters.
  cmd/agent/app/options/options.go
  cmd/aggregated-apiserver/app/options/options.go
  cmd/controller-manager/app/options/options.go
  cmd/descheduler/app/options/options.go
  cmd/karmada-search/app/options/options.go
  cmd/metrics-adapter/app/options/options.go
  cmd/scheduler-estimator/app/options/options.go
  cmd/scheduler/app/options/options.go
  cmd/webhook/app/options/options.go
  pkg/metricsadapter/controller.go
  pkg/metricsadapter/multiclient/client.go
Labels: kind/bug, kind/feature, approved, size/L, lgtm

#4804 add e2e test for lazy propagation policy
  test/e2e/lazy_activation_policy_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#4785 add image pullSecrets for cfssl and kubectl in charts
  charts/karmada/README.md
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: kind/feature, size/S, approved, lgtm

#4843 update lazy-activation-preference.md and lazy_activation_policy_test.go
  docs/proposals/scheduling/activation-preference/lazy-activation-preference.md
  test/e2e/lazy_activation_policy_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#4836 Add finalizer for propagation policy
  pkg/detector/detector.go
  pkg/util/constants.go
Labels: kind/feature, approved, size/L, lgtm

#4839 feat: show `status.labelSelector` for CloneSet
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations.yaml
Labels: kind/feature, approved, lgtm, size/XS

#4636 provide a tips to fix golangci-lint error
  hack/verify-staticcheck.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#4852 Remove print in test
  pkg/util/helper/taint_test.go
Labels: approved, lgtm, size/XS, kind/failing-test

#4853 Adopt gotestsum
  .github/workflows/ci.yml
  Makefile
Labels: kind/feature, approved, lgtm, size/M

#4848 Introduce a mechanism to scheduler to actively trigger rescheduling
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/assignment_test.go
  pkg/scheduler/core/common.go
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/generic_scheduler_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/binding.go
  pkg/util/binding_test.go
Labels: kind/feature, kind/api-change, approved, size/XL, lgtm

#4841 Introduce a new API named WorkloadRebalancer to support rescheduling
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml
  charts/karmada/_crds/kustomization.yaml
  charts/karmada/templates/post-delete-job.yaml
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/templates/pre-install-job.yaml
  cmd/controller-manager/app/controllermanager.go
  hack/.import-aliases
  hack/tools/swagger/generateswagger.go
  hack/update-codegen.sh
  hack/update-crdgen.sh
  pkg/apis/apps/v1alpha1/doc.go
  pkg/apis/apps/v1alpha1/workloadrebalancer_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.register.go
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/apps_client.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_apps_client.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_workloadrebalancer.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/apps/v1alpha1/workloadrebalancer.go
  pkg/generated/informers/externalversions/apps/interface.go
  pkg/generated/informers/externalversions/apps/v1alpha1/interface.go
  pkg/generated/informers/externalversions/apps/v1alpha1/workloadrebalancer.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/apps/v1alpha1/expansion_generated.go
  pkg/generated/listers/apps/v1alpha1/workloadrebalancer.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/util/apigroup.go
  pkg/util/gclient/gclient.go
Labels: kind/feature, kind/api-change, approved, size/XXL, lgtm

#4863 Add image-pull-policy field for karmada-operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/defaults.go
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/apiserver/mainfests.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/etcd/mainfests.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/metricsadapter/mainfests.go
  operator/pkg/controlplane/metricsadapter/metricsadapter.go
  operator/pkg/controlplane/search/mainfests.go
  operator/pkg/controlplane/search/search.go
  operator/pkg/controlplane/webhook/mainfests.go
  operator/pkg/controlplane/webhook/webhook.go
Labels: kind/feature, approved, size/L, lgtm

#4693 operator: update operator crd when upgrading chart
  charts/karmada-operator/templates/_helpers.tpl
  charts/karmada-operator/templates/post-hook-configmap.yaml
  charts/karmada-operator/templates/post-hook-job.yaml
  charts/karmada-operator/templates/post-hook-rbac.yaml
  charts/karmada-operator/templates/post-hook-serviceacconut.yaml
  charts/karmada-operator/values.yaml
Labels: kind/feature, approved, size/L, lgtm

#4865 replace work namespace/name labels with annotations
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
Labels: kind/bug, size/S, approved, lgtm

#4864 etcd:Update version to 3.5.13
  artifacts/deploy/karmada-etcd.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: size/S, approved, lgtm

#4825 add: Use opts.ResyncPeriod as controlPlaneInformerManager and sharedF…
  cmd/controller-manager/app/controllermanager.go
  pkg/resourceinterpreter/interpreter.go
Labels: approved, lgtm, size/XS, kind/cleanup

#4828 karmadactl: add common code for create and wait deployments.
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/deploy.go
Labels: approved, lgtm, size/M, kind/cleanup

#4874 Update controller-gen version from v0.13.0 to v0.14.0
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
  hack/update-crdgen.sh
  operator/config/crds/operator.karmada.io_karmadas.yaml
Labels: approved, size/XXL, lgtm, kind/cleanup

#4813 Deprecate name/namespace labels of work
  pkg/apis/work/v1alpha1/well_known_constants.go
  pkg/apis/work/v1alpha2/well_known_constants.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/karmadactl/promote/promote.go
  pkg/resourceinterpreter/default/native/prune/prune.go
  pkg/resourceinterpreter/default/native/prune/prune_test.go
  pkg/util/objectwatcher/objectwatcher.go
  pkg/webhook/work/mutating.go
Labels: kind/feature, approved, size/L, lgtm

#4561 e2e: Remove annotaions when pp/cpp is deleted
  pkg/detector/detector.go
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/coverage_docs/clusterpropagationpolicy_test.md
  test/e2e/coverage_docs/propagationpolicy_test.md
  test/e2e/propagationpolicy_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#4881 upgrade arduino/setup-protoc from v1 to v3
  .github/workflows/ci.yml
Labels: approved, lgtm, size/XS, kind/flake

#4880 ObjectWatcher.Delete checks if resource can be deleted
  pkg/controllers/execution/execution_controller.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, lgtm, size/M, kind/cleanup

#4892 Add release notes of v1.7.4, v1.8.3, v1.9.1
  docs/CHANGELOG/CHANGELOG-1.7.md
  docs/CHANGELOG/CHANGELOG-1.8.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, kind/documentation, lgtm, size/M

#4474 feat: add permanent id label to pp/cpp/rb/crb/work resources
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  cmd/webhook/app/webhook.go
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/util/label.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/clusterresourcebinding/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
  pkg/webhook/resourcebinding/mutating.go
  pkg/webhook/work/mutating.go
Labels: kind/feature, approved, size/L, lgtm

#4885 silence the 'log.SetLogger(...) was never called; logs will not be displayed' error
  cmd/controller-manager/controller-manager.go
  cmd/metrics-adapter/main.go
  cmd/webhook/main.go
  examples/customresourceinterpreter/webhook/main.go
Labels: size/S, approved, lgtm, kind/cleanup

#4872 add short name for resourceinterpretercustomizations
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
Labels: kind/feature, approved, lgtm, size/XS
