Repository karmada-io/karmada, pull requests merged in 2024-07, with the labels that each got.

#5023 Adding FlinkDeployment CRD to supported third party resource customizations
  pkg/resourceinterpreter/customized/declarative/luavm/kube.go
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/testdata/desired-flinkdeployment.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/testdata/observed-flinkdeployment.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/testdata/status-file.yaml
Labels: kind/feature, approved, size/L, lgtm

#5110 add sbom to release assests
  .github/workflows/release.yml
Labels: size/S, approved, lgtm, kind/cleanup

#5112 Add release notes of v1.8.5, v1.9.4, v1.10.2
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.8.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, lgtm, kind/cleanup

#5097 charts: Adding TLS Certificate Authentication to gRPC
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
Labels: kind/feature, size/S, approved, lgtm

#5117 Automated cherry pick of #5110: add sbom to release assests
  .github/workflows/release.yml
Labels: size/S, approved, lgtm

#5113 cleanup helm chart
  charts/karmada/templates/post-install-job.yaml
  charts/karmada/values.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5119 set the permissions required for job in ci-image-scanning.yaml
  .github/workflows/ci-image-scanning.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#5077 additional print columns for CRDs: `ResourceInterpreterCustomization`…
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/apis/policy/v1alpha1/propagation_types.go
Labels: kind/feature, kind/api-change, approved, lgtm, size/M

#5082 Define top level Permission for dockerhub-latest-chart.yml (latest chart to Dockerhub) work flow
  .github/workflows/dockerhub-latest-chart.yml
Labels: kind/feature, approved, lgtm, size/XS, ok-to-test

#5081 Define top level Permission for lint-chart.yaml (Chart Lint) workflow
  .github/workflows/lint-chart.yaml
Labels: kind/feature, size/XS

#5123 set Minimum GITHUB_TOKEN permissions to github workflow
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-chart.yml
  .github/workflows/dockerhub-released-image.yml
  .github/workflows/release.yml
  .github/workflows/swr-latest-image.yml
  .github/workflows/swr-released-image.yml
Labels: size/S, approved, lgtm, kind/cleanup

#5114 Improve code reusability
  operator/pkg/certs/certs.go
Labels: approved, lgtm, size/XS

#5080 Define top level Permission for fossa.yml (FOSSA) workflow
  .github/workflows/fossa.yml
Labels: kind/feature, approved, lgtm, size/XS

#5111 Switch openapi-gen from k8s.io/code-generator to k8s.io/kube-openapi
  hack/tools/tools.go
  hack/update-codegen.sh
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, kind/cleanup

#5131 Correct licenses format
  pkg/apis/autoscaling/v1alpha1/cronfederatedhpa_types.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
  pkg/registry/cluster/storage/aggregate.go
  pkg/util/helper/cronfederatedhpa.go
  pkg/util/lifted/discovery_test.go
  pkg/webhook/cronfederatedhpa/validating.go
  pkg/webhook/resourcedeletionprotection/validating.go
  test/e2e/cronfederatedhpa_test.go
  test/e2e/federatedhpa_test.go
  test/e2e/framework/cronfederatedhpa.go
  test/e2e/framework/federatedhpa.go
Labels: approved, lgtm, size/M, kind/cleanup

#5132 Automated cherry pick of #4899: chore: let kube version of artifaces/deploy/karmada-apiserver
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  hack/deploy-karmada.sh
Labels: size/S, approved, lgtm

#5134 Automated cherry pick of #4899: chore: let kube version of artifaces/deploy/karmada-apiserver
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  hack/deploy-karmada.sh
Labels: size/S, approved, lgtm

#5137 Define top level Permission for lint-chart.yaml (Chart Lint) workflow
  .github/workflows/lint-chart.yaml
Labels: kind/feature, approved, lgtm, size/XS

#5133 Automated cherry pick of #4899: chore: let kube version of artifaces/deploy/karmada-apiserver
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/kube-controller-manager.yaml
  hack/deploy-karmada.sh
Labels: size/S, approved, lgtm, tide/merge-method-squash

#5138 Unify column names and add missing age column
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/work/v1alpha1/work_types.go
  pkg/apis/work/v1alpha2/binding_types.go
Labels: approved, lgtm, size/M, kind/cleanup

#5149 Skip generating proto for kubernetes apis in vendor
  hack/update-estimator-protobuf.sh
Labels: size/S, approved, lgtm, kind/cleanup

#5148 Remove unused cleanup code in endpointslice-controller
  pkg/controllers/mcs/endpointslice_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#5147 Remove managed label in collected endpointslice and derived service
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_import_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5086 Align federated GitRepository's observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/desired-gitrepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/observed-gitrepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/status-file.yaml
Labels: kind/feature, approved, lgtm, size/M

#5142 ci: delete the step for upgrade/downupgrade karmada-apiserver.
  .github/workflows/ci-schedule-compatibility.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5153 Transplant propagation policy finalizer to karmada-webhook
  pkg/detector/detector.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating.go
Labels: size/S, approved, lgtm, kind/cleanup

#5069 Define top level Permission for ci-schedule workflow
  .github/workflows/ci-schedule.yml
Labels: kind/feature, approved, lgtm, size/XS

#5057 Align federated CloneSet's observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/desired-cloneset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/observed-cloneset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/status-file.yaml
Labels: kind/feature, approved, size/L, lgtm

#5154 Fix mockgen generated files not group imports issue
  hack/update-import-aliases.sh
  hack/update-mocks.sh
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/testing/mock_interface.go
Labels: size/S, approved, lgtm, kind/cleanup

#5144 GroupClusters should sort by score and availableReplica count
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/util_test.go
Labels: kind/feature, approved, lgtm, size/M

#5164 Add more columns for cluster
  pkg/printers/internalversion/printers.go
  pkg/printers/internalversion/printers_test.go
Labels: kind/feature, approved, lgtm, size/M

#5139 Expose containing port of serving metrics
  charts/karmada/templates/karmada-agent.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-scheduler.yaml
Labels: size/S, approved, lgtm

#5168 Expose metrics port for helm installation
  charts/karmada-operator/templates/karmada-operator-deployment.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-webhook.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5169 Expose metrics port for karmadactl installation
  pkg/karmadactl/addons/descheduler/manifests.go
  pkg/karmadactl/addons/estimator/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/register/register.go
Labels: approved, lgtm, size/M, kind/cleanup

#5180 Automated cherry pick of #5144: GroupClusters should sort by score and availableReplica count
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/util_test.go
Labels: approved, lgtm, size/M

#4620 `karmadactl`: Add the reserved label `karmada.io/system` to resources created by the `join` command
  pkg/karmadactl/register/register.go
  pkg/util/constants.go
  pkg/util/credential.go
Labels: kind/feature, approved, lgtm, size/M

#5127 feat: karmadactl add ca-cert-path and ca-key-path opts
  pkg/karmadactl/cmdinit/cert/cert.go
  pkg/karmadactl/cmdinit/cert/cert_test.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: kind/feature, approved, lgtm, size/M

#5177 Adopt deprecated AddToScheme functions
  pkg/apis/cluster/install/install.go
  pkg/apis/search/install/install.go
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/util/gclient/gclient.go
Labels: approved, lgtm, size/M, kind/cleanup

#5184 replace RecommendedOptions with needed subset options in karmada-aggregate-apiserver component
  cmd/aggregated-apiserver/app/options/options.go
  cmd/aggregated-apiserver/app/options/validation.go
Labels: approved, lgtm, size/M, kind/cleanup

#5186 replace RecommendedOptions with needed subset options in karmada-search component
  cmd/karmada-search/app/karmada-search.go
  cmd/karmada-search/app/options/options.go
  cmd/karmada-search/app/options/validation.go
Labels: approved, lgtm, size/M, kind/cleanup

#5165 Align federated DaemonSet's observedGeneration semantics with its native
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/resourceinterpreter/default/native/reflectstatus.go
  pkg/resourceinterpreter/default/native/status_type.go
Labels: kind/feature, approved, size/L, lgtm

#5209 Update karmada-apiserve and kube-controller-manager to v1.29.6 by default.
  charts/karmada/README.md
  charts/karmada/values.yaml
  hack/deploy-karmada.sh
  operator/README.md
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: size/S, approved, lgtm, kind/cleanup

#5195 test/e2e/karmadactl_test.go: test logs command
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5140 add security-insights.yml
  SECURITY-INSIGHTS.yml
Labels: approved, kind/documentation, lgtm, size/M

#5188 Fix the issue of residual work in the MultiClusterService feature.
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/util/helper/work.go
Labels: kind/bug, size/S, approved, lgtm

#5192 test/e2e/karmadactl_test.go: test version command
  test/e2e/karmadactl_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#5211 Automated cherry pick of #5188: Fix the issue of residual work in the MultiClusterService
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/util/helper/work.go
Labels: size/S, approved, lgtm

#5212 Automated cherry pick of #5188: Fix the issue of residual work in the MultiClusterService
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/util/helper/work.go
Labels: size/S, approved, lgtm

#5190 test/e2e/karmadactl_test.go: test get command
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5213 Automated cherry pick of #5188: Fix the issue of residual work in the MultiClusterService
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/util/helper/work.go
Labels: size/S, approved, lgtm

#5167 Align federated daemonsets.apps.kruise.io observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/desired-daemonset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/observed-daemonset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/status-file.yaml
Labels: kind/feature, approved, size/L, lgtm

#5191 test/e2e/karmadactl_test.go: test describe command
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5222 Add release notes of v1.8.6, v1.9.5, v1.10.3
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.8.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, lgtm, kind/cleanup

#5174 Add missing command line arguments for karmada-operator
  operator/cmd/operator/app/operator.go
  operator/cmd/operator/app/options/options.go
Labels: size/S, approved, lgtm, kind/cleanup

#5215 Adding generic handling of priorityclass + namespace for flinkdeployment interpreter
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml
Labels: kind/feature, size/S, approved, lgtm

#5226 test/e2e: unify access to cluster members utilizing `framework.ClusterMembers()[i]`
  test/e2e/aggregatedapi_test.go
  test/e2e/clusteraffinities_test.go
  test/e2e/dependenciesdistributor_test.go
  test/e2e/fieldselector_test.go
  test/e2e/karmadactl_test.go
  test/e2e/lazy_activation_policy_test.go
  test/e2e/mcs_test.go
  test/e2e/preemption_test.go
  test/e2e/rescheduling_test.go
  test/e2e/search_test.go
  test/e2e/tainttoleration_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#5196 Align federated helmrepositories.source.toolkit.fluxcd.io observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/desired-helmrepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/observed-helmrepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/status-file.yaml
Labels: approved, lgtm, size/M

#5210 test/e2e/karmadactl_test.go: test token command
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5118 [Proposal] Support for cluster-level resource propagation pause and resume capabilities
  docs/proposals/dispatch-suspension/README.md
Labels: approved, size/L, kind/documentation, lgtm, kind/design

#5189 make cleanup with multiclusterservice controllers
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/util/constants.go
Labels: approved, lgtm, size/M, kind/cleanup

#5221 test/e2e/karmadactl_test.go: test options command
  test/e2e/karmadactl_test.go
Labels: size/S, approved, lgtm, kind/failing-test

#4575 complete the e2e test case scenarios for clusterpp
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/coverage_docs/clusterpropagationpolicy_test.md
  test/e2e/framework/clusterpropagationpolicy.go
  test/e2e/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5239 test: unify access to cluster members utilizing `framework.ClusterMembers()` as input parameter
  test/e2e/federatedresourcequota_test.go
  test/helper/policy.go
Labels: size/S, approved, lgtm, kind/cleanup

#5175 improve karmadactl unit test: check the cert file exist
  pkg/karmadactl/cmdinit/cert/cert_test.go
Labels: approved, lgtm, size/M

#5193 Align federated buckets.source.toolkit.fluxcd.io observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/desired-bucket.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/observed-bucket.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/status-file.yaml
Labels: kind/feature, approved, lgtm, size/M

#5197 Align federated ocirepositories.source.toolkit.fluxcd.io observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/desired-ocirepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/observed-ocirepository.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/status-file.yaml
Labels: kind/feature, approved, lgtm, size/M

#5194 Align federated helmcharts.source.toolkit.fluxcd.io observedGeneration semantics with its native
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/desired-helmchart.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/observed-helmchart.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/status-file.yaml
Labels: kind/feature, approved, size/L, lgtm

#5246 relabel webhooks to make it obvious they belong to karmada
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
Labels: kind/feature, size/S, approved, lgtm

#5253 fix: kustomize syntax for webhook caBundle
  charts/karmada/_crds/patches/webhook_in_clusterresourcebindings.yaml
  charts/karmada/_crds/patches/webhook_in_resourcebindings.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#5243 add karmada.io/system label to created execution namespaces
  pkg/controllers/cluster/cluster_controller.go
  pkg/karmadactl/util/idempotency.go
Labels: kind/feature, approved, lgtm, size/XS

#5247 add metrics for recreate/update resource event when sync work status
  pkg/controllers/status/work_status_controller.go
  pkg/metrics/resource.go
Labels: kind/feature, approved, lgtm, size/M

#5252 fix: `ClusterResourceBinding` scope in `MutatingWebhookConfiguration`
  charts/karmada/templates/_karmada_webhook_configuration.tpl
Labels: kind/bug, approved, lgtm, size/XS

#5255 fix unexpected interference between different e2e use cases
  test/e2e/clusterpropagationpolicy_test.go
Labels: approved, lgtm, size/XS, kind/failing-test

#5261 e2e: clusterresourcebinding permanent-id label
  test/e2e/clusterresourcebinding_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#5155 cleanup: use patches instead to patchesStrategicMerge for kustomize.
  charts/karmada/_crds/kustomization.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#5264 fix unexpected interference between different e2e use cases
  test/e2e/clusterpropagationpolicy_test.go
  test/e2e/propagationpolicy_test.go
Labels: approved, lgtm, size/XS, kind/failing-test

#5145 Proposal: Custom CRD Download Strategy Support for Karmada Operator
  docs/proposals/operator-custom-crd-download-strategy/README.md
Labels: approved, size/L, lgtm, kind/design

#5223 Standardize the health probe arguments
  artifacts/agent/karmada-agent.yaml
  charts/karmada/templates/karmada-agent.yaml
  cmd/agent/app/agent.go
  cmd/agent/app/options/options.go
  cmd/agent/app/options/validation.go
  cmd/agent/app/options/validation_test.go
  pkg/karmadactl/cmdinit/utils/examples.go
  pkg/karmadactl/register/register.go
Labels: kind/feature, approved, lgtm, size/M, kind/cleanup, kind/deprecation

#5259 optimization: add retry when clean up mark from resourcetemplate failed
  pkg/detector/detector.go
Labels: approved, lgtm, size/M, kind/cleanup

#5262 Automated cherry pick of #5252: fix: `ClusterResourceBinding` scope in
  charts/karmada/templates/_karmada_webhook_configuration.tpl
Labels: approved, lgtm, size/XS

#5263 print all binding and related objects to log file after each e2e failure case
  test/e2e/suite_log_test.go
  test/e2e/suite_test.go
Labels: approved, size/L, lgtm, kind/flake

#5234 only generate json patch for status filed when patchBindingStatus
  pkg/scheduler/scheduler.go
  pkg/util/helper/patch.go
Labels: size/S, approved, lgtm, kind/cleanup

#5279 Fix incorrect error code judgment in e2e tests
  test/e2e/failover_test.go
  test/e2e/framework/cluster.go
  test/e2e/suite_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#5280 [Cleanup] update pluginToClusterScores length from filterPlugins length to scorePlugins length
  pkg/scheduler/framework/runtime/framework.go
Labels: approved, lgtm, size/XS, kind/cleanup
