Repository karmada-io/karmada, pull requests merged in 2024-11, with the labels that each got.

#5769 Restrict supported service types of Karamda APIServer supported by karmada-operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
Labels: kind/api-change, approved, lgtm, size/M, kind/cleanup

#5764 Stop bump krew for release-1.10
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#5599 Proposal: Add API Server Service Information to `KarmadaStatus`
  docs/proposals/karmada-operator/api-server-service-status/README.md
Labels: approved, size/L, lgtm, kind/design

#5773 enable LoadBalancer type karmada-apiserver service in operator
  operator/pkg/tasks/init/upload.go
Labels: kind/feature, size/S, approved, lgtm

#5775 Add API Server Service Information to `KarmadaStatus`
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/controller/karmada/planner.go
  operator/pkg/controller/karmada/planner_test.go
Labels: kind/feature, approved, lgtm, size/M

#4451 Enhanced forced deletion on karmadactl unjoin
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/unregister/unregister.go
  pkg/karmadactl/util/cluster.go
Labels: kind/feature, approved, size/L, lgtm

#5780 fix crb_status_controller ut is referencing namespaced objects
  pkg/controllers/status/crb_status_controller_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#5778 pkg: unit test aggregatedAPIServer
  pkg/aggregatedapiserver/apiserver.go
  pkg/aggregatedapiserver/apiserver_test.go
Labels: approved, size/L, lgtm

#5765 pkg/karmadactl/addons: unit test descheduler
  pkg/karmadactl/addons/descheduler/descheduler.go
  pkg/karmadactl/addons/descheduler/descheduler_test.go
  pkg/karmadactl/addons/estimator/estimator.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter_test.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/addons/utils/helpers.go
  pkg/karmadactl/register/register.go
Labels: approved, size/L, lgtm

#5610 cluster proxy transport disable keepalive
  pkg/util/proxy/proxy.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5759 pkg/karmadactl/cmdinit: unit test bootstraptoken
  pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap.go
  pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap_test.go
Labels: approved, size/L, lgtm

#5792 Added unit tests for scheduler's cache package
  pkg/util/lifted/scheduler/cache/cache_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#5795 pkg/search: unit test karmada search APIServer
  pkg/search/apiserver.go
  pkg/search/apiserver_test.go
Labels: approved, size/L, lgtm

#5770 Added unit tests for the scheduler cache snapshot functionality
  pkg/util/lifted/scheduler/cache/snapshot_test.go
Labels: kind/feature, approved, size/L, lgtm

#5786 pkg/karmadactl/cmdinit/karmada: unit test check
  pkg/karmadactl/cmdinit/karmada/check_test.go
Labels: approved, size/L, lgtm

#5804 [UT] cancel concurrent test for SetupWithManager
  pkg/controllers/namespace/namespace_sync_controller_test.go
  pkg/controllers/remediation/remedy_controller_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#5798 Added unit tests for pkg/util/helper/workstatus.go
  pkg/util/helper/workstatus_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5808 Bump controller-gen to v0.16.5
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
  hack/update-crdgen.sh
  operator/config/crds/operator.karmada.io_karmadas.yaml
Labels: approved, size/XL, lgtm, kind/cleanup

#5801 karmada-search: support field selector for corev1 resources
  pkg/search/proxy/framework/plugins/cache/apis/core/v1/conversion.go
  pkg/search/proxy/framework/plugins/cache/apis/core/v1/register.go
  pkg/search/proxy/framework/plugins/cache/cache.go
  pkg/search/proxy/framework/plugins/cache/scheme.go
Labels: kind/feature, approved, size/L, lgtm

#5673 image-scanning: fix ratelimiting error when downloading vulnerability db from ghcr.io
  .github/workflows/ci-image-scanning-on-schedule.yml
  .github/workflows/ci-image-scanning.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#5816 feat(stateful failover support) Introduce PurgeMode to GracefulEvictionTask in ResourceBinding
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, lgtm, size/M

#5493 Added tests for controllers/deploymentreplicassyncer
  pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller_test.go
Labels: kind/feature, approved, size/XL, lgtm, kind/failing-test

#5810 pkg/search: unit test controller
  pkg/search/controller.go
  pkg/search/controllers_test.go
Labels: approved, size/XL, lgtm

#5821 Support PurgeMode setting in evection tasks
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/apis/work/v1alpha2/binding_types_helper_test.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, approved, lgtm, size/M

#5794 Proposal: Support Custom CA Certificate for Karmada Instance in Operator
  docs/proposals/karmada-operator/custom_ca_cert/README.md
  docs/proposals/karmada-operator/custom_ca_cert/architecture-overview.png
Labels: approved, size/L, lgtm, kind/design

#5820 Bump Golang version to v1.22.9
  .go-version
  go.mod
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#5822 Added unit tests for general estimator package
  pkg/estimator/client/general_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5828 Added unit tests for reflect status interpreter
  pkg/resourceinterpreter/default/native/reflectstatus_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#5814 refactor operator module validation logic for Karmada objects
  operator/pkg/controller/karmada/controller.go
  operator/pkg/controller/karmada/validating.go
  operator/pkg/controller/karmada/validating_test.go
  operator/pkg/init.go
  operator/pkg/tasks/init/etcd.go
Labels: approved, size/L, lgtm, kind/cleanup

#5834 fix operatore ci fail for invalid crdtarball
  hack/deploy-karmada-operator.sh
  hack/local-up-karmada-by-operator.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#5826 Update application failover purge mode comments
  pkg/apis/policy/v1alpha1/propagation_types.go
Labels: size/S, approved, lgtm, kind/cleanup

#5837 Standardize the naming conventions for karmada system roles
  artifacts/deploy/admin-clusterrole-aggregation.yaml
  artifacts/deploy/bootstrap-token-configuration.yaml
  charts/karmada/templates/_karmada_bootstrap_token_configuration.tpl
  pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap.go
  pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
Labels: approved, lgtm, size/M, kind/cleanup

#5809 feat(dependenciesdistributor): introduce --concurrent-dependent-resource-syncs flag
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/app/options/options.go
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: kind/feature, size/S, approved, lgtm

#5841 Update group_clusters.go
  pkg/scheduler/core/spreadconstraint/group_clusters.go
Labels: approved, kind/documentation, lgtm, size/XS

#5838 Added unit tests for the CustomizedInterpreter
  pkg/resourceinterpreter/customized/webhook/customized_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#5793 minimize the RBAC permissions for the pull mode cluster
  artifacts/deploy/bootstrap-token-configuration.yaml
  charts/karmada/templates/_karmada_bootstrap_token_configuration.tpl
  pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/rbac.go
  pkg/karmadactl/cmdinit/karmada/rbac_test.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/unregister/unregister.go
  pkg/karmadactl/unregister/unregister_test.go
  pkg/karmadactl/util/work.go
  pkg/util/rbac.go
Labels: kind/feature, approved, size/XXL, lgtm

#5835 Adopt generic ratelimter queue
  pkg/metricsadapter/controller.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/search/controller.go
  pkg/servicenameresolutiondetector/coredns/detector.go
  pkg/sharedcli/ratelimiterflag/ratelimiterflag.go
  pkg/util/worker.go
Labels: approved, lgtm, size/M, kind/cleanup

#5849 Automated cherry pick of #4451: enhanced forced deletion on karmadactl unjoin
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/util/cluster.go
  test/e2e/rescheduling_test.go
Labels: approved, size/L, lgtm

#5845 Automated cherry pick of #4451: enhanced forced deletion on karmadactl unjoin
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/util/cluster.go
Labels: approved, size/L, lgtm

#5848 Automated cherry pick of #4451: enhanced forced deletion on karmadactl unjoin
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/util/cluster.go
Labels: approved, size/L, lgtm

#5844 Automated cherry pick of #5318: fix expected patch operations may be missed when
  pkg/controllers/status/common.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/crb_status_controller_test.go
  pkg/controllers/status/rb_status_controller.go
  pkg/controllers/status/rb_status_controller_test.go
  pkg/controllers/status/work_status_controller.go
  pkg/util/helper/patch.go
  pkg/util/helper/patch_test.go
  pkg/util/helper/status.go
  pkg/util/helper/workstatus.go
  pkg/util/helper/workstatus_test.go
Labels: approved, size/XL, lgtm

#5853 Automated cherry pick of #5318: fix expected patch operations may be missed when
  pkg/controllers/status/common.go
  pkg/controllers/status/crb_status_controller.go
  pkg/controllers/status/crb_status_controller_test.go
  pkg/controllers/status/rb_status_controller.go
  pkg/controllers/status/rb_status_controller_test.go
  pkg/controllers/status/work_status_controller.go
  pkg/util/helper/patch.go
  pkg/util/helper/patch_test.go
  pkg/util/helper/status.go
  pkg/util/helper/workstatus.go
  pkg/util/helper/workstatus_test.go
Labels: approved, size/XL, lgtm

#5851 Update karmada-apiserver and kube-controller-manager to v1.31.3 by default
  charts/karmada/README.md
  charts/karmada/values.yaml
  hack/deploy-karmada.sh
  operator/README.md
  operator/config/samples/karmada-sample.yaml
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
Labels: size/S, approved, lgtm, kind/cleanup

#5852 publish releasenote for release v1.9.9, v1.10.7, v1.11.3
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.9.md
Labels: approved, size/L, kind/documentation, lgtm

#5854 etcd: update default version to 3.5.16-0
  artifacts/deploy/karmada-etcd.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
  operator/config/samples/karmada-sample.yaml
  operator/config/samples/karmada.yaml
  operator/pkg/constants/constants.go
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
Labels: size/S, approved, lgtm, kind/cleanup

#5691 Update types.go
  api/openapi-spec/swagger.json
  pkg/apis/cluster/types.go
  pkg/apis/cluster/v1alpha1/types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, size/L, kind/documentation, lgtm

#5842 Support Custom API Server CA Certificate for Karmada Instance in Operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/certs/certs.go
  operator/pkg/init.go
  operator/pkg/tasks/init/cert.go
  operator/pkg/tasks/init/data.go
  operator/pkg/tasks/init/test_helpers.go
Labels: kind/feature, approved, size/L, lgtm

#5856 fix flake test of TestUpdateClusterEventHandler
  pkg/search/controller.go
  pkg/search/controllers_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#5857 Automated cherry pick of #5840: Fix: karmada-metrics-adapter use the correct certificate when
  pkg/karmadactl/addons/metricsadapter/manifests.go
Labels: approved, lgtm, size/XS

#5825 add agentcsrapproving controller to auto approve agent csr
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/certificate/approver/agent_csr_approving.go
  pkg/util/certificate/csr.go
  pkg/util/certificate/csr_test.go
Labels: kind/feature, approved, size/L, lgtm

#5859 Automated cherry pick of #5840: Fix: karmada-metrics-adapter use the correct certificate when
  pkg/karmadactl/addons/metricsadapter/manifests.go
Labels: approved, lgtm, size/XS

#5863 feat(dependenciesdistributor): remove dependenciesdistributor concurrentreconciles
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: kind/feature, approved, lgtm, size/XS

#5874 cleanup csrapproving controller from kube-controller-manager
  artifacts/deploy/kube-controller-manager.yaml
  charts/karmada/values.yaml
  cmd/controller-manager/app/controllermanager.go
  operator/pkg/controlplane/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/register/register.go
Labels: kind/feature, size/S, approved, lgtm

#5879 Update taint-manager to config eviction task with purgeMode
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/cluster/taint_manager_test.go
Labels: kind/feature, size/S, approved, lgtm

#5873 pkg/karmadactl: unit test exec
  pkg/karmadactl/exec/exec.go
  pkg/karmadactl/exec/exec_test.go
Labels: approved, lgtm, size/M

#5865 let rb status controller onCreate predicate return true
  pkg/controllers/status/common.go
Labels: kind/bug, approved, lgtm, size/XS

#5861 Enable the deprecation check which was disabled for version upgrade
  .golangci.yml
  cmd/aggregated-apiserver/app/options/options.go
  cmd/karmada-search/app/karmada-search.go
  cmd/metrics-adapter/app/options/options.go
  pkg/util/grpcconnection/config.go
Labels: size/S, approved, lgtm, kind/deprecation

#5714 Redact sensitive information from the karmadactl init command output
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/examples.go
  pkg/karmadactl/cmdinit/utils/examples_test.go
Labels: kind/feature, approved, lgtm, size/M

#5885 Introduce StatePreservation to PropagationPolicy API
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#5886 Add Docs for Creating and Inspecting Karmada Instance by Operator
  charts/karmada-operator/README.md
Labels: approved, lgtm, size/M

#5703 karmada-operator: add CRDs archive verification to enhance file system robustness
  operator/pkg/tasks/init/crd.go
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: kind/feature, approved, size/L, lgtm

#5883 Automated cherry pick of #5865: let rb status controller onCreate predicate return true
  pkg/controllers/status/common.go
Labels: approved, lgtm, size/XS

#5882 Automated cherry pick of #5865: let rb status controller onCreate predicate return true
  pkg/controllers/status/common.go
Labels: approved, lgtm, size/XS

#5884 Automated cherry pick of #5865: let rb status controller onCreate predicate return true
  pkg/controllers/status/common.go
Labels: approved, lgtm, size/XS

#5713 karmadactl init: add CRDs archive verification to enhance file system robustness
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/utils/util.go
  pkg/util/validation/validation_test.go
Labels: kind/feature, approved, lgtm, size/M

#5887 Build PreservedLabelState when triggering evition in RB/CRB application controller
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/controllers/applicationfailover/common.go
  pkg/controllers/applicationfailover/common_test.go
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, approved, size/XL, lgtm

#5889 Cleanup works from cluster if purgemode is immediately
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
Labels: kind/feature, approved, lgtm, size/M

#5875 pkg/search/controllers_test: address flaky test
  pkg/search/controllers_test.go
Labels: approved, lgtm, size/M

#5890 Add ut for parseJSONValue function to cover the JSONPath main parse ability
  pkg/controllers/applicationfailover/common_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#5893 Inject preservedLabelState to the failover to clusters
  pkg/controllers/binding/common.go
Labels: kind/feature, approved, lgtm, size/M

#5897 Add stateful application failover status injection feature gate
  api/openapi-spec/swagger.json
  artifacts/deploy/karmada-controller-manager.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/controllers/applicationfailover/common.go
  pkg/controllers/applicationfailover/common_test.go
  pkg/controllers/binding/common.go
  pkg/features/features.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, approved, lgtm, size/M

#5899 Disable cluster failover by default which should be explicitly enabled by administrators
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/applicationfailover/common.go
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
  pkg/controllers/cluster/cluster_controller_test.go
  pkg/controllers/cluster/taint_manager.go
  pkg/features/features.go
Labels: kind/feature, approved, lgtm, size/M

#5850 Added unit tests for interpretation context handling
  pkg/resourceinterpreter/customized/webhook/request/resourceinterpretercontext_test.go
Labels: kind/feature, approved, size/XL, lgtm

#5896 publish release note for v1.12.0
  docs/CHANGELOG/CHANGELOG-1.12.md
Labels: approved, size/L, kind/documentation, lgtm
