Repository karmada-io/karmada, pull requests merged in 2025-06, with the labels that each got.

#6409 JSON logging support for Karmada controller manager component
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/controllermanager.go
  cmd/controller-manager/controller-manager.go
  pkg/features/features.go
Labels: approved, lgtm, size/M, tide/merge-method-squash

#6453 flakey test: Retry on failed deployment update
  test/e2e/framework/deployment.go
  test/e2e/suites/base/federatedresourcequota_test.go
Labels: approved, lgtm, size/M, kind/flake

#6444 Remove default-not-ready-toleration-seconds and default-unreachable-toleration-seconds flags
  artifacts/deploy/karmada-webhook.yaml
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
  operator/pkg/controlplane/webhook/manifests.go
  pkg/util/helper/taint.go
  pkg/util/helper/taint_test.go
  pkg/webhook/clusterpropagationpolicy/mutating.go
  pkg/webhook/clusterpropagationpolicy/mutating_test.go
  pkg/webhook/propagationpolicy/mutating.go
  pkg/webhook/propagationpolicy/mutating_test.go
  test/e2e/suites/base/clusteraffinities_test.go
  test/e2e/suites/base/failover_test.go
Labels: approved, size/L, lgtm, kind/deprecation

#6455 chore: update maintained versions to `1.14` and bump imageTag to `v1.14.0`
  .github/dependabot.yml
  .github/workflows/ci-image-scanning-on-schedule.yml
  .github/workflows/ci-schedule-compatibility.yaml
  operator/config/samples/karmada.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#6447 feat: make expiry configurable for root ca cert
  charts/karmada/templates/pre-install-job.yaml
  charts/karmada/values.yaml
Labels: approved, lgtm, size/XS

#6452 add helm index v1.14
  charts/index.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#6450 Remove failover-eviction-timeout flag in the karmada-controller-manager
  artifacts/deploy/karmada-controller-manager.yaml
  cmd/controller-manager/app/options/options.go
  operator/pkg/controlplane/manifests.go
Labels: approved, lgtm, size/XS, kind/deprecation

#6435 JSON logging for cluster controllers
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/taint_manager.go
Labels: approved, lgtm, size/M

#6442 added json logging support in karmada-agent
  artifacts/agent/karmada-agent.yaml
  cmd/agent/app/agent.go
  cmd/agent/main.go
Labels: kind/feature, approved, lgtm, size/M, tide/merge-method-squash

#6457 JSON logging support for Karmada scheduler-estimator
  artifacts/deploy/karmada-scheduler-estimator.yaml
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler-estimator/main.go
Labels: kind/feature, approved, lgtm, size/M

#6473 Add json logging support for karmada scheduler
  artifacts/deploy/karmada-scheduler.yaml
  cmd/scheduler/app/scheduler.go
  cmd/scheduler/main.go
Labels: kind/feature, approved, lgtm, size/M

#6466 JSON logging support for Karmada Search component
  artifacts/deploy/karmada-search.yaml
  cmd/karmada-search/app/karmada-search.go
  cmd/karmada-search/main.go
Labels: kind/feature, approved, lgtm, size/M

#6474 Fix workload scale up bypass FederatedResourceQuota check issue
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  test/e2e/suites/base/federatedresourcequota_test.go
  test/e2e/suites/base/scheduling_test.go
Labels: kind/bug, approved, size/L, lgtm

#6484 improve pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S, approved, lgtm, kind/cleanup

#6487 continue using klog with structured logging
  pkg/controllers/execution/execution_controller.go
Labels: approved, lgtm, size/M

#6477 Use rbSpec.clusters and rbSpec.ReplicaRequirements to calculate rb' resource usage
  pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6502 Automated cherry pick of #6474: fix the issue where federatedresourcequota becomes invalid
  pkg/controllers/binding/common.go
  pkg/controllers/binding/common_test.go
  test/e2e/framework/deployment.go
  test/e2e/suites/base/federatedresourcequota_test.go
  test/e2e/suites/base/scheduling_test.go
Labels: approved, size/L, lgtm

#6503 Automated cherry pick of #6477: use rbSpec.clusters and rbSpec.ReplicaRequirements to
  pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller_test.go
Labels: approved, size/L, lgtm
