Repository karmada-io/karmada, pull requests merged in 2025-03, with the labels that each got.

#6190 move Maintainers to community repo
  MAINTAINERS.md
Labels: size/S, approved, kind/documentation, lgtm

#6191 chore: remove deprecated --ca-cert-path from karmadactl
  pkg/karmadactl/register/register.go
Labels: approved, lgtm, size/XS

#6180 Fix issues with running multiple Karmada instances in the same namespace
  hack/deploy-karmada-operator.sh
  hack/local-up-karmada-by-operator.sh
  hack/operator-e2e-environment.sh
  operator/config/deploy/karmada-operator-clusterrole.yaml
  operator/config/deploy/karmada-operator-clusterrolebinding.yaml
  operator/config/deploy/karmada-operator-deployment.yaml
  operator/config/deploy/karmada-operator-serviceaccount.yaml
  operator/pkg/constants/constants.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/apiserver/manifests.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/etcd/manifests.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/metricsadapter/manifests.go
  operator/pkg/controlplane/metricsadapter/metricsadapter.go
  operator/pkg/controlplane/search/manifests.go
  operator/pkg/controlplane/search/search.go
  operator/pkg/controlplane/webhook/manifests.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/tasks/init/wait.go
  operator/pkg/util/apiclient/wait_test.go
Labels: kind/bug, approved, size/XL, lgtm

#6176 Proposal: Add Support to Configure Leaf Certificate Validity Period in Karmada Operator
  docs/proposals/karmada-operator/custom-leaf-cert-validity/README.md
Labels: approved, lgtm, kind/design, size/M

#6148 update object watcher metrics and simplify cluster object version recording
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/metrics/resource.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: approved, size/L, lgtm, kind/cleanup

#6196 add helm index v1.13.0
  charts/index.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#6198 remove extra symbol '/' in the karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-aggregated-apiserver.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#6193 Add Support to Configure Leaf Certificate Validity Period in Karmada Operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/tasks/init/cert.go
Labels: kind/feature, approved, lgtm, size/M

#6200 Automated cherry pick of #6180: Fix issues with running multiple Karmada instances in the
  hack/deploy-karmada-operator.sh
  hack/local-up-karmada-by-operator.sh
  hack/operator-e2e-environment.sh
  operator/config/deploy/karmada-operator-clusterrole.yaml
  operator/config/deploy/karmada-operator-clusterrolebinding.yaml
  operator/config/deploy/karmada-operator-deployment.yaml
  operator/config/deploy/karmada-operator-serviceaccount.yaml
  operator/pkg/constants/constants.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/apiserver/manifests.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/etcd/manifests.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/metricsadapter/manifests.go
  operator/pkg/controlplane/metricsadapter/metricsadapter.go
  operator/pkg/controlplane/search/manifests.go
  operator/pkg/controlplane/search/search.go
  operator/pkg/controlplane/webhook/manifests.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/tasks/init/wait.go
  operator/pkg/util/apiclient/wait_test.go
Labels: approved, size/XL, lgtm, tide/merge-method-squash

#6184 gencomponentdocs support module all to generate all karmada components docs
  hack/tools/gencomponentdocs/gen_component_docs.go
Labels: approved, lgtm, size/M, kind/cleanup

#6206 Fix the naming of the server certificate of karmada-scheduler-estimator
  artifacts/deploy/karmada-scheduler-estimator.yaml
  hack/deploy-karmada.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#6145 add the ratelimiter options parameter for controllers that are missing it
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/certificate/approver/agent_csr_approving.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/hpascaletargetmarker/hpa_scale_target_marker_controller.go
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/mcs/service_import_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
Labels: kind/feature, approved, size/L, lgtm

#6211 Update Works index with a unique name
  pkg/controllers/binding/binding_controller_test.go
  pkg/controllers/binding/cluster_resource_binding_controller_test.go
  pkg/controllers/status/crb_status_controller_test.go
  pkg/controllers/status/rb_status_controller_test.go
  pkg/util/helper/binding_test.go
  pkg/util/helper/index.go
  pkg/util/helper/work.go
  pkg/util/helper/work_test.go
  pkg/util/helper/workstatus_test.go
  pkg/util/indexregistry/fieldindex.go
Labels: approved, size/L, lgtm, kind/cleanup

#6043 feat: replace instruction annotation with work suspendDispatching field
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/ctrlutil/work_test.go
  pkg/controllers/mcs/common.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller_test.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/util/constants.go
  pkg/util/helper/predicate.go
  pkg/util/helper/predicate_test.go
  pkg/util/helper/work.go
  pkg/webhook/work/mutating.go
Labels: approved, size/L, lgtm, kind/deprecation

#6220 fix: typo error in karmadactl register
  pkg/karmadactl/register/register.go
Labels: size/S, approved, lgtm, kind/cleanup

#6214 Fix segmentation violation error in `agent` component
  cmd/agent/app/agent.go
Labels: kind/bug, approved, lgtm, size/XS

#6218 Bump golang to 1.23.7 and golangci-lint to 1.64.8
  .go-version
  go.mod
  hack/verify-staticcheck.sh
  pkg/controllers/binding/common.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/utilization.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/workloadrebalancer/workloadrebalancer_controller_test.go
  pkg/estimator/client/cache.go
  pkg/estimator/client/general.go
  pkg/estimator/server/estimate.go
  pkg/estimator/server/framework/plugins/resourcequota/resourcequota.go
  pkg/estimator/server/replica/replica.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
  pkg/resourceinterpreter/interpreter.go
  pkg/scheduler/core/generic_scheduler_test.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_cluster.go
  pkg/util/helper/binding.go
  pkg/util/helper/workstatus_test.go
  pkg/util/overridemanager/overridemanager.go
  pkg/webhook/interpreter/response.go
Labels: approved, lgtm, size/M, kind/cleanup

#6222 Automated cherry pick of #6214: Fix segmentation violation error in karmada-agent component
  cmd/agent/app/agent.go
Labels: approved, lgtm, size/XS

#6223 Automated cherry pick of #6214: Fix segmentation violation error in karmada-agent component
  cmd/agent/app/agent.go
Labels: approved, lgtm, size/XS

#6224 Automated cherry pick of #6214: Fix segmentation violation error in karmada-agent component
  cmd/agent/app/agent.go
Labels: approved, lgtm, size/XS

#6228 update mismatch log info in the taint-manager
  pkg/controllers/cluster/taint_manager.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6227 fix the issue where the binding gracefulEvictionTask can never be clear
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller_test.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller_test.go
Labels: kind/bug, approved, size/L, lgtm

#6209 add docs for configuring API Server sidecar in karmada operator
  operator/README.md
Labels: approved, kind/documentation, lgtm, size/M

#6236 Automated cherry pick of #6227: to prevent the generation judgment from always being false
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Labels: approved, size/L, lgtm

#6234 Automated cherry pick of #6227: to prevent the generation judgment from always being false
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller_test.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller_test.go
Labels: approved, size/L, lgtm

#6235 Automated cherry pick of #6227: to prevent the generation judgment from always being false
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller_test.go
  pkg/controllers/gracefuleviction/evictiontask.go
  pkg/controllers/gracefuleviction/evictiontask_test.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller_test.go
Labels: approved, size/L, lgtm

#6095 unify http ratelimiter for control plane client
  cmd/agent/app/agent.go
  cmd/aggregated-apiserver/app/options/options.go
  cmd/controller-manager/app/controllermanager.go
  cmd/descheduler/app/descheduler.go
  cmd/karmada-search/app/karmada-search.go
  cmd/metrics-adapter/app/options/options.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/scheduler.go
  cmd/webhook/app/webhook.go
Labels: kind/bug, size/S, approved, lgtm

#6208 e2e: add sidecar configuration e2e test
  test/e2e/suites/operator/api_sidecar_test.go
  test/e2e/suites/operator/suite_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6188 Fix missing ClusterRole, ClusterRoleBinding, and ServiceAccount for Custom Cert Mode in Helm Chart
  charts/karmada/templates/pre-install-job.yaml
Labels: kind/bug, approved, size/L, lgtm

#6242 Automated cherry pick of #6188: Fix Missing Role, RoleBinding, and ServiceAccount for Custom
  charts/karmada/templates/pre-install-job.yaml
Labels: approved, size/L, lgtm

#6241 Automated cherry pick of #6188: Fix Missing Role, RoleBinding, and ServiceAccount for Custom
  charts/karmada/templates/pre-install-job.yaml
Labels: approved, size/L, lgtm

#6243 release-1.11: remove charts maintainer
  .github/workflows/lint-chart.yaml
  charts/OWNERS
  charts/karmada/Chart.yaml
  hack/setup-dev-base.sh
Labels: approved, size/L, lgtm, kind/cleanup

#6221 Update Karmada CI and Documentation
  .github/dependabot.yml
  .github/workflows/ci-image-scanning-on-schedule.yml
  .github/workflows/ci-schedule-compatibility.yaml
  operator/config/samples/karmada.yaml
Labels: size/S, approved, kind/documentation, lgtm

#6240 Automated cherry pick of #6188: Fix Missing Role, RoleBinding, and ServiceAccount for Custom
  charts/karmada/templates/pre-install-job.yaml
Labels: approved, size/L, lgtm
