Repository karmada-io/karmada, pull requests merged in 2025-04, with the labels that each got.

#6249 don't add cluster name to hostname field when aggregate service status
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/resourceinterpreter/default/native/aggregatestatus_test.go
  test/e2e/suites/base/resource_test.go
Labels: kind/bug, size/S, approved, lgtm

#6250 Update alpine version used by karmadactl init
  charts/karmada/README.md
  operator/config/samples/karmada.yaml
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: size/S, approved, kind/documentation, lgtm

#6199 fix(dependenciesdistributor): reduce update trigger
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
Labels: kind/feature, approved, size/L, lgtm

#6253 fix: A new pull-mode cluster may overwrite the existing member clusters
  cmd/agent/app/agent.go
  pkg/karmadactl/join/join.go
  pkg/karmadactl/join/join_test.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
Labels: kind/bug, approved, size/L, lgtm

#5830 pkg/karmadactl: unit test deinit
  pkg/karmadactl/deinit/deinit.go
  pkg/karmadactl/deinit/deinit_test.go
Labels: approved, size/L, lgtm

#6265 cleanup unused err check
  pkg/util/cluster.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6262 Automated cherry pick of #6253: fix: A new pull-mode cluster may overwrite the existing
  cmd/agent/app/agent.go
  pkg/karmadactl/join/join.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
Labels: approved, size/L, lgtm

#6259 Automated cherry pick of #6253: fix: A new pull-mode cluster may overwrite the existing
  cmd/agent/app/agent.go
  pkg/karmadactl/join/join.go
  pkg/karmadactl/join/join_test.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
Labels: approved, size/L, lgtm

#6261 Automated cherry pick of #6253: fix: A new pull-mode cluster may overwrite the existing
  cmd/agent/app/agent.go
  pkg/karmadactl/join/join.go
  pkg/util/cluster.go
  pkg/util/cluster_test.go
Labels: approved, size/L, lgtm

#6268 Update Kubernetes compatibility
  README.md
Labels: size/S, approved, kind/documentation, lgtm

#6238 publish release notes for v1.11.8,v1.12.5,v1.13.1,v1.14.0-alpha.1
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.13.md
  docs/CHANGELOG/CHANGELOG-1.14.md
Labels: approved, size/L, kind/documentation, lgtm

#6258 when cluster is not-ready doesn't cleanup MultiClusterService and EndpointSlice work
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/multiclusterservice/mcs_controller_test.go
Labels: kind/feature, approved, lgtm, size/M

#6272 Bump go version to 1.23.8
  .go-version
  go.mod
Labels: approved, lgtm, size/XS, kind/cleanup

#6270 fix the issue where discovery-timeout fails to work properly
  pkg/karmadactl/addons/utils/helpers.go
  pkg/karmadactl/cmdinit/utils/deploy.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/check.go
Labels: kind/bug, size/S, approved, lgtm

#6280 Automated cherry pick of #6270: fix the issue where discovery-timeout fails to work properly
  pkg/karmadactl/addons/utils/helpers.go
  pkg/karmadactl/cmdinit/utils/deploy.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/check.go
Labels: size/S, approved, lgtm

#5334 test/e2e/karmadactl_test.go: test register command
  test/e2e/suites/base/karmadactl_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#6279 Automated cherry pick of #6270: fix the issue where discovery-timeout fails to work properly
  pkg/karmadactl/addons/utils/helpers.go
  pkg/karmadactl/cmdinit/utils/deploy.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/check.go
Labels: size/S, approved, lgtm

#6278 Automated cherry pick of #6270: fix the issue where discovery-timeout fails to work properly
  pkg/karmadactl/addons/descheduler/descheduler.go
  pkg/karmadactl/addons/estimator/estimator.go
  pkg/karmadactl/addons/metricsadapter/metricsadapter.go
  pkg/karmadactl/addons/search/search.go
  pkg/karmadactl/cmdinit/utils/deploy.go
  pkg/karmadactl/register/register.go
  pkg/karmadactl/util/check.go
Labels: size/S, approved, lgtm

#6215 feat: add build_info metrics and go runtime metrics for karmada
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  cmd/descheduler/app/descheduler.go
  cmd/metrics-adapter/app/options/options.go
  cmd/scheduler-estimator/app/scheduler-estimator.go
  cmd/scheduler/app/scheduler.go
  cmd/webhook/app/webhook.go
  operator/cmd/operator/app/operator.go
Labels: kind/feature, approved, lgtm, size/M

#6252 Deduplicate and sort status for Service and Ingress when aggregating status
  pkg/resourceinterpreter/default/native/aggregatestatus.go
  pkg/util/helper/ingress.go
  pkg/util/helper/ingress_test.go
  pkg/util/helper/service.go
  pkg/util/helper/service_test.go
Labels: kind/feature, approved, size/XL, lgtm

#6237 Upgrade golangci-lint from v1.64.8 to v2.0.2
  .golangci.yml
  hack/verify-staticcheck.sh
Labels: approved, size/L, lgtm, kind/cleanup

#6289 Fix lint issue ST1019
  .golangci.yml
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  operator/pkg/tasks/init/cert_test.go
  pkg/controllers/unifiedauth/unified_auth_controller_test.go
  pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo_test.go
  pkg/scheduler/scheduler_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#6291 Fix lint issue QF1004
  .golangci.yml
  hack/tools/gencomponentdocs/postprocessing.go
  hack/tools/genkarmadactldocs/gen_karmadactl_docs.go
  pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6292 Fix lint issue QF1003
  .golangci.yml
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/detector/detector.go
  pkg/estimator/server/framework/interface.go
  pkg/estimator/server/framework/plugins/resourcequota/resourcequota.go
  pkg/scheduler/framework/interface.go
  pkg/util/helper/mcs.go
Labels: approved, lgtm, size/M, kind/cleanup

#6290 Fix lint issue ST1005
  .golangci.yml
  hack/tools/gencomponentdocs/gen_component_docs.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6285 Update bind addresses to use POD_IP for local-up script
  artifacts/agent/karmada-agent.yaml
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-metrics-adapter.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-search.yaml
  artifacts/deploy/karmada-webhook.yaml
Labels: kind/feature, approved, lgtm, size/M

#6295 Add comment for disabling QF1008
  .golangci.yml
Labels: approved, lgtm, size/XS, kind/cleanup

#6297 Fix lint issue QF1001
  .golangci.yml
  pkg/karmadactl/get/get.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6294 Move index register to dedicated package
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/binding/binding_controller_test.go
  pkg/controllers/binding/cluster_resource_binding_controller_test.go
  pkg/controllers/status/crb_status_controller_test.go
  pkg/controllers/status/rb_status_controller_test.go
  pkg/util/helper/binding_test.go
  pkg/util/helper/index.go
  pkg/util/helper/work_test.go
  pkg/util/helper/workstatus_test.go
  pkg/util/indexregistry/fieldindex.go
  pkg/util/indexregistry/fieldindex_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6296 Fix lint issue ST1011
  .golangci.yml
  cmd/service-name-resolution-detector-example/app/options/coredns.go
  cmd/service-name-resolution-detector-example/app/service-name-resolution-detector.go
  pkg/servicenameresolutiondetector/coredns/detector.go
  pkg/servicenameresolutiondetector/coredns/detector_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#6287 update Flink interpreter to check error when job state is not published
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml
Labels: approved, lgtm, size/XS

#6299 Add comment for disabling ST1000 and package-comments
  .golangci.yml
Labels: size/S, approved, lgtm, kind/cleanup

#6301 publish release note for v1.14.0-alpha.2
  docs/CHANGELOG/CHANGELOG-1.14.md
Labels: approved, kind/documentation, lgtm, size/M

#6283 Proposal: Add PodDisruptionBudget (PDB) Support in the Karmada Operator
  docs/proposals/karmada-operator/pod-disruption-budget/README.md
Labels: approved, size/L, lgtm, kind/design, tide/merge-method-squash

#6303 fix fhpa metrics issue introduced by #6300
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/client.go
Labels: size/S, approved, lgtm

#6309 chore: add kubernetes 1.32.0 to ci
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/installation-chart.yaml
  .github/workflows/installation-cli.yaml
  .github/workflows/installation-operator.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#6306 feat: Add SchedulePriority e2e tests
  test/e2e/framework/priorityclass.go
  test/e2e/suites/base/schedule_priority_test.go
  test/helper/priorityclass.go
Labels: kind/feature, approved, size/L, lgtm

#6314 fix fhpa metrics issue introduced by #6300
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/client.go
Labels: size/S, approved, lgtm

#6313 fix fhpa metrics issue introduced by #6300
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/client.go
Labels: size/S, approved, lgtm

#6312 fix fhpa metrics issue introduced by #6300
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/client.go
Labels: size/S, approved, lgtm

#5813 disable deepcopy for list action
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/detector/preemption.go
  pkg/util/overridemanager/overridemanager.go
Labels: kind/feature, approved, lgtm, size/M

#5592 operator/pkg/controlplane/etcd: remove redundant `EtcdPeerServiceName`
  operator/pkg/controlplane/etcd/etcd.go
Labels: approved, lgtm, size/XS, kind/cleanup

#5785 pkg/karmadactl: unit test apply command
  pkg/karmadactl/apply/apply.go
  pkg/karmadactl/apply/apply_test.go
Labels: approved, size/L, lgtm

#5539 pkg/webhook: refactor Multi-Cluster Service test
  pkg/webhook/multiclusterservice/mutating_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#6318 .github/workflows/installation-charts.yaml: update Helm and Kustomize to latest versions
  .github/workflows/installation-chart.yaml
Labels: approved, lgtm, size/XS

#5638 operator/pkg/tasks/init: unit test upload
  operator/pkg/tasks/init/upload_test.go
Labels: approved, size/L, lgtm

#6150 Add deepequal check for objectWatcher.Update()
  pkg/controllers/status/work_status_controller.go
  pkg/util/objectwatcher/objectwatcher.go
Labels: kind/feature, approved, lgtm, size/M

#6326 fix proxy request error with pb content type
  pkg/search/proxy/controller.go
  pkg/search/proxy/framework/interface.go
  pkg/search/proxy/framework/plugins/cache/cache.go
  pkg/search/proxy/framework/plugins/cluster/cluster.go
  pkg/search/proxy/framework/plugins/cluster/cluster_test.go
  test/e2e/suites/base/search_test.go
Labels: kind/bug, approved, size/L, lgtm

#6324 Update bind addresses to use POD_IP for helm
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-agent.yaml
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-metrics-adapter.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/templates/karmada-webhook.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#6323 Update bind addresses to use POD_IP for karmadactl
  pkg/karmadactl/addons/descheduler/manifests.go
  pkg/karmadactl/addons/estimator/manifests.go
  pkg/karmadactl/addons/metricsadapter/manifests.go
  pkg/karmadactl/addons/search/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
Labels: approved, lgtm, size/M, kind/cleanup

#6321 Update bind addresses to use POD_IP for karmada-operator
  operator/pkg/controlplane/apiserver/manifests.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/metricsadapter/manifests.go
  operator/pkg/controlplane/search/manifests.go
  operator/pkg/controlplane/webhook/manifests.go
Labels: approved, lgtm, size/M, kind/cleanup

#4562 'karmadactl register' should use bootstrap endpoint for karmada-agents' kubeconfig instead of discovered cluster-info
  pkg/karmadactl/register/register.go
Labels: kind/bug, approved, lgtm, size/XS

#6181 Proposal to enhance FederatedResourceQuota to enforce resource limits directly on Karmada level
  docs/proposals/federated-resource-quota-enhancement/federated-resource-quota-enhancement.md
  docs/proposals/federated-resource-quota-enhancement/policy.yaml
  docs/proposals/federated-resource-quota-enhancement/resources/admission-controller-request-queue.png
  docs/proposals/federated-resource-quota-enhancement/resources/failover-example-1.png
  docs/proposals/federated-resource-quota-enhancement/resources/failover-example-2.png
  docs/proposals/federated-resource-quota-enhancement/resources/resource-quota-assignment.png
Labels: approved, size/L, lgtm, kind/design

#6284 Fix cluster status update interval not hornor `--cluster-status-update-frequency` issue
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/XS

#6338 Automated cherry pick of #6318: .github/workflows: update helm and kustomize env
  .github/workflows/lint-chart.yaml
Labels: approved, lgtm, size/XS

#6339 Automated cherry pick of #6318: .github/workflows: update helm and kustomize env
  .github/workflows/lint-chart.yaml
Labels: approved, lgtm, size/XS

#6340 Automated cherry pick of #6318: .github/workflows: update helm and kustomize env
  .github/workflows/installation-chart.yaml
Labels: approved, lgtm, size/XS

#6336 Automated cherry pick of #6284: update to 'predicate.GenerationChangedPredicate' in
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/XS

#6335 Automated cherry pick of #6284: update to 'predicate.GenerationChangedPredicate' in
  pkg/controllers/status/cluster_status_controller.go
Labels: approved, lgtm, size/XS

#6331 publish release note for v1.14.0-beta.0, v1.13.2, v1.12.6, v1.11.9
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.13.md
  docs/CHANGELOG/CHANGELOG-1.14.md
Labels: approved, size/L, kind/documentation, lgtm
