Repository karmada-io/karmada, pull requests merged in 2025-01, with the labels that each got.

#6004 Automated cherry pick of #5984: fix verify license lint error
  hack/verify-license.sh
  operator/pkg/controller/karmada/validating_test.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers.go
  pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go
  pkg/util/helper/index.go
  pkg/util/helper/index_test.go
Labels: approved, lgtm, size/M

#6008 Automated cherry pick of #5976: Only genrate ETCD PKI for local ETCD setup
  operator/pkg/certs/certs.go
  operator/pkg/init.go
  operator/pkg/tasks/init/cert.go
  operator/pkg/tasks/init/cert_test.go
  operator/pkg/tasks/init/upload.go
Labels: approved, lgtm, size/M

#5937 feat: cluster-level resource scheduling suspend and resume capabilities
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/event_handler_test.go
  pkg/util/binding.go
  pkg/util/binding_test.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm, tide/merge-method-squash

#5690 [Proposal] Support for resource scheduling suspend and resume capabilities
  docs/proposals/scheduling-suspension/README.md
Labels: approved, size/L, kind/documentation, lgtm, kind/design

#5945 remove workaround code for resolving workqueue metrics loss by modifying import order
  cmd/agent/main.go
  cmd/controller-manager/controller-manager.go
  cmd/descheduler/main.go
  cmd/scheduler-estimator/main.go
  cmd/scheduler/main.go
  operator/cmd/operator/operator.go
Labels: kind/bug, approved, lgtm, size/XS

#6011 publish release v1.13.0-alpha.1, v1.12.2, v1.11.5, v1.10.9
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.13.md
Labels: approved, size/L, kind/documentation, lgtm

#6013 expose metrics of karmada-metrics-adapter
  artifacts/deploy/karmada-metrics-adapter.yaml
  charts/karmada/templates/karmada-metrics-adapter.yaml
  cmd/metrics-adapter/app/options/options.go
  operator/pkg/controlplane/metricsadapter/manifests.go
  pkg/karmadactl/addons/metricsadapter/manifests.go
Labels: kind/feature, approved, lgtm, size/M

#6015 Add docs for exposing Karmada APIServer provisioned by operator
  operator/README.md
Labels: approved, kind/documentation, lgtm, size/M

#6019 Add ResourceBinding scheduling suspension helper function
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/apis/work/v1alpha2/binding_types_helper_test.go
  pkg/scheduler/event_handler.go
  pkg/util/binding.go
  pkg/util/binding_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6027 Version Updates in files
  hack/util.sh
  operator/config/samples/karmada.yaml
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Labels: kind/feature, size/S, approved, lgtm, kind/cleanup, ok-to-test

#6018 move CreateOrUpdateWork() and related functions to controllers/ctrlutl
  pkg/controllers/binding/common.go
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/ctrlutil/work_test.go
  pkg/controllers/ctrlutil/workoption.go
  pkg/controllers/ctrlutil/workoption_test.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/namespace/namespace_sync_controller.go
  pkg/controllers/unifiedauth/unified_auth_controller.go
  pkg/util/helper/work.go
  pkg/util/helper/work_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#6033 Update community meeting time
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#6010 Proposal: Add Support for Component Priority Class Configuration in Karmada Operator
  docs/proposals/karmada-operator/component-priority-class-name/README.md
Labels: approved, lgtm, kind/design, size/M

#6026 Replace grpc.DialContext and grpc.WithBlock with grpc.NewClient
  pkg/util/grpcconnection/config.go
Labels: approved, lgtm, size/M, kind/cleanup

#6034 fix the attached binding deletion problem
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
Labels: kind/bug, approved, size/L, lgtm

#6049 publish release v1.13.0-alpha.2
  docs/CHANGELOG/CHANGELOG-1.13.md
Labels: approved, kind/documentation, lgtm, size/M

#5939 fix deep equal check failure in CreateOrUpdateWork(), by replace the marshaler
  pkg/controllers/ctrlutil/work.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6053 Automated cherry pick of #6034: fix the attached binding deletion problem
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
Labels: approved, size/XL, lgtm

#6054 Automated cherry pick of #6034: fix the attached binding deletion problem
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
Labels: approved, size/L, lgtm

#6055 Automated cherry pick of #6034: fix the attached binding deletion problem
  pkg/dependenciesdistributor/dependencies_distributor.go
  pkg/dependenciesdistributor/dependencies_distributor_test.go
Labels: approved, size/L, lgtm

#5990 Fix local up installation failed on macOS duo to missing envsubst
  hack/deploy-karmada.sh
Labels: kind/bug, approved, lgtm, size/M

#6052 config security context
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-apiserver.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-etcd.yaml
  artifacts/deploy/karmada-metrics-adapter.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-search.yaml
  artifacts/deploy/karmada-webhook.yaml
  artifacts/deploy/kube-controller-manager.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#6062 fix pp suspension mistakenly override scheduling suspension
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/detector/detector.go
Labels: kind/bug, size/S, priority/important-soon, approved, lgtm

#6066 Bump Go version to 1.22.11
  .go-version
  go.mod
  hack/util.sh
  pkg/util/membercluster_client_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#6069 Automated cherry pick of #6066: Bump Go version to 1.22.11
  .go-version
  go.mod
  hack/util.sh
  pkg/util/membercluster_client_test.go
Labels: approved, lgtm, size/M

#6070 Automated cherry pick of #6066: Bump Go version to 1.22.11
  .go-version
  go.mod
  hack/util.sh
  pkg/util/membercluster_client_test.go
Labels: approved, lgtm, size/M

#6072 feat(dependenciesdistributor): remove log
  pkg/dependenciesdistributor/dependencies_distributor.go
Labels: approved, lgtm, size/XS

#6065 fix(search/proxy/controller): resourceregistry merge ns
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
  pkg/search/proxy/testing/constant.go
Labels: kind/bug, approved, size/L, lgtm

#6061 enhance ensureWork to continue processing clusters after individual failures
  pkg/controllers/binding/common.go
Labels: kind/feature, approved, lgtm, size/M

#5797 standardize the naming of karmada config in karmadactl method
  pkg/karmadactl/addons/descheduler/manifests.go
  pkg/karmadactl/addons/init/enable_option.go
  pkg/karmadactl/addons/metricsadapter/manifests.go
  pkg/karmadactl/addons/search/manifests.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/util/global.go
  pkg/util/names/names.go
Labels: kind/feature, approved, size/L, lgtm, kind/cleanup

#6068 Add Support for Component Priority Class Configuration in Karmada Operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/apiserver/apiserver_test.go
  operator/pkg/controlplane/apiserver/manifests.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/controlplane_test.go
  operator/pkg/controlplane/etcd/etcd.go
  operator/pkg/controlplane/etcd/etcd_test.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/metricsadapter/metricsadapter.go
  operator/pkg/controlplane/metricsadapter/metricsadapter_test.go
  operator/pkg/controlplane/search/search.go
  operator/pkg/controlplane/search/search_test.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/controlplane/webhook/webhook_test.go
  operator/pkg/util/patcher/pather.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#6085 Read MIN_GO_VERSION directly with Go CLI
  go.mod
  hack/util.sh
Labels: size/S, approved, lgtm, kind/cleanup

#6087 karmada lua uses more secure string functions
  pkg/resourceinterpreter/customized/declarative/luavm/lua.go
  pkg/util/lifted/lua/string_safe.go
Labels: kind/feature, approved, size/L, lgtm

#6090 publish release v1.13.0-beta.0, v1.12.3, v1.11.6, v1.10.10
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.13.md
Labels: approved, size/L, kind/documentation, lgtm
