Repository karmada-io/karmada, pull requests merged in 2025-02, with the labels that each got.

#6086 Avoid coupling tests with hardcoded test CA certs
  pkg/util/membercluster_client_test.go
Labels: approved, lgtm, size/M, tide/merge-method-squash, kind/flake

#6073 Updating FlinkDeployment interpreter to display error status, improving health interpreter
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml
Labels: kind/feature, size/S, approved, lgtm

#6003 introduce tests to check whether workqueue metrics exist
  .github/workflows/installation-cli.yaml
  go.mod
  test/e2e/framework/cluster.go
  test/e2e/framework/metrics.go
  test/e2e/metrics_test.go
  test/e2e/suite_test.go
Labels: approved, size/L, lgtm, kind/failing-test

#6082 Standardize the naming of karmada config in Karmada Operator
  hack/deploy-karmada-by-operator.sh
  operator/pkg/controller/karmada/planner.go
  operator/pkg/controller/karmada/planner_test.go
  operator/pkg/controlplane/apiserver/apiserver.go
  operator/pkg/controlplane/apiserver/apiserver_test.go
  operator/pkg/controlplane/apiserver/manifests.go
  operator/pkg/controlplane/controlplane.go
  operator/pkg/controlplane/controlplane_test.go
  operator/pkg/controlplane/manifests.go
  operator/pkg/controlplane/metricsadapter/manifests.go
  operator/pkg/controlplane/metricsadapter/metricsadapter.go
  operator/pkg/controlplane/metricsadapter/metricsadapter_test.go
  operator/pkg/controlplane/search/manifests.go
  operator/pkg/controlplane/search/search.go
  operator/pkg/controlplane/search/search_test.go
  operator/pkg/controlplane/webhook/manifests.go
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/controlplane/webhook/webhook_test.go
  operator/pkg/tasks/deinit/kubeconfig.go
  operator/pkg/tasks/deinit/kubeconfig_test.go
  operator/pkg/tasks/init/upload.go
  operator/pkg/util/naming.go
Labels: kind/feature, approved, size/L, lgtm, kind/cleanup

#6100 Automated cherry pick of #6065: fix: resourceregistry merge the same cluster gvk's namespace
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
  pkg/search/proxy/testing/constant.go
Labels: approved, size/L, lgtm

#6101 Automated cherry pick of #6065: fix: resourceregistry merge the same cluster gvk's namespace
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
  pkg/search/proxy/testing/constant.go
Labels: approved, size/L, lgtm

#6102 Automated cherry pick of #6065: fix: resourceregistry merge the same cluster gvk's namespace
  pkg/search/proxy/controller.go
  pkg/search/proxy/controller_test.go
  pkg/search/proxy/store/util.go
  pkg/search/proxy/store/util_test.go
  pkg/search/proxy/testing/constant.go
Labels: approved, size/L, lgtm

#6104 charts: fix typo in templates/kube-controller-manager.yaml
  charts/karmada/templates/kube-controller-manager.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#6079 karmada-webhook: fix the no such host error
  charts/karmada/_crds/patches/webhook_in_clusterresourcebindings.yaml
  charts/karmada/_crds/patches/webhook_in_resourcebindings.yaml
  hack/deploy-karmada.sh
  operator/pkg/tasks/init/karmadaresource.go
  operator/pkg/util/util.go
  operator/pkg/util/util_test.go
  pkg/karmadactl/cmdinit/karmada/deploy.go
  pkg/karmadactl/cmdinit/karmada/deploy_test.go
Labels: kind/bug, approved, size/L, lgtm

#6106 remove mockResourceDetector
  pkg/detector/detector_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6108 Add Support for Component Priority Class Configuration in helm
  charts/karmada/templates/etcd.yaml
  charts/karmada/templates/karmada-agent.yaml
  charts/karmada/templates/karmada-aggregated-apiserver.yaml
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/templates/karmada-controller-manager.yaml
  charts/karmada/templates/karmada-descheduler.yaml
  charts/karmada/templates/karmada-metrics-adapter.yaml
  charts/karmada/templates/karmada-scheduler-estimator.yaml
  charts/karmada/templates/karmada-scheduler.yaml
  charts/karmada/templates/karmada-search.yaml
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/templates/kube-controller-manager.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, lgtm, size/M

#6110 Add Support for Component Priority Class Configuration in karmadactl init
  pkg/karmadactl/cmdinit/cmdinit.go
  pkg/karmadactl/cmdinit/kubernetes/deploy.go
  pkg/karmadactl/cmdinit/kubernetes/deployments.go
  pkg/karmadactl/cmdinit/kubernetes/statefulset.go
Labels: approved, size/L, lgtm

#6112 Unify Component Priority Class in local-up
  artifacts/agent/karmada-agent.yaml
  artifacts/deploy/karmada-aggregated-apiserver.yaml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-etcd.yaml
  artifacts/deploy/karmada-metrics-adapter.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-search.yaml
  artifacts/deploy/karmada-webhook.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#6109 Explain the interpreter webhook comunication channel
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, kind/documentation, lgtm, size/M, kind/cleanup

#6113 [Cleanup] update some describetion with the resourceinterpreterwebhook readme file
  examples/customresourceinterpreter/README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#6116 Bump helm/chart-testing-action from 2.6.1 to 2.7.0
  .github/workflows/installation-chart.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#5866 fix(cluster): remove related metrics label when cluster is deleted
  pkg/controllers/status/cluster_status_controller.go
  pkg/metrics/cluster.go
Labels: kind/bug, size/S, approved, lgtm

#6081 Restrict the cluster sync mode for the unjoin and unregister command
  pkg/karmadactl/unjoin/unjoin.go
  pkg/karmadactl/unjoin/unjoin_test.go
  pkg/karmadactl/unregister/unregister.go
  pkg/karmadactl/unregister/unregister_test.go
Labels: kind/feature, approved, lgtm, size/M

#6119 publish release v1.13.0-rc.0
  docs/CHANGELOG/CHANGELOG-1.13.md
Labels: approved, kind/documentation, lgtm, size/M

#6125 fix: when contenxt fails to run when it contains quotes
  pkg/karmadactl/cmdinit/utils/examples.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6131 Bump Go version to 1.22.12
  .go-version
  go.mod
Labels: approved, lgtm, size/XS, kind/cleanup

#4993 Propose binding priority and preemption
  docs/proposals/scheduling/binding-priority-preemption/README.md
  docs/proposals/scheduling/binding-priority-preemption/binding-priority-preemption.png
  docs/proposals/scheduling/binding-priority-preemption/priority-queued.png
Labels: approved, size/L, lgtm, kind/design

#6099 Proposal: Add Support for API Server Sidecar Containers in Karmada Operator
  docs/proposals/karmada-operator/api-server-sidecard-containers/README.md
Labels: approved, size/L, lgtm, kind/design

#5962 Add priorityClassName in PropagationPolicy & ClusterPropagationPolicy
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#5963 Add Priority and PreemptionPolicy fields in ResourceBinding
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#6132 Automated cherry pick of #6131: Bump Go version to 1.22.12
  .go-version
  go.mod
Labels: approved, lgtm, size/XS

#6136 Automated cherry pick of #5936: pkg/search/controllers_test: wait for cache sync
  pkg/search/controllers_test.go
Labels: approved, lgtm, size/M

#6140 fixed some UTs did not pass apiversion and kind when generating unstuctured.Unstructured
  pkg/controllers/multiclusterservice/mcs_controller_test.go
  pkg/controllers/namespace/namespace_sync_controller_test.go
  pkg/detector/detector_test.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
  pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go
  pkg/resourceinterpreter/default/native/aggregatestatus_test.go
  pkg/resourceinterpreter/default/native/reflectstatus_test.go
  pkg/resourceinterpreter/default/native/retain_test.go
  pkg/scheduler/scheduler_metrics_test.go
  pkg/util/eventfilter/eventfilter_test.go
  pkg/util/helper/unstructured_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6128 add e2e test for the case fixed by #6065
  test/e2e/suites/base/search_test.go
  test/e2e/suites/base/suite_test.go
Labels: approved, size/L, lgtm

#6143 Automated cherry pick of #6131: Bump Go version to 1.22.12
  .go-version
  go.mod
Labels: approved, lgtm, size/XS

#6006 feat : add cluster registration step in pull mode to installation-cli.yaml
  .github/workflows/installation-cli.yaml
  hack/cli-testing-environment.sh
  hack/cli-testing-init-with-config.sh
Labels: approved, lgtm, size/M

#6151 Introduce PriorityBasedScheduling feature gate
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-scheduler.yaml
  pkg/features/features.go
Labels: kind/feature, size/S, approved, lgtm

#6076 add work mutating in ctrlutil.CreateOrUpdateWork()
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller_test.go
  pkg/util/helper/work.go
  pkg/webhook/work/mutating.go
Labels: kind/feature, approved, lgtm, size/M

#6158 operator: fix the issue that the default values of Karmada are not correctly applied
  operator/pkg/controller/karmada/controller.go
Labels: kind/bug, size/S, approved, lgtm

#6120 add operator e2e suites
  .github/workflows/ci.yml
  hack/operator-e2e-environment.sh
  hack/run-e2e-operator.sh
  test/e2e/framework/cluster.go
  test/e2e/framework/clusterresourcebinding.go
  test/e2e/framework/configmap.go
  test/e2e/framework/constant.go
  test/e2e/framework/customresourcedefine.go
  test/e2e/framework/deployment.go
  test/e2e/framework/events.go
  test/e2e/framework/federatedresourcequota.go
  test/e2e/framework/job.go
  test/e2e/framework/mcs.go
  test/e2e/framework/namespace.go
  test/e2e/framework/persistentvolumeclaim.go
  test/e2e/framework/pod.go
  test/e2e/framework/propagationpolicy.go
  test/e2e/framework/rbac.go
  test/e2e/framework/resource/operator/karmada.go
  test/e2e/framework/resourcebinding.go
  test/e2e/framework/resourcequota.go
  test/e2e/framework/secret.go
  test/e2e/framework/service.go
  test/e2e/framework/statefulSet.go
  test/e2e/framework/work.go
  test/e2e/framework/workload.go
  test/e2e/framework/workloadrebalancer.go
  test/e2e/suites/operator/priorityclass_test.go
  test/e2e/suites/operator/status_test.go
  test/e2e/suites/operator/suite_test.go
  test/helper/karmada.go
Labels: approved, size/XL, lgtm, kind/flake

#6157 fix(detector): Fix the invalid behavior in the detector to determine whether the binding object needs to be updated.
  pkg/detector/detector.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: kind/bug, approved, lgtm, size/M

#6161 fix(detector): forgot to clean the legacy merge operation
  pkg/detector/detector.go
Labels: approved, lgtm, size/XS

#6163 Make priorityClassSource in the SchedulePriority of PropagationPolicy a required field
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, size/S, approved, lgtm

#6149 priority scheduling: add priority queue
  pkg/apis/work/v1alpha2/binding_types_helper.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/internal/heap/heap.go
  pkg/scheduler/internal/heap/heap_test.go
  pkg/scheduler/internal/queue/active_queue.go
  pkg/scheduler/internal/queue/active_queue_test.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/internal/queue/types.go
  pkg/scheduler/metrics/queue/metric_test.go
  pkg/scheduler/metrics/queue/metrics.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_metrics_test.go
  pkg/scheduler/scheduler_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#6165 Build application priority when creating ResourceBinding
  pkg/detector/detector.go
  pkg/util/helper/priorityclass.go
  pkg/util/helper/priorityclass_test.go
Labels: approved, size/L, lgtm, ok-to-test

#6167 Automated cherry pick of #6157, #6161: fix(detector): Fixed the issue where the `detector` unnecessary updates for RB issue.
  pkg/detector/detector.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: approved, lgtm, size/M

#6169 Automated cherry pick of #6157 #6161 upstream release 1.11
  pkg/detector/detector.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: approved, lgtm, size/M

#6170 Automated cherry pick of #6157 #6161 upstream release 1.10
  pkg/detector/detector.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: approved, lgtm, size/M

#6164 publish v1.13.0, v1.12.4, v1.11.7, v1.10.11
  docs/CHANGELOG/CHANGELOG-1.10.md
  docs/CHANGELOG/CHANGELOG-1.11.md
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.13.md
Labels: approved, size/L, kind/documentation, lgtm

#6159 Allow configuring karmada-apiserver OIDC via Helm
  charts/karmada/templates/karmada-apiserver.yaml
  charts/karmada/values.yaml
Labels: kind/feature, approved, lgtm, size/M
