Repository karmada-io/karmada, pull requests merged in 2025-09, with the labels that each got.

#6650 Add UT for service-export-controller
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/mcs/service_export_controller_test.go
  pkg/util/fedinformer/genericmanager/testing/fake.go
Labels: approved, size/XXL, lgtm, kind/flake

#6723 fix the issue that rbSpec.Components is not updated when the template is updated
  pkg/detector/detector.go
Labels: kind/bug, approved, lgtm, size/XS

#6726 Update sample file of Karmada operator
  operator/config/samples/karmada.yaml
Labels: size/S, approved, kind/documentation, lgtm

#6732 automatic modify image version in helm operator chart when releasing
  charts/karmada-operator/values.yaml
  hack/package-helm-chart.sh
Labels: size/S, approved, lgtm, kind/cleanup

#6733 Update Kubernetes compatibility: add v1.15 and remove v1.12
  README.md
Labels: size/S, approved, lgtm, kind/cleanup

#6731 revise charts appVersion
  charts/index.yaml
  hack/package-helm-chart.sh
Labels: approved, lgtm, size/M, kind/cleanup

#6741 update default node image to v1.33.1
  hack/util.sh
Labels: approved, lgtm, size/XS, kind/cleanup

#6740 Introduce components field to webhook interpreter response
  pkg/apis/config/v1alpha1/interpretercontext_types.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, lgtm, size/M

#6749 escape the dot and colon characters when convert the lua result
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert_test.go
Labels: kind/bug, approved, lgtm, size/M

#6758 fix the issue that omitempty json tag is not consistent with required mark
  api/openapi-spec/swagger.json
  operator/pkg/apis/operator/v1alpha1/type.go
  pkg/apis/networking/v1alpha1/service_types.go
  pkg/apis/policy/v1alpha1/override_types.go
  pkg/apis/search/searchregistry_types.go
  pkg/apis/search/v1alpha1/searchregistry_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: size/S, approved, lgtm

#6757 Setup the unit tests for Dispenser before refactor it
  pkg/scheduler/core/division_algorithm_test.go
  pkg/util/helper/binding_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6767 Automated cherry pick of #6749: escape the dot and colon characters when convert the lua
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_convert_test.go
Labels: approved, lgtm, size/M

#6755 fix nil pointer dereference error
  pkg/webhook/resourcebinding/validating.go
  pkg/webhook/resourcebinding/validating_test.go
Labels: kind/bug, approved, size/L, lgtm

#6764 Change kubectl repo reference (Bitnami deprecation)
  charts/karmada-operator/values.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
Labels: kind/bug, approved, lgtm, size/XS, tide/merge-method-squash, kind/deprecation

#6775 Make sure CRDs are updated on upgrades
  operator/pkg/tasks/init/karmadaresource.go
  operator/pkg/util/apiclient/idempotency.go
Labels: approved, lgtm, size/M

#6773 Fix flaky test failures in taint manager due to time differences
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/cluster/taint_manager_test.go
  pkg/util/helper/taint.go
  pkg/util/helper/taint_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#6789 update explain cmd long message
  pkg/karmadactl/explain/explain.go
Labels: size/S, approved, lgtm, kind/cleanup

#6765 Adding maxAvailableComponentSets to estimator interface
  pkg/estimator/client/accurate.go
  pkg/estimator/client/general.go
  pkg/estimator/client/interface.go
Labels: kind/feature, approved, lgtm, size/M

#6806 Automated cherry pick of #6764: Fix bitname kubectl repo: bitnamisecure/kubectl
  charts/karmada-operator/values.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
Labels: approved, lgtm, size/XS

#6807 Automated cherry pick of #6764: Fix bitname kubectl repo: bitnamisecure/kubectl
  charts/karmada-operator/values.yaml
  charts/karmada/README.md
  charts/karmada/values.yaml
Labels: approved, lgtm, size/XS
