Repository karmada-io/karmada, pull requests merged in 2025-05, with the labels that each got.

#6192 use singleton rate limiter for dynamically created member cluster clients
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  cmd/metrics-adapter/app/options/options.go
  pkg/controllers/context/context.go
  pkg/controllers/execution/execution_controller_test.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/status/cluster_status_controller.go
  pkg/controllers/status/cluster_status_controller_test.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/metricsadapter/controller.go
  pkg/metricsadapter/multiclient/client.go
  pkg/search/controller.go
  pkg/util/membercluster_client.go
  pkg/util/membercluster_client_test.go
  pkg/util/membercluster_ratelimiter.go
  pkg/util/membercluster_ratelimiter_test.go
  pkg/util/objectwatcher/objectwatcher.go
  test/e2e/framework/cluster.go
Labels: kind/bug, approved, size/L, lgtm

#6343 Bump golang.org/x/net version to 0.39.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup

#6344 Bump custom-metrics-apiserver version to v1.32.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS, kind/cleanup

#6189 docs: add proposal of Karmada Self-Signed Certificate Content Standardization
  docs/proposals/cert/Self-Signed_Certificate_Content_Standardization.md
Labels: approved, size/XL, lgtm

#6351 Twist the behavior of staticAssignments in FederatedResourceQuota
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
  pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, size/S, approved, lgtm, kind/cleanup

#6356 fixed the issue where resource scheduling suspension may become ineffective
  pkg/scheduler/event_handler.go
Labels: kind/bug, size/S, approved, lgtm

#6315 operator/pkg/util/naming: update go doc comments for more clarity and readability
  operator/pkg/util/naming.go
Labels: approved, size/L, kind/documentation, lgtm, kind/cleanup

#6360 Automated cherry pick of #6356: fixed the issue where resource scheduling suspension may
  pkg/scheduler/event_handler.go
Labels: size/S, approved, lgtm

#6364 additional print columns for CRDs FederatedResourceQuota
  charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
  pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
Labels: kind/feature, size/S, approved, lgtm

#6365 e2e: cleanup all namespaces created both in control plane and member clusters
  test/e2e/suites/base/search_test.go
  test/e2e/suites/base/suite_test.go
Labels: size/S, approved, lgtm, kind/cleanup

#6366 add `FederatedQuotaEnforcement` feature flag
  pkg/features/features.go
Labels: approved, lgtm, size/XS

#2168 feature: add name length check for fedresourcequota
  pkg/webhook/federatedresourcequota/validating.go
  pkg/webhook/federatedresourcequota/validating_test.go
Labels: kind/bug, approved, lgtm, size/M

#6363 FederatedResourceQuota: skip creating redundant ResourceQuotas to member clusters
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller_test.go
  test/e2e/suites/base/federatedresourcequota_test.go
  test/helper/policy.go
Labels: kind/feature, approved, size/L, lgtm

#6269 design:Add component certificate identification for karmada components
  hack/deploy-karmada.sh
Labels: approved, size/L, lgtm, kind/design

#6348 feat(operator): support loadBalancerClass for karmadaAPIServer
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/controlplane/apiserver/apiserver.go
Labels: approved, lgtm, size/M

#6374 Automated cherry pick of #6369: fix the issue where bindings that fails
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/XS

#6319 Add the ClusterTaintPolicy API
  charts/karmada/_crds/bases/policy/policy.karmada.io_clustertaintpolicies.yaml
  charts/karmada/_crds/kustomization.yaml
  pkg/apis/policy/v1alpha1/clustertaint_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/policy/v1alpha1/zz_generated.register.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/clustertaintpolicy.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/fake/fake_clustertaintpolicy.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/fake/fake_policy_client.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/policy/v1alpha1/policy_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/policy/v1alpha1/clustertaintpolicy.go
  pkg/generated/informers/externalversions/policy/v1alpha1/interface.go
  pkg/generated/listers/policy/v1alpha1/clustertaintpolicy.go
  pkg/generated/listers/policy/v1alpha1/expansion_generated.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/XL, lgtm

#6375 move functions from pkg/util/helper/work.go to pkg/util/work.go
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/mcs/common.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/util/helper/predicate.go
  pkg/util/helper/work.go
  pkg/util/helper/work_test.go
  pkg/util/work.go
  pkg/util/work_test.go
  pkg/webhook/work/mutating.go
  test/e2e/suites/base/clusterpropagationpolicy_test.go
  test/e2e/suites/base/propagationpolicy_test.go
Labels: approved, size/XL, lgtm, kind/cleanup

#6367 Create federated-resource-quota-enforcement-controller
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller_test.go
  pkg/events/events.go
  pkg/util/helper/binding.go
Labels: kind/feature, approved, size/L, lgtm

#6382 staticAssignment only updates AggregatedStatus
  pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
Labels: kind/feature, approved, lgtm, size/XS

#6377 Create RB ValidatingWebhook for FederatedResourceQuota check
  artifacts/deploy/karmada-webhook.yaml
  artifacts/deploy/webhook-configuration.yaml
  charts/karmada/templates/_karmada_webhook_configuration.tpl
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
  operator/pkg/karmadaresource/webhookconfiguration/manifests.go
  pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
  pkg/webhook/resourcebinding/validating.go
  pkg/webhook/resourcebinding/validating_test.go
Labels: kind/feature, approved, size/XXL, lgtm

#6368 Add the ClusterTaintPolicy controller to handle taints on the clusters
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/taint/clustertaintpolicy_controller.go
  pkg/controllers/taint/clustertaintpolicy_controller_test.go
  pkg/util/helper/taint.go
Labels: kind/feature, approved, size/XL, lgtm

#6384 Add feature gates support to karmada-webhook config (Helm Chart)
  charts/karmada/templates/_helpers.tpl
  charts/karmada/templates/karmada-webhook.yaml
  charts/karmada/values.yaml
Labels: kind/feature, size/S, approved, lgtm

#6378 publish release note for v1.14.0-rc.0
  docs/CHANGELOG/CHANGELOG-1.14.md
Labels: approved, lgtm, size/M

#6358 Proposal: Support Suspension of Reconciliation for Karmada Control Planes
  docs/proposals/karmada-operator/reconciliation-suspension/README.md
Labels: approved, lgtm, kind/design, size/M

#6359 Support Suspension of Reconciliation for Karmada Control Planes
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/controller/karmada/controller.go
Labels: approved, lgtm, size/M, tide/merge-method-squash

#6385 Add feature gates support to karmada-webhook config (Operator)
  operator/pkg/controlplane/webhook/webhook.go
  operator/pkg/controlplane/webhook/webhook_test.go
Labels: kind/feature, approved, lgtm, size/M

#6386 cleanup: refactor GenerateTaintsMessage method
  pkg/util/helper/taint.go
  pkg/util/helper/taint_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#6380 feat(controller.karmada): validateKarmadaAPIServer validate lbClass
  operator/pkg/controller/karmada/validating.go
Labels: kind/feature, approved, lgtm, size/XS

#6372 unify index registration
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/binding/binding_controller_test.go
  pkg/controllers/binding/cluster_resource_binding_controller_test.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/cluster_controller_test.go
  pkg/controllers/cluster/common.go
  pkg/controllers/cluster/taint_manager.go
  pkg/controllers/cluster/taint_manager_test.go
  pkg/controllers/mcs/common.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/status/crb_status_controller_test.go
  pkg/controllers/status/rb_status_controller_test.go
  pkg/util/helper/binding_test.go
  pkg/util/helper/work.go
  pkg/util/helper/work_test.go
  pkg/util/helper/workstatus_test.go
  pkg/util/indexregistry/fieldindex.go
Labels: approved, size/L, lgtm, kind/cleanup

#6390 Add comments for field updation and policy deletion for ClusterTaintPolicy API
  charts/karmada/_crds/bases/policy/policy.karmada.io_clustertaintpolicies.yaml
  pkg/apis/policy/v1alpha1/clustertaint_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/taint/clustertaintpolicy_controller.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/api-change, approved, size/L, lgtm

#6399 Sort policies in cluster-taint-policy-controller to ensure idempotency
  pkg/controllers/taint/clustertaintpolicy_controller.go
Labels: kind/feature, size/S, approved, lgtm

#6373 Deprecated default-not-ready-toleration-seconds and default-unreachable-toleration-seconds flags for karmada-webhook
  cmd/webhook/app/options/options.go
Labels: kind/feature, approved, lgtm, size/XS, kind/deprecation

#6389 cluster-controller no longer taints clusters based on conditions
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/cluster_controller_test.go
  test/e2e/framework/cluster.go
  test/e2e/framework/constant.go
  test/e2e/suites/base/clusteraffinities_test.go
  test/e2e/suites/base/failover_test.go
  test/e2e/suites/base/karmadactl_test.go
  test/e2e/suites/base/resource_test.go
Labels: kind/feature, approved, size/L, lgtm

#6411 Skip reconcile ResourceBindings if it has not been scheduled
  pkg/controllers/status/common.go
Labels: approved, lgtm, size/M, kind/cleanup

#6403 No longer add terminting NoExecute taint for the Deleting Cluster
  cmd/controller-manager/app/controllermanager.go
  pkg/apis/cluster/v1alpha1/well_known_constants.go
  pkg/controllers/cluster/cluster_controller.go
  pkg/controllers/cluster/cluster_controller_test.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/event_handler.go
  pkg/scheduler/scheduler.go
Labels: kind/feature, approved, size/L, lgtm

#6418 publish release v1.14.0&v1.13.3
  docs/CHANGELOG/CHANGELOG-1.13.md
  docs/CHANGELOG/CHANGELOG-1.14.md
Labels: approved, size/L, kind/documentation, lgtm

#6370 Add the ClusterTaintPolicy validation
  artifacts/deploy/karmada-webhook.yaml
  artifacts/deploy/webhook-configuration.yaml
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
  pkg/webhook/clustertaintpolicy/validating.go
  pkg/webhook/clustertaintpolicy/validating_test.go
Labels: kind/feature, approved, size/L, lgtm
