Repository karmada-io/karmada, pull requests merged in 2025-08, with the labels that each got.

#6571 structured logging for cronfederatedhpa controllers
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler.go
  pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
Labels: kind/feature, approved, lgtm, size/M

#6555 refactor(app): improve logging in graceful eviction controllers
  pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
  pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Labels: size/S, approved, lgtm, kind/cleanup

#6566 application failover klog structured logging
  pkg/controllers/applicationfailover/common.go
  pkg/controllers/applicationfailover/crb_application_failover_controller.go
  pkg/controllers/applicationfailover/rb_application_failover_controller.go
Labels: approved, lgtm, size/M

#6577 Proxy Support for Custom HTTP Source CRD Download Strategy in Karmada Operator
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  operator/config/crds/operator.karmada.io_karmadas.yaml
  operator/pkg/apis/operator/v1alpha1/type.go
  operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  operator/pkg/controller/karmada/validating.go
  operator/pkg/tasks/init/crd.go
  operator/pkg/util/util.go
  operator/pkg/util/util_test.go
Labels: kind/feature, approved, size/L, lgtm

#6596 Add support for specifying env vars and extra args for the Karmada operator
  charts/karmada-operator/templates/karmada-operator-deployment.yaml
  charts/karmada-operator/values.yaml
Labels: kind/feature, approved, lgtm, size/M

#6551 refactor: enable JSON logging in mcs controller
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/mcs/service_import_controller.go
Labels: approved, lgtm, size/M

#6481 Add quota exceeded conditions in case scheduler fails to update resourcebinding
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/scheduler/helper.go
  pkg/util/constants.go
  pkg/webhook/resourcebinding/validating.go
  pkg/webhook/resourcebinding/validating_test.go
Labels: kind/feature, approved, lgtm, size/M

#6622 When using MCS and MCI simultaneously, prevent resource residuce caused by deleting MCS and MCI
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller_test.go
  pkg/util/finalizer.go
  pkg/util/finalizer_test.go
Labels: kind/bug, approved, size/L, lgtm

#6630 Bump golang to 1.24.6
  .go-version
  go.mod
Labels: approved, lgtm, size/XS, kind/cleanup

#6626 ensure resource interpreter cache sync before starting controllers
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/resourceinterpreter/customized/declarative/configmanager/manager.go
  pkg/resourceinterpreter/customized/webhook/configmanager/manager.go
  pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/resourceinterpreter/customized/webhook/customized_test.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/constants.go
Labels: kind/bug, approved, size/L, lgtm

#6611 Optimize the ResourceBinding validation webhook for better extensibility
  pkg/webhook/resourcebinding/validating.go
  pkg/webhook/resourcebinding/validating_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6627 update -f flag description for karmadactl interpret
  pkg/karmadactl/interpret/interpret.go
Labels: approved, kind/documentation, lgtm, size/XS

#6633 Automated cherry pick of #6622: When using MCS and MCI simultaneously, prevent resource residuce caused by deleting MCS and MCI
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller_test.go
  pkg/util/finalizer.go
  pkg/util/finalizer_test.go
Labels: approved, size/L, lgtm

#6634 Automated cherry pick of #6622: When using MCS and MCI simultaneously, prevent resource residuce caused by deleting MCS and MCI
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller_test.go
  pkg/util/finalizer.go
  pkg/util/finalizer_test.go
Labels: approved, size/L, lgtm

#6636 Automated cherry pick of #6622: When using MCS and MCI simultaneously, prevent resource residuce caused by deleting MCS and MCI
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller_test.go
  pkg/util/finalizer.go
  pkg/util/finalizer_test.go
  pkg/util/helper/work.go
Labels: approved, size/L, lgtm

#6638 Automated cherry pick of #6544: detector: eliminate the mutation of the informer cache
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/helper/binding.go
Labels: size/S, approved, lgtm

#6645 Automated cherry pick of #6602 #6612 #6626 on release-1.14
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/resourceinterpreter/customized/declarative/configmanager/manager.go
  pkg/resourceinterpreter/customized/declarative/configmanager/manager_test.go
  pkg/resourceinterpreter/customized/webhook/configmanager/manager.go
  pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go
  pkg/resourceinterpreter/customized/webhook/customized.go
  pkg/resourceinterpreter/customized/webhook/customized_test.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/constants.go
Labels: approved, size/XL, lgtm

#6651 fix formatted strings
  pkg/karmadactl/create/create.go
  pkg/karmadactl/explain/explain.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6652 publish release v1.15.0-rc.0, v1.14.3, v1.13.6, v1.12.9
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.13.md
  docs/CHANGELOG/CHANGELOG-1.14.md
  docs/CHANGELOG/CHANGELOG-1.15.md
Labels: approved, size/L, kind/documentation, lgtm

#6610 Introduced `spec.failover.cluster` to the PropagationPolicy API for application-level cluster failover
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/policy/v1alpha1/propagation_types.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/feature, kind/api-change, approved, size/L, lgtm

#6668 Introduce new interpreter operation InterpretComponent
  pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
Labels: approved, lgtm, size/XS, kind/cleanup

#6662 feat: introduce ControllerPriorityQueue feature gate
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/features/features.go
Labels: kind/feature, size/S, approved, lgtm

#6665 Resolve binding components using GetComponents interpreter hook
  pkg/detector/detector.go
Labels: kind/feature, approved, lgtm, size/M

#6667 add validation for policyv1alpha1.StatePreservation.Rules[*].AliasLabelName
  pkg/util/validation/validation.go
  pkg/util/validation/validation_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6669 Fix the issue that the cache is out of sync within the resource interpreter when using karmadactl promote
  pkg/karmadactl/promote/promote.go
Labels: kind/bug, approved, lgtm, size/XS

#6681 Automated cherry pick of #6603: Fix the issue of infinite loop caused by connection failure
  pkg/webhook/interpreter/http.go
  pkg/webhook/interpreter/http_test.go
Labels: approved, lgtm, size/M

#6680 Automated cherry pick of #6603: Fix the issue of infinite loop caused by connection failure
  pkg/webhook/interpreter/http.go
  pkg/webhook/interpreter/http_test.go
Labels: approved, lgtm, size/M

#6679 Automated cherry pick of #6603: Fix the issue of infinite loop caused by connection failure
  pkg/webhook/interpreter/http.go
  pkg/webhook/interpreter/http_test.go
Labels: approved, lgtm, size/M

#6678 Implement `GetComponents` for `ConfigurableInterpreter`
  pkg/resourceinterpreter/customized/declarative/configmanager/accessor.go
  pkg/resourceinterpreter/customized/declarative/configmanager/accessor_test.go
  pkg/resourceinterpreter/customized/declarative/configurable.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
  pkg/resourceinterpreter/interpreter.go
Labels: kind/feature, approved, size/L, lgtm

#6687 Implement `GetComponents` for `thirdpartyInterpreter`
  pkg/resourceinterpreter/default/thirdparty/thirdparty.go
  pkg/resourceinterpreter/interpreter.go
Labels: kind/feature, size/S, approved, lgtm

#6523 Fixed the issue that reporting repeat EndpointSlice resources leads to duplicate backend IPs
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/util/constants.go
  pkg/util/helper/mcs.go
  pkg/util/helper/mcs_test.go
Labels: kind/bug, approved, lgtm, size/M

#6656 fixed the issue where pp-related claimMetadata was not properly cleaned up
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/selector.go
  pkg/util/selector_test.go
Labels: kind/bug, approved, size/XL, lgtm

#6698 Fix the issue that the cache is out of sync within the resource inter…
  pkg/karmadactl/promote/promote.go
Labels: kind/bug, size/S, approved, lgtm

#6541 enable mutation detection in e2e
  .github/workflows/ci.yml
  artifacts/deploy/karmada-controller-manager.yaml
  artifacts/deploy/karmada-descheduler.yaml
  artifacts/deploy/karmada-metrics-adapter.yaml
  artifacts/deploy/karmada-scheduler-estimator.yaml
  artifacts/deploy/karmada-scheduler.yaml
  artifacts/deploy/karmada-search.yaml
  hack/deploy-karmada.sh
  hack/deploy-scheduler-estimator.sh
  hack/run-e2e.sh
  hack/util.sh
Labels: approved, size/L, lgtm, kind/cleanup

#6597 Improve the performance of karmada-scheduler
  pkg/scheduler/core/assignment.go
  pkg/scheduler/core/assignment_test.go
  pkg/scheduler/core/common.go
  pkg/scheduler/core/common_test.go
  pkg/scheduler/core/division_algorithm.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/generic_scheduler_test.go
  pkg/scheduler/core/spreadconstraint/group_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_cluster.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go
  pkg/scheduler/core/spreadconstraint/select_clusters_by_region_test.go
  pkg/scheduler/core/spreadconstraint/select_clusters_test.go
  pkg/scheduler/core/util.go
  pkg/scheduler/core/util_test.go
Labels: kind/feature, approved, size/XL, lgtm

#6694 Automated cherry pick of #6523: Exclude EndpointSlice resources managed by Karmada system to avoid duplicate reporting
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/util/constants.go
  pkg/util/helper/mcs.go
  pkg/util/helper/mcs_test.go
Labels: approved, lgtm, size/M

#6693 Automated cherry pick of #6523: Exclude EndpointSlice resources managed by Karmada system to avoid duplicate reporting
  pkg/controllers/mcs/endpointslice_controller.go
  pkg/controllers/mcs/service_export_controller.go
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/util/constants.go
  pkg/util/helper/mcs.go
  pkg/util/helper/mcs_test.go
Labels: approved, lgtm, size/M

#6702 Fix the issue that the cache is out of sync within the resource inter…
  pkg/karmadactl/promote/promote.go
Labels: kind/bug, approved, lgtm, size/XS

#6697 Adding componentResource calculation for FlinkDeployment
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml
Labels: kind/feature, approved, size/L, lgtm

#6686 When controller calls IsAPIEnabled, it also considers whether the judgment result is trustworthy
  pkg/apis/cluster/v1alpha1/cluster_helper.go
  pkg/apis/cluster/v1alpha1/cluster_helper_test.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
  pkg/controllers/multiclusterservice/mcs_controller_test.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
  pkg/search/controller.go
  pkg/search/proxy/controller.go
  pkg/util/helper/cluster.go
  pkg/util/helper/cluster_test.go
  test/e2e/framework/customresourcedefine.go
Labels: approved, size/L, lgtm, kind/cleanup

#6495 [Proposal] Support cluster failover for stateful workloads
  docs/proposals/failover/stateful-workload-cluster-failover.md
Labels: kind/feature, approved, size/L, kind/documentation, lgtm

#6674 fix the issue that the relevant fields in rb and pp are inconsistent
  pkg/detector/detector.go
  pkg/detector/detector_test.go
  pkg/detector/policy.go
Labels: kind/bug, approved, size/L, lgtm

#6704 Automated cherry pick of #6656: fixed the issue where pp-related claimMetadata was not
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/selector.go
  pkg/util/selector_test.go
Labels: approved, size/XL, lgtm

#6705 Automated cherry pick of #6656: fixed the issue where pp-related claimMetadata was not
  pkg/detector/detector.go
  pkg/detector/policy.go
  pkg/util/selector.go
  pkg/util/selector_test.go
Labels: approved, size/XL, lgtm

#6708 Rename ComponentRequirements field in ResourceBinding
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
  pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller_test.go
  pkg/detector/detector_test.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/resourceinterpreter/customized/declarative/configurable.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua.go
  pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
  pkg/resourceinterpreter/default/native/default.go
  pkg/resourceinterpreter/default/thirdparty/thirdparty.go
  pkg/resourceinterpreter/interpreter.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
  pkg/webhook/resourcebinding/validating_test.go
Labels: approved, size/L, lgtm, kind/cleanup

#6671 Ensure in directly purgeMode: resources removed from old cluster before being created in new cluster
  pkg/controllers/binding/binding_controller.go
  pkg/controllers/binding/cluster_resource_binding_controller.go
  pkg/controllers/binding/common.go
  pkg/util/helper/binding.go
  pkg/util/helper/binding_test.go
Labels: kind/feature, approved, size/L, lgtm

#6699 added validation check for the components section of resourcebinding
  api/openapi-spec/swagger.json
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  pkg/apis/work/v1alpha2/binding_types.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/webhook/resourcebinding/validating.go
  pkg/webhook/resourcebinding/validating_test.go
Labels: kind/feature, approved, size/L, lgtm

#6707 fix the issue that the binding's suspension persists when the policy deletes the suspension configuration
  pkg/detector/detector.go
  pkg/util/binding.go
  pkg/util/binding_test.go
  test/e2e/suites/base/propagationpolicy_test.go
Labels: kind/bug, approved, size/L, lgtm

#6717 Automated cherry pick of #6707: fix the issue that the binding's suspension persists when the
  pkg/detector/detector.go
  pkg/util/binding.go
  pkg/util/binding_test.go
  test/e2e/suites/base/propagationpolicy_test.go
Labels: approved, size/L, lgtm

#6718 Automated cherry pick of #6707: fix the issue that the binding's suspension persists when the
  pkg/detector/detector.go
  pkg/util/binding.go
  pkg/util/binding_test.go
  test/e2e/suites/base/propagationpolicy_test.go
Labels: approved, size/L, lgtm

#6535 Refine Multiple Pod Templates Scheduling proposal
  docs/proposals/scheduling/multi-podtemplate-support/multiple-pod-template-support.md
  docs/proposals/scheduling/multi-podtemplate-support/schedule-flink-use-case.png
Labels: kind/feature, approved, size/XL, lgtm

#6711 Automated cherry pick of #6674: fix the issue that the relevant fields in rb and pp are
  pkg/detector/detector.go
  pkg/detector/detector_test.go
  pkg/detector/policy.go
Labels: approved, size/L, lgtm

#6714 Automated cherry pick of #6674: fix the issue that the relevant fields in rb and pp are
  pkg/detector/detector.go
  pkg/detector/detector_test.go
  pkg/detector/policy.go
Labels: approved, size/L, lgtm

#6715 Automated cherry pick of #6674: fix the issue that the relevant fields in rb and pp are
  pkg/detector/detector.go
  pkg/detector/detector_test.go
  pkg/detector/policy.go
Labels: approved, size/L, lgtm

#6721 publish release v1.15.0, v1.14.4, v1.13.7, v1.12.10
  docs/CHANGELOG/CHANGELOG-1.12.md
  docs/CHANGELOG/CHANGELOG-1.13.md
  docs/CHANGELOG/CHANGELOG-1.14.md
  docs/CHANGELOG/CHANGELOG-1.15.md
Labels: approved, size/L, kind/documentation, lgtm
