Repository karmada-io/karmada, pull requests merged in 2025-07, with the labels that each got.

#6462 fix: ensure APIEnablement plugin never deletes scheduled resources
  pkg/scheduler/framework/plugins/apienablement/api_enablement.go
  pkg/scheduler/framework/plugins/apienablement/api_enablement_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#6517 fix: Update Karmada search template to use search.resources for resources
  charts/karmada/templates/karmada-search.yaml
Labels: kind/bug, approved, lgtm, size/XS

#6515 CI: add Gemini assist for code reviews
  .gemini/config.yaml
Labels: kind/feature, approved, lgtm, size/M

#6529 Automated cherry pick of #6519: Eliminate Trivy abnormal alerts #6514: Bump aquasecurity/trivy-action from 0.31.0 to 0.32.0
  .github/workflows/ci-image-scanning-on-schedule.yml
  .github/workflows/ci-image-scanning.yaml
  .github/workflows/release.yml
Labels: size/S, approved, lgtm

#6527 [release-1.14] update trivy version
  .github/workflows/ci-image-scanning-on-schedule.yml
  .github/workflows/ci-image-scanning.yaml
  .github/workflows/release.yml
Labels: size/S, approved, lgtm, kind/cleanup

#6528 [release-1.13] update trivy version
  .github/workflows/ci-image-scanning-on-schedule.yml
  .github/workflows/ci-image-scanning.yaml
  .github/workflows/release.yml
Labels: size/S, approved, lgtm, kind/cleanup

#6525 Fixed the issue that resources will be recreated after deleted on the cluster when resource is suspended for dispatching
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
Labels: kind/bug, size/S, approved, lgtm

#6536 Automated cherry pick of #6525: don't recreate resource in the member cluster when it is
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
Labels: size/S, approved, lgtm

#6534 publish release v1.15.0-alpha.2
  docs/CHANGELOG/CHANGELOG-1.15.md
Labels: approved, kind/documentation, lgtm, size/M

#6552 Fix the rate-limit issue of kustomize action
  .github/workflows/installation-chart.yaml
Labels: approved, lgtm, size/XS, kind/flake

#6549 Bump sigs.k8s.io/kind to v0.29.0
  go.mod
  go.sum
  hack/cli-testing-environment.sh
  hack/cli-testing-init-with-config.sh
  hack/setup-dev-base.sh
  hack/util.sh
  vendor/al.essio.dev/pkg/shellescape/.gitignore
  vendor/al.essio.dev/pkg/shellescape/.golangci.yml
  vendor/al.essio.dev/pkg/shellescape/.goreleaser.yml
  vendor/al.essio.dev/pkg/shellescape/AUTHORS
  vendor/al.essio.dev/pkg/shellescape/CODE_OF_CONDUCT.md
  vendor/al.essio.dev/pkg/shellescape/LICENSE
  vendor/al.essio.dev/pkg/shellescape/Makefile
  vendor/al.essio.dev/pkg/shellescape/README.md
  vendor/al.essio.dev/pkg/shellescape/shellescape.go
  vendor/github.com/google/safetext/LICENSE
  vendor/github.com/google/safetext/common/common.go
  vendor/github.com/google/safetext/yamltemplate/yamltemplate.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/yaml.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/installcni/cni.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/create.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeadm/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/encode.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/read.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/logs/logs.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/nerdctl/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/nodeutils/util.go
  vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
  vendor/sigs.k8s.io/kind/pkg/exec/helpers.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/encoding/load.go
  vendor/sigs.k8s.io/kind/pkg/internal/patch/toml.go
Labels: approved, size/XXL, lgtm, kind/cleanup

#6557 Bump go version to 1.24.5
  .go-version
  go.mod
Labels: approved, lgtm, size/XS, kind/cleanup

#6512 Delete the propagation.karmada.io/instruction label
  cmd/agent/app/agent.go
  cmd/controller-manager/app/controllermanager.go
  pkg/controllers/ctrlutil/work.go
  pkg/controllers/ctrlutil/work_test.go
  pkg/controllers/execution/execution_controller.go
  pkg/controllers/status/work_status_controller.go
  pkg/controllers/status/work_status_controller_test.go
  pkg/util/constants.go
  pkg/util/helper/predicate.go
  pkg/util/helper/predicate_test.go
Labels: approved, size/L, lgtm, kind/deprecation

#6556 Update Kubernetes versions in CI workflows to include v1.33.0
  .github/workflows/ci-schedule-compatibility.yaml
  .github/workflows/ci-schedule.yml
  .github/workflows/ci.yml
  .github/workflows/installation-chart.yaml
  .github/workflows/installation-cli.yaml
  .github/workflows/installation-operator.yaml
Labels: size/S, approved, lgtm, kind/cleanup

#6558 Bump controller-gen version to v0.18.0
  charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
  charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml
  charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
  charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
  charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_clustertaintpolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
  charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
  charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
  charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
  examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
  hack/update-crdgen.sh
  operator/config/crds/operator.karmada.io_karmadas.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#6524 feat: add resource interpreter customization for SidecarSet
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/testdata/desired-sidecarset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/testdata/observed-sidecarset-nginx.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/testdata/status-file.yaml
Labels: kind/feature, approved, size/L, lgtm

#6533 feat: add resource interpreter customization for UnitedDeployment
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/customizations.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/customizations_tests.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/testdata/desired-uniteddeployment.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/testdata/observed-uniteddeployment.yaml
  pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/testdata/status-file.yaml
Labels: kind/feature, approved, size/L, lgtm

#6545 Add Structured Logging for Federated HPA controller
  pkg/controllers/federatedhpa/federatedhpa_controller.go
  pkg/controllers/federatedhpa/metrics/client.go
Labels: approved, lgtm, size/M

#6546 JSON logging for multiclusterservice controllers
  pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
  pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
  pkg/controllers/multiclusterservice/mcs_controller.go
Labels: approved, size/L, lgtm

#6434 Ensure EndpointSlice informer cache is synced before reporting EndpointSlice
  pkg/controllers/mcs/service_export_controller.go
Labels: kind/bug, size/S, approved, lgtm, priority/critical-urgent

#6567 JSON logging for RB Status Controller
  pkg/controllers/status/rb_status_controller.go
Labels: approved, lgtm, size/XS

#6575 Group operator design documents under `docs/proposals/karmada-operator` directory
  docs/proposals/karmada-operator/operator-custom-crd-download-strategy/README.md
Labels: approved, lgtm, size/XS, kind/cleanup

#6585 Automated cherry pick of #6434: wait for EndpointSlice informer synced when report
  pkg/controllers/mcs/service_export_controller.go
Labels: size/S, approved, lgtm

#6584 Automated cherry pick of #6434: wait for EndpointSlice informer synced when report
  pkg/controllers/mcs/service_export_controller.go
Labels: size/S, approved, lgtm

#6583 Automated cherry pick of #6434: wait for EndpointSlice informer synced when report
  pkg/controllers/mcs/service_export_controller.go
Labels: size/S, approved, lgtm

#6578 Work status controller structured logging
  pkg/controllers/status/work_status_controller.go
Labels: approved, kind/documentation, lgtm, size/M, kind/cleanup
